### ISSUE TITLE
Game crashes if a scaffold is broken while under a blood splot.

### ISSUE THREAD

**Issue by Sovietsupporter69** [rubensworks/EvilCraft#1000]
#### Issue type:

- :bug: Bug

____

#### Short description:

I fell in the nether and tried to clutch with a scaffold, forgot to crouch and died. Upon getting back I broke the scaffold which now had a blood splot on top of it (due to the death) and my game instantly crashed.

#### Steps to reproduce the problem:

1. Place a scaffold down
2. die on top of said scaffold (Fall damage is the easiest) 
3. come back and break the scaffold while the blood splot is still there

#### Expected behaviour:

Instantaneous crash

#### Versions:

- This mod: 1.2.24
- Minecraft: 1.19.2
- Forge: 43.2.14

I am in a mod pack (ATM 8) but because this issue was very simple to explain I skipped the single mod testing. If this proves to be impossible to replicate please just assume it was a mod pack issue.

#### Log file:

https://drive.google.com/drive/folders/1CpkY3pvIdHI32U2OX5Fr2x0vG5du595s?usp=sharing
This is my entire logs folder I was unsure if you would need anything more so I just uploaded it all

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
The crashlog is not present in your log files unfortunately. I'll need the actual crashlog file.

**Comment by Sovietsupporter69** [comment]
Sorry about that, the crash logs where in a separate file. There was only one log so I put it into the same spot as the others under the name "crash-2023-08-17_22.05.55-server".

**Comment by rubensworks** [comment]
I see this in your logs:

> java.lang.NoClassDefFoundError: net/minecraft/CrashReportDetail

Are you sure that there are no other crashlogs?

Because that crashlog indicates that something is horribly broken in your MC installation, and that core MC classes are missing. (I see nothing related to EvilCraft in that log)

**Comment by Sovietsupporter69** [comment]
Nah this is the only crash log in the folder, sorry for wasting your time then and thanks for letting me know my MC is buggy as all hell.

**Comment by rubensworks** [comment]
No worries. Just let me know once you'd get a different crashlog :-)
