### ISSUE TITLE
[1.18.2] Spirit Furnace doesn't produce player only kills drops.

### ISSUE THREAD

**Issue by DamondSword2247** [rubensworks/EvilCraft#1001]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Player only kills drops like phantom membrane and rabbits foot aren't produced by the furnace.

#### Steps to reproduce the problem: 

1. Catch a spirit of a mob that has a player kill only drop. Example: a phantom
2. Put the box in the furnace and get no player kill drops.

#### Expected behaviour:

Things like Phantom Membrane and rabbits foot get produced with their normal drops.
____

#### Versions:

- This mod: Evilcraft-1.18.2-1.2.19  
- CyclopsCore-1.18.2-1.17.5
- Minecraft: 1.18.2
- Forge: Forge-40.2.0
- MouseTweaks-forge-mc1.18-2.21
- jei-1.18.2-forge-10.2.1.1005

#### Log file:
https://pastebin.com/NLvYBsyX  (I doubt this log will be necessary but it's there if needed)

**Comment by rubensworks** [comment]
Thanks for reporting!
