### ISSUE TITLE
crash when click on JEI Creative tab for EvilCraft

### ISSUE THREAD

**Issue by furtabs** [rubensworks/EvilCraft#1002]
[crash-2023-08-30_05.56.27-client.txt](https://github.com/CyclopsMC/EvilCraft/files/12474416/crash-2023-08-30_05.56.27-client.txt)

**Comment by rubensworks** [comment]
@EndangeredNayla Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
