### ISSUE TITLE
Entangled Chalice Sound Bug.

### ISSUE THREAD

**Issue by SilverScythe64** [rubensworks/EvilCraft#1003]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When the Entangled Chalice fills an item in your inventory, it triggers the "item.bucket.fill:minecraft" sound.

#### Steps to reproduce the problem:

1. ... https://www.youtube.com/watch?v=xS9FE7FaQ_g

#### Expected behaviour:

Not to hear the bucket fill sound.
____
#### Versions:

- This mod: EvilCraft-1.20.1-1.2.28.jar
- Minecraft: 1.20.1
- Forge: 47.1.3

**Comment by rubensworks** [comment]
Thanks for reporting!
