### ISSUE TITLE
Crash when rendering merchant's Vengeance Spirit

### ISSUE THREAD

**Issue by FalAut** [rubensworks/EvilCraft#1004]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Rendering Vengeance Spirit after killing the merchant of Farming for Blockheads will cause the game to crash.

#### Steps to reproduce the problem:

1. enabled Vengeance Ring
2. kill the merchant of Farming for Blockheads
3. game crash
#### Expected behaviour:
Adding "farmingforblockheads:merchant" to [mob.vengeance_spirit]-entityBlacklist in the config file can fixes this bug.
This bug can break save, it is recommended to add the blacklist to the default configuration

____

#### Versions: 1.19.2,and 1.16-1.19 all have this bug

- This mod: EvilCraft-1.19.2-1.2.26
- CyclopsCore-1.19.2-1.18.8
- farmingforblockheads-forge-1.19.2-11.3.1
- balm-forge-1.19.2-4.5.7
- Minecraft: 1.19.2
- Forge: 43.2.23

#### Log file:
https://pastebin.com/WGk2d2vA

**Comment by rubensworks** [comment]
Thanks for reporting!
