### ISSUE TITLE
Broom duplication

### ISSUE THREAD

**Issue by LordGuppy** [rubensworks/EvilCraft#1007]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When riding a broom, another player destroying the broom with a weapon will dupe the broom.

#### Steps to reproduce the problem:

1. acquire friend (difficulty: impossible)
2. get on broom
3. have friend smack broom and break it while you are riding
4. ???
5. profit

#### Expected behaviour:

I expected my broom to not have babies.
____

#### Versions:

- This mod: 1.2.28
- Minecraft: 1.19.2
- Forge: 43.3.0

**Comment by rubensworks** [comment]
Thanks for reporting!
