### ISSUE TITLE
[1.19.2] Error: "GUI did not draw the dark background..."

### ISSUE THREAD

**Issue by Sandriell** [rubensworks/EvilCraft#1008]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Getting the following error in the client log:

`[Render thread/WARN] [me.je.gu.ev.GuiEventHandler/]: GUI did not draw the dark background layer behind itself, this may result in display issues: org.cyclops.evilcraft.client.gui.container.ContainerScreenOriginsOfDarkness`

#### Steps to reproduce the problem:

1. Open the Origins of Darkness

#### Expected behaviour:

No error, and I guess a darker background?

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.29
- Minecraft: 1.19.2
- Forge: 43.2.21

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Sandriell** [comment]
Still getting the same error in the console, and no darkened background, using the latest version of Cyclops Core, 1.19.2-1.18.9

**Comment by rubensworks** [comment]
Woops, wasn't really awake while fixing this it seems...
