### ISSUE TITLE
Wierd tooltip

### ISSUE THREAD

**Issue by castilio20** [rubensworks/EvilCraft#1009]
- This mod: EvilCraft-1.20.1-1.2.31
- Minecraft: 1.20.1
- neo:47.1.79

![2023-10-24_11 06 34](https://github.com/CyclopsMC/EvilCraft/assets/76228548/9bb933fb-388c-4881-8bbc-5f24d756a16c)

**Comment by rubensworks** [comment]
Thanks for reporting!
