### ISSUE TITLE
Effortless ring crashes when put in a chest

### ISSUE THREAD

**Issue by medsal15** [rubensworks/EvilCraft#1011]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Effortless ring crashes my game when put in a chest

#### Steps to reproduce the problem:

1. Put an effortless ring in a chest

#### Expected behaviour:

Minecraft doesn't crash

____

#### Versions:

- This mod: 1.2.32
- Minecraft: 1.20.1
- Forge: 47.2.1

#### Log file:

https://pastebin.com/raw/g9MgFwuy

**Comment by rubensworks** [comment]
Thanks for reporting!
