### ISSUE TITLE
Effortlessl ring crashed minecraft when moved in my inventory

### ISSUE THREAD

**Issue by Tarquimene** [rubensworks/EvilCraft#1012]
#### Issue type:

- :bug: Bug 

Bug: Crash
____

#### Short description:

When you get the ring, if you try to move it to another Inventory slot when it's in your inventory it crashes. Mostly in survival.
#### Steps to reproduce the problem:

1. Get the ring in your inventory
2. Open the inventory
3. click in the effortless ring
4. try to move it to another Inventory slot, It should crash

Expected behaviour:

Move the ring to another inventory slot and still be in use, With No Crash
____

#### Versions:

- This mod: Evilcraft 1.2.32
- Minecraft: 1.20.1
- Forge: 47.2.1

#### Log file:

https://paste.ee/p/kDbl0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Please update to the latest version of this mod, this problem was fixed there.
