### ISSUE TITLE
Dark Temple hangs void worlds

### ISSUE THREAD

**Issue by Jackiecrazy** [rubensworks/EvilCraft#1013]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Why does it even generate in a void world? Shouldn't [this](https://github.com/CyclopsMC/EvilCraft/blob/4cb0870d762154ebd5fed460ab642ad211e59238/src/main/java/org/cyclops/evilcraft/world/gen/structure/WorldStructureDarkTemple.java#L251) have some kind of limiter to prevent this sort of thing?

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

A dimensional blacklist for dark temples would be good.

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jackiecrazy** [comment]
I do realize this isn't a very well written bug report. I guess it's meant to be a feature request to add dimensional blacklists for the temple.

**Comment by rubensworks** [comment]
Sidenote: you can modify biomes in which the temple is generated via datapacks: https://github.com/CyclopsMC/EvilCraft/blob/master-1.20/src/main/resources/data/evilcraft/tags/worldgen/biome/has_structure/dark_temple.json
