### ISSUE TITLE
1.20.1 Forge 47.2.17 ``Crash on Manual Reload`` the crash points directly to ``Biome Extractor``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [rubensworks/EvilCraft#1016]
#### Issue type:

- :bug: Bug 
- Crashed on manual reload

____

#### Short description:

It crashed

#### Steps to reproduce the problem:

I have no idea use my pack and then reload using pack menu reload button?

#### Expected behaviour:

No crash
____

#### Versions:

https://mclo.gs/mhzUXnU

``CyclopsCore-1.20.1-1.18.14``
``EvilCraft-1.20.1-1.2.34``

I am the mod pack dev. 

#### Log file:

https://mclo.gs/j3eo16c

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by P3rf3ctXZer0** [comment]
[1.20.1-FFCM-C-rc03-20.0.2.zip](https://github.com/CyclopsMC/EvilCraft/files/13575823/1.20.1-FFCM-C-rc03-20.0.2.zip)
This build is missing 5 mods
- Excavar (Light weight block mining)
- Hole Filler Mod (Repair large holes fast)
- Measurements (What do you think this does?)
- Pack Menu (Fancy start screen)
- Pack Tape (Move full chests without breaking them)
