### ISSUE TITLE
Colossal Blood Chest missing texture

### ISSUE THREAD

**Issue by met4000** [rubensworks/EvilCraft#1017]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Colossal Blood Chest has a purple/black missing-texture texture.

See also: [initial report on discord](https://discord.com/channels/386052815128100865/386054141237002241/1170406693365100644), [latest report on discord](https://discord.com/channels/386052815128100865/386054141237002241/1184183738863726642), AllTheMods/ATM-9#726

The normal blood chest renders with what I assume is the correct texture; it doesn't have the purple/black missing-texture texture.

#### Steps to reproduce the problem:

1. Make a colossal blood chest multiblock

The complete multiblock does change model, but has a texture as shown below

![image](https://github.com/CyclopsMC/EvilCraft/assets/15624876/e545bd4c-c921-4eca-bfaa-21ac6ac5381c)

#### Expected behaviour:

Non-missing-texture texture is rendered.

____

#### Versions:

![image](https://github.com/CyclopsMC/EvilCraft/assets/15624876/3e467900-f565-41e4-89e1-d892a8dd4da2)

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
