### ISSUE TITLE
1.20.1 - Darkened apple will not spawn anomaly after mob dies

### ISSUE THREAD

**Issue by darraross** [rubensworks/EvilCraft#1020]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Whenever I try to feed a darkened apple to a mob or player an anomaly doesn't spawn after the mob dies. This has been tried on both desktop and laptop with the same results

#### Steps to reproduce the problem:

1. Load into a new or pre-existing world
2. obtain a darkened apple either through crafting or cheats
3. feed it to any mob or player
4. Mob/player will begin taking damage until death
5. Anomaly doesn't spawn after mob/player dies
6. (optional) Hold down F3 + C until debug crash is triggered

#### Expected behavior:

After a mob/player consumes a darkened apple they receive a damaging status effect which kills them, after which an anomaly is supposed to spawn. 

____

#### Versions:

- Evilcraft: 1.20.1-1.2.36
- CyclopsCore: 1.20.1-1.18.14
- Minecraft: 1.20.1
- Forge: 47.2.20

#### Log file:

Desktop crash report, latest log, debug log:
Crash: https://pastebin.com/WxMZrzju
Latest: https://pastebin.com/bqr9nDdF
Debug: https://pastebin.com/KDsRYLfp

Laptop crash report, latest log, debug log:
Crash: https://pastebin.com/q05yHxSy
Latest: https://pastebin.com/H8q39kM3
Debug: https://pastebin.com/YuJSXsJU

**Comment by rubensworks** [comment]
Thanks for reporting!
