### ISSUE TITLE
Human Rotten Flesh cause a Crash Report about Rendering Screen.

### ISSUE THREAD

**Issue by SoyJetixXD** [rubensworks/EvilCraft#1021]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Hello, I hope you are having a good day!
I will explain the error to you in the best possible way, it all started on a mod server (We use MOHIST) that I created with my friends in 1.16.5 (We are faithful supporters of that version) and of course your wonderful mod could not be missing from the Modpack, everything was going well and without any failure until we started to die and they gave us our OWN ROTTEN FLESH.
As some users have knowledge of the mod itself, they kept the ROTTEN FLESH in their chests or inventory and that is where the CRASH occurred, you have to point the mouse at the item itself.

#### Steps to reproduce the problem:

1. Die until you get your own rotten flesh
2. Select the item itself with the mouse
3. Your game CRASH
If I don't explain it well or it's not clear, here is a video I made.
https://www.youtube.com/watch?v=OT0hNstcHkQ

#### Expected behaviour:

Well I hope we can find a solution, because my friends and I love this mod and we don't want to have to delete it, our love for the mod was so great that we even went into the CONFIG file and tried to disable the rotting human flesh.

![Captura de pantalla (70)](https://github.com/CyclopsMC/EvilCraft/assets/60457424/a183a633-7e5b-46ff-9200-d4324beb8ab9)
![Captura de pantalla (71)](https://github.com/CyclopsMC/EvilCraft/assets/60457424/00f90978-f775-4c37-8d48-1d208b547d37)
But then we found another error caused (we think) by the configuration, but this time I just shut down the server.
https://pastebin.com/LzFHte5K
____

#### Versions:

- This mod: EvilCraft-1.16.5-1.1.17
- Minecraft:  1.16.5 
- Forge: 36.2.41
- Mohist: 1.16.5 - 1220 / mohist-1.16.5-154-server
- Modpack: https://www.mediafire.com/file/dn4ug4ny5h98gpw/ADX_RELEASE_3.zip/file

#### Log file:

Rendering Crash: (https://pastebin.com/tzdTF7Js)
Server Crash: https://pastebin.com/LzFHte5K
THANK YOU for reading and I hope you can help us!
Anything i can do, don't hesitate to tell me!

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, but MC 1.16 is not supported anymore.

**Comment by SoyJetixXD** [comment]
It's okay, it's a shame. But please, isn't there a way to deactivate the human rotten flesh?
