### ISSUE TITLE
Hardened blood bug

### ISSUE THREAD

**Issue by EnderUnkMons** [rubensworks/EvilCraft#1022]
#### Issue type: Can't get an core item

- :bug: Bug 

____

#### Steps to reproduce the problem: 

1. I just let the blood from the extractor on the ground
2. When it solidify I try to broke it with the flint and steel but it just become liquid again 
3. I try to take the whole block with a silk touch pickaxe but it liquefy again

#### Expected behaviour: To give me the hardened blood shard if I break it with the flint and steel or give me entire block with silk touch pickaxe

____

#### Versions: 1.16.5

- This mod: Evilcraft
- Minecraft: 1.16.5
- Forge: 36.2.42

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by EnderUnkMons** [comment]
OK I just find the problem
It's and incompatibility with inventory pets, when you have loot pet on you hotbar and try to break the hardened blood it just liquifies, but if you break it without it you can do it normaly

**Comment by rubensworks** [comment]
I'm sorry, but MC 1.16 is not supported anymore.
