### ISSUE TITLE
Server crush

### ISSUE THREAD

**Issue by IArturiosI** [rubensworks/EvilCraft#1023]
[

#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem: the server is breaking down

1. ...

#### Expected behaviour:

____

#### Versions: 1.20.1

- This mod:  EvilCraft-1.20.1-1.2.37
- Minecraft:  1.20.1
- Forge: https://mclo.gs/rhwFyX7

#### Log file:  ---- Minecraft Crash Report ----
// You're mean.
	Forge: net.minecraftforge:47.2.20

**Comment by rubensworks** [comment]
Thanks for reporting!
