### ISSUE TITLE
Eternal Water block turns to Ice when on a ad astra space station in an oxygenated environment.

### ISSUE THREAD

**Issue by Pelkenator** [rubensworks/EvilCraft#1024]
Placing the eternal water block in a sealed room with oxygen and placing torches around it to attempt to prevent it from freezing doesn't seem to work. I wanted to use this for my nuclear reactor space station but they turn to ice.

#### Issue type:

- :bug: Bug 

____

#### Short description:

<I Have also reported the issue to ad astra and im going to report it to the modpack as well>

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Please fill in the proper issue template. I am missing information that is required to resolve this issue.

**Comment by Pelkenator** [comment]
what other information is required? 1.2.37.jar is interacting with ad astra in a strange way. The eternal water block freezes and turns to ice when in an oxygenated space I have no idea how this happens if it is considered a block. even if i place torches around the block it freezes.

**Comment by rubensworks** [comment]
> what other information is required?

MC version, Forge version, mod version, ...
