### ISSUE TITLE
Input-output issues with“Colossal Blood Chest”

### ISSUE THREAD

**Issue by QQQQQQNB** [rubensworks/EvilCraft#1025]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.30
- Minecraft: 1.19.2
- Forge: 43.3.8

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you give some more details on what the problem is exactly, and how to reproduce it?

**Comment by QQQQQQNB** [comment]
![B6415D552A63F6BC9269951AFAC9D111](https://github.com/CyclopsMC/EvilCraft/assets/78477862/132ae289-af01-42aa-a74b-06a13d880d07)
![CDB60C92EC1FDF1E87BB1E9689C83D59](https://github.com/CyclopsMC/EvilCraft/assets/78477862/6be46e70-0b7c-4196-af82-9eea5bc6e173)
There can only be one 'Colossal Blood Chest' in the structure, 
which can input items while on top of it, but cannot output items. It can output items while it is underneath, but cannot import items.
I want this structure to be so that any face can be interacted with. Alternatively, any face of the 'Colossal Blood Chest' can support input and output
sourry my english is not good,I hope I'm clear enough

**Comment by rubensworks** [comment]
Can you try the sides? Those should be able to input as well.
Output is only bottom indeed.

**Comment by QQQQQQNB** [comment]
I have already tried, but I cannot input from the side either

**Comment by rubensworks** [comment]
Ok, thanks for checking!
