### ISSUE TITLE
Effortless Ring doesn't affect step height when Apotheosis is also loaded

### ISSUE THREAD

**Issue by qyurila** [rubensworks/EvilCraft#1026]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Effortless Ring doesn't seem to give player a step assist when there is Apotheosis loaded at the same time.

#### Steps to reproduce the problem:

1. Install the latest EvilCraft, Apotheosis, and their dependencies on a Forge instance.
2. Give player an Effortless Ring.
3. Try to step up 1 block height. (it doesn't work)

#### Expected behaviour:

The player should be able to step up 1 block height when the Effortless Ring is given.

____

##### 1.20.1

- This mod: 1.2.38
- Minecraft: 1.20.1
- Forge: 47.1.3

<details>
<summary>other mods</summary>

- Cyclops Core: 1.19.1
- Apotheosis: 7.3.4
  - Apothic Attributes: 1.3.4
  - Patchouli: 1.20.1-84-FORGE
  - Placebo: 8.6.1

</details>

##### 1.19.2

- This mod: 1.2.31
- Minecraft: 1.19.2
- Forge: 43.3.0

<details>
<summary>other mods</summary>

- Cyclops Core: 1.19.1
- Apotheosis: 6.5.0
  - Patchouli: 1.19.2-77
  - Placebo: 7.4.0

</details>

Didn't check the other versions

#### Log file:

---

P.S. Can you believe that this issue has been around for at least [8 months](https://www.reddit.com/r/allthemods/comments/169hvs3/update_woes) now and nobody who plays ATM8/ATM9 or other modpacks (FTB University, in my case) has had a chance to enjoy the full potential of the glorious Effortless Ring? It's unfortunate that this hasn't been reported already...

**Comment by rubensworks** [comment]
Thanks for reporting!
