### ISSUE TITLE
I can't place tinkers construct tools in the blood chest

### ISSUE THREAD

**Issue by Nodajecode** [rubensworks/EvilCraft#1028]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I have a problem with evilcraft and tinkers construct, the book "The Origins Of Darkness" says that the tinkers constrct tools can be fixed, however it does not allow me to place them in it.

#### Steps to reproduce the problem:

1. put blood chest 
2. open the blood chest
3. try to put some tools or armor from tinker construct mod 

#### Expected behaviour:

im use a personal server im already search on the configuration of the mod but nothing seems to be causing conflicts
____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.32
- Minecraft: Minecraft 1.19.2
- Forge: forge-1.19.2-43.4.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Yeah, the book is outdated. Compat support hasn't been around for several versions.
