### ISSUE TITLE
Error in the texture of the blook in the purifier

### ISSUE THREAD

**Issue by 0Trinster0** [rubensworks/EvilCraft#1029]
the blook has no texture in the purifier:/

![2024-07-04_18 39 43](https://github.com/CyclopsMC/EvilCraft/assets/150207340/2649b072-a55d-4fa2-85f9-1eaf8a5233df)

**Comment by rubensworks** [comment]
@0Trinster0 Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
