### ISSUE TITLE
Error in the texture of the blook in the purifier ( 2.0 )

### ISSUE THREAD

**Issue by 0Trinster0** [rubensworks/EvilCraft#1030]
#### Issue type:

- :bug: Bug 

____  Bug (Visual Bug)

![2024-07-04_18 39 43](https://github.com/CyclopsMC/EvilCraft/assets/150207340/f7e24d17-5558-4401-8b1a-68dcf96d78bb)

#### Steps to reproduce the problem: 

1. place the purifier
2. put a blook inside the purifier

#### Expected behaviour:

____ I would like the blook texture to be visible.

#### Versions:

- This mod: EvilCraft-1.20.1-1.2.40
- Minecraft: 1.20.1
- Forge: 47.3.4

#### Log file: 
[latest.log](https://github.com/user-attachments/files/16111997/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!
