### ISSUE TITLE
Error on 'Advanced Blood Infusion' (web) book page

### ISSUE THREAD

**Issue by met4000** [rubensworks/EvilCraft#1031]
#### Issue type:

- :bug: Bug 

____

#### Short description:

After the recipes for the promise of tenacity tiers I and II, there is a duplicate recipe for tier II rather than one for tier III.
In-game book has not been checked.

#### Steps to reproduce the problem:

The first and last saves of the web book in the wayback machine have this problem ([Dec 2022](https://web.archive.org/web/20221231104859/https://evilcraft.rubensworks.net/book/second_age/blood_infusion/advanced_blood_infusion.html), and [Nov 2023](https://web.archive.org/web/20231127082543/https://evilcraft.rubensworks.net/book/second_age/blood_infusion/advanced_blood_infusion.html)) in addition to the current copy of the web book (as of making this issue) - https://evilcraft.rubensworks.net/book/second_age/blood_infusion/advanced_blood_infusion.html

![image](https://github.com/user-attachments/assets/aa81e9c0-496b-4426-aeb9-e646577dcb57)

#### Expected behaviour:

The recipe for promise of tenacity tier III is shown rather than a duplicate for tier II.

____

#### Versions:

N/A - also see wayback machine links in the reproduction section

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Fixed, but the website may only be updated later.
