### ISSUE TITLE
Crash. Mod not loaded.

### ISSUE THREAD

**Issue by Drexiz97** [rubensworks/EvilCraft#1032]
[crash-2024-02-21_13.19.02-server.txt](https://github.com/user-attachments/files/16276615/crash-2024-02-21_13.19.02-server.txt)

#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You're installing the wrong EC version (1.20.1) for the wrong MC version (1.20.4).

**Comment by Drexiz97** [comment]
Hello.

In Modrinth the latest mod version for Forge 1.20.4 was 1.20.1. The rest of
versions was for NeoForge. Is there any other Mod page where it is updated?

**Comment by rubensworks** [comment]
The MC 1.20.4 version is here: https://modrinth.com/mod/evilcraft/version/1.20.4-1.2.38
Only NeoForge though.

<blockquote><img src="https://cdn.modrinth.com/data/3ANq2btA/icon.png" width="48" align="right"><div><img src="/favicon.ico" height="14"> Modrinth</div><div><strong><a href="https://modrinth.com/mod/evilcraft/version/1.20.4-1.2.38">1.20.4-1.2.38 - EvilCraft</a></strong></div><div>Download EvilCraft 1.20.4-1.2.38 on Modrinth. Supports 1.20.4 Neoforge. Published on Jun 24, 2024. 32 downloads.</div></blockquote>

**Comment by Drexiz97** [comment]
Ok, thank you.
