### ISSUE TITLE
[1.21]EvilCraft Crash with Common Capabilities

### ISSUE THREAD

**Issue by Periam** [rubensworks/EvilCraft#1034]
#### Issue type:

- :bug: Bug 

____

#### Short description:

After installing EvilCraft with common capabilities the game crash

#### Steps to reproduce the problem:

1. Install Mods and depencies
2. Run MC

#### Expected behaviour:

To launch the game

____

#### Versions:

- This mod:  EvilCraft-1.21-neoforge-1.2.40
- Minecraft: NeoForge 21.0.113
- Common Capabilties: 1.21-neoforge-2.9.1 

#### Log file:
[debug.log](https://github.com/user-attachments/files/16322429/debug.log)
[latest.log](https://github.com/user-attachments/files/16322430/latest.log)

[crash-2024-07-20_17.01.18-fml.txt](https://github.com/user-attachments/files/16322432/crash-2024-07-20_17.01.18-fml.txt)

![Screenshot 2024-07-20 170206](https://github.com/user-attachments/assets/7278ef30-ed11-4374-96f8-590f93b679d9)

**Comment by rubensworks** [comment]
Thanks for reporting!
