### ISSUE TITLE
[1.21 NeoForge]: Chalice model texture is 1024x1024 when it should be like 42x42

### ISSUE THREAD

**Issue by TelepathicGrunt** [rubensworks/EvilCraft#1035]
Someone checked the texture and found that it was massive:
https://github.com/CyclopsMC/EvilCraft/blob/master-1.21/src/main/resources/assets/evilcraft/textures/model/chalice.png

Which is odd as this texture doesn't need 1024x1024 resolution. It should be just 42x42 and then resized in renderer as needed. Be sure to check the other textures as well. Shrinking will lower file size and may help performance.

**Comment by rubensworks** [comment]
Even worse, I think the texture is not even being used...
