### ISSUE TITLE
No Dark Ore generating in world.

### ISSUE THREAD

**Issue by Lychosis** [rubensworks/EvilCraft#1037]
#### Issue type:

- :bug: Bug, Dark Ores don't seem to spawn during world gen.

____

#### Short description:

I added Evilcraft to All The Mods 10 and after traveling great distances I found no Dark Ore having generated despite noticing Environmental Accumulators generating in the same chunks.  I tried Mekanism digital miner and digging my own strip mines to look for it.  I found nothing.  I checked in ATM discord and found others reporting the same.  No one had a soultion.  Then I then created a test world in 1.21 with just Evilcraft and Mekanism (for the digital miner) to rule out other mods and found none in that test world either.  

#### Steps to reproduce the problem:

1. Added Evilcraft to All the Mods 10 and started a new 1.21 instance with just Evilcraft and Mekanism and there was no Dark Ore in the world.

#### Expected behaviour:

Dark ore spawning in the world.
____

#### Versions:

- This mod: 1.2.41, 1.2.42 and 1.2.43
- Minecraft: 1.21
- Forge: Using Neoforge 21.0.86 and 21.0.115

#### Log file:

n/a

**Comment by rubensworks** [comment]
Thanks for reporting!
