### ISSUE TITLE
Dark ore block not turning into gems.

### ISSUE THREAD

**Issue by Lychosis** [rubensworks/EvilCraft#1038]
#### Issue type:

- :bug: Bug No Dark Gems from ore.

____

#### Short description:

Issue #1037 was closed. It fixed the issue of adding Dark Ore generation to new worlds however now when you break the Dark Ore block, it doesn't turn into Dark ore gems.

#### Steps to reproduce the problem:

1. Spawn a new world.
2. Find Dark Ore
3. Break Dark Ore block
4. Instead of turning into gems you get the Dark Ore block.  
5. Tested with normal pick and fortune pick.  Both gave the block back instead of the gems.
6. Also unable to put block in furnace to process into gems (if that is intended?)

Tested both in new Test World using just Evilcraft and Mekanism (for the digital miner to find the ore) and in ATM10.  Same results in both.

#### Expected behaviour:

Dark ore block should break into dark gems.
____

#### Versions:

- This mod: 1.2.45
- Minecraft: 1.21
- Forge: Neoforge 21.0.86 and 21.0.117

**Comment by rubensworks** [comment]
Thanks for reporting!
