### ISSUE TITLE
Lighting up a Lightning Bomb crashes game

### ISSUE THREAD

**Issue by Jmpp2909** [rubensworks/EvilCraft#1040]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Lighting up a lighting up crashes client

#### Steps to reproduce the problem:
Be in server
Light up a Lightning Bomb

#### Expected behaviour:
Not crashing

____

#### Versions:
EvilCraft-1.21-neoforge-1.2.46.jar

- This mod: 1.2.46
- Minecraft: 1.21
- Forge: neoforge-21.0.134

#### Log file:
https://mclo.gs/FMumyCv

**Comment by rubensworks** [comment]
Thanks for reporting!
