### ISSUE TITLE
forge 1.21

### ISSUE THREAD

**Issue by dopdoptoi** [rubensworks/EvilCraft#1044]
#### Issue type: version

- :heavy_plus_sign: Feature request 

____

#### Short description:

I need the mod for the last version of forge, most of the mods i use are nor in neoforge

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Forge is not supported, only NeoForge.

**Comment by dopdoptoi** [comment]
> Forge is not supported, only NeoForge.

¿? is not supported? but in the before version its supported

**Comment by Jack-McKalling** [comment]
> > Forge is not supported, only NeoForge.
> 
> ¿? is not supported? but in the before version its supported

He means that Forge is not supported anymore for Minecraft versions after 1.20.1, since we're following NeoForge onwards. It is too much time-consuming to support multiple modloaders for the same version.
