### ISSUE TITLE
Environmental Accumulators crashing game

### ISSUE THREAD

**Issue by djnifos** [rubensworks/EvilCraft#1045]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Using an environmental accumulator in 1.21 neo versions 148 or 151 will crash the game.  

#### Expected behaviour:

____

#### Versions:

- This mod: 1.2.49
- Minecraft: 1.21
- NeoForge: 21.0.148 - 21.0.151
- Pack: ATM 10 

#### Log file:

https://mclo.gs/Q3Ddek3
https://mclo.gs/RKEPcNh

**Comment by rubensworks** [comment]
Thanks for reporting!
