### ISSUE TITLE
Purifier does not purify items from curses

### ISSUE THREAD

**Issue by MarwenX3M** [rubensworks/EvilCraft#1046]
#### Issue type:

- :bug: Bug 

____

#### Short description:
The purifier does not purify items from curses

#### Steps to reproduce the problem:

Make a purifier, fill it with blood and insert a cursed item, such as a Vengeance Pickaxe

1. ...

#### Expected behaviour:

The curse would disappear from the item and a animation would accompany this

____

#### Versions:

- This mod: 1.2.50
- Minecraft: 1.21
- Forge: Neoforge 21.0.163

Tried in ATM 10 as well as a separate on a profile with only Evilcraft

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Curses can not be removed from the Vengeance Pickaxe on purpose.
It should work on all other items though. (please let me know if this is _not_ the case)
