### ISSUE TITLE
The textures of the broom don't work well for me.

### ISSUE THREAD

**Issue by alexo202** [rubensworks/EvilCraft#1047]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by alexo202** [comment]
![Uploading 2024-08-16_17.47.13.png…]()

**Comment by alexo202** [comment]
![2024-08-16_17 47 13](https://github.com/user-attachments/assets/5aba7ca7-2a0d-4652-acf8-0d6d783c300e)

**Comment by alexo202** [comment]
I would like help on how to fix it.

**Comment by rubensworks** [comment]
What MC version are you using?

From your screenshot, it also seems you're using a shader mod, which may be breaking things. Could you try disabling it? And if that caused the problem, I recommend reporting it to the shader's mod issue tracker.
