### ISSUE TITLE
using Purifier with Blook on Enchanted Book crashes the game

### ISSUE THREAD

**Issue by NielsPilgaard** [rubensworks/EvilCraft#1048]
Relayed from https://github.com/EnigmaticaModpacks/Enigmatica10/issues/88

#### Issue type:

- :bug: Bug 

____

#### Short description:

Using the Purifier from EvilCraft with Blook on Enchanted Book crashes the game

#### Expected behaviour:

I was hoping to split the enchantments from random enchanted book I found

____

#### Versions:

- This mod: EvilCraft-1.21-neoforge-1.2.50
- Minecraft: 1.21.0
- Mod loader version: NeoForge 21.0.166

#### Log file:

https://gist.github.com/rybacki-t/6d0e0d3cb2f6e5c125c0eba37151be07

**Comment by rubensworks** [comment]
Thanks for reporting!
