### ISSUE TITLE
Memory Leak of Ingredients

### ISSUE THREAD

**Issue by pietro-lopes** [rubensworks/EvilCraft#1049]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

Ingredient is being stored in *Identity Map* without any cleanup on reload logic.

#### Steps to reproduce the problem:

1. join game
2. use your IDE to watch for `SanguinaryEnvironmentalAccumulatorRecipeJEI.RECIPE_WRAPPERS_2`

1st load:
![image](https://github.com/user-attachments/assets/3efdb206-39d6-4246-bbfd-75e63991d506)

2nd load:
![image](https://github.com/user-attachments/assets/0386d9dc-f55e-4ef5-a13c-b3d813d58a16)

____

#### Versions:

- This mod: 1.2.51
- Minecraft: 1.21.1
- Forge: 21.1.21

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Ouch, good catch. Looks like this one has been around for a long time.
