### ISSUE TITLE
After using the Broom it gives you creative flight

### ISSUE THREAD

**Issue by DexxKnight1** [rubensworks/EvilCraft#1050]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When I use the broom it gives me creative flight but you still get fall damage.

#### Steps to reproduce the problem:

1. Fly with the broom.
2. Let the broom.
3. I get creative flight (with fall damage)

#### Expected behaviour:

Don't want the creative flight after using my broom.

#### Versions:

- This mod: 1.2.37
- Minecraft: 1.19.2
- Mod loader version: Forge 43.4.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Are you using any other mods? If so, could you retry without other mods installed?

**Comment by ModernGamingWorld** [comment]
@rubensworks This issue is still happening in 1.19.2 and causing issues. Could you please fix the issues for 1.19.2, so people who use the mod can enjoy it without having creative flight

**Comment by rubensworks** [comment]
@ModernGamingWorld Since this issue is not reproducible on my end, there may be a mod causing conflicts in your pack. Could you try removing mods until you find the offending one?
