### ISSUE TITLE
Memory Leak of Server

### ISSUE THREAD

**Issue by pietro-lopes** [rubensworks/EvilCraft#1051]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

This field is storing statically this event, which contains Entity, that contains ServerLevel that contains MinecraftServer.
https://github.com/CyclopsMC/EvilCraft/blob/fe0ef57dfcda0001c5399cc1fb6ac6fa107abd4a/src/main/java/org/cyclops/evilcraft/enchantment/entityeffect/EnchantmentEntityEffectHealFromDamage.java#L31

You may want to add a cleanup strategy or rework this to not hold the event.

#### Steps to reproduce the problem:

1. Join World
2. Punch a skeleton in the face
3. Leave world to Main Menu
4. Check memory for objects, and server, levels, entity are all there.

____

#### Versions:

- This mod: 1.2.51
- Minecraft: 1.21.1
- Forge: 21.1.23

#### Profiler output:

![image](https://github.com/user-attachments/assets/aa3d39e8-8bfa-4b40-add4-a05c5043b4d1)

**Comment by rubensworks** [comment]
Thanks for reporting!
