### ISSUE TITLE
Can't make witches from villagers

### ISSUE THREAD

**Issue by MuteTiefling** [rubensworks/EvilCraft#1052]
This just doesn't seem to work. I always get the werewolf villager. I've hit about 50 villagers with lightning at this point and get no witches.

I'm on Hard difficulty, so I should be getting them. 

https://github.com/CyclopsMC/EvilCraft/blob/fe0ef57dfcda0001c5399cc1fb6ac6fa107abd4a/src/main/java/org/cyclops/evilcraft/event/EntityStruckByLightningEventHook.java#L62C14-L63C47

Mod Version: EvilCraft-1.21.1-neoforge-1.2.53

**Comment by rubensworks** [comment]
Thanks for reporting!
