### ISSUE TITLE
Please provide a config for your villager

### ISSUE THREAD

**Issue by MuteTiefling** [rubensworks/EvilCraft#1053]
#### Issue type:

Overriding a Vanilla mechanic (Lightning turns Villagers to Witches) needs to have a config to disable. Other mods can be dependant on such mechanics. 

____

#### Short description:

Please create a config that disables the lightning conversion and instead gives villagers a standard Point of Interest to convert. Or some other form of conversion.

**Comment by rubensworks** [comment]
Thanks for the suggestion!
