### ISSUE TITLE
Blood Chest java.lang.IllegalArgumentException: Bound must be positive

### ISSUE THREAD

**Issue by MuteTiefling** [rubensworks/EvilCraft#1054]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Game crashed when blood chest ran out of blood

#### Steps to reproduce the problem:

1. Place Blood Chest
2. Supply a limited amount of blood
3. put items in to repair
4. crash when it runs out of blood

#### Expected behaviour:
no crash

____

#### Versions:

- This mod: 
- Minecraft: 1.21.1
- Mod loader version: neoforge 21.1.31

#### Log file:

https://gist.github.com/MuteTiefling/31a80e611e58ca238e3377862410fdbf

**Comment by rubensworks** [comment]
Thanks for reporting!
