### ISSUE TITLE
Many pages appear to be missing from the book

### ISSUE THREAD

**Issue by MuteTiefling** [rubensworks/EvilCraft#1055]
#### Issue type:

- :bug: Bug 

____

#### Short description:

A good 50% of the book is just blank pages

#### Steps to reproduce the problem:

1. Open book
2. Flip through it

#### Expected behaviour:
Book should book :D

____

#### Versions:

- This mod: 
- Minecraft: EvilCraft-1.21.1-neoforge-1.2.53
- Mod loader version: neoforge 21.1.31

#### Log file:

![image](https://github.com/user-attachments/assets/d25f082a-146b-4a96-b5d1-2cc4e061585a)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Do you have any other mods installed?
If so, could you try without any other mods?

**Comment by MuteTiefling** [comment]
Lots. I can try doing a binary search to see what might be doing it if you're sure the book is otherwise fine.

**Comment by MuteTiefling** [comment]
No added mods. Only EvilCraft. Not even JEI:

![image](https://github.com/user-attachments/assets/81835f45-25a9-4c77-8cb1-25e7ebe85d94)

**Comment by MuteTiefling** [comment]
https://gist.github.com/MuteTiefling/4fbf8a0826c51fae63dfcff288baf545

<blockquote><img src="https://github.githubassets.com/assets/gist-og-image-54fd7dc0713e.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/MuteTiefling/4fbf8a0826c51fae63dfcff288baf545">latest.log</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by rubensworks** [comment]
Thanks for checking!
