### ISSUE TITLE
EVILCRAFT CRASH WHEN USING BROOM 1.20.1

### ISSUE THREAD

**Issue by AntonioKeyxer** [rubensworks/EvilCraft#1056]
#### Issue [type:]([crash-2024-09-03_19.06.26-server.txt](https://github.com/user-attachments/files/16853787/crash-2024-09-03_19.06.26-server.txt))

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Server crash report mensions error with evilcraft entity Broom

#### Expected behaviour:

____

#### Versions:

- This mod: 1.20.1 - 1.2.45
- Minecraft: Java 1.20.1
- Mod loader version: Forge 47.2.20

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by UnluckyGuyy** [comment]
Just got the same playing on the All The Mod 9 modpack, upon loading the chunk, the server crash.
It happened after my friend added 4 redstone to it's broom and getting on it.
I advise to make regular backup when using the mod.

**Comment by rubensworks** [comment]
@UnluckyGuyy That seems unrelated this the crashlog reported above.
If the log is indeed different, please create a different issue for it, so I can look into it.
