### ISSUE TITLE
Spirit furnace - no more space for drops error

### ISSUE THREAD

**Issue by kurpav00** [rubensworks/EvilCraft#1058]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When cooking a mob that has lots of drops in the Spirit Furnace, the process stops after one iteration saying "No more space for drops" and does not resume automatically if the drops are pulled out of the output slots using hopper or a pipe. The player has to manually re-insert the Box of Eternal Closure in order for the cooking to resume. This behavior has been observed in case of multiple modded mobs that produce a large amount of multiple types of drops.

#### Steps to reproduce the problem:

1. Install EvilCraft together with e.g. Iron's Spells 'n Spellbooks
2. Make Box of Eternal Closure containing the The Dead King
3. Create a Spirit Furnace with blood supply; hopper out its output into a chest
4. Insert the Box with The Dead King
5. Wait for the cooking to complete to see "No more space for drops" even after the hopper removes all the drops from the output slots

#### Expected behaviour:

The Spirit Furnace should continue working automatically after the drops from the output slots are sucked out by a hopper.

____

#### Versions:

- This mod: EvilCraft-1.20.1-1.2.46
- Minecraft: 1.20.1
- Mod loader version: Forge 47.3.7

**Comment by rubensworks** [comment]
Thanks for reporting!
