### ISSUE TITLE
crash with the enchanted chalices in server

### ISSUE THREAD

**Issue by loquende33** [rubensworks/EvilCraft#1060]
#### Issue type:crashh
[2024-09-13-4.log.gz](https://github.com/user-attachments/files/17006761/2024-09-13-4.log.gz)

- :bug: Bug 

____
description:When I try to enter my server the game throws me an error and does not let me enter. I have been investigating and it is because of the evilcraft mod, more specifically because of the enchanted chalices of the mod. When I place them and leave the server, it no longer lets me enter, causing the following error: Lost Connection
Internal Exception: java.lang.NullPointerException: Cannot invoke "net.minecraft.client-player-LocalPlayer.m_9236_()" because "net.minecraft.client.Minecraft.m_91087_().F_91074_" is null.
´
This is due to the enchanted chalices and I would like to know if there is a way to solve it and be able to use them.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you share your crashlog and the used mod/MC versions?
