### ISSUE TITLE
Mod loading error on Neoforge 1.20.4.

### ISSUE THREAD

**Issue by ornithophobe** [rubensworks/EvilCraft#1061]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Upon launching the game from the Minecraft Launcher with Evilcraft installed, the game will boot to the "Error loading mods" screen.

#### Steps to reproduce the problem:

1. Create a NeoForge modpack with Evilcraft. It does not matter if other mods are installed, as long as it has CyclopsCore and Evilcraft.
2. Boot minecraft.
3. 
![image](https://github.com/user-attachments/assets/62931e27-f805-4419-9e51-0e71d39380fd)

#### Expected behaviour:
Game boots normally to the menu.

____

#### Versions:

- This mod: EvilCraft-1.20.4-neoforge-1.2.38.jar, CyclopsCore-1.20.4-neoforge-1.19.3.jar
- Minecraft: 1.20.4
- Mod loader version: NeoForge 20.4.237

#### Log file:

[debug.log](https://pastebin.com/5Nv36xtX)
[latest.log](https://pastebin.com/0WDGvVpk)
[crash log](https://pastebin.com/Bmph79Th)

If any other information is needed, feel free to contact me on Discord at @barneycalh0un

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
1.20.4 is not maintained anymore unfortunately. But your problem can be solved by installing the CommonCapabilities mod.
