### ISSUE TITLE
[Server Crash] The server crashes on launch

### ISSUE THREAD

**Issue by Dinocraft1515YT** [rubensworks/EvilCraft#1063]
#### Issue type: Crash

- :bug: Bug

____

#### Steps to reproduce the problem:

1. Install NeoForge 1.21.1 as a server on your PC
2. Install the mod for the latest version (1.21.1) with this modpack I made: https://drive.google.com/file/d/1oUsEMtHHWoAylPFJkzm2vHLXks_PdYMM/view?usp=sharing
3. Execute the server
4. Server crash

#### Expected behaviour:

Server should start, but it doesn't.

#### Versions:

- This mod: 1.2.56
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.57

With only this mod and CyclopsCore, the server starts correctly

#### Log file:
[latest.log](https://github.com/user-attachments/files/17084218/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Dinocraft1515YT** [comment]
when install, delete "Open Parties & Claims", we have an issue with the client side, I'll delete it from the modpack

**Comment by rubensworks** [comment]
Could you share the crashlog?

**Comment by Dinocraft1515YT** [comment]
Here is the crash log
[crash-2024-09-21_15.53.25-fml.txt](https://github.com/user-attachments/files/17084270/crash-2024-09-21_15.53.25-fml.txt)

**Comment by rubensworks** [comment]
Could you try removing mods until it stops breaking?
There may be a mod in your pack that messes with block registration orders.

**Comment by Dinocraft1515YT** [comment]
Vibranium

**Comment by rubensworks** [comment]
Thanks for checking!
Could you report it to their issue tracker and link back here?
Happy to make changes here if that would be needed.
