### ISSUE TITLE
Item Tag Additions

### ISSUE THREAD

**Issue by TheBedrockMaster** [rubensworks/EvilCraft#1065]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

It would be nice if the following items got these item tags added in 1.21.1 Neoforge:

Dark Gem: `c:gems`
Vein Sword: `c:tools/melee_weapon`, `minecraft:swords`
Vengeance Pickaxe: `c:tools/mining_tool`, `minecraft:pickaxes`
Dark Ore: `c:ores_in_ground/stone`
Deepslate Dark Ore: `c:ores_in_ground/deepslate`
Stripped Undead Log: `minecraft:logs_that_burn`
Reinforced Undead Plank Stairs: `minecraft:stairs`
Dark Brick Stairs: `minecraft:stairs`
Dark Blood Brick Stairs: `minecraft:stairs`
Undead Fence Gate: `minecraft:fence_gates`, `c:fence_gates/wooden`

**Comment by rubensworks** [comment]
Thanks for the suggestion!
