### ISSUE TITLE
Spawned-in empty Weather Containers do not work with Environmental Accumulator

### ISSUE THREAD

**Issue by Realta23** [rubensworks/EvilCraft#1067]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Spawned-in empty Weather Containers do not work with Environmental Accumulator. Crafted Weather Containers work as intended.

#### Steps to reproduce the problem:

1. Load new world with vanilla Minecraft (Java) with the addition of the two mods: Cyclops Core and EvilCraft.
2. Enter creative mode. 
3. Spawn in Weather Container (empty) from creative inventory
4. Drop spawned Weather Container on Environmental Accumulator in a dark temple. 
5. Wait for animation to end
6. Receive identical empty Weather Container. 

#### Expected behaviour:
Both spawned in and hand crafted empty weather containers are expected to fill with the current weather.

____

#### Versions:

- This mod: EvilCraft 1.21.1 - neoforge-1.2.58.jar with CyclopsCore 1.21.1 - neoforge - 1.25.1.jar
- Minecraft: Java
- Mod loader version: Neoforge 21.1.72

**Comment by rubensworks** [comment]
Thanks for reporting!
