### ISSUE TITLE
Cannot purify Vengeance Pickaxe

### ISSUE THREAD

**Issue by uhloin** [rubensworks/EvilCraft#1069]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Purifier doesn't purify Curse of Vengeance III from Vengeance Pickaxe

____

#### Versions:

- This mod: 1.2.59
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Curses can not be removed from the Vengeance Pickaxe.
This is by design, as the pickaxe would be to op otherwise.
