### ISSUE TITLE
Vengeance Spirits block movement

### ISSUE THREAD

**Issue by uhloin** [rubensworks/EvilCraft#1070]
#### Issue type:

- :bug: Bug 

____

#### Short description:

After kill mob invisible Vengeance Spirit blocks player movement as usual mob. 

____

#### Versions:

- This mod: 1.2.59
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can you try reproducing without any other mods installed?
Because I can't reproduce the problem.

**Comment by uhloin** [comment]
I'm trying in the creative mode, but cannot create spirits. In my survival world they just start appearing since some unknown moment. But I can see them on Хaero map. I didn't create evilcraft rings yet. Could you say conditions to start Vengeance Spirits generation?

**Comment by rubensworks** [comment]
Mining with a vengeance pickaxe, or killing mobs with an enabled vengeance ring should work.

**Comment by uhloin** [comment]
Looks like I triggered generation by kill mob with spiked plate. And without other mods cannot reproduce, I will find a problematic mod.

**Comment by uhloin** [comment]
I found that issue is related to Lithium mod. 
Do not know which of mods (Evilcraft or Lithium) makes wrong things, so here is a duplicate:
https://github.com/CaffeineMC/lithium-fabric/issues/578

**Comment by rubensworks** [comment]
Aha, good catch!
