### ISSUE TITLE
[Suggestion] Tweak vengeance spirit spawning

### ISSUE THREAD

**Issue by Kevin-Marsh** [rubensworks/EvilCraft#1071]
#### Issue type:

Vengeance spirits can cause issues when they randomly spawn visibly with lightning or invisibly.
____

#### Short description:

Would it be possible to change the spawning to require a weapon/ enchantment/ other item to spawn? One potential method would require the player to have a vengeance ring in their possession to spawn and see them rather than just see them. This would eliminate a lot of potential issues going forward and allow players who want to be able to utilise this mechanic to still utilise it.

**Comment by rubensworks** [comment]
> Vengeance spirits can cause issues when they randomly spawn visibly with lightning or invisibly.

What issues are you talking about exactly? Perhaps these can be solved?

In any case, the behaviour you are describing can be achieved by setting the `spawnLimit` config option to `0`.
This will disable vengeance spirit spawning when not killed by a player. Only when a player with a vengeance ring kills a mob, will it spawn a vengeance spirit.
