### ISSUE TITLE
bug blood extractor

### ISSUE THREAD

**Issue by laijara** [rubensworks/EvilCraft#1072]
hi, help me please
i don't understand how to fix  bug
version forge 1.20.1

when I try to pour blood on the block, the blood extractor, which was combined with others, resets to the original 5000 mb, and also all the blood in it disappears, there is a feeling that it resets the tag of the item to the initial one, please help

link to the video showing the bug
https://youtu.be/Pn35Fx9Zo7s

**Comment by laijara** [comment]
Wines Mod Mo ' Enchantments version 1.20.1-1.10

**Comment by Jack-McKalling** [comment]
Could you please use the existing template for a bug? We need more information about your environment and steps to reproduce it. If you use the template we'll be able to better help you.

You can edit your post and copy paste the template text into it, that you get if you click the New Issue button, and then you can fill in all the missing info.

**Comment by laijara** [comment]
WARNING!!!!
I used a language translator to communicate with you, the translation may be incorrect in places, I'm sorry, I don't know English well

The Mo' Enchantments mod is to blame, its version 1.20.1-1.10, I know a little about programming, and I can assume that this bug can be implemented using other mods that will affect the written libraries, most likely the vulnerability is somewhere in the tags of the item, because they are reset when updating the properties of the item, if easier, the interactions with the blocks, as shown in the video, were not observed with previous versions of Mo' Enchantments

verison forge 1.20.1
Cyclops core 1.18.13 - 1.20.1
EvilCraft 1.2.37
Mo' Enchantments - 1.10 - 1.20.1

I downloaded mods from these sources

link Mo'Enchantment - https://www.curseforge.com/minecraft/mc-mods/mo-enchantments/files/5558472
link EvilCraft - https://modrinth.com/mod/evilcraft/version/1.20.1-1.2.37
link Cyclops core - https://modrinth.com/mod/cyclops-core/version/1.20.1-1.18.13




> Could you please use the existing template for a bug? We need more information about your environment and steps to reproduce it. If you use the template we'll be able to better help you.
> 
> You can edit your post and copy paste the template text into it, that you get if you click the New Issue button, and then you can fill in all the missing info.



<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/976/691/256/256/638480774425344013.png" width="48" align="right"><div>CurseForge</div><div><strong><a href="/minecraft/mc-mods/mo-enchantments/files/5558472">Mo' Enchantments</a></strong></div><div>Add highly configurable vanilla-friendly enchantments!
239.4K Downloads | Mods</div></blockquote>
<blockquote><img src="https://cdn.modrinth.com/data/3ANq2btA/4a3de92c4cab2b622027d46b5de67862ce5ef6cc_96.webp" width="48" align="right"><div><img src="/favicon.ico" height="14"> Modrinth</div><div><strong><a href="https://modrinth.com/mod/evilcraft/version/1.20.1-1.2.37">1.20.1-1.2.37 - EvilCraft</a></strong></div><div>Download EvilCraft 1.20.1-1.2.37 on Modrinth. Supports 1.20.1 Forge. Published on Feb 5, 2024. 4587 downloads.</div></blockquote>
<blockquote><img src="https://cdn.modrinth.com/data/Z9DM0LJ4/icon.png" width="48" align="right"><div><img src="/favicon.ico" height="14"> Modrinth</div><div><strong><a href="https://modrinth.com/mod/cyclops-core/version/1.20.1-1.18.13">1.20.1-1.18.13 - Cyclops Core</a></strong></div><div>Download Cyclops Core 1.20.1-1.18.13 on Modrinth. Supports 1.20.1 Forge. Published on Oct 21, 2023. 8399 downloads.</div></blockquote>

**Comment by laijara** [comment]
There are no other mods

**Comment by Jack-McKalling** [comment]
Please use the template for reporting a bug. If you don't use the template this report will automatically close after a while.
