### ISSUE TITLE
How to use the Blood Purifier?

### ISSUE THREAD

**Issue by ZombieFighterTX** [rubensworks/EvilCraft#1073]
#### Issue type: How to use it

- :question: Question 

____

#### Question: I cant seem how to fill up the purifier with blood (In All The Mods 10), ive tried everything ive seen from tutorials i found on youtube but they're outdated. How do i fill it with blood? PLS HELP

 How to fill the Purifier with Blood?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
You can just right-click with a bucket of blood, or pipe in blood fluid with any kind of fluid pipe mod.
