### ISSUE TITLE
Game crash on trying to make spawn egg of non standard entities

### ISSUE THREAD

**Issue by ghost** [rubensworks/EvilCraft#1075]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Relaying on behalf of another: server thread stalls and eventually crashes game when trying to fetch game profile data, when trying to make a spawn egg.

#### Steps to reproduce the problem:

Steps weren't provided to me other than some images
![box](https://github.com/user-attachments/assets/dd211799-8d32-4c0e-ba31-b73695357c2d)
![furn](https://github.com/user-attachments/assets/df2b1b95-509b-45ba-9b3f-1e1d6e37b69d)
![crash](https://github.com/user-attachments/assets/601c9168-6725-49ef-8b69-8e354ca18946)

#### Expected behaviour:

When trying to make spawn egg of things that dont have spawn eggs, halt processing of the item instead of the server thread

____

#### Versions:

- This mod: 1.2.60-552
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.90

#### Log file:

Was not provided. Sorry for low quality report, the user just sounded kinda upset about it so i said "ill see what i can do"

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
I tried to reproduce this with a normal box of eternal closure (containing vengeance spirit) from creative inventory, and it refuses to start the craft. Eventhough there is a spawn egg for vengeance spirits. So unless I did something wrong, I cannot reproduce this.

If you can request steps to reproduce this bug or more info about the circumstances under which they experienced it, or even have them add it to this report themselves, that would help a lot.

**Comment by ghost** [comment]
I have asked the user to apply the updated version and to report back if it fixes the issue

**Comment by ghost** [comment]
User reports it does indeed fix their crashing issue, thank you for your time
