### ISSUE TITLE
Eternal Water Bucket disappears after placing water in world

### ISSUE THREAD

**Issue by ArtpokeBr** [rubensworks/EvilCraft#1076]
#### Issue type:

- :bug: Bug

____

#### Short description:

Just reposting what was reported [here](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6429) And I do confirm that its happening.

#### Steps to reproduce the problem:

1. Use a Eternal Water Bucket
2. Admire the fact that it vanished from your hand!

#### Expected behaviour:

- Eternal Water Buckets should be... Eternal!

____

#### Versions:

- Evilcraft: 1.2.61
- Minecraft: 1.21.1
- Mod loader version: Neoforge - 21.1.85

**Comment by rubensworks** [comment]
Thanks for reporting!
