### ISSUE TITLE
Fancy tooltip info for configurables in config GUI

### ISSUE THREAD

**Issue by immortaleeb** [rubensworks/EvilCraft#206]
When configuring values using the forge GUI (mods > EvilCraft > Config), only the evilcraft identifiers (e.g. darkTemple.maxSpawnHeight) are mentioned, it would be nice if we had some nice descriptions in the tooltips or at least a more prettier name.

**Comment by rubensworks** [comment]
This feature already exists, but because of the Forge bug that config files sometimes have their config comments removed this does not always work. (These tooltips are fed by the config file itself for some reason)
