### ISSUE TITLE
Crash when i disable items while thaumcaft aspects are on

### ISSUE THREAD

**Issue by Zebia** [rubensworks/EvilCraft#209]
http://openeye.openmods.info/crashes/0919ec69e58c0a4d2da2f0973c47ad5e

the above crash happens with version 8.0b when i have any items disabled while "B:Thaumcraft=true" in the config file

**Comment by rubensworks** [comment]
That's indeed a major derp of mine. I'll try to push a fix for this later today. In the meantime you can either enable all disabled element, use the old mod version or disable thaumcraft integration.
