### ISSUE TITLE
Exalted Crafter Tweak

### ISSUE THREAD

**Issue by ShadowsVengeance** [rubensworks/EvilCraft#225]
I think it would be a nice quality of life tweak (if possible) for the exalted crafter "clear button/hotkey" to dump the items into the internal inventory instead of the player inventory. I've been finding myself clearing it and then moving all the items back into the internal inventory a lot. Thanks and keep up the good work! :D

**Comment by rubensworks** [comment]
This might already be possible (haven't tested this yet) when setting the config option `B:exaltedCrafter.shiftCraftingGrid` to `true`.
But I might add a slightly easier option for this in the future.

Note to self: Add toggle button to choose target inventory when removing items from crafting grid with both shift-clicking and crafting grid clearing.
