### ISSUE TITLE
Blood Infuser crash

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [rubensworks/EvilCraft#235]
Suddenly I keep getting this crash:

http://hastebin.com/cotefanuzo.pl

**Comment by rubensworks** [comment]
This must be because some internal Forge library isn't loaded for some reason.
Did you recently update Forge? Maybe something got corrupted, in which case you should try re-installing Forge.

**Comment by Unrepentant-Atheist** [comment]
I did actually. Now that you mention it. From 1387 to 1388, which completely removed the edited .jar file after installing forge prior 1387. Guess it's back to 1387 again.

**Comment by rubensworks** [comment]
There were apparently some recent changes in FML (d14d1a8fea4c9242c944079ab8e4cdd516dfce4c) that could cause this issue. I'll leave this issue open for now, hopefully the FML change will be reverted or fixed soon.

**Comment by Unrepentant-Atheist** [comment]
It works reverting back to 1387. Cheers.

**Comment by rubensworks** [comment]
The breaking change has been reverted in FML (MinecraftForge/FML@7c10b93a2ded2799d41b73b67a2766c31e992d8a), so one of the next Forge releases should fix this issue.
