### ISSUE TITLE
Vengenance focus not in the book

### ISSUE THREAD

**Issue by wizard1399** [rubensworks/EvilCraft#238]
Hello,

I have been playing with this mod and really love it, however there is no documentation in the book you get from the anomaly on how to capture spirits or about the vengeance focus.  Vengeance focus can be seen in NEI, but the in game book needs to be updated.

**Comment by rubensworks** [comment]
It's under 'Vengeance Spirits' > 'Catching Spirits'.
But 'Vengeance Focus' is not mentioned explicitly, so you're right that this might be better to add.
