### ISSUE TITLE
Vengeance spirit attracts attacks

### ISSUE THREAD

**Issue by kutschkem** [rubensworks/EvilCraft#246]
Vengeance spirits should ideally be ignored by other mobs. Right now mobs that are hostile to the original creature are also hostile against the vengeance spirit. For example, Sentry turrets from PortalGun, Crushrooms from Erebus and others that attack other mobs.

**Comment by rubensworks** [comment]
I'll look into it, this is also the cause of Iron Golems attacking the invisible spirits.

Note to self: Look at EntityAITarget#isSuitableTarget(...)
