### ISSUE TITLE
Client crash - unable to render ModelBloodStainedBlock

### ISSUE THREAD

**Issue by ProsperCraft** [rubensworks/EvilCraft#250]
http://pastebin.com/HKf3YJfy

I was flying around a newly generated world in creative.

**Comment by rubensworks** [comment]
This was fixed in 0acdd2060a19fc3bc684115da25c17618a6de63d.
You can use the latest EvilCraft and Cyclops Core dev builds (http://maven.rubensworks.net/org/cyclops/) for a fix, or wait for a new release (probably this week).
