### ISSUE TITLE
Error by registering event (Enchantment-ID)

### ISSUE THREAD

**Issue by chaos234** [rubensworks/EvilCraft#261]
Hey,

I want to create my own modpack and after a few looks on it, I got this registering error:

http://hastebin.com/ofupopehes.avrasm

Here is the actually full modlist:

http://hastebin.com/xoqedobumi.coffee

**Comment by rubensworks** [comment]
This means you have a plain old conflicting enchantment id.
Either change the id of the 'breaking' enchant in the EvilCraft config file or change the id of the 'soulbound' enchant for the other mod.

**Comment by chaos234** [comment]
Thanks for the replay, I'll try it ou ;).

Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: Ruben Taelman notifications@github.com 
Datum: 27.08.2015  09:23  (GMT+01:00) 
An: CyclopsMC/EvilCraft EvilCraft@noreply.github.com 
Cc: Chaos234 info@deltanet-production.de 
Betreff: Re: [EvilCraft] Error by registering event (Enchantment-ID) (#261) 

This means you have a plain old conflicting enchantment id.

Either change the id of the 'breaking' enchant in the EvilCraft config file or change the id of the 'soulbound' enchant for the other mod.
