### ISSUE TITLE
Dark Sticks

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#275]
Post your Dark Stick problems here

**Comment by JonaBrackenwood** [comment]
![image](https://cloud.githubusercontent.com/assets/1567798/10711519/03498d6e-7a7e-11e5-875b-fb2853cf42dc.png)

Dropping more than one stick causes funny glitches

**Comment by JonaBrackenwood** [comment]
stick almost never points to a temple, even if a temple i generated

**Comment by JonaBrackenwood** [comment]
stick starts spinning in chunks where no temple is present

**Comment by JonaBrackenwood** [comment]
the stick also doesn't point to these spinning chunks...
