### ISSUE TITLE
0.9.0 recipe bug

### ISSUE THREAD

**Issue by BrokenHearted2** [rubensworks/EvilCraft#298]
I didn't notice it till now, but 9.0 has a recipe bug. If you put a dark tank in a crafting bench/window it tries to give you a blood extractor, this is even with more then one tank in it. I thought it was borked on my end so I deleted the config, still messed up. Reverted back to 8.9 and it was fixed, so went back to 9.0 and it came back.
![2015-11-02_16 12 482](https://cloud.githubusercontent.com/assets/12975884/10898275/caa17f6a-817d-11e5-9795-ae44c6f56e92.png)

**Comment by rubensworks** [comment]
Ah, I already know what I did wrong, it's a simple fix.
Thanks for reporting this, expect a fix by tomorrow.

**Comment by BrokenHearted2** [comment]
Awesome, thanks! and keep up the great work, love the mod!

**Comment by rubensworks** [comment]
You can keep this issue open for now, so I don't forget to implement the actual fix :)

**Comment by BrokenHearted2** [comment]
9.1 fixed it kinda, one tank no longer gives a blood extractor but now two tanks do.
![2015-11-03_15 01 142](https://cloud.githubusercontent.com/assets/12975884/10924556/4ae7a438-823c-11e5-9980-75e7e5650879.png)

**Comment by rubensworks** [comment]
I could've sworn I tested this case...
Well, I'll fix it for the next patch release.
