### ISSUE TITLE
1.7.10 Crash on consuming my own flesh.

### ISSUE THREAD

**Issue by Divineaspect** [rubensworks/EvilCraft#300]
http://pastebin.com/yKwDwZfu

To be fair to me, I was really hungry. To be fair to you, I don't see anything in the crashlog that points to you.

**Comment by rubensworks** [comment]
Eating your own flesh? Disgusting!

Is there anything else you can tell me about the situating in which you ate that flesh? Was it day or night? Had you any special potion effects on you? Any special mods that could change consumption of food?
Are you able to reproduce that crash?

**Comment by Divineaspect** [comment]
hrm, nothing that affected food, night, thunderstorm, I did have a night
vision and invisibility buff on.

Jeremiah Grimsley

"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by rubensworks** [comment]
And did you try eating it later on again? Did it result in the same crash?

**Comment by Divineaspect** [comment]
I only had the one piece. Lemmie load up the world and creative some in.

**Comment by Divineaspect** [comment]
Well other then not having any luck setting it to be my own flesh. 
I can't duplicate, due to having lost the artifacts I was wearing... Which I have now retrieved, along with a piece of my own flesh. Saved my inventory so I can now reproduce. One of the artifacts attempt to restore my hunger when it drops below half which may relate to the occasional loss of hunger points when eating flesh.
Eating my own flesh inflicts wither and blindness (which may be intentional) but not the same crash.

**Comment by rubensworks** [comment]
In that case, I'll close this issue, as I don't think it's related to EvilCraft.
I assume it's just a coincidence, and a vanilla bug (I think I saw that one before when playing vanilla).
If you would ever have the same crash, be sure to post it here again.

Thanks for reporting anyways :-)
