### ISSUE TITLE
1.7 Liquid Poison does not dmg while still in fluid

### ISSUE THREAD

**Issue by nanakisan** [rubensworks/EvilCraft#301]
It seems that while you're still in the fluid. The poison stops ticking until you get out. I believe the expected result is for it to continuously damage the player. No matter how long they stand in the fluid.

**Comment by rubensworks** [comment]
Poison should directly not be damaging you, but it should give you the poison potion effect, does this happen for you?

**Comment by nanakisan** [comment]
It does give the poison effect. But as long as you stay in the liquid you're not damaged by the poison effect. It just keeps infinitely ticking and resetting the poison effects counter.

**Comment by rubensworks** [comment]
Hmmm, that is strange. I'll look into it soon and see if I can reproduce it.
Thanks for reporting.

**Comment by nanakisan** [comment]
no problem, glad I could be of assistance.
