### ISSUE TITLE
ID is already registered

### ISSUE THREAD

**Issue by SvEgiiVEteR** [rubensworks/EvilCraft#304]
1710 forge 1541
after installing the mod.
http://hastebin.com/ugipexuzaf.md
full log http://paste.ubuntu.com/13208581/
and .minecraft\dumps\entity.csv
http://hastebin.com/zavotasaya.avrasm

**Comment by rubensworks** [comment]
You have conflicting mob entity id's, you should either change the conflicting mob id in the Runic Dungeons mod config with id 122 or the EvilCraft mob with that id.

**Comment by SvEgiiVEteR** [comment]
entity.csv
(global),122,GalacticraftCore.EvolvedZombie,micdoodle8.mods.galacticraft.core.entities.EntityEvolvedZombie
I understand they are assigned automatically.
because at a workable game, ID 122 from another mod.

no EvilCraft no Runic Dungeons not have an ID that can be changed in the config file.
it could help but there is no ...
if I install just two mod, all is well.(entity.csv http://hastebin.com/iwuvurekoy.avrasm)
problem in automatic ID assigning
it can be corrected on the side of one or another mod.
in the config I can not do that .... :(

https://github.com/clienthax/chococraft/issues/21
A similar problem was when installing this mod(chococraft) + Galaxy Space

**Comment by rubensworks** [comment]
Ok, I forgot that EvilCraft uses Forge's automatic mob id assignment, which hides entity configuration for the players.
Your entity csv indicates that the galacticraft mod causes the incorrect mob registration.

I'm also not quite sure why you are posting this crash here, since this is a conflict between Runic Dungeons and Galacticraft...

**Comment by SvEgiiVEteR** [comment]
between these modes is no problem.
the problem occurs when I install EvilCraft.
probably after installing mod ID shifted to other values

java.lang.IllegalArgumentException: ID is already registered: 122
    at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:94)
    at net.minecraft.entity.EntityList.func_75614_a(EntityList.java:108)
but runicdungeons (global),117,Guardian,mrcomputerghost.runicdungeons.entity.EntityGuardian
For this reason I wrote you.

I wrote Runic Dungeons
about a similar problem with other mods
https://github.com/MrComputerGhost/Runic-Dungeons/issues/26
but .. the answer and the solution was not.
For this reason, I am hoping that you can fix it on the side of your mod ...

**Comment by rubensworks** [comment]
Sorry, there's nothing I can do about another mod is not using the Forge API correctly.
For the rest of your search, use `findGlobalUniqueEntityId()` as keyword, this is the method that mods should call when registering a mob with a global id, and I assume that one mod in your pack is not calling this method what causes other mods to fail.
