### ISSUE TITLE
vengence spirit not so vengeful

### ISSUE THREAD

**Issue by ewsmith** [rubensworks/EvilCraft#305]
vengence spirits find two block tall spaces so comfortable that they don't hate me :c
tested with mc18 and the vengence pick

**Comment by rubensworks** [comment]
Do these spirits spawn in these two-block tall spaces? Or do they stop moving/attacking once they are in such a two-block tall space?

**Comment by ewsmith** [comment]
only if they spawn in the two block spaces
in my branch mine they ignore me but near the entrance of the branch mine (a normal cave) they run in and attack me

**Comment by rubensworks** [comment]
Finally got around to testing this...
The spirit height is the same as its original mob, so if that mob is taller than two blocks, it won't be able to move in such spaces.
Note that degraded spirits (the swarms), have a random height, so some of them will be able to move in two-block tall spaces, others won't.

But thanks for reporting this anyways! :)
