### ISSUE TITLE
Spirit Reanimator spawn eggs

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#313]
If you try to use the Spirit Reanimator on most non-Vanilla mobs that have Spawn Eggs it simply doesn't work

**Comment by Blue64** [comment]
Are there any exceptions? Perhaps it would help to narrow down the problem if we knew either what does, or what doesn't work.

**Comment by rubensworks** [comment]
Apparently not, but I have a good idea what the problem might be, so I don't expect much trouble fixing this.

**Comment by Blue64** [comment]
Is this limited to 1.8 only, or can I expect to see this with 1.7.10 (for example, I have Dire Witch Vengeance Spirit)

**Comment by rubensworks** [comment]
For 1.7.10 you can only reanimate mobs which have a global entity id (which includes all vanilla and evilcraft mobs, but not all mod mobs will have this)
For 1.8, Forge did some changes with spawn eggs which makes it possible for all mod mobs to be contained in a spawn egg.

I was planning on making a custom spawn egg item which would circumvent this issue, but since 1.8 introduced a clean workaround for this, I won't implement this for just 1.7.10.

**Comment by Blue64** [comment]
Would it be difficult? Because I'd totally use a mod like that lol

**Comment by rubensworks** [comment]
No, not at all.
But it would take time, time I'd rather spend on other things, because this custom spawn egg would just exist for 1.7.10.
Everyone seems to be going to 1.8 now (which is good), so I want to focus on that as well.

**Comment by Blue64** [comment]
I personally don't desire to move to 1.8 because I prefer the Mojang version over the Microsoft version. I know Mojang had their reasons for selling, but I don't like how Microsoft has been handling their Software stuff lately, eg. Win8, Win10, and they even patched Win7 so that it's no longer possible to play Sid Meijer's Civilization 4 because "it has known issues" even though I was playing it just fine before updating my Win7.

**Comment by rubensworks** [comment]
It's still the same people working on the game :)
IMO, the internal code structure has improved a lot, so as a mod developer I want to fully move to 1.8+ as soon as possible.

**Comment by Blue64** [comment]
I would like to point out: [THIS](http://forum.industrial-craft.net/index.php?page=Thread&postID=192320#post192320) so not everyone will be on 1.8 lol perhaps you should set the sights on a trifecta of 1.7.X~1.9.X?

**Comment by Blue64** [comment]
very good to know that they kept the original staff though, I was unsure what they'd done about that. I just figured Mojang moved on and Microsoft would have used it's own people.

**Comment by rubensworks** [comment]
In theory, supporting multiple MC versions at once is the best indeed (this is what nova is trying to accomplish https://github.com/NOVA-Team).
But unfortunately, this is really time intensive at the moment due to the massive changes introduced in each major minecraft version. Supporting 1.7.X~1.9.X would take me approximately three times the amount of time it would when just working on one version.
EvilCraft 0.9.x will most likely exist only for MC 1.8 (unless I notice that there is still a major part of the playerbase that has not yet moved to 1.8).
Obviously, I will still fix any bugs that are found for 1.7.10.

**Comment by Blue64** [comment]
another obvious possibility is of course to have a different person for each version (thus dividing the time down to the standard `1:1` instead of `1:X` where `X` is the number of supported versions).

before I go forgetting, could you at least upload the code you have down so far (or at least the flow for the concept) to the GitHub? Who knows, perhaps I'll look it over, understand it, and maybe even Code it up, and Fork it in (or someone else) so it could be included in the next update of 1.7.10. It's your Idea, I'd like you to at LEAST get the credit for the original upload lol

**Comment by rubensworks** [comment]
1. True, that's why this mod is open source, anyone is allowed to send PR's :-)
2.  So you think of making a separate mod for these spawn eggs? Not sure how this would work...

**Comment by Blue64** [comment]
much simpler to have it as a PR lol

**Comment by Blue64** [comment]
If I made a separate Mod, I'd go **_way**_ past just the Spawn Eggs lol I'd be like `Random Things 2`, it'd be this massive compilation I'd have created to basically overwrite any errors I found in my Cross-Mod compatibility (over 150 mods, bound to happen, eg: `<ore:aluminium>` & `<ore:aluminum>`, both are `Aluminum`, neither enjoys recognizing the other, both use `Explicit Recipes` (not `OreDict`), [using `MineTweaker` to fix](https://github.com/Blue64/MT-ZenScript) (WIP) currently) `:P`

**Comment by Blue64** [comment]
I think I just figured out [why](https://github.com/CyclopsMC/Versions/tree/master/1.8) you have so little time lol

**Comment by Blue64** [comment]
a "little" fix huh? lol your definition of "little" is mind boggling.

Edit: (I pity & envy your girlfriend lol)

**Comment by rubensworks** [comment]
"62 additions and 17 deletions", I call that a little fix :)
Essentially, I just needed to add a special case for entity-names next to the already existing entity-ids.

**Comment by Blue64** [comment]
Any chance of seeing a Werewolf Vengeance Spirit in 1.7.10? lol it's kinda awkward that Villagers have em, I have em, but Werewolf Villagers don't xD

**Comment by Blue64** [comment]
It's still on topic, because I'd love to use their Spirits to farm Werewolf items via Spirit Reanimator `:P`

**Comment by rubensworks** [comment]
@Blue64 The werewolves are blacklisted from spawning a vengeance spirit in the config file at the entry `entityBlacklist`. I can't really remember why I blacklisted them, but you can easily enable it again by removing its line.

**Comment by Blue64** [comment]
I did remove them from the blacklist, it reads an error in my logs during launch and removes them that way

**Comment by rubensworks** [comment]
I'll need to see the logs for that.
You might want to open a separate issue for that as well.

**Comment by Blue64** [comment]
I'll get on that later today. Alternatively, I believe one of my crash logs in my misc section of my github (gany's nether crash I think) has a full log, which should also contain the error. I'll edit the link into this post, and also create a separate issue for it.
- Edit: **_[Link](https://github.com/Blue64/Misc/blob/master/Gany's%20Nether%20Crash%201.log#L4845-#L5010)**_
- Edit 2: **_[Issue](https://github.com/CyclopsMC/EvilCraft/issues/317)**_
