### ISSUE TITLE
Spirit Furnace crash

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#314]
Trying to use the Spirit Furnace with a Box of Eternal Closure containing a third-party mob mod crashes the console and sends you back to the launcher. Placing the Box of Eternal Closure with their contained Vengeance Spirit in it is fine, but if any blood is in the machine and it tries to process them it crashes and will keep crashing on returning to the world. I'm using the ATL launcher for this.

Source: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445975-evilcraft-open-source-v0-9-2?comment=491

**Comment by Blue64** [comment]
`trying to use the Spirit Furnace with them crashes the console and sends you back to the launcher.`
Them? Define "them" please.

**Comment by rubensworks** [comment]
(Updated the comment)
It was just copied from a comment on MCF :-)

**Comment by Blue64** [comment]
Ah, that's better. Also might desire to provide the reference link since it's not exactly your post originally.

**Comment by rubensworks** [comment]
Hmm, you're right, I should start doing that.

**Comment by rubensworks** [comment]
Crash log: http://paste.atlauncher.com/view/e92150ac
