### ISSUE TITLE
Werewolf Vengance Spirit Error 1.7.10

### ISSUE THREAD

**Issue by Blue64** [rubensworks/EvilCraft#317]
[Full Log](https://github.com/Blue64/Misc/blob/master/Gany's%20Nether%20Crash%201.log)
- [Werewolf Vengeance Spirit Error](https://github.com/Blue64/Misc/blob/master/Gany's%20Nether%20Crash%201.log#L4845-#L5010)

That log was originally uploaded to report a crash in Gany's Nether (newest update patched it, it was an issue with the `Magmatic Centrifuge` Recipes XML), which is what crashed it. The Werewolf error has never crashed it (I've even killed a few dozen werewolves, no crash), but it shows up in the log during launch like that every time during Entity Registration.

**Comment by Blue64** [comment]
Well that was fast lol

**Comment by rubensworks** [comment]
The Werewolf constructor seems to call the Werewolf Villager config, before it is instantiated.
I should do some initialization re-ordering to fix this.

**Comment by Blue64** [comment]
I had a hunch that load order was some sort of issue, but wasn't sure, as I haven't seen many load order issues before lol
