### ISSUE TITLE
Farting might be broken

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#319]
(Don't tell anyone...)

**Comment by rubensworks** [comment]
Seems to be a server-specific packet issue for the CyclopsCore packet handler, see https://github.com/CyclopsMC/CyclopsCore/issues/9

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/CyclopsCore@47b6cb350cfdbd7703e5ab6e2a1958689a1d9d6d

**Comment by Blue64** [comment]
Couldn't fart for 8 whole days huh? I pity the nearby people :P

**Comment by rubensworks** [comment]
It was a server-specific issue (all servers running on CentOS), most servers were unaffected.

**Comment by Blue64** [comment]
So there were lots of people who couldn't fart for 8 days, oh the humanity lol
