### ISSUE TITLE
Dark Tanks don't take into account light-level

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#321]

**Comment by Blue64** [comment]
Are they supposed to? And what effect would it cause?

**Comment by rubensworks** [comment]
They don't get darker when it's night, probably caused by some light-level check I forgot in the new 1.8 TESR.

**Comment by Blue64** [comment]
I noticed that problem with the Thaumcraft Aura Nodes in 1.7.10 lol the block the node is in is constantly lit, even when not emanating light.
