### ISSUE TITLE
idk if this is bug

### ISSUE THREAD

**Issue by JokerReaper** [rubensworks/EvilCraft#328]
on 1.7.10 version 0.9.3 ive noticed the promise of productivity can be stacked, not just in the inventory but in the machines i found out by shift left clicking them into the Blood Infuser idk if this intentional or not, but i figured id ask

**Comment by rubensworks** [comment]
This has always been a feature, their maximum stack size is 4.
If you can have more than 4 items in one slot, that would be a bug :)

**Comment by JokerReaper** [comment]
oh ok, its been a while since ive had free time to mess with any of these mods, thanks for clarifying
