### ISSUE TITLE
Pendant working without blood

### ISSUE THREAD

**Issue by JokerReaper** [rubensworks/EvilCraft#329]
ive noticed that for some reason, the pendant still works even after being drained of blood, ive removed it completely to make sure that it was in fact that & not some mystcraft bug & it does in fact keep removing effects, ive tested it on a number of effects like fire & potion effects like weakness, which brings me to the 2nd issue, while testing the pendant, i was going to use poison & had a few poison sacs when i viewed how to make the poison potion it was shown that i could make poison using the magma crucible from thermal expansion to turn them into straight liquid, but you cant put them into the crucible, figured i'd mention both of these for version 1.7.10- 0.9.3 since they happened at the same time

**Comment by rubensworks** [comment]
The first thing is probably not a bug, all items will automatically look for other blood containers in the inventory. They should stop working when no blood can be found in the inventory.
Could you make a separate issue for the second problem?

**Comment by JokerReaper** [comment]
made the 2nd its own issue tag

**Comment by rubensworks** [comment]
Could you let me know if the problem was indeed the one I mentioned?

**Comment by JokerReaper** [comment]
ive removed all sources of blood from my inventory & went back to a mystcraft world that was indeed unstable with bad effects & with the empty pendant it in fact was using the blood i had stored in another vessel ie the extractor.

**Comment by rubensworks** [comment]
Ok, so it works as intented.

**Comment by JokerReaper** [comment]
yeah it does work as it should, i'll test it on a few other things, but im sure the results should be the same
