### ISSUE TITLE
poison sacs can not be used in the magma crucible

### ISSUE THREAD

**Issue by JokerReaper** [rubensworks/EvilCraft#330]
as the title says the magma crucible from thermal expansion can not be used to make poison sacs into poison liquid but the recipe is there in NEI. version 1.7.10-0.9.3

**Comment by Blue64** [comment]
are you perhaps getting the name wrong? what specifically were you putting down to attempt this? (please use the `code ` ` ` tag`)

**Comment by JokerReaper** [comment]
its the only poison sac i have in the collection of mods i play with, the ones from the libelle dragonflies id number 4427

**Comment by Blue64** [comment]
there's still a wide variety of ways for this to go wrong lol How exactly are you attempting this recipe? (default, mod pack, custom recipe, etc.)

**Comment by JokerReaper** [comment]
its not a mod pack, just mods ive put together, & its not a custom recipe, just shows that i can put poison sac into a magma crucible, the recipe shown is what NEI shows http://i65.tinypic.com/2i70nm.png
its my own collection of mods installed one at a a time to make sure they work

heres the list:
[1.7.10]bspkrsCore-universal-6.16
[1.7.10]Treecapitator-universal-2.0.4
adventurebackpack-1.7.10-0.8c
B0bGary's Growable Ores-2.5.4 for 1.7.10
Baubles-1.7.10-1.0.1.10
buildcraft-7.1.14
CodeChickenCore-1.7.10-1.0.7.47-universal
CodeChickenLib-1.7.10-1.1.3.140-universal
CoFHCore-[1.7.10]3.1.0-323
CoFHLib-[1.7.10]1.1.1-181
Damage-Indicators-Mod-1.7.10
denseores-1.6.2
EvilCraft-1.7.10-0.9.3
FamiliarsAPI-1.7.10
FamiliarsDefaultMobPack-1.7.10
FamiliarsExtendedFamPack-1.7.10
FamiliarsHerobrineFamPack-1.7.10
iChunUtil-4.2.2
ironchest-1.7.10-6.0.62.742-universal
mychunkloader-1710.01
mystcraft-1.7.10-0.12.3.01
NotEnoughItems-1.7.10-1.0.5.118-universal
OptiFine_1.7.10_HD_C1
Reis-Minimap-Mod-1.7.10
Thaumcraft-1.7.10-4.2.3.5
ThermalExpansion-[1.7.10]4.1.1-237
ThermalFoundation-[1.7.10]1.2.2-111

the only ones thats been updated as of right now has been thermal expansion & foundation, none of the mods i have listed here change any recipes
