### ISSUE TITLE
a slight texture issue

### ISSUE THREAD

**Issue by JokerReaper** [rubensworks/EvilCraft#332]
i was using the chalice to power some machines when i noticed that when using fuel from, i think its build craft, i could see through the liquid & anything behind the chalice while holding it in my hand, i could see a torch's flame moving, i thought that maybe it was my texture pack but it does this in vanilla textures as well, was looking at all the different liquids & to some degree you can see through the chalice ive left a screen shot of the one that you can see through the most to show it.

 http://i66.tinypic.com/2hgztc4.png

**Comment by rubensworks** [comment]
Oh wow, didn't see that before.
I think that's caused by the way Minecraft works, but I'll have a look at it anyways.

**Comment by JokerReaper** [comment]
yeah i believe it has to do with the liquid being translucent, like in the tanks or other containers

**Comment by Blue64** [comment]
perhaps removing the Alpha Layer would help? I'm assuming you're grabbing the Fluid Color and using it as an Array, but if you don't remove the Alpha Layer of the pictures, things like this can happen (Could be worse, at least that fluid was semi-solid!), alternatively you can always just use a custom texture and force it's texture layer to a smaller Z-Scale whilst rendering an empty background (sorta like how if you stand inside someone you can see inside their head! `:P`)
