### ISSUE TITLE
Enchantment ID conflict with ThaumicBases

### ISSUE THREAD

**Issue by LlubNek** [rubensworks/EvilCraft#335]
You have an enchantment ID conflict with ThaumicBases (enchantment ID 101).

Here's the crash report:
http://pastebin.com/YHTkDP8S

Here's the log:
http://pastebin.com/2rkPtfbE

Here's a link to the matching issue for ThaumicBases:
https://github.com/Modbder/ThaumicBases/issues/37

**Comment by rubensworks** [comment]
No, you have an enchantment ID conflict :-)
You manually have to change the enchantment id in the evilcraft config file, due to how to Forge handles enchantments there nothing I can do on my end.
