### ISSUE TITLE
Forestry Squeezer can squeeze blood out of any log

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#337]
Got this strange report, to be tested...
More details: https://forums.atlauncher.com/thread-12649.html
Will be handled by Forestry: ForestryMC/ForestryMC#1061

**Comment by rubensworks** [comment]
Fixed from ForestryMC/ForestryMC@98e13299d647c234524338d4679d2ecaff09e98b

**Comment by ResqDiver1317** [comment]
I know this is closed and labeled as MC 1.7 but we are having this issue with 1.10.2. We are running the latest EvilCraft for 1.10.2 and Forestry 1.10.2-5.2.17.387 and this issue was just reported to me by a few of our players.

**Comment by rubensworks** [comment]
As mentioned above, this is a Forestry issue.

**Comment by josephcsible** [comment]
I commented there about it.
