### ISSUE TITLE
Sanguinary Env. Acc. Not Working

### ISSUE THREAD

**Issue by TheWerdOfRa** [rubensworks/EvilCraft#341]
I cannot find any tutorial on how to get this unit to work. The book alludes to the fact that it works the same as the ones found in the wild. I setup the unit, placed 8 dark tanks totaling exactly 2,400,000mB of blood in the correct locations. However, the unit says it is 'empty' and refuses to function. In addition, the recipes show the machine having a gauge for how much blood it will take to complete the recipe, but the machine itself does not have a gauge.

Can more clear directions be provided or is it not working?

![2016-02-25_23 22 14](https://cloud.githubusercontent.com/assets/17488364/13343116/4c72840a-dc17-11e5-9665-b2c75823376f.png)
![2016-02-25_23 27 41](https://cloud.githubusercontent.com/assets/17488364/13343125/60383494-dc17-11e5-8917-a2cdf2d6df37.png)

**Comment by rubensworks** [comment]
Your setup is correct, but the recipes which require a certain weather don't seem to be working anymore atm (as I have just tested it). Biome extraction for example works just fine it seems.
I'll have a look at it later today, expect a bugfix release this week.

**Comment by TheWerdOfRa** [comment]
Thank you :+1:

**Comment by rubensworks** [comment]
@TheWerdOfRa I forgot to mention that I rebalanced the blood cost for these recipes a bit, I thought 2,400,000mB for one recipe might be a bit too much...
You'll have to reset your evilcraft config file for these changes to take effect.
