### ISSUE TITLE
Primed Pendants absorbing non-blood liquids from tanks

### ISSUE THREAD

**Issue by Yowesephth** [rubensworks/EvilCraft#348]
having any liquid in a tank an an empty primed pendant with a potion in it will absorb the liquid even if it's not blood. This doesn't seem to happen if you don't have a source of blood in your inventory as well, thus leading to it using both the blood AND the other nonblood fluid. I've observed it absorbing liquid blue slime from tinker's construct, as well as purifying liquid and liquid death from thaumcraft.

**Comment by rubensworks** [comment]
Thanks for reporting, I assume this is on 1.7.10?

**Comment by Yowesephth** [comment]
1.8 actually, my apologies for not mentioning that
