### ISSUE TITLE
Crash when looking up recipes for blood in NEI

### ISSUE THREAD

**Issue by lilmoefow** [rubensworks/EvilCraft#349]
Not necessarily sure who to report this to. was only getting this crash when looking up the recipes for blood while in the gui of your blood infuser

when i left click here http://imgur.com/YFsxp5k
it crashes the client

http://pastebin.com/xK70kd0p

Forge 1.7.10 - 10.13.4.1614
EvilCraft-1.7.10-0.9.5.jar
forestry_1.7.10-4.2.11.59.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar

**Comment by rubensworks** [comment]
It looks like this is caused by Forestry, so it may be good to report it over there as well.
But I'll look into it on my end.

**Comment by lilmoefow** [comment]
updated NEI and still getting same crash

NotEnoughItems-1.7.10-1.0.5.120-universal.jar

**Comment by lilmoefow** [comment]
tried looking into this again, so far after removing forestry and any add-ons i had (ex. binnies mods, binnes patcher, magic bees) im getting this crash  

http://pastebin.com/mh9KjHfE

NEIIntegration-MC1.7.10-1.1.2.jar

after removing NEI Integration the crash stops, but after adding back in forestry with out nei integration. i get this crash still 

http://pastebin.com/5CdGBDu9

**Comment by rubensworks** [comment]
Did you report it to NEI Integration? It seems to be a bug at their end.

**Comment by lilmoefow** [comment]
the crash happens without nei integration as well.

**Comment by lilmoefow** [comment]
Sweet. Is there somewhere i can download a jar for this or do i need to wait for it to be on curse?

EDIT: nvm im a derp. i got the download from the minecraft forum post  thanks for the fix :)
