### ISSUE TITLE
Temples sometimes spawn too close

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#352]
This for example should never happen:
https://t.co/3EkP5SC5ZC

**Comment by ghost** [comment]
I'm seeing that too. Especially on rivers. I can follow a river and get a new temple every 100 blocks or so. Can you add a minimum distance check and log them like Ruins or something? They should be more rare.

**Comment by zlyfire** [comment]
In my current world, I have found that near Z:0 and also near X:0, there's an absolute cluster of the temples, all within 5 blocks of the last one, forming a decently long line. Definitely should have a distance check.
