### ISSUE TITLE
Fill bucket crash

### ISSUE THREAD

**Issue by BrokenHearted2** [rubensworks/EvilCraft#353]
I got this crash when trying to fill a bucket from a lava pool, using 1.9-0.9.6.
[pastebin.com/cCAtWWsK](http://pastebin.com/cCAtWWsK)

It almost acts like issue CyclopsMC/CyclopsCore#15.

**Comment by rubensworks** [comment]
You're right, this will require the exact same fix as CyclopsMC/CyclopsCore@008c31c38cf7e20775c74858c11f6f02e278f8d5
I'll look into it later today.
