### ISSUE TITLE
Keep crashing in the nether with particle effect errors

### ISSUE THREAD

**Issue by b0bst3r** [rubensworks/EvilCraft#354]
http://pastebin.com/hHU3Uc8y

CyclopsCore-1.9-0.5.7.jar
EvilCraft-1.9-0.9.6.jar
Forge 12.16.0.1865

**Comment by rubensworks** [comment]
Hmm, I never actually went into the nether in 1.9. Thanks for reporting this!
In the meantime, disabling particles _should_ stop the crash from occuring.

**Comment by b0bst3r** [comment]
I set B:particle=false and it still crashes.

It's weird though, its like it waits for a certain thing to happen, I just spent over 30 mins in the nether mining np and on the way out, boom crash.  So is something occuring at random intervals to do with particles?

Don't know if it helps but this is what the server does http://i.imgur.com/N6joXr9.png

**Comment by rubensworks** [comment]
It's probably just an entity walking over a nether fish spawn block.
(I meant disabling MC particles, I'm not sure where you found this `B:particle` option)

**Comment by b0bst3r** [comment]
"degradation effect" {
    B:biome=true
    B:knockbackDistort=true
    B:mobSpawn=true
    B:nauseate=true
    B:paling=true
    B:particle=false   <<----- 
    B:sound=true
    B:terraform=false
}

And I set video particles to ... oh decreased.. will try on minimal

**Comment by rubensworks** [comment]
Ah yes, that option has nothing to do with those particles :-)
This option only controls whether or not the Environmental Accumulator should show particles when degrading the environment.

**Comment by ProsperCraft** [comment]
http://pastebin.com/kgVt5DTF

Having the crash as well in 1.9 in the nether.

**Comment by b0bst3r** [comment]
@ProsperCraft If you set minecraft video settings of particles to minimum it stops the crash whilst ruben fixes the problem.
