### ISSUE TITLE
Stacking 2 tanks on top of each other allows you to walk into them

### ISSUE THREAD

**Issue by b0bst3r** [rubensworks/EvilCraft#358]
I kid you not these are 2 x 144,000mb tanks both set to empty, place one down and the other on top and you can walk into it taking damage (I suspect from the lava inside).

No crash or anything just freaked me out when I did it by accident, wonder wtf I went to lol.

**Comment by rubensworks** [comment]
Probably some kind of bounding box issue that causes suffocation.
MC 1.9?

**Comment by b0bst3r** [comment]
yes sorry 1.9 

Forge 1865
EvilCraft-1.9-0.9.7
