### ISSUE TITLE
[1.9] client crash using flint-steel on hardened blood

### ISSUE THREAD

**Issue by kwpugh** [rubensworks/EvilCraft#361]
Crash report:  http://pastebin.com/raw/iXzY34kP

Forge: 1864 & 1882
Mod: EvilCraft-1.9-0.9.8.jar

Client crashes when you click the hardened blood with a flint & steel to create blood shards.

**Comment by rubensworks** [comment]
Dumb mistake of mine, it's a miracle that I didn't detect this while testing...
