### ISSUE TITLE
Undead sapling not working 

### ISSUE THREAD

**Issue by megaloloful** [rubensworks/EvilCraft#362]
When a undead sapling grows it just vanishes and doesn't grow a tree. The sapling also doesn't have a model or a texture when placed

EvilCraft1.9-0.9.8

CyclopsCore 1.9-0.5.7 

forge 12.16.0.1865

**Comment by b0bst3r** [comment]
Yep had this too crashed the server with the following:

http://pastebin.com/17BhGHDq

Same mods as Mega but we're using Forge 1887
