### ISSUE TITLE
Server crash, I've never seen a crash like this in my life

### ISSUE THREAD

**Issue by b0bst3r** [rubensworks/EvilCraft#364]
Forge 1887
EvilCraft-1.9-0.9.8.jar

Think I'll just leave this here and run off http://pastebin.com/bKPTVM3C

On a more serious note, the server froze on what looks like evilcraft world gen (wild guess) what happened after that in the crash log ...... no clue

**Comment by rubensworks** [comment]
That looks like vanilla worldgen logic, so I'm not sure if I'll be able to fix anything, but I'll look into this.
I assume that a restart solves the problem?

**Comment by b0bst3r** [comment]
Yes a restart fixed the issue.

**Comment by b0bst3r** [comment]
This is what it looks like from a server point of view http://i.imgur.com/ylJLAow.png, the crash log it generates is almost identical to the one in the OP.

**Comment by rubensworks** [comment]
I'm having trouble reproducing this bug, but I think last commit may have fixed it.
Could you have a look and see if this solves your bug? You can download the dev build here: https://bintray.com/cyclopsmc/dev/EvilCraft/1.9-0.9.8-355/view (Build may still be in progress)

**Comment by b0bst3r** [comment]
The evil dungeon it refers to in the crash log is that the square thing on the suface with the environmental accumulator in the middle or is it something else?

**Comment by rubensworks** [comment]
No, it's the dungeon that spawns below the surface. It's like a vanilla dungeon, but larger and with bloody cobblestone on the floor.

**Comment by b0bst3r** [comment]
Well this is the longest anyone has ever gone without crashing the server genning new chunks, so the outlook is positive.

**Comment by rubensworks** [comment]
Cool, thanks for testing. I'll release the new version publicly in about an hour. It'll contain some other fixes as well.

**Comment by b0bst3r** [comment]
oh does this build not contain the undead tree fix or the slime crash?

**Comment by rubensworks** [comment]
It should contain fixes for that. But I'm preparing new release as we speak, so it might be better to check those. If you still have the crashes there, we can reopen the issues.

**Comment by rubensworks** [comment]
@b0bst3r The new release is out. If you still experience problems with this issue, #362 or #363, please let me know in their respective issue threads.
