### ISSUE TITLE
[Client crash 1.9] While trying to craft a 144,000mb dark tank

### ISSUE THREAD

**Issue by DingoX3** [rubensworks/EvilCraft#365]
Minecraft 1.9
Forge version 1867
Evilcraft version: 1.9-0.9.8
TConstruct version: 1.9-2.2.2

My minecraft window turned light blue for 5 sec and then crashed and sent me to desktop while I was in a Tinkers crafting station trying to use left click to split a stack of 2 dark blocks and move one around to make a dark tank. When i logged back in there seemed to be some kind of a rendering issue. The screen turned a pinkish purple that time. I am currently unable to "Fully" log back into the game on the server. It loads in, renders whats in my hand(a tinkers hammer) then freezes and crashes.

Full crash report of first initial crash: http://pastebin.com/Xr3i7767
Crash report of second crash: http://pastebin.com/9gssNiLG

**Comment by zlyfire** [comment]
The same is happening to me while trying to craft a purifier at a tinkers' crafting station. It seems that, for some reason, TiC does not like to render the dark block on the station. Considering  it's perfectly fine rendering all sorts of other blocks and items, it is quite likely a bug in how the dark block is drawn.  
If you can turn off the tinkers' table rendering items on it, you will no longer crash. That's how I resumed play in my single-player world.

**Comment by DingoX3** [comment]
Good idea. I forgot about it rendering on top of the table. I'll turn that off and see if it fixes it. Thanks for the reply.

**Comment by rubensworks** [comment]
Hmm, I did not realise that this is due to the rendering on these tables. In that case, the crash might be caused by TiC passing incorrect arguments to the block model. But I'll have to investigate it to be sure.

**Comment by DingoX3** [comment]
I can confirm turning off the rendering did allow me to re-enter my world and continue playing.
