### ISSUE TITLE
Crash when making blood shards 1.9

### ISSUE THREAD

**Issue by tlitookilakin** [rubensworks/EvilCraft#366]
http://pastebin.com/sTDJFz8n
Steps to recreate:
1. Install evilcraft on forge 1.9 (12.16.1.1887)
2. place liquid blood and let it dry
[2.5] Minor texture error with connected textures as well.
3. right-click hardened blood with flint and steel
This was done in a singleplayer world.

**Comment by rubensworks** [comment]
@swyrl This should've been fixed in #361. Could you try the latest EvilCraft version (0.9.9) and see if that solves the problem for you?

**Comment by tlitookilakin** [comment]
Yep, it's been fixed. Thanks!
