### ISSUE TITLE
[1.9] Can't craft Box of Eternal Closure 

### ISSUE THREAD

**Issue by b0bst3r** [rubensworks/EvilCraft#367]
See http://i.imgur.com/QMmhTc0.png the water bottles have no texture, look in JEI my water bottles indeed have textures so no clue what those water bottles are supposed to be.

This is the 1.9 version.

**Comment by b0bst3r** [comment]
Oh I see this "water bottle" is actually made by crafting a Poison bucket with a bottle, maybe it's conflicting with existing water bottles and should be called murky water bottle or something?

**Comment by rubensworks** [comment]
Ah, I see. This is being caused by the potion registry changes. You would normally need weakness potions, but I will need to remake the recipe in order to make it work in 1.9.
