### ISSUE TITLE
Crash on startup with newest forge

### ISSUE THREAD

**Issue by zlyfire** [rubensworks/EvilCraft#370]
It seems that forge changed something in regards to loot tables, as this crash suggests: http://pastebin.com/mzaC2Xcv  
This was discovered when updating forge, mantle, and Tinkers' Construct, though the latter two were then downgraded but the crash still remains.

**Comment by 0Navis0** [comment]
I get exactly the same bug, I don't know from where it comes.

**Comment by zlyfire** [comment]
I think it comes from forge adding loot accessors again (from what I gather from other mods' changelogs) and somehow breaking evilcraft's loot access

**Comment by rubensworks** [comment]
Yes, @zlyfire is right. I tried to be smart and coding everything in such a way so that when Forge implemented loot accessors, EC would work with it right away. Unfortunately they did more changes to that system than expected, so I'll have to change some things after all.

**Comment by AxolotlAccount** [comment]
same happens to me (forge-1.9-12.16.1.1900)

http://pastebin.com/598hHnf7

**Comment by AxolotlAccount** [comment]
still not fixed, even updating cyclopscore and forge

**Comment by rubensworks** [comment]
@EnderT5 But ... I'm still in the process of releasing a new EvilCraft version, that's the one that will fix it. Just a little bit more patience :-)

**Comment by rubensworks** [comment]
@EnderT5 Update is available now.

**Comment by AxolotlAccount** [comment]
THANKS !

**Comment by zlyfire** [comment]
Excellent!
