### ISSUE TITLE
Can't fill tank from extractor

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#372]
In the current release, I can't seem to fill the dark tank from the blood extractor.  Right-clicking on any other block drops a block of blood as usual.

**Comment by rubensworks** [comment]
Thanks for reporting.
Which MC version are you using?

**Comment by MentalMouse** [comment]
Forge 1901 (1.9)  And for the record, "current" Evilcraft is 0.9.10.

**Comment by MentalMouse** [comment]
Further investigation (having made an infuser) indicates that the extractor can't feed blood to the infuser either, suggesting that the problem is with the extractor.
