### ISSUE TITLE
Spirits may be pushing players in 1.9 (despite being invisible)

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#376]
Remember how I noticed spirits leaving bubbles in water?  I suspect that 1.9 with its newly pushy mobs (including bats, oy) has added another wrinkle:  Several times I've killed something and shortly thereafter "stumbled over" something, much as if I'd run into an animal.  Also, they seem to make an alarming amount of noise.

You might want to divorce spirits entirely from the "Mob" class, making them a special entity.

**Comment by rubensworks** [comment]
That does sound like something I should look into.
