### ISSUE TITLE
Armor slots in Blood Chest are scrambled.

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#377]
The armor slots displayed when opening the blood slots seem very confused.  The diagrams run from head on the bottom to feet at top.  When you're already wearing armor though, the pieces show up in the usual order.  If you shift-click them all to the BC slots, then back, they go back in the diagram order.  If you then exit the BC and look in your regular inventory (OK, the Baubles inventory for me), you will then appear to be wearing your armor upside down, with the boots on your head and so on.

Also, an axe seems willing to shift-click into the top ("boot") slot...

**Comment by zlyfire** [comment]
Any item seems to enjoy going into the boot slot/top slot (the blood extractor, a sentient sword, any item)

**Comment by rubensworks** [comment]
Fixed in release 0.10.0
