### ISSUE TITLE
You can hear spirits

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#381]
But you can't see them

**Comment by MentalMouse** [comment]
Indeed.  Even without the collision issues (I see you dealt with that), the Dark One's "discovery" of spirits might not be so special if every animal farmer can hear the wailing ghosts of their slain beasts.

BTW, if I wasn't clear enough on the collision thread, this isn't just an alpha/dev thing, invisible spirits are quite audible even in the current version.

**Comment by rubensworks** [comment]
Fixed in dev
