### ISSUE TITLE
NettyIO nullponter with smash on broom

### ISSUE THREAD

**Issue by JonaBrackenwood** [rubensworks/EvilCraft#388]
if you fly against another player whils smash is on your broom, you will disconnect from the server with a NettyIO nullpointer. No further errors.

**Comment by JonaBrackenwood** [comment]
Same result if flying against other entities.

**Comment by rubensworks** [comment]
Can't reproduce, please _always_ post your crashlogs.

**Comment by JonaBrackenwood** [comment]
No crach, only disconnect.

> [15:51:48] [Netty Client IO #1/ERROR]: java.lang.NullPointerException

Not that it helps much. Maybe check on the server for an error at that timestamp.
