### ISSUE TITLE
Suggestion:  All this gem dust... How about using it for Bottles of Enchantment?

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#392]
In my new game, I'm already getting multiple stacks of gem dust.  My first thought was a non-reversable conversion to gems, 9:1 to outpace the various grinders and such.

But I think I've got something better.  It needs to be used in a recipe for something consumable, that players will be producing in quantity... How about Bottles o'Enchanting?  You don't really have a mechanism to feed levels into it, but I think the numbers are such that it's reasonably balanced anyway: 

Average yield is 7 xp/bottle, and with the new table you need way more than 1:1 for any reasonable number of levels.  For example, from zero to level 8 would need 16 bottles on average, zero to level 16 would need 50 (that is, most of a stack).  ETA:  Recovering from a max-power enchantment (level 27 to level 30) would need 44 bottles.

This could be done through brewing (that is, Nether-Fortress gated), or just crafting the dust with bottles of blood (Infuser or Tenacity gated).  And of course, there's the risk of using up all your dust and then needing it for a more ordinary crafting....

**Comment by rubensworks** [comment]
It's an original idea, but I don't really like it. I think there will be too many balancing issues with other mods.
