### ISSUE TITLE
Vengeance Spirit crash when combined with certain mods

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#394]
Just make the `isEnabledVengeance` check player-null safe.
More info: Xilef11/runesofwizardry-classics#2

**Comment by MentalMouse** [comment]
Not sure if this is directly related, but it's a Ticking Entity crash that seems to be on a Vengance Spirit:

http://pastebin.com/7iSShXA1

**Comment by rubensworks** [comment]
@MentalMouse It looks like a different thing, but it's caused by Vengeance Spirits.
Could you create another issue for it? Otherwise I might forget that these are two separate things that should be fixed.

**Comment by MentalMouse** [comment]
OK, did so at #396 .
