### ISSUE TITLE
[1.9.4] Server Startup Crash

### ISSUE THREAD

**Issue by Shadows-of-Fire** [rubensworks/EvilCraft#402]
As the title says.
MC Crash Report https://gist.github.com/Shadows-of-Fire/32b85dde7a6ae81d44f33839943087c8
FML-SERVER-LATEST.log https://gist.github.com/Shadows-of-Fire/70368724f17aec7cf5e74a2ff42acb08

**Comment by rubensworks** [comment]
Yes, I've made a stupid mistake, will be fixed later today.
Same problem as CyclopsMC/IntegratedDynamics#51

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/CyclopsCore@890d99b5e2c89b13677aca841fea8a080bfbe62f
New release of CyclopsCore coming later today.
