### ISSUE TITLE
Blood is a solid block

### ISSUE THREAD

**Issue by Majestyc2k1** [rubensworks/EvilCraft#403]
Problem: Trying to create a Dark Power Gem. I placed 5 blocks of blood in a hole and threw the gem in. It stayed on top of the blood, not sinking in. I could also walk across the top of the blood. Mod version 1.9.4-0.10.1; Forge 12.17.0.1909.

Expected behavior: Dropping a gem into blood creates a Dark Power Gem.

**Comment by Majestyc2k1** [comment]
The blood is identified as a block, not a liquid. I compared info from Blood Magic Life Essence.

**Comment by rubensworks** [comment]
That's a pretty serious problem obviously, will look into it later today.

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/CyclopsCore@4feeea8271b664805fb41572b20c624f067267c6
New release won't be for today, feel free to download the dev version here: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/
