### ISSUE TITLE
Spirits holding down pressure plates?

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#407]
I'm still playing 1.9, but if you haven't fixed it for 1.9.4, it might still be there?  I was fighting zombies etc at a doorway with a wooden pressure plate on my side.  Repeatedly now, after killing a mob the plate stays down for several seconds afterwards.  Given the prior bugs, I'm wondering....

Perhaps spirits should always vanish on contact with the player, whether or not they were allowed to actually attack.

**Comment by rubensworks** [comment]
I remember fixing this in 1.7.10, but there may be regression due to the updates.
