### ISSUE TITLE
Crash on server startup.

### ISSUE THREAD

**Issue by mrapplexz** [rubensworks/EvilCraft#408]
Forge log link: fml-server-latest.log: part 1- [http://pastebin.com/niWgywsT](http://pastebin.com/niWgywsT), part 2 - [http://pastebin.com/ZJyuzhVH](http://pastebin.com/ZJyuzhVH). latest.log: http://pastebin.com/sC1gpaBK
Problem: Crash on server startup.
I'm using EvilCraft 1.9.4-0.10.2 and Cyclops Core 1.9.4-0.6.3

**Comment by immortaleeb** [comment]
I removed `FakeWorld` in de8e68300c8e9c6ed78793a2c70275105454054d.
Problems like this shouldn't happen in the next EvilCraft update.
