### ISSUE TITLE
Crash while trying to render vengeanceSpirit 

### ISSUE THREAD

**Issue by JCMais** [rubensworks/EvilCraft#410]
Forge log link: https://gist.github.com/JCMais/52cf3823de942991f69625498a1cc53f

Problem: One player broke a Thut's Elevator controller, then a vengeance spirit tried to spawn, which crashed everyone near because of problem while rendering it.

Version of Evilcraft: 1.9.4-0.10.2

**Comment by rubensworks** [comment]
What makes you think a vengeance spirit caused this crash?
I don't see anything in the crashlog that could relate this to EvilCraft.

It looks like your server is spamming a lot of exceptions from abyssalcraft rendering though...

**Comment by JCMais** [comment]
That is, strange...

The log that was on Minecraft launcher when the game crashed showed something about Vengeance Spirit. The only thing I can recover from it is the following:

> -- Entity being rendered --
> Details:
>     Entity Type: evilcraft.vengeanceSpirit (org.cyclops.evilcraft.entity.monster.VengeanceSpirit)
>     Entity ID: 1423424
>     Entity Name: Vengeance Spirit
>     Entity's Exact location: 133,50, 65,00, 338,50
>     Entity's Block location: World: (133,65,338), Chunk: (at 5,4,2 in 8,21; contains blocks 128,0,336 to 143,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
>     Entity's Momentum: 0,00, 0,00, 0,00
>     Entity's Passengers: []
>     Entity's Vehicle: ERROR NullPointerException: null
> Stacktrace:
>     at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:413)
>     at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:362)
>     at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:800)
>     at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1726)
>     at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1555)
>     at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1334)
>     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)

I will make sure to update the report if it happens again.

**Comment by immortaleeb** [comment]
I recently made quite a few drastic changes in the way vengeance spirits work.
Since I can't pinpoint what went wrong here, I can't really say if my changes will fix your problem or not.
For now, I'll leave this issue open and if I don't see this problem coming back after the next 1.9 update then I'll consider this issue fixed.

**Comment by Zaweri** [comment]
@immortaleeb 
I reproduced the issue by accidentally shooting at a ThutTech elevator.
http://pastebin.com/qz5N2TtH

**Comment by JCMais** [comment]
I think it should be safe to just catch that exception and ignore the event.

**Comment by rubensworks** [comment]
Wait... It looks like elevator is some kind of entity. And when the elevator 'dies', a spirit is created for it. Elevator spirits shouldn't exist, that just sounds like a horrible meme.
