### ISSUE TITLE
Crash SpongeForge 

### ISSUE THREAD

**Issue by knoxhack** [rubensworks/EvilCraft#411]
Crash with latest SpongeForge
http://pastebin.com/3TYkGbBG

**Comment by rubensworks** [comment]
@immortaleeb  is phasing out all usages of `FakeWorld` for the next EvilCraft version, so this won't be an issue anymore in the next version.
But in the meantime, it might be good to open an issue for this at SpongeForge, there also were some incompatibilities in the past (1.7.10).

**Comment by knoxhack** [comment]
Glad to hear that, I didn't want to remove Evilcraft from my Server/Modpack. And yeah I reported that bug to the SpongeForge guys already

**Comment by knoxhack** [comment]
I got response from the SpongeForge team https://github.com/SpongePowered/SpongeForge/issues/692#event-696773337

**Comment by rubensworks** [comment]
@knoxhack Great news!
