### ISSUE TITLE
Crash when rendering Blood Stained Block item/entity

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#412]
Crash log: http://pastebin.com/va3Br3Ev
More info: CyclopsMC/CyclopsCore#18

**Comment by immortaleeb** [comment]
Fixed this in d1f5ab7d6b8d2c7c2d298fe68975c54bfcfdda1d by showing a missing texture model.
We might want to display the actual block when in inventory in the future though, but I'll consider this a minor issue for now (see #416)
