### ISSUE TITLE
Crash with latest SpongeForge on server (again)

### ISSUE THREAD

**Issue by knoxhack** [rubensworks/EvilCraft#413]
Forge log link:
https://gist.github.com/knoxhack/ff0469664e10a563d3099cf0d9d399cc

Problem:
crash with spongeforge

Expected behaviour:
crash on server

**Comment by immortaleeb** [comment]
I just pushed a bunch of changes to the master branch.
One of the changes involved removing `FakeWorld` in de8e68300c8e9c6ed78793a2c70275105454054d, so problems like this should not happen in the future.
