### ISSUE TITLE
Conflicting recipes for wood rod and undead rod

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#414]
Source: http://minecraft.curseforge.com/projects/evilcraft?comment=80

**Comment by immortaleeb** [comment]
We can't just ignore the ore dictionary for only undead wood, so how do you want to solve this?
We can change either of those recipes, but what do you want them to look like?

**Comment by rubensworks** [comment]
I think changing the undead rod recipe would be the best solution here.
I was thinking about just requiring one more or one less plank in the recipe, or maybe even use a log.
But it's up to you, go wild!

**Comment by immortaleeb** [comment]
Fixed in 397f8bed1fb0c9453c2b1b4bc85be51754cf8bf0
