### ISSUE TITLE
No effect potion in Primed Pendant crashes client.

### ISSUE THREAD

**Issue by ehwuts** [rubensworks/EvilCraft#415]
Forge log link: http://pastebin.com/raw/LE5ZWm0H

Problem: Pendant accepts "potions" with no effects, then crashes because trying to apply a null value.

Expected behaviour: Either nothing happening or pendant not accepting the item.

Steps to reproduce the problem:
- have blood in pendant or needle
- put water bottle or awkward potion in primed pendant

**Comment by rubensworks** [comment]
That's not supposed to happen, indeed :)

**Comment by immortaleeb** [comment]
Fixed this for 1.7 in 5f78c702dfb0e49b59e6b034af69b852c6a89f27
This fix will be included in the next release for 1.7 which will probably be very soonish.

In 1.9, this problem shouldn't occur due to changes to how effects are fetched from items.
