### ISSUE TITLE
Blood stained block has missing texture when in inventory

### ISSUE THREAD

**Issue by immortaleeb** [rubensworks/EvilCraft#416]
Normally, you're not supposed to be able to pick up blood stained blocks so we can consider this as "normal behavior".
However some mods might add blocks which allow you to pick up the blood stained block and we might want to place nice with them.

**Comment by LemADEC** [comment]
Issue is visible with ICBM explosions

**Comment by rubensworks** [comment]
Assuming fixed

**Comment by LemADEC** [comment]
Issue is still reproduced with 	EvilCraft-1.12.2-0.10.76 and ICBM-classic-1.12.2-3.3.0b63
![image](https://user-images.githubusercontent.com/4776032/60045247-a35c4380-96c4-11e9-994c-0342cce0a5cd.png)

**Comment by rubensworks** [comment]
@LemADEC That does not seem to be exactly the same problem as described in this issue. Please open a new issue where you describe the exact problem.
