### ISSUE TITLE
Missing TCon modsupport

### ISSUE THREAD

**Issue by digitalseraphim** [rubensworks/EvilCraft#423]
I see that you "re-enabled" TCon support in commit 3382594 (https://github.com/CyclopsMC/EvilCraft/commit/3382594), which claims to be part of 0.10.2, however the jar file on curseforge, which was uploaded almost a month after the commit, but doesn't contain the TCon mod support files, even though the ingame documentation talks about support.

**Comment by rubensworks** [comment]
You're right, something must have gone horribly wrong there.
Just tested this with the latest dev version, and everything seems to be working there.
So this will be fixed in the next release.
