### ISSUE TITLE
[1.10.2] Server crash when placing dead bush in Blood Infuser

### ISSUE THREAD

**Issue by b0bst3r** [rubensworks/EvilCraft#427]
CommonCapabilities-1.9.4-1.0.0.jar
EvilCraft-1.9.4-0.10.3.jar
CyclopsCore-1.9.4-0.7.0.jar

Forge log link: http://pastebin.ubuntu.com/18474682/

Problem: Place dead bush in infuser and server crashes and player in area unable to log back in

Expected behaviour: Expected to make dead tree sapling

Steps to reproduce the problem:

**Comment by Peach774** [comment]
This occurs with anything in the blood infuser on 1.10.2. This completely breaks worlds

**Comment by rubensworks** [comment]
That's a serious problem, will release a hotfix asap.

**Comment by rubensworks** [comment]
@b0bst3r, @Peach774 I'm preparing a new release as we speak, thanks for bringing this to my attention, I should've discovered this during testing.
