### ISSUE TITLE
Client Crash on placing Sanguinary Environmental Accumulator on a server.

### ISSUE THREAD

**Issue by mattfreyer** [rubensworks/EvilCraft#429]
Forge log link:
http://s000.tinyupload.com/?file_id=08678843234900243456
Problem:
Crashes the client after placing Sanguinary Environmental Accumulator then it continues to crash after you re-join
Expected behaviour:
Not to crash
Steps to reproduce the problem:
-Place Sanguinary Environmental Accumulator
- Then crash

**Comment by rubensworks** [comment]
That crash should not be able to occur...
Added an extra check to make sure it doesn't happen again, will be included in next patch.

**Comment by mattfreyer** [comment]
For 1.7.10 because that is the version of minecraft the mod is in.

**Comment by rubensworks** [comment]
@mattfreyer I'll wait a while for releasing a new 1.7.10 version, because new bugs may come in. In the meantime, you can use a dev version: https://bintray.com/cyclopsmc/dev

**Comment by mattfreyer** [comment]
Great ill add it in see if it fixes it .
