### ISSUE TITLE
Blood Infuser + Velocity fills and destroys chalice 1.9.4

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#430]
ETA:  Forge 1976, EvilCraft CyclopsCore-1.9.4-0.7.1.jar  EvilCraft-1.9.4-0.10.4.jar

Forge log link:  (no messages in log aside from the obvious ones)

Problem:  When used to fill a chalice (or filled externally by a chalice), a blood infuser destroys the chalice.  This apparently is specific to having a Promise of Velocity in the infuser.

Setup:  Place Promise of Velocity in infuser.  Fill infuser with at least 4 buckets of blood.  Place chalice in target slot of infuser.   

Expected behaviour:  Chalice fills, then moves to output slot.

Actual Behavior:  Chalice will fill, but then disappear from target slot, without reappearing in output slot.  

Also:  In survival mode, shift-right click with a full chalice to transfer its contents to the infuser.  At least sometimes, that makes the chalice disappear. (possibly different promises required)

**Comment by rubensworks** [comment]
Thanks for reporting this!

I saw your comment on MCF, but didn't have time to respond yet.
Could you also create an issue for that other problem you reported on the forums?

**Comment by MentalMouse** [comment]
Still happening in 0.10.5

**Comment by rubensworks** [comment]
@MentalMouse Could you tell me step-by-step what you do to have this problem, with all additional details? Because I am unable to reproduce this.

**Comment by MentalMouse** [comment]
I set up a testing profile, Forge 1976 with just the mods CyclopsCore-1.9.4-0.7.1.jar  EvilCraft-1.9.4-0.10.5.jar.

I have an infuser set up with a Promise of Strength as its only add-on, filled with blood.  (The Promise seems not to be necessary for all cases of the bug, but it seems to be reliable for the EvilCraft-only profile).  

Creative-spawn a chalice, and "pick" them to get a linked set.  

Drop one of the empty chalices into the target slot of the infuser.  Watch it fill and disappear.  Note that this only happens if the chalice fills completely.

In my main world, I also had a problem one time (which I can't reproduce) where I left a grail in the infuser's _source_ slot, then went downstairs to plug its mate into a blood farm.  When I got back, the grail in the infuser was showing a red "0", and when I tried to remove it, it disappeared.

**Comment by rubensworks** [comment]
I tried everything possible with exactly the same versions of everything, but I can't seem to reproduce your problem. I did however add an extra check that might solve your problem (even though it should be impossible to occur). Could you try out the latest dev version (build 453) and see if this fixes your problem? https://bintray.com/cyclopsmc/dev/EvilCraft

**Comment by MentalMouse** [comment]
Hmm.  No direct download from there, it will take me a while to figure out how to set up a SCCS/build environment.

**Comment by rubensworks** [comment]
Not needed, here's the direct link: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/evilcraft/EvilCraft/1.9.4-0.10.5-453/EvilCraft-1.9.4-0.10.5-453.jar

**Comment by MentalMouse** [comment]
Link doesn't work:  "The requested path was not found."

**Comment by rubensworks** [comment]
Oops, updated the link. (Not sure how I messed that up)

**Comment by MentalMouse** [comment]
Whatever you did does seem to fix the disappearing chalice, good work and thanks!

**Comment by rubensworks** [comment]
That's great news! I'll release the patched version later today.
