### ISSUE TITLE
Vengance items don't make spirits visible. (1.9.4)

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#431]
Forge 1976, EvilCraft CyclopsCore-1.9.4-0.7.1.jar EvilCraft-1.9.4-0.10.4.jar

As documented, having a Vengance item in your hotbar (or entire inventory?) is supposed to make spirits visible.  In practice, this does not seem to work for newly-slain mobs.  In survival mode, newly slain spirits are not visible, but are still present (changing to creative mode reveals them), and can be captured by blindly using a Vengance Focus over an open Box.  They also do not attack the player.

If captured and then released, while holding the Focus, the spirits will be visible as "normal", with sound and mob image.

**Comment by rubensworks** [comment]
Do you have a Vengeance Ring in your inventory? Because simply having the focus won't do anything.

**Comment by MentalMouse** [comment]
Aha!  The Focus doesn't itself provide the sight?

**Comment by rubensworks** [comment]
No, only the ring. Does that work for you?

**Comment by MentalMouse** [comment]
Hmm.  I could swear I've seen monster forms for some of the spirits I've seen holding the Pickaxe (probably that was in 1.9, though).  I assumed all the items gave the sight.  I was going to say "they should", but it occurs to me that blind-catching might be a decent tactic.  I will check the ring.

**Comment by rubensworks** [comment]
Just tested the ring, everything is working as intented.
