### ISSUE TITLE
[1.10.2] Compatibility with EnderIO

### ISSUE THREAD

**Issue by C0rn3j** [rubensworks/EvilCraft#435]
I'm trying to transfer blood from one dark tank to another through dimensional transceivers. Chunks are loaded, fluid transfer is enabled and set correctly, pipes are set correctly, I checked multiple times. It just won't transfer through the transceiver. 

I tried extracting the blood from Tconstruct smeltery and it worked just fine, so I really don't know what the problem is.

Sending transceiver fluid menu: http://i.imgur.com/CyS5DRv.png

Receiving end: http://i.imgur.com/uw8fEwl.png

Modlist: http://pastebin.com/nvyVt5EE
Client forge 2014, Server forge 2010.

**Comment by C0rn3j** [comment]
The fluid started transferring when the Dark tank was completely empty and it now seemingly works without any problems. I'm very confused. 
I'm almost certain that there was a different type of blood than Tconstruct's blood. Could the blood perhaps be merged in the dark tanks as it's a vital part of the mod?

**Comment by rubensworks** [comment]
The Dark Tank does not merge the different Blood types, only the machines (like the Blood Infuser) do that. So you probably mixed up the TCon and EC fluids, can be confusing since they share the same name ;-)
