### ISSUE TITLE
Spirits knocked back by slash attack.

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#438]
Yes, it's unruly spirits yet again!  I was fighting a stream of zombies at my fence with the V-Ring on.  When I hit the current zombie, I got a sweep attack and the spirits of his predecessors were knocked back.

**Comment by rubensworks** [comment]
That should not happen, this may be a Forge bug. I'll look into it.

**Comment by rubensworks** [comment]
Now that I looked into it, I don't really see this as a bug.
No actual damage is applied to the spirits, only a knockback, which is an unintended but interesting feature.
This introduces some interesting ways to combat spirits.
