### ISSUE TITLE
Placing empty Box of Eternal Closure crashes again...

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#440]
Forge log link:  https://www.dropbox.com/s/w42t2ef1rzvrowv/latest.log?dl=0

Problem:  Latest EvilCraft/Cyclops core:  CyclopsCore-1.9.4-0.7.3.jar, EvilCraft-1.9.4-0.10.7.jar, Forge 1976 (MC 1.9.4)

Expected behaviour:  Box would be placed
##

**Comment by MentalMouse** [comment]
Unlike the previous instance, loading the game did work, at least initially, and it show the box as placed.  ETA:  In fact, the box was also in my inventory -- that is, duplicated.

**Comment by rubensworks** [comment]
@immortaleeb Maybe something in Forge changed?

**Comment by MentalMouse** [comment]
IIRC, this is actiually the same forge release (1976) that I was using the last time this came up.

**Comment by rubensworks** [comment]
@MentalMouse I tried fixing this issue here (I could not reproduce your problem): https://dl.bintray.com/cyclopsmc/dev/org/cyclops/evilcraft/EvilCraft/1.9.4-0.10.7-464/EvilCraft-1.9.4-0.10.7-464.jar
Could you try this new version?

**Comment by MentalMouse** [comment]
Might be a day or two before I can get to that, but yeah.

**Comment by MentalMouse** [comment]
OK, the dev version does seem to fix the problem.  Along the way I discovered that only one of my BECs triggered the bug, presumably the original one.  Thanks!
