### ISSUE TITLE
Abyssalcraft's Dreaded Abyssinalite Golem spirit doesn't work in Reviver, Spirit Furnace

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#441]
The spirit of an @AbyssalCraft ( @Shinoow) Dreaded Abyssinalite Golem doesn't drop anything in the Spirit Furnace, and when "reanimated" it yields a nonfunctional gray spawn egg.

**Comment by rubensworks** [comment]
@Shinoow Are you using loot tables for those golems? How do you register those entities? Do they have a regular spawn egg?

**Comment by Shinoow** [comment]
I don't have loot tables for all my entities, and those are in the group that's still using the old stuff. I use this to register my entities (been the same for eternities) https://github.com/Shinoow/AbyssalCraft/blob/master/src/main/java/com/shinoow/abyssalcraft/init/EntityHandler.java#L206-L210

**Comment by rubensworks** [comment]
Is there a specific reason for not using loot tables for all entities? Or did you just not get around to implementing it yet?

The entity (spawn egg) registration looks fine to me, so something must be wrong on my end.

**Comment by Shinoow** [comment]
It's purely me being lazy. I started converting things over to loot tables on a couple of entities (and structure chests), but then I just never went through with adding loot tables for all entities in the mod. It's probably about time I switch it all over.
