### ISSUE TITLE
[1.10.2] Crash on Startup

### ISSUE THREAD

**Issue by nikkimas** [rubensworks/EvilCraft#442]
Forge log link: http://pastebin.com/a5j4U9jD

Crash-Report: http://pastebin.com/uz2q4ktg

Problem: Crash on Startup

Expected behaviour: No crash on startup

Steps to reproduce the problem:
- Start Minecraft
- Wait
- See Crash

**Comment by rubensworks** [comment]
Did you disable the box of eternal closure?
Are you using a mod that is removing/changing the ender chest and/or potions?

**Comment by nikkimas** [comment]
I didn't disable anything from Evilcraft.

I have a mod that lets you change the vanilla ender chest into a color coded ender chest. But it changes nothing of the recipe, and is done by shift right clicking with an Item on the chest.

I think I have no mod, which changes potions, but i'm not 100% sure of that.

**Comment by rubensworks** [comment]
It probably has something to do with that ender chest mod.
Could you tell me the name of that mod?
I'll look into it then.

Note to self: make infobook recipe baking safer when recipes are not found.

**Comment by nikkimas** [comment]
The mod is called "Enderthing"

[Cursepage](https://minecraft.curseforge.com/projects/enderthing)

[Github page](https://github.com/gigaherz/Enderthing/)

**Comment by nikkimas** [comment]
Okay, I removed Evilcraft, and it's not starting up.
Now It's Vampirism, I think (I have no clue how to read crash reports)

Here is the new crash-Report: http://pastebin.com/VKMXCvcz

I'll go to Vampirisms Github and post it there.

**Comment by rubensworks** [comment]
Yes, that's Vampirism.
But that issue has nothing to do with the crash you posted earlier though.

**Comment by nikkimas** [comment]
Oh, okay. So I'll leave this issue open.

~~Why am I always a Bug Magnet? D:~~

**Comment by nikkimas** [comment]
Update: It works, when you disable the box of eternal Closure in the config.

`B:boxOfEternalClosure=false`

(Just a temporary fix, if anyone else encounters that error :) )

**Comment by rubensworks** [comment]
Ok, this is useful information for other people encountering this issue.

I assume the ender chest mod is messing up the box of eternal closure recipe, which my system does not handle very well.

**Comment by nikkimas** [comment]
Seems not to be Ender-Thing.
I removed it and enabled the box.. again.
Report: http://pastebin.com/bAremr8W

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/CyclopsCore@4b1049ae95c053a1f23ee3e02740fd94edee6bbe
Will be released as CyclopsCore 0.7.5 somewhere this week (hopefully).
