### ISSUE TITLE
Chalice Blood Dupication

### ISSUE THREAD

**Issue by Nonsanity** [rubensworks/EvilCraft#444]
Duplication bug without crash, so no log.

Steps to reproduce:
- Place an Ender IO fluid conduit between a Chalice and a Dark Tank.
- Right click the Chalice end of the conduit and set it to always extract.
- Place a small quantity of blood in the Chalice.
- Observe as the tank completely fills without draining anything out of the Chalice.

Expected Behavior: "What comes out must have gone in." :)

**Comment by rubensworks** [comment]
Thanks for reporting, this is a major problem.
