### ISSUE TITLE
Bound Blood Drop in Infuser drains Blood Magic network without filling Infuser

### ISSUE THREAD

**Issue by digitalseraphim** [rubensworks/EvilCraft#448]
Forge log link:
These two lines are immediately before and after placing Drop into Infuser, there were no lines inbetween
[22:40:18] [Client thread/INFO]: [CHAT] Successfully added 0 LP to §rdigitalseraphim§r's LP network.
[22:40:39] [Client thread/INFO]: [CHAT] Successfully added 329955 LP to §rdigitalseraphim§r's LP network.

Problem:
When placing the Bound Blood Drop into the Infuser, the player's blood magic network is completely drained "instantly" (test shown above was over 300,000LP) and no blood was transferred to the infuser

Expected behaviour:
Blood slowly drained from Drop and added to infuser, as it is with the Blood Chest.  Other blood containing objects work fine. 

Steps to reproduce the problem:
1) Put blood into players blood network:
     /bm network add @p 300000
2) obtain a Bound Blood Drop and link to player
3) place in Infuser 
4) ...
5) Experience nausea, as your blood magic network is now empty.

**Comment by rubensworks** [comment]
Thanks for reporting, will look into it in a couple of days.
