### ISSUE TITLE
[1.10.2] Evilcraft causes Immersive Engineering to Crash

### ISSUE THREAD

**Issue by Morpheus1101** [rubensworks/EvilCraft#467]
Crash log @ http://pastebin.com/zfaKmFbt .. this has  been reported also on IE

**Comment by rubensworks** [comment]
It looks like a null entity renderer snuck it's way into the render map.
I'll have a look if I'm somehow responsible for this.

https://github.com/BluSunrize/ImmersiveEngineering/blob/1.10/src/main/java/blusunrize/immersiveengineering/client/ClientProxy.java#L1206
