### ISSUE TITLE
Texture bug or glitch: Waila and Evilcraft

### ISSUE THREAD

**Issue by BatteryVoltic** [rubensworks/EvilCraft#474]
When looking at an evilcraft item i get a missing texture in Waila -this was requested by rubensworks to post this here. Minecraft version 1.10.2 on the MMD Dev server
![2016-09-01_04 29 35](https://cloud.githubusercontent.com/assets/10549249/18175445/56b071e0-703f-11e6-978b-bcd7f3d2accc.png)

**Comment by rubensworks** [comment]
Will be fixed in next release.
