### ISSUE TITLE
MenuMobs crashes on rendering Vengeance Spirit

### ISSUE THREAD

**Issue by C0rn3j** [rubensworks/EvilCraft#476]
Not sure which mod is at fault, so I'm making an issue on both trackers.

http://pastebin.com/8LsY0VAE

Forge 2076
CyclopsCore-1.9.4-0.7.7.jar
EvilCraft-1.10.2-0.10.11.jar
[1.10]MenuMobs-universal-1.9.jar

https://github.com/superbas11/MenuMobs/issues/14

**Comment by bschoenmaeckers** [comment]
Fixed it on my side. mc.thePlayer is not null anymore but still added the vengeance Spirit to the blacklist because its not visible.

**Comment by rubensworks** [comment]
Ok, awesome, thanks!
