### ISSUE TITLE
[1.10.2] SilkTouch Evilcraft Gem has no texture

### ISSUE THREAD

**Issue by Morpheus1101** [rubensworks/EvilCraft#477]
I used the rftools Builder with Silk Touch Quarry to mine an got a DarkGem silkTouched, but had no texture on the block

**Comment by rubensworks** [comment]
Fixed in https://github.com/CyclopsMC/CyclopsCore/commit/ed359ae84812cf245a30aad68bc35c032bb5c8fe
Will be included in the next CyclopsCore release.
