### ISSUE TITLE
Crash when registering Gregtech block in Display Stand

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#479]
https://github.com/Blood-Asp/GT5-Unofficial/issues/638

Moved from CyclopsMC/CyclopsCore#24

**Comment by Rongmario** [comment]
When is this being fixed may I ask?

**Comment by rubensworks** [comment]
Most likely not before next week, in the meantime you can disable the Display Stand, this should allow you to start without crashing.

**Comment by Rongmario** [comment]
Oh thanks! Sorry for the bugging.
