### ISSUE TITLE
Crashing when placing Tinker Construct items in blood chest.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [rubensworks/EvilCraft#482]
1. Put any damaged Tinker's Construct item into the blood chest for repair
2. Crash randomly

Log: https://gist.github.com/anonymous/a2afba54e332298f73146ff5428b2afa

It's random. Doesn't happen often, but it does.

**Comment by rubensworks** [comment]
Next release will contain a possible fix for this, keep me posted if this resolves your issue after the release.

**Comment by rubensworks** [comment]
Assuming fixed.
