### ISSUE TITLE
[1.10.2] Intergrated Dynamics Drying Basin dosent dry blood when filled

### ISSUE THREAD

**Issue by Morpheus1101** [rubensworks/EvilCraft#483]
Since the blood drying thing shows in JEI as a valid option to use blood to dry to make solid blood blocks, i thought it would work, unfortunately it dosent, however being that this relates to Intergrated Dynamics i'll also shove it over on there github since i cant be sure as if its ID or EC fault to why it isnt working as JEI sais its meant to.

https://github.com/CyclopsMC/IntegratedDynamics/issues/69

**Comment by rubensworks** [comment]
Thanks!
I'll close the issue here, since the recipes are added in ID.
