### ISSUE TITLE
NPE server crash with environmental accumulator

### ISSUE THREAD

**Issue by LemADEC** [rubensworks/EvilCraft#484]
NullPöinterException in environmental accumulator related to recipe handling.

Crash report is here: http://pastebin.com/gWGyQqh1
Using EvilCraft-1.7.10-0.9.9.jar
According to logs player did nothing special, just moving around her base and disconnecting. Hence, it might be related to chunk unloading.

**Comment by rubensworks** [comment]
Will be fixed in next release.
