### ISSUE TITLE
Received an invalid item request

### ISSUE THREAD

**Issue by DatrixTHLK** [rubensworks/EvilCraft#487]
- FML Log: https://gist.github.com/DatrixTHLK/9779e3a193a71e7f132087993c558027
- The problem I am getting Is that FML is telling me of an error that is dealing with your mod
- The behavior that I was expecting was that the recipe for items that don't exist would actually exist
- There weren't any steps, FML just told me to report this.
  Minecraft: 1.10.2
  Forge: 2095
  Cyclops Core: 1.9.4-0.7.7
  Evilcraft: 1.10.2-0.10.11

**Comment by rubensworks** [comment]
Fixed in 70b33e2e88752ee5bd2f9e600e4d974fca986eeb (unreleased)

**Comment by DatrixTHLK** [comment]
Thanks rubenworks.
