### ISSUE TITLE
Vengeance Spirits always attacking

### ISSUE THREAD

**Issue by darklordwonton** [rubensworks/EvilCraft#489]
I like vengeance spirits as a mechanic but they're way too powerful (it might just be because of the other mods I have though) an option to make them only attack players who can see them would be handy.

**Comment by rubensworks** [comment]
Vengeance spirits should only attack players who can seen them though, are you experience this otherwise?
They should only become visible when using a vengeance tool.

**Comment by darklordwonton** [comment]
I've been experiencing vengeance spirits attacking me even when I can't see them. This might be caused by the mod I have, I'll post a full mod list later but I think the most likely culprit is either Epic Siege or Rough Mobs.

**Comment by rubensworks** [comment]
Any news on this? I think you were probably wearing an activated Vengeance Ring, which will constantly summon vengeance spirits.

**Comment by APolarBaer** [comment]
i think my issue may be Epic Siege Mod aswell then, because im running into this and using Epic Siege

**Comment by rubensworks** [comment]
@APolarBaer Could you report this issue to the authors of that mod? Be sure to mention this issue thread as well. They might be doing something like angering all mobs in the area all the time, which could cause the invisible vengeance spirits to be angered as well.

**Comment by APolarBaer** [comment]
https://github.com/Funwayguy/Epic-Siege-Mod/issues/46

**Comment by APolarBaer** [comment]
https://github.com/Funwayguy/Epic-Siege-Mod/issues/46

**Comment by rubensworks** [comment]
Seems to be caused by the Epic Siege Mod, not much I can do about it from my end.

@APolarBaer I'm subscribed to the issue you created, so I'll know if the Epic Siege Mod author needs anything from my end to fix this.

**Comment by Normal69** [comment]
I am currently searching for the exact name of the mob to insert here, version 1.12.2:
general {
    # Mobs that are exempt from AI modifications [default: [minecraft:villager_golem]]
    S:"AI Blacklist" <
        minecraft:villager_golem
        evilcraft:VengeanceSpirit  <-- is it this one?
        evilcraft:*
        minions:AS_EntityMinion
     >

**Comment by rubensworks** [comment]
@Normal69 Should be `evilcraft:vengeance_spirit`.

**Comment by Normal69** [comment]
Thank you very much.
