### ISSUE TITLE
Can't see the recipe for Blood Extractor

### ISSUE THREAD

**Issue by C0rn3j** [rubensworks/EvilCraft#493]
http://i.imgur.com/WeIkZVK.png

Forge - 2107

Modlist - http://pastebin.com/hEMvVjJd

**Comment by rubensworks** [comment]
Huh, at one point in time JEI was able to show these crafting recipes.
Something in JEI might have changed with regards to items that have both a regular crafting recipe and can be used as fluid containers in other recipes.

@mezz Could this be a problem on your end? Or should I add specific crafting handlers for this?

**Comment by mezz** [comment]
JEI has a relatively new subtype registry system for interpreting items with nbt, capabilities, etc. 
The fluid capability is automatically supported, so for recipes JEI is going to consider a filled blood extractor to be different from an empty one. I'm not exactly sure why this would stop it from looking up your recipe, but I'm pretty sure it's related to this issue.
If you want to have JEI interpret it differently, first update to the latest JEI version and then you can override the default behavior by using `ISubtypeRegistry`. The javadoc there will explain more.

**Comment by rubensworks** [comment]
The blood extractor has some additional NBT data, so that will be the problem.
I'll look into the `ISubtypeRegistry`, thanks!
