### ISSUE TITLE
Vengeance Spirit String -> Integer cast

### ISSUE THREAD

**Issue by murapix** [rubensworks/EvilCraft#494]
Playing Elucent's newest custom pack, occasionally crash to desktop with this crash log:

http://pastebin.com/FkehiHUW

No idea how to create or reproduce this, just happens occasionally upon joining the server.

**Comment by rubensworks** [comment]
Maybe @immortaleeb knows what the problem is here.

**Comment by C0rn3j** [comment]
Similar issue happened when slaying/hitting a zombie pigman in the overworld.

http://pastebin.com/ei9wCLxF

**Comment by rubensworks** [comment]
I'm not able to reproduce the crash, but the changes in the last commit could resolve your issues.
A new update with this change is coming soon.
