### ISSUE TITLE
Breaking tank losing fluid

### ISSUE THREAD

**Issue by TBone311xXx** [rubensworks/EvilCraft#499]
Forge log link: none available

Problem: evilcraft tank was full, then when broken by another player and replaced, became empty. The fluid that it was full of was ars magica liquid essence.

Expected behaviour: not to be empty when it was full when broken and replaced

Steps to reproduce the problem:
- difficult to reproduce, only happened once, may be tied to it being full when broken
-

**Comment by rubensworks** [comment]
If you're not able to reproduce it, it will be difficult for me to do so as well.
It's the first time I hear about a bug like this, so I would think this is being caused by something else.

I'll leave this issue open for now until someone is able to reproduce it.

**Comment by rubensworks** [comment]
Not reproducible.
