### ISSUE TITLE
[1.10.2.0.10.13] No recipe for crushed dark gem.

### ISSUE THREAD

**Issue by BrelanAllin** [rubensworks/EvilCraft#500]
Trying to use extra utils 2 crusher or immersive engineering crusher.

When checking NEI I see no recipe to make it.

**Comment by rubensworks** [comment]
No support for these mods exist at the moment.
You probably can add the recipe yourself in the config files of those mods.

**Comment by Runesmacher** [comment]
Added support for Immersive engineering with #525 
And support for the EnderIO SAG Mill with #526 

Support for extra utilities 2 might be added later

**Comment by rubensworks** [comment]
Thanks @Runesmacher
