### ISSUE TITLE
[1.10.2] Non-Fatal crash on recipe 

### ISSUE THREAD

**Issue by b0bst3r** [rubensworks/EvilCraft#502]
Forge log link: http://pastebin.ubuntu.com/23473468/ line 7637

Problem: Found a broken recipe: org.cyclops.evilcraft.core.recipe.DisplayStandRecipe@aa82113
Failed to create recipe wrapper

The display stands in game have no recipe in JEI.

EvilCraft-1.10.2-0.10.14

**Comment by rubensworks** [comment]
Thanks for reporting! There was an incompatibility with the newer JEI versions.
