### ISSUE TITLE
Crash when respawning if you have broom in inventory and broom in display stand nearby

### ISSUE THREAD

**Issue by hiimcody1** [rubensworks/EvilCraft#503]
Forge log link: http://pastebin.com/nR57z2SP - latest.log
http://pastebin.com/T8GhBqLY - crash report
Problem:
Crash when respawning after dying with broom in inventory. Display stand that contains another broom is noted in the crash.
Expected behaviour:
Respawn without crashing
Steps to reproduce the problem:
Die with broom in inventory and display stand containing broom nearby, respawn.

**Comment by rubensworks** [comment]
Ah, a typical world-is-still-loading-while-rendering problem.
I thought Forge would've fixed these by now.
But it's an easy fix, I'll look into it.
