### ISSUE TITLE
Poison-Sacs Pufferfish, and plurals

### ISSUE THREAD

**Issue by UnrefinedCatalyst** [rubensworks/EvilCraft#504]
Well, i've had this mod for a while and i was thinking. If you can use poisoned potatoes and poison sacs, why can't we use pufferfish?
 I mean, they poison you when you eat them. you could craft them to make poison sacs, or you can just do the same thing you did with the potatoes.
Maybe you could even make it so that you cut the poison sac out of the pufferfish, and you can eat the pufferfish meat.

This was just something that i thought would be interesting.

by the way, i've been using this mod with another called saltymod, which adds salt, salt lakes, and that sort of thing, and the dark tanks and endless water source block make a furnace like item in saltymod that extracts salt much more useful.

-UnrefinedCatalyst

**Comment by rubensworks** [comment]
Makes sense, that's an easy thing to add, I can look into doing that.

**Comment by UnrefinedCatalyst** [comment]
great!
