### ISSUE TITLE
Spirit Furnace not producing player-only mob drops.

### ISSUE THREAD

**Issue by The-Key** [rubensworks/EvilCraft#505]
Forge log link:
[log.zip](https://github.com/CyclopsMC/EvilCraft/files/648242/log.zip)

Problem:
Spirit furnace won't produce drops that require a player to kill the mob.

Expected behaviour:
Blazes to produce blaze rods and withers to produce nether stars.

Steps to reproduce the problem:
-Capture a vengeance spirit from a mob that has player only drops.
-Put box in spirit furnace.

**Comment by rubensworks** [comment]
MC, Forge and EvilCraft versions?

**Comment by The-Key** [comment]
MC:1.10.2
Forge: 12.18.3.2185
Evilcraft: 0.10.16
