### ISSUE TITLE
Environmental Accumulator's Beam sees through water

### ISSUE THREAD

**Issue by SpartanSamuel** [rubensworks/EvilCraft#506]
Forge log link: http://pastebin.com/ecPP0GaX

Problem: The Environmental Accumulator's beacon beam allows me to see through water to the riverbed. http://imgur.com/nP6CBOS

Expected behavior: The beam shouldn't see through water.

Steps to reproduce the problem:
-Looked through Environmental Accumulator's beam near a river...?

MC: 1.10.2
Forge: 12.18.3.2185
EC: 0.10.16
CC: 0.8.2

**Comment by rubensworks** [comment]
Unfortunately, this is not something that can easily be fixed without rewriting significant parts of the MC rendering engine.
Last time I checked, this problem also occurs with vanilla beacon beams and lightning strikes.

**Comment by SpartanSamuel** [comment]
Ah, alright. I understand.

For clarification, though, vanilla beacon beams work just fine. I don't know about lightning strikes.
