### ISSUE TITLE
Non-Serverbreaking (I think) error found in server console/log

### ISSUE THREAD

**Issue by sharkck** [rubensworks/EvilCraft#507]
[fml-server-latest.txt](https://github.com/CyclopsMC/EvilCraft/files/679521/fml-server-latest.txt)

We havent noticed anything gameplay wise that isnt working.  I just noticed this error being spammed in the console and wanted to report it.  I'm not sure when it started or why it's happening.

I can provide further info if needbe.  

Running Evilcraft  2.0.10.16 on Forge 2185 MC 1.10.2.

Here is a screenshot of our mob drop where the pedestal is.

![screenshot 2016-12-31 02 37 10](https://cloud.githubusercontent.com/assets/960552/21576534/10165dd6-cf02-11e6-8e41-0f5f88bfb604.png)

**Comment by rubensworks** [comment]
Ah, it looks like I'm doing something wrong with sending particles to the client. I'm surprised this doesn't crash servers...
