### ISSUE TITLE
[1.10.2] Client Crash On load with VengeanceRing

### ISSUE THREAD

**Issue by Morpheus1101** [rubensworks/EvilCraft#509]
Forge *.2202
EvilCraft 0.10.18

Crash log @ https://puu.sh/th71n/dc41e6ecaf.txt
fml-client-latest @ https://puu.sh/th7e1/2979f7feab.log

**Comment by rubensworks** [comment]
Does this crash occur only after updating to the latest EvilCraft version?
Can you reproduce this without any other mods installed?

**Comment by Morpheus1101** [comment]
Testing with EC on its own and this only occured when i added in OpenComputers & Actually Computers

EDIT:

Tested with EC on its own, works fine .. tested with EC + Opencomputers and Actually Computers an works fine, so id have to run through a mod by mod basis to find out which mod is causing this conflict

**Comment by rubensworks** [comment]
That crashlog would make me think that one of those mods is shipping an invalid version of Baubles API. Are you aware of Baubles support in either of those mods?

**Comment by Morpheus1101** [comment]
Now that you mention it, i think maybe 1 or 2 mods uses that API....id have to check

**Comment by rubensworks** [comment]
In that case, make sure to report it to their issue tracker as well, because this crash is caused by Forge thinking that Baubles is loaded, while it actually isn't.

**Comment by Morpheus1101** [comment]
Im going to close this issue here as this from further testing is clearly not EC bug, but more what ever mod has the API, as disabling EC an c.Core just causes a baubles crash issue in another mod which im going to assume will be the case if i also disable that mod an so on an so forth.
