### ISSUE TITLE
[1.11.2]Server crashed when some in the nether

### ISSUE THREAD

**Issue by Amamiya-Nagisa** [rubensworks/EvilCraft#511]
Forge log link:http://pastebin.com/WETe9p5W

Crash-report:http://pastebin.com/YKdEv9TF

Problem:Server crashed when some in the nether

Steps to reproduce the problem:
-Go to the nether

**Comment by rubensworks** [comment]
Duplicate of #510.

@Amamiya-Nagisa Please always check the closed issues before reporting a new one.
