### ISSUE TITLE
[1.11.2] [EvilCraft-1.11.2-0.10.18] Cannot feed passive animal Darkened Apple

### ISSUE THREAD

**Issue by shortybsd** [rubensworks/EvilCraft#513]
Minecraft 1.11.2
Forge 2223
EvilCraft-1.11.2-0.10.18

Cannot feed an animal a Darkened Apple. Only way I was able to get the book is to suicide by eating the Darkened Apple then another player throw a book on the orb coming off my corpse, then visa versa.

**Comment by rubensworks** [comment]
Oops, this mod is not meant to be _that_ evil.

**Comment by shortybsd** [comment]
LOL ! <3

**Comment by rubensworks** [comment]
I can't reproduce this, seems to work just fine for me.
What animals did you try this on?

**Comment by shortybsd** [comment]
Pig, Sheep, Chicken & Cow.

**Comment by rubensworks** [comment]
@shortybsd This could be a mod conflict issue. Can you try it without any other mods installed? Except for EvilCraft and CyclopsCore?

**Comment by shortybsd** [comment]
I will once I get home from work. I have no other animal mod that does anything with them so I am lost on which mod to assume is conflicting with yours. If I have enough time, I will load each of the mods to figure out which one it is, unless a list would help you.
