### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by Sean-Amor** [rubensworks/EvilCraft#514]
I'm in the very fetal stages of learning to mod, it's a stretch but I'd love to see if you could make a separate mod that only has the broom, no parts or anything like that just a broom that can be picked from creative, and flown, no "energy" required. Perhaps there can be a weak broom, and a fast broom. Then post it's source on a github page? I can see how you have the broom, but all the parts, and modifiers go right over my head and seem unecessary. Totally understand if you choose not to make this, I'm just making a Harry Potter mod, and thought this was perfect.

**Comment by rubensworks** [comment]
The broom will remain part of this mod, I won't be extracting this, or at least not any time soon. Sorry.
