### ISSUE TITLE
Dark Ore missing texture (Quarry Silk Touch)

### ISSUE THREAD

**Issue by Discomanco** [rubensworks/EvilCraft#515]
Forge log link: 
-

Problem:
Dark Ore is missing all texture when taken from a Quarry with Silk Touch (Digital Miner with Silk Touch, RFTools Builder with Silk Touch Quarry card)

Expected behaviour:
Should have texture, just like when mined with Silk Touch Quarry

Steps to reproduce the problem:
- Get any Quarry that can have Silk Touch (RFTools Builder, Mekanism Digital Miner)
- Let it mine Dark Ore with Silk Touch
- Notice missing texture
Gains normal texture when placed in world
Has normal texture when mined from a tool with silk touch
Missing texture Dark Ore doesn't stack with normal Dark Ore
http://i.imgur.com/BAKWax2.png

Minecraft: 1.10.2
Forge: 12.18.3.2221
EvilCraft: 0.10.19

**Comment by rubensworks** [comment]
I thought I fixed this before already, may be a regression.

**Comment by rubensworks** [comment]
This is caused by RFTools and Mekanism, and has been reported.
