### ISSUE TITLE
Uncraftable and Useable broom

### ISSUE THREAD

**Issue by zerowily** [rubensworks/EvilCraft#519]
Forge log link: http://pastebin.com/3HSzLpzE

Problem: I was trying to create a broom now that I need to gather popped Chorus fruit and End Crystals I crafted a feather brush and a bone rod with a dark power gem cap. Upon putting these in my crafting bench or exalted crafter, I did not get the completed recipe for the broom I was trying to make. I tried a diamond cap and a dark gem cap and it still did not work. I then wanted to see if I could exchange the parts in a pre-made broom, So I went into creative and spawned in the broom made from a dark gem cap wood rod and wheat brush. I tried to add my parts but it wouldn't craft again, So I decided to try out that broom and see if I could fix my parts later. When I loaded the wood broom with blood and attempted to fly the blood simply vanished and the broom flew slowly. I tried this three times to no avail.

Expected behaviour: I expected to have a craftable broom and a working broom.

Steps to reproduce the problem:
- I crafted my Feather Brush, Bone Rod, Dark Power Gem Cap.
- I attempted to put them in a vertical line in my crafting bench, Then my wooden exalted crafter. Nothing crafted.
- I attempted to use a diamond cap and a dark gem cap. It didn't work either
- I then attempted to try and change up the placements of items in the crafting grid, nothing changed.
- Moving to creative I spawned a broom and tried to change the parts. It didn't craft either.
- Then I tested the use of a broom with the one I spawned. Using some blood in my infuser I mounted the broom and watched the blood disappear from its small bar in the right bottom corner and the broom flew slowly.

**Comment by rubensworks** [comment]
I remember that I haven't tested this yet when porting to 1.11, which explains these issues...
I'll look into it soon.

**Comment by zerowily** [comment]
Thanks!

**Comment by rubensworks** [comment]
Related: db96a6afc44fa6a07269c83e504c4eba34d49e24

**Comment by FuriousT** [comment]
Hi! 

I have a similar problem. I'm running my own server with 12 mods, my minecraft version is 1.11.2 and evilcraft is 0.10.17.

Is this already fixed somehow? We would like to create our own brooms. 

I'm sorry if it's fixed already, but I could use simple instructions, since I'm not so good with running my own server.

**Comment by rubensworks** [comment]
@FuriousT Fixed in dev, to be released.
