### ISSUE TITLE
Can't use blood from Evilcraft in Blood Magic altars!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [rubensworks/EvilCraft#530]
How come I can't use the blood from Evilcraft in my Blood Magic altars, even though it's part of the blood network?

https://imgur.com/a/78YkS

**Comment by rubensworks** [comment]
That's normal, because the blood you extract there is EvilCraft blood, not BM's life essence. BM probably has a way to load soul network life essence into the altar. Otherwise, you could use the Fluid Converters mod to convert blood into life essence.
