### ISSUE TITLE
Upgraded dark tank only retains part of the stored fluid when broken

### ISSUE THREAD

**Issue by tommyTT** [rubensworks/EvilCraft#536]
Forge log link:
https://hastebin.com/ruwodatubi.md

Problem:
A upgraded dark tank only retains 16 buckets of its fluid when breaking the tank.

Expected behaviour:
Tank retains all of the fluids when breaking it.

Steps to reproduce the problem:
- Upgrade a dark tank (I crafted two together).
- Place the tank down and fill it with more than the initial 16 buckets of any fluid (I used lava).
- Break the tank and pick it up.

**Comment by rubensworks** [comment]
Fixed in EvilCraft `0.10.21`.
