### ISSUE TITLE
Undefined function called resulting in crash

### ISSUE THREAD

**Issue by mikromax0** [rubensworks/EvilCraft#538]
* Forge log link:

Minecraft log: https://paste.ee/p/GUerh
Forge log: https://paste.ee/p/UXzQe
Crash log: https://paste.ee/p/3mmke

* Problem:

Crash on world load implicating EvilCraft / Cyclops Core. Cyclops Core appears to call an unimplemented function, resulting in the crash: 

org.cyclops.cyclopscore.inventory.PlayerExtendedInventoryIterator.setBaublesStack()

* Expected behaviour:

No crash on world load.

* Steps to reproduce the problem:

Unclear.  I have many hours of game play logged for this world.  The issue arose after I upgraded EvilCraft and Cyclops Core to the latest versions. I also added Integrated Dynamics.  The bug manifests reliably when I attempt to load the world (as soon as the game starts ticking my character).  Seems to be related to the Entangled Chalice in my inventory.  Previous to this I did not have the Baubles mod in my modpack.  I added it to see if it would help resolve this issue.  It did not.

**Comment by rubensworks** [comment]
Ah, the Baubles mod seems to have changed its mod id to lowercase in 1.11, will be an easy fix.
