### ISSUE TITLE
Recursive Worldgen Issue

### ISSUE THREAD

**Issue by mezz** [rubensworks/EvilCraft#539]
Hey,

In Forge 1.11.2 - 13.20.0.2258 there is a new detection for worldgen features that load new chunks and cause more worldgen.  
This can cause a lot of lag when loading new chunks. [I wrote a post about the issue here.](https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/)

>[Server thread/WARN] [FML/]: EvilCraft loaded a new chunk (-12, 1  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker.

You can debug this by grabbing the latest Forge, creating a new world or flying around, and putting a breakpoint at this log (at the bottom of `Chunk.java`). You should see that one of your worldgen features is loading a new chunk and causing more worldgen.

**Comment by rubensworks** [comment]
Thanks for reporting this, I'll look into it.
