### ISSUE TITLE
[1.11.2][0.10.21] Naturally generated Dark Ore has no texture when mined with a silk touch pickaxe

### ISSUE THREAD

**Issue by starg09** [rubensworks/EvilCraft#541]
Forge log link:

Problem: Mining a naturally-generated Dark Ore with a Silk Touch pick drops a ore item with a broken texture/model. This happens when mining them both manually (regardless of the pick used, can be replicated with vanilla), or with a machine like RFTools' Builder. Manually placed ores (given through creative tab, or through JEI if installed) don't seem to have this issue. As a note: besides this visual glitch, the item itself works properly.

This can be replicated on a clean instance with only Forge, CyclopsCore and EvilCraft (like the one used for the log above).

Expected behaviour: The ore not to have a broken texture.

Steps to reproduce the problem:
- Create a new instance with only:
  + Forge 2259
  + CyclopsCore 0.9.4
  + EvilCraft 0.10.21
- Open a brand new world, default generation (also affects others, like ATG; mentioning it just in case)
- Search for some natural Dark Ore
- Mine one normally, no issues there (drops dark gems as expected.
- Mine one with a silk touch pick, get an item with no texture.

**Comment by starg09** [comment]
Seems like this still happens on release 0.10.22 for MC 1.11.2

**Comment by rubensworks** [comment]
@starg09 Is this occurring in newly generated chunks? Because the bug was caused by invalid blockstates during worldgen, so any previously generated chunks will still have the problem.

**Comment by starg09** [comment]
Tested it on a brand new world, clean instance with only forge (2260),
newest evilcraft (on mobile rn, the one with the fix on CF), and using
vanilla tools.

El 27 mar. 2017 8:15 AM, "Ruben Taelman" <notifications@github.com>
escribió:

@starg09 <https://github.com/starg09> Is this occurring in newly generated
chunks? Because the bug was caused by invalid blockstates during worldgen,
so any previously generated chunks will still have the problem.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/CyclopsMC/EvilCraft/issues/541#issuecomment-289359455>,
or mute the thread

**Comment by rubensworks** [comment]
Strange, I tested this right before the release, and it worked just fine then.
Maybe I did something stupid, I'll look into it.
