### ISSUE TITLE
1.11.2: if i disable a few items from config, the game crashes when making the book

### ISSUE THREAD

**Issue by Lothrazar** [rubensworks/EvilCraft#542]
Forge log link: http://pastebin.com/jgWh6XKb

Problem:
I disabled a few items in the config file. Then the game crashed on startup.  Relevant line is 
java.lang.NullPointerException
	at org.cyclops.evilcraft.infobook.OriginsOfDarknessBook$2.create(OriginsOfDarknessBook.java:69) ~[OriginsOfDarknessBook$2.class:?]

Expected behaviour:
Game starts up with those items disabled, and dont show up in the book

Steps to reproduce the problem:
- i think it was only
sanguinary_environmental_accumulator=false
environmental_accumulator=false
- Then startup the game and it crashes

**Comment by rubensworks** [comment]
Probably a simple `isEnabled` check that must be added, will look into it soon.
