### ISSUE TITLE
Infinite Blood Dupe

### ISSUE THREAD

**Issue by greenking13** [rubensworks/EvilCraft#546]
Forge log link: Not a crash

Problem: I'm pretty certain I just found a blood dupe with your mod and blood magic.

Expected behaviour: The amount of blood inside the blood infuser plus the amount in the blood drop should be equal to the amount inside the blood infuser plus the blood drop after removing blood via shift right click method.

Steps to reproduce the problem:
1. Acquire Bound Blood Drop
2. Put in Blood Infuser one Promise of Tenacity 3, three Promise of Productivities, and four Promise of Velocities. 
3. Place x amount of blood in blood infuser. (I'd say 100,000 to be on the safe side.)
4. Using shift-right-click remove blood from the blood infuser via the Bound Blood Drop.
5. After repeating step 4 multiple times, add the amount in the Bound Blood Drop and Blood Infuser and compare the the x amount you put in.

Versions:
BloodMagic-1.10.2-2.1.8-77
EvilCraft-1.10.2-0.10.21
(I just took the file names tbh.)

Extra Information:
This was found and tested on a server. I have not tested if this behavior occurs in single player.

If any other information is needed, please just say so and I'll do the best I can to get it to you in a timely fashion.

**Comment by greenking13** [comment]
As an added bonus tidbit... should you be able to exceed the set max of 250,000mb? Because I now have 267,233mb in it.

**Comment by greenking13** [comment]
Also, apologies for not stating the MC version in the title, it's MC 1.10.2.

**Comment by rubensworks** [comment]
Yes, it's normal that you can exceed the maximum amount, but only if it is being filled externally via the BM Soul Network.
