### ISSUE TITLE
Mekanism digiminer issue

### ISSUE THREAD

**Issue by ApostolosRisen** [rubensworks/EvilCraft#548]
the dark ore from this mod will not be mined by the digiminer although it is found in the ore dictionary  and registered in the digiminer  
![image](https://cloud.githubusercontent.com/assets/26664327/25318454/43d4ab00-285d-11e7-9c1c-cb9fcf63b89d.png)
this is cross posted on the mekanism page as well 
any help would be appreciated

**Comment by rubensworks** [comment]
For reference: aidancbrady/Mekanism#4338

**Comment by rubensworks** [comment]
Related to #541 and will therefore be fixed in the next EC release.
