### ISSUE TITLE
xceptionModCrash: Caught exception from EvilCraft

### ISSUE THREAD

**Issue by IchigoGames** [rubensworks/EvilCraft#549]
Forge log link: https://www.dropbox.com/s/aqo32lafzm06qy9/latest.log?dl=0

Forge 2282 

minecraft 1.11.2

crash report https://pastebin.com/M0PpnHxH

Problem: crashing with ic2

Expected behaviour: not crashing

Steps to reproduce the problem:
- add forge

-add EvilCraft

-add ic2

CyclopsCore-1.11.2-0.10.2
EvilCraft-1.11.2-0.10.23
does not work with 
industrialcraft-2-2.7.12-ex111 
not sure if this is a bug on your end or theres.

**Comment by rubensworks** [comment]
It looks like they made a constructor private, I'll have to push a new fix for that.

**Comment by rubensworks** [comment]
New EC update is pending on CurseForge.
