### ISSUE TITLE
[1.7.10] No start-up with CloneCraft

### ISSUE THREAD

**Issue by Kahra** [rubensworks/EvilCraft#550]
Forge log link: https://pastebin.com/y3ChGHsg

Problem: 
On 1.7.10, EvilCraft seems to conflict with CloneCraft. When both are present, the launcher is stuck at the step 5/7 
"Loading - Initializing mods Phase 3" on the 
"PostInitialization - CloneCraft".
So, it might be on CloneCraft side but I don't know if you have a clue of the origin ? (as CloneCraft'dev seems pretty busy atm)

Expected behaviour: The loading don't stuck.

Steps to reproduce the problem:
- Install CloneCraft 3.0.15-Beta 
(http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1281105-clonecraft-vb3-0-11-mc-1-7-10-adds-npc-humans-for)
and the latest EvilCraft for 1.7.10
-

**Comment by rubensworks** [comment]
Something is going wrong in CloneCraft, not much I can do from my end unfortunately.
You should report it to the CloneCraft developer.

**Comment by Kahra** [comment]
Ok, thx for the quick answer
