### ISSUE TITLE
the blood and poison in the tanks have no name

### ISSUE THREAD

**Issue by DSLM** [rubensworks/EvilCraft#552]
![2017-05-14_10 13 58](https://cloud.githubusercontent.com/assets/12635058/26034698/8686b54c-388e-11e7-8363-c05cbe5577aa.png)
![2017-05-14_10 16 12](https://cloud.githubusercontent.com/assets/12635058/26034703/90d2ffce-388e-11e7-848a-b3ddcfc5a72e.png)

**Comment by rubensworks** [comment]
Ah yes, this was something I broke in the last CC update.
I already fixed in dev and will be included in the next CC release: CyclopsMC/CyclopsCore@e59987d852566d942affb3cc933ec081455d9ace
