### ISSUE TITLE
broom problem

### ISSUE THREAD

**Issue by DSLM** [rubensworks/EvilCraft#554]
1. When craft a broom part, you can use any broom part as bare part to craft (ex. 2 diamond and a bare part can get a diamond cap)
2. When you ride broom to the ceiling, you will suffocate.

**Comment by rubensworks** [comment]
Fix for 1 will be included in the next release.
2. is intended, following the vanilla behaviour when riding horses.

**Comment by DSLM** [comment]
OK, thx
