### ISSUE TITLE
Bound Blood Drop Problem

### ISSUE THREAD

**Issue by DSLM** [rubensworks/EvilCraft#557]
1. Bound Blood Drop will take out 6000mb blood from Purifier when there is 3000mb blood inside. (other containers work normally)
2. Bound Blood Drop looks like only 250000mb room for blood, but if it's full, it still can put blood in.
3. Bound Blood Drop can have more blood than the limit of Blood Magic Orb level.

**Comment by rubensworks** [comment]
1 sounds like a bug.

2 and 3 are intended.

**Comment by DSLM** [comment]
thx
