### ISSUE TITLE
Allow Spirit Furnace mob drop overriding via config file

### ISSUE THREAD

**Issue by belathus** [rubensworks/EvilCraft#560]
Forge log link:
https://drive.google.com/file/d/0B49aLxlzNByoZUNYMTVBRFFNNzQ/view?usp=sharing

Problem:
I attempted to place an Ovis Atir from @An-Sar's PrimalCore into the spirit furnace to get their wool. I heard the sounds of them dying, but nothing appeared in the outlet slots. I then attempted to put a cyberzombie (from @Flaxbeard's Cyberware) into the spirit furnace and only got vanilla drops, despite the fact that I had edited zombie's drops using MobProperties (specifically, I removed their ability to drop iron ingots and added copper, zinc, and tin ingots to their drops; I got iron ingots from the spirit furnace).

Expected behaviour:
I was expecting the ovis atir to drop their wool and meat. I similarly expected cyberzombies to potentially drop cyberware components.

Steps to reproduce the problem:
Place ovis atir in the spirit furnace and supply blood.
The cyberzombie thing might be a little more complicated, as I modified their drops. I modified them here: https://github.com/belathus/Wanderlust-Renewed/blob/master/config/MobProperties/cyberware/cyberzombie.json

Furthermore, I did notice there was references in your code for the spirit furnace to override mob drops. I didn't see exactly how to do that, but I'd love to know how!

**Comment by rubensworks** [comment]
If the mobs are using the JSON-based loot files they should work.
Special cases should be manually added using the spirit furnace drops overrides in the config file, for which an example is added for villagers dropping emeralds.

**Comment by belathus** [comment]
This line?
```
    # The 1/X chance for villagers to drop emeralds. 0 means no drops.
    I:spiritFurnace.villagerDropEmeraldChance=20
```

**Comment by rubensworks** [comment]
Hmm, no, that's not it.
There should be something related to spirit drop overrides.

I'm on the road now, so I can't check myself.

**Comment by belathus** [comment]
I'm not having much luck finding overrides for the spirit furnace.

Sadly, many mods don't seem to be using the JSON based drop lists. If an entity doesn't have a loot table written for it already, is it possible to add one for it without modifying the mod, or does need to reference a loot table for it to produce drops from it?

**Comment by rubensworks** [comment]
It looks like EC doesn't provide a way to override mob drops via the config file, but it does via IMC.
Perhaps I should look into adding functionality for that...
