### ISSUE TITLE
Mobs over-spawning in overworld and not spawning in nether due to EvilCraft

### ISSUE THREAD

**Issue by IchigoGames** [rubensworks/EvilCraft#562]
Forge log link :https://www.dropbox.com/s/1tlaxqgc5ym6s3k/latest.log?dl=0 i dont think this will help but here you go.
Problem: with EvilCraft-1.11.2-0.10.26 and CyclopsCore-1.11.2-0.10.4  mobs are over spawning in the overworld and mobs in the nether like blaze and wither skeleton are not spawning but with CyclopsCore-1.11.2-0.10.3 and EvilCraft-1.11.2-0.10.25 it seems to work fine.
Expected behaviour: for mobs to spawn as normal 
Steps to reproduce the problem: not sure on this it seems to happen in my modpack The New Frontier but not in vannla but like i said when i downgraded it it works fine so it could be something with EvilCraft and other mods.

**Comment by IchigoGames** [comment]
hopefully you can find out why this happens if not ill have to stay with older EvilCraft in my pack

**Comment by rubensworks** [comment]
Can you reproduce this with just EC and CC installed?
Nothing much has changed between version 25 and 26, so EC is unlikely to be the cause of this.

**Comment by IchigoGames** [comment]
may have been a false flag back to the drawing board for me.
