### ISSUE TITLE
Bound Blood Drop has incorrect recipe on 1.11.2

### ISSUE THREAD

**Issue by esotericist** [rubensworks/EvilCraft#564]
In the current version of evilcraft(EvilCraft-1.11.2-0.10.26.jar), both the mod ID and the item ID for the bound blood aren't correct, making the blood drop not craftable (although it still works correctly if you cheat one in).

The relevant section of bloodinfuser_mods.xml should probably read (and this is what I'm currently using in my _overrides folder):

    <recipe type="evilcraft:bloodinfuser">
        <condition type="mod">bloodmagic</condition>
        <condition type="config">blood_infuser</condition>
        <condition type="config">bound_blood_drop</condition>
        <input>
            <item meta="2">bloodmagic:itembloodorb</item>
            <fluid amount="10000">evilcraftblood</fluid>
        </input>
        <output>
            <item>evilcraft:bound_blood_drop</item>
        </output>
        <properties>
            <duration>1000</duration>
            <tier>2</tier>
            <xp>10</xp>
        </properties>
    </recipe>

**Comment by rubensworks** [comment]
Thanks, I'll update the recipe with your version soon! :-)

**Comment by esotericist** [comment]
Wow, that was fast!
