### ISSUE TITLE
Unable to craft Bound blood drop

### ISSUE THREAD

**Issue by Caopr** [rubensworks/EvilCraft#565]
Trying to click for the recipe nothing happens. UNable to place blood orbs in the infuser either

I looked around in bloodinfuser_mods.xml and found this which might be it

            <item>bloodmagic:bloodmagic:itembloodorb</item>
should just be 
            <item>bloodmagic:itembloodorb</item>

I tested this change and was able to use the Tier 1 orb to make the Bound blood drop.

p.s. Love the mod

Evilcraft version - EvilCraft-1.11.2-0.10.27.jar

BloodMagic version - BloodMagic-1.11-2.1.10-79.jar

**Comment by rubensworks** [comment]
:man_facepalming:
Apparently my fix for #564 failed horribly.
Will fix in the next update.
