### ISSUE TITLE
Entities registered globally instead of per mod

### ISSUE THREAD

**Issue by LemADEC** [rubensworks/EvilCraft#566]
Forge log link: n/a

Problem:
As of EvilCraft-1.7.10-0.9.13, according to NEI Integration dump, entities are registered globally instead of being attached to EvilCraft:
![image](https://user-images.githubusercontent.com/4776032/27503217-87aaa512-587a-11e7-8ebc-f2623fd1e4e7.png)

Expected behaviour:
Register entities per mod.

**Comment by rubensworks** [comment]
I don't think this causes any problems, right?

Unfortunately, I don't support 1.7.10 anymore, as 1.11.2 is my main target now.

**Comment by LemADEC** [comment]
it can cause conflict with other mods and it makes it more complicated to filter by mod.
Are you confident it's fixed in 1.11.2?

**Comment by rubensworks** [comment]
@LemADEC Yes: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.11/src/main/java/org/cyclops/cyclopscore/config/configurabletypeaction/MobAction.java#L33-L36
