### ISSUE TITLE
[1.7.10][0.9.13] Origins of Darkness rendering incorrectly

### ISSUE THREAD

**Issue by SageStarCodes** [rubensworks/EvilCraft#567]
The Origins of Darkness renders incorrectly in the 0.9.13 version for Minecraft 1.7.10.

Forge version is 10.13.4.1614

Screenshot: http://puu.sh/wy7nj/b4fa8e59ad.png

**Comment by rubensworks** [comment]
1.7.10 is not supported anymore, unless major bugs would appear.

Go play 1.11.2 or something :-)

**Comment by SageStarCodes** [comment]
Our modpack that has 310+ mods will remain on 1.7.10 because that is the last version we feel like playing Minecraft and not something broken and weird, thank you. Would you accept a PR if I tried to fix the broken rendering?

**Comment by rubensworks** [comment]
Feel free to make your own fork and use that to play with, but I won't be doing any new 1.7.10 releases. I barely have time to maintain the 1.10/1.11 versions, let alone update to 1.12, so it's impossible for me to take care of 1.7.10 as well.
