### ISSUE TITLE
Forge version issue with 1.7.10

### ISSUE THREAD

**Issue by NEXUS2345** [rubensworks/EvilCraft#568]
Could you please update the mod to use Forge build 1558 or higher for 1.7.10 seeing as that is recommended. 1614 would be even better. The lack of support for Forge builds higher than 1472 means your mod is difficult to use in modpacks unless you use outdated versions of other mods.

**Comment by SageStarCodes** [comment]
@NEXUS2345 we use 1614 with no problem except #567, what problems are you having? (we have 310+ mods so I'm 99% sure you are doing something wrong)

**Comment by NEXUS2345** [comment]
We kept experiencing crashes with NoClassDefFound exceptions from EvilCraft and we came to the conclusion it was likely to do with the fact the mod was compiled against Forge 1472 rather than the recommended 1558.
________________________________

**Comment by rubensworks** [comment]
As mentioned before, 1.7.10 is not supported anymore sorry.

I can't see your full crashlog, but it sounds like some kind of mod conflict. Such as a mod including an outdated API of another mod.
