### ISSUE TITLE
Crash when clicking on spirit forge

### ISSUE THREAD

**Issue by Harenavermis** [rubensworks/EvilCraft#572]
Forge log link: https://pastebin.com/4Qdgcbk2

Problem: Right clicking on spirit forge causes the game to crash

Expected behaviour: Something besides a crash

Steps to reproduce the problem:
- Go to creative mode
- Place a Spirit forge block
- Right click on it

**Comment by rubensworks** [comment]
Hmm, is your multiblock fully formed or not?
(eitherway, it shouldn't crash)

**Comment by rubensworks** [comment]
Fixed in bd4505604d7b7e8feed93d84a421a5abd940eb75
