### ISSUE TITLE
Compatibility with BOP? IllegalArgumentException crash

### ISSUE THREAD

**Issue by janssen-dev** [rubensworks/EvilCraft#575]
Forge log link: https://hastebin.com/luticiluma.sql

Problem: Server crash (uncaught IllegalArgumentException)

Expected behaviour: No crash

Steps to reproduce the problem:
- Being in certain chunks with BOP

**Please look here: https://github.com/Glitchfiend/BiomesOPlenty/issues/1086**

**Comment by rubensworks** [comment]
What MC and mod version are you using?

**Comment by janssen-dev** [comment]
Minecraft: 1.12
EvilCraft: 1.12-0.10.30

**Comment by rubensworks** [comment]
@ImpulseTheFox Could you re-share the crashlog? Hastebin seems to be empty... :/

**Comment by rubensworks** [comment]
Might be resolved by fe3eb33ba42adaf83f010b48b022d66dfc9e83b1, let me know if this is not the case.
