### ISSUE TITLE
Piercing Vengeance focus does not damage Vengence Spirits

### ISSUE THREAD

**Issue by tyler489** [rubensworks/EvilCraft#576]
im not sure if this is a bug but i need vengence essence so i crafted a vengence ring a piercing ring and a vengence pickaxe im taking random damage so im assuming that they are spawning but i cant see them or hit them with a piercing ring. am i doing something wrong?

**Comment by rubensworks** [comment]
If you enable the ring, you _should_ be able to see them if they come your way, is this the case?
Using the pickaxe should also allow you to see them.

**Comment by tyler489** [comment]
no. might have something to do with spongeforge?
using 1.12 0.10.30

**Comment by rubensworks** [comment]
Can you try it without any other mods installed (except for CyclopsCore)?
If it still doesn't work, it'll be a bug.

**Comment by tyler489** [comment]
let me try in sp in a non spongeforge envonment

**Comment by tyler489** [comment]
ok i cant see them in singleplayer either. Modpack can be found here
https://minecraft.curseforge.com/projects/beyond-the-new-frontier/

**Comment by tyler489** [comment]
ok... its something in the pack then...

**Comment by tyler489** [comment]
however i cant hit them with the pierced ring  with just evilcraft and forge

**Comment by tyler489** [comment]
Im not a dev by any means but i knoticed this  ```ExtendedDamageSource.VengeanceBeamDamageSource```
but i dont see you import the extended damage source class in Vengencespirit.java could that do it?

**Comment by rubensworks** [comment]
So you can see them with just EC and Forge installed?
In that case it must be another mod messing with it.
If so, report this to your modpack author.

**Comment by tyler489** [comment]
i can see them with just evilcraft and forge.. but i cant hit them with the spiked ring

**Comment by tyler489** [comment]
ok well something is messing with entity ids in the pack. in the pack it says {name} was slain by Unknown

with just evilcraft and cyclops it says {name} was slain by vengeance spirit

**Comment by rubensworks** [comment]
Are you holding right-click with the piercing focus to emit purple beams?

**Comment by tyler489** [comment]
yeah... on the server it has red beams though

**Comment by rubensworks** [comment]
Please explain clearly what the issue is, because your comments seem to be all over the place.

**Comment by tyler489** [comment]
i cant kill the spirit........  with the piercing focus in either the modpack or with just evilcraft and cyclops core

**Comment by tyler489** [comment]
and i cant see them on the modpack <- not your issue

**Comment by rubensworks** [comment]
I appreciate your effort for reporting this issue, but this is not a chatbox, so one consice messages stating your problem is sufficient. I don't have the time to spent a lot of time per issue.

**Comment by rubensworks** [comment]
![2017-08-05_16 11 26](https://user-images.githubusercontent.com/440384/28996069-ac8a3eb6-79f8-11e7-8d67-454c836183e1.png)

Works just fine for me...

**Comment by codewarrior0** [comment]
This looks like a cross-mod issue with another mod which doesn't correctly provide some info EvilCraft needs for the vengeance spirits. In my case, I found a spirit which doesn't get hit by the beam from the Focus, and attaching a debugger showed me it was a spirit of an Assassin mob from Atum:

![image](https://user-images.githubusercontent.com/307683/59566557-7c837a80-8ffd-11e9-8354-5c9cfee1a2ed.png)

The workaround is to blacklist the mobs that don't spawn hittable spirits using this EvilCraft config:

![image](https://user-images.githubusercontent.com/307683/59566566-9755ef00-8ffd-11e9-961e-e8848a8fef91.png)

I wonder if it's possible to blacklist an entire mod, using something like `atum:*` in the blacklist?

**Comment by rubensworks** [comment]
> I wonder if it's possible to blacklist an entire mod, using something like atum:* in the blacklist?

Not possible at the moment, but should be possible to implement.

**Comment by rubensworks** [comment]
The next update will allow you to add regex entries to the blacklist, such as `atum:.*`.
