### ISSUE TITLE
Not compatible with chisel    IllegalArgumentException crash

### ISSUE THREAD

**Issue by Nidero** [rubensworks/EvilCraft#577]
----- REMOVE ME START -----

You can ignore this template when reporting anything other than a crash/bug.
Steps for reporting an issue:
- Include a link to the full Forge log `logs/latest.log` (even if there was no crash).
Don't paste the log directly in here, but use an external service like http://hastebin.com/ or http://pastebin.com/
- Explain your problem
- Explain what behaviour you would expect
- List the steps (in detail) that are required to reproduce the problem. 
- Make sure to remove this this block of text before submitting this issue!

----- REMOVE ME END -----
 
Forge log link: https://hastebin.com/unafovotuz.vbs

Crash-report link: https://hastebin.com/oreqarumid.http

Problem:Server crash

Expected behaviour:No crash

Minecraft version:1.10.2

Forge version:1.10.2-12.18.3.2316

Steps to reproduce the problem:
-Empty hand destroyed the Blood stained limestone
-

**Comment by Nidero** [comment]
Mod version：

**Comment by Nidero** [comment]
Mod version：
CyclopsCore-1.9.4-0.10.6
EvilCraft-1.10.2-0.10.27

**Comment by janssen-dev** [comment]
Really same thing here with BOP https://github.com/CyclopsMC/EvilCraft/issues/575

**Comment by rubensworks** [comment]
@Nidero Could you re-share the crashlog? Hastebin seems to be empty... :/

**Comment by Nidero** [comment]
@rubensworks Re-uploaded crash-report, this is a new link ：https://pastebin.com/4uHRbYjE

**Comment by rubensworks** [comment]
@Nidero Does this still occur on version 0.10.32?

**Comment by rubensworks** [comment]
Assuming fixed, @Nidero let me know if this is not the case.
