### ISSUE TITLE
[1.12] CT support does not work

### ISSUE THREAD

**Issue by TheLimePixel** [rubensworks/EvilCraft#580]
On the 1.12 versions of the mod, the CraftTweaker support simply does not work. When using the given examples, in the chat it says "no such member: evilcraft" and even External Tweaker which lists everything that can be done with CraftTweaker, including mod integration, does not display the EvilCraft recipes. Therefore, it's safe to say that the 1.12 CraftTweaker support does not work.

 The last time I tested it on the 1.11.2 version it also did not work, but that was a month ago, so I am not sure if it was fixed later on or not.

**Comment by rubensworks** [comment]
It looks like CT changed quite a bit. I tried updating the compat code, but I can't get my test scripts to work at all. Will have to look into this later.

For reference: https://github.com/CyclopsMC/EvilCraft-Compat/commits/feature-update-crafttweaker https://github.com/CyclopsMC/CyclopsCore/commits/feature-update-crafttweaker
