### ISSUE TITLE
[1.12-0.10.32] [1.12.1] Effortless ring keeps jumping constantly?

### ISSUE THREAD

**Issue by Kazzamkablam** [rubensworks/EvilCraft#581]
For some reason effortless ring keeps constantly jumping when moving around without being able to stop it?

(forge 14.22.0.2457)

**Comment by rubensworks** [comment]
What do you mean exactly? Is it the player or the ring that jumps? In what scenario's?

**Comment by rubensworks** [comment]
Seems to work just fine for me.

**Comment by Kazzamkablam** [comment]
player keeps jumping when you press forward, no idea what's causing that, might be mod incompatibility with something. It only keeps jumping if you move forward, not backgwards.

**Comment by DarthZeroX** [comment]
I happen the same, any solution? MC 1.12.1

**Comment by rubensworks** [comment]
New release containing the fix is coming soon.
