### ISSUE TITLE
box of eternal closure losing spirit

### ISSUE THREAD

**Issue by gerb82** [rubensworks/EvilCraft#582]
Forge log link:
irrelevant
Problem:
when i break the box of eternal closure in order to try and pick it up, i just get the empty box without the spirit in it.
it does not matter which spirit it is. both modded and vanilla ones vanish

Steps to reproduce the problem:
- play on evilcraft-1.12-0.10.33
- trap a spirit in a box of eternal closure
- break it with a pickaxe (both silk touch and non-silktouch)

additional notes: breaking the block below still doesn't work.
there is a mod in the pack i'm playing on that is called carry on. it lets you carry machines, and it works on the box of eternal closure. when i carry it, it doesn't look closed, but i actually see it empty. on top of that, using the one probe, i didn't see anything in the box (though i am not sure if normally i would).

**Comment by dannydjdk** [comment]
This bug also exists in the 1.11.2 version (0.10.30). Are you still doing bug fixes for 1.11.2?

**Comment by rubensworks** [comment]
Same as #584

**Comment by JerryLes** [comment]
Also picking up boxes without the spirits being in there in 1.10.2-0.10.28. This version makes default dark tanks when you break an upgraded dark tank as well.
