### ISSUE TITLE
Dark tank loses upgrades and contents when broken

### ISSUE THREAD

**Issue by ShaunDreclin** [rubensworks/EvilCraft#584]
Title

Evilcraft 1.12-0.10.33

**Comment by kurtu5** [comment]
I am using EvilCraft-1.12-0.10.33.jar and its still doing this.

**Comment by rubensworks** [comment]
@kurtu5 Are you using the latest CC version?

**Comment by dannydjdk** [comment]
I can confirm that this is happening in 1.11.2 with CC 0.10.8 and EvilCraft 0.10.30.
When broken with pick, I always end up with an empty 16,000 mb tank.

**Comment by rubensworks** [comment]
I still do 1.11.2 fixes for major bugs (like this), yes. This should have been fixed in 0.10.8 though. Will try to look into this soon.

**Comment by rubensworks** [comment]
It looks like I only implemented the fix in the 1.12 version, but forgot to backport it to 1.10/1.11, will do that now.

**Comment by rubensworks** [comment]
New 1.10 and 1.11 CyclopsCore versions have been pushed to CurseForge, you'll see them once they have been approved.

**Comment by belathus** [comment]
How long does approval usually take? I don't see the update yet on CurseForge.

**Comment by rubensworks** [comment]
@belathus The update is there, it was approved on the same day (i.e. 17 days ago), just use the latest version and you should be fine.

**Comment by belathus** [comment]
Oh, I see. I need to update Cyclops Core.
