### ISSUE TITLE
key.evilcraft.exaltedCrafting

### ISSUE THREAD

**Issue by JonaBrackenwood** [rubensworks/EvilCraft#585]
See beautiful freehand circles.
![image](https://user-images.githubusercontent.com/1567798/29790493-656bf7c8-8c3a-11e7-9f5a-9e98455e438f.png)

**Comment by rubensworks** [comment]
The "Evil_craft" issue was apparently already fixed in-dev.

I feel bad I have to close this issue with this nice picture now 😢
