### ISSUE TITLE
Tesselating block model crash

### ISSUE THREAD

**Issue by MaienM** [rubensworks/EvilCraft#586]
Forge log link: [latest.log](https://github.com/CyclopsMC/EvilCraft/files/1290478/latest.log.txt)
Problem: The game crashes.
Expected behaviour: The game doesn't crash.
Steps to reproduce the problem: 

- Be in a situation where spiked plates have to be rendered
- Be unlucky?

The problem first occurred immediately after updating from 1.12 to 1.12.1. I then removed and re-placed all spiked plates, but the problem still occurs. I'm not sure what triggers it, as I had been in the area without issues for ~10 minutes. I was afk when my client crashed, and it is unlikely any mobs were interacting with the plates as the mob farm was turned off. 

As an aside, my FPS tanks when near the area where the spikes are. This doesn't occur anywhere else, and this didn't happen on 1.12. Not sure if it's related or not, but figured it was worth mentioning.

**Comment by MaienM** [comment]
The FPS problem seems to have been related to there being no room to pump out the blood, which is unlikely to be related to this mod or this issue.

**Comment by rubensworks** [comment]
Can you reproduce it with just EC (and CC) installed?

**Comment by MaienM** [comment]
I'll try. Unfortunately it doesn't have an obvious trigger, so it might take a while.
