### ISSUE TITLE
 eternal water bucket sprite glitching under certain circumstances

### ISSUE THREAD

**Issue by Twisted-Code** [rubensworks/EvilCraft#587]
Forge log link:  [client](https://gist.github.com/macks2008/4222353698e75dc2dc9f19a99cca4460) & [server](https://gist.github.com/macks2008/8833ae119a366e6008edc030d44ac47d)... 
(I assume you actually wanted the FML logs, not "latest.log", since that only appears to be console output, i.e. "Player joined the game." "Player was blown up by creeper.", etc. Let me know if you actually wanted the latest.log)

Problem:

sometimes the sprite on the Eternal Water bucket will turn into that of a normal empty bucket, such as when I use one to add water to a Tinkers' Construct smeltery (there are other times this has happened, but I can't remember the details). Thankfully, it returns to normal next time I refresh the render (such as by dropping it or trying to use it), so it's not destroying items or anything... It just looks like it is.  Hopefully this is a simple fix (like maybe adjusting the right-click function to refresh the sprite after finishing whatever else it does), because I'm not looking forward to the "false positive" lost item reports when I open my server to the public...

Expected behaviour:

the normal sprite (dark gem bucket full of water) should either remain all the time (it is an "eternal" bucket after all) or at least automatically refresh itself when a known issue might arise to change the sprite, such as adding water to a smeltery

Steps to reproduce the problem:
-as far as I know, it should be as simple as right clicking a smeltery drain with an eternal water bucket  while the smeltery is valid and has at least 1000mb free space. In other words

1. installed the relevant mods, Tinkers' Construct and EvilCraft (duh)
2. Build a smeltery including at least one drain oriented properly (the dark side of the drain should be inside the smeltery structure)
3. Give yourself an eternal water bucket
4. Right-click the bucket on one of the exterior faces of a smeltery drain. If successful, the bucket will look like an empty iron bucket until you drop it or otherwise refresh its sprite
-

**Comment by rubensworks** [comment]
Fyi, I actually always require latest.log

**Comment by rubensworks** [comment]
I could only reproduce this in MC 1.12 though. (And as I've mention, 1.10 is not updated anymore, unless major crashes are discovered)
