### ISSUE TITLE
Enchantment ID conflict

### ISSUE THREAD

**Issue by Twisted-Code** [rubensworks/EvilCraft#588]
Forge log link: should show up in the logs from the last issue I reported, since neither client nor server restarted and this issue is persistent across all sessions of my pack. For your convenience: [client](https://gist.github.com/macks2008/4222353698e75dc2dc9f19a99cca4460) & [server](https://gist.github.com/macks2008/8833ae119a366e6008edc030d44ac47d)

Problem:

vengeance pickaxe and the enchanted book that's supposed to be "poisoned tip" (or whatever its name is) instead have enchantments from other mods. Specifically, they have enchantment.vampirism.vampireSlayer III and Wrecking, on the pickaxe and book respectively

Expected behaviour:

the pickaxe should have vengeance III (I mean it's literally in the name, and the pickaxe is kind of overpowered otherwise), and the book should have "poisoned tip"

Steps to reproduce the problem:
- not entirely sure, but I was hoping you would know why this is happening without needing to reproduce the problem. Presumably your mechanisms for assigning the items their lore is being fed an incorrect ID somehow?
-
note: possibly related to #335 , but doesn't crash me so I'm not sure if it's actually a conflict so much as just general confusion, or maybe a conflict that somehow slipped by?

**Comment by rubensworks** [comment]
Is it possible that you added new mods _after_ you've added EvilCraft to your pack?

If so, then there's nothing I can do about that unfortunately, as enchantment id's can change when the set of active mods is changed, which means that (moddd) enchantments on existing items can change.

I assume the enchantments on the creative-tab items are correct?

**Comment by Twisted-Code** [comment]
That might be part of the issue, at least. The pickaxe has the correct enchantments when spawned in, so it might have been that the pickaxe I had  corrupted when the enchant ID in its lore changed to point to a different enchantment. However, that doesn't explain why the recipe for Poisoned Tip gets added with an incorrect enchantment. Shouldn't the recipe update when the enchantment ID changes?

**Comment by rubensworks** [comment]
That second thing indeed sounds like an actual issue that could go wrong on my end. Will look into it.

**Comment by rubensworks** [comment]
I just looked into it, and nothing seems to be wrong on my end.
I only refer to the Poison Tip enchant _after_ all enchantments should have been registered, so the IDs should be in place by then.

It is however possible that some other mod in your pack is registering new enchants _after_ the recipes have been registered (which should *not* be done). This could be the case if a certain mod is not properly using Forge's new registry events.

It will probably be not an easy thing to figure out what mod is causing it though...

**Comment by Twisted-Code** [comment]
hmm... okay then. Might be easier for me to just manually correct the recipe using minetweaker. I'll update this issue if I find any new information about what's going wrong.

**Comment by Twisted-Code** [comment]
I do notice the log says something about  forge fixing an ID mismatch for the enchantment in question at 8:25:15. Wonder if that actually broke something rather than fixing it? Anyway, like I said, I'll update this issue if I find anything useful. Preferably more concrete than "maybe Forge broke something trying to fix it" XD

**Comment by rubensworks** [comment]
> Wonder if that actually broke something rather than fixing it?

That's definitely possible. It's also very possible that this behaviour has been fixed in 1.12 already, but they don't backport fixes to 1.10 unfortunately.

**Comment by rubensworks** [comment]
@macks2008 Any updates on this? Will close this otherwise.
