### ISSUE TITLE
exalted crafter deleting items under certain circumstances

### ISSUE THREAD

**Issue by Twisted-Code** [rubensworks/EvilCraft#590]
Forge log link: not sure if the log will actually show anything, but here ([client log](https://gist.github.com/macks2008/35e97db9b7c49e004fdf9660c62d5409); [server log](https://gist.github.com/macks2008/35e97db9b7c49e004fdf9660c62d5409)) you go. As before, I am assuming you wanted the FNL log, not the other one

Problem:
under certain circumstances (the list of which I have not exhaustively deduced), the exalted crafter (not necessarily the wooden one, but I can't say for sure) will delete items that remain in the crafting grid when the UI is closed.. For instance, while crafting some iron blocks with an (enderchest) exalted crafter, I  closed the UI,, and any  "unbalanced"  ingots (i.e., any ingots that would not complete a recipe in their current position. If I had 10 ingots, I would only be able to balance 9. The remaining ingot would be "unbalanced") remaining in the grid were deleted
Expected behaviour:
items should not be deleted under any circumstances other than them falling in lava, dragging them to NEI's trashcan, etc.
Steps to reproduce the problem:
- get an exalted crafter (It might be prudent to test with all four, but at least test with the un-empowered ender one)
- put some items in it, such as 18 iron ingots to form 2 iron blocks.
- add some extra items (iron ingots in the example above) that, in their current positions, will not increase the stack size of the output
- if successfully reproduced, these extra items will not  be properly saved when you close the interface, resulting in their effective deletion/data loss
my comments:
I suspect you simply tried to take a shortcut when saving the crafter's data, which worked on the assumption/oversight there would never be unbalanced items, so you could just save it as the recipe grid's current "shape" and count. I would appreciate if you would  tell me if I'm right. Good luck, and happy (bug) hunting! *Hands you a flyswatter, pulls a portable hole out of his pocket, throws it on the ground, and jumps through*

**Comment by Twisted-Code** [comment]
possibly related: opening an exalted crafter while it is in your offhand causes  the interface  to instantly close and whatever is in your main hand will no longer stack with other items (as if it has picked up overflow NBT data). I am currently in the process of trying to retrieve the NBT data. I'll update this comment when I get it

**Comment by rubensworks** [comment]
I can't reproduce the deletion of items, unless you can provide me with a clear way to reproduce it without any other mods installed, I assume it is being caused by another mod in your pack.

I can however reproduce the offhand usage not working, will look into that.

**Comment by rubensworks** [comment]
I've only implemented the fix for 1.12, as it would require too much work to backport it to 1.10.

**Comment by Twisted-Code** [comment]
Maybe sometime I'll offer to backport it as a PR. Right now I don't know Java NOR how to PR. I'm working on it though
