### ISSUE TITLE
[Question/Issue] Undead Tree Blood

### ISSUE THREAD

**Issue by Timeslice42** [rubensworks/EvilCraft#591]
So the undead trees (once grown) have nifty blood drop particle effects, but they never leave any blood stains on the ground. I thought these were meant to be used for automated blood collection. Is this working as designed, a bug, or is there just a config option I didn't see that is perhaps disabled in the modpack I'm playing?

**Comment by rubensworks** [comment]
Those drops are purely cosmetic. You can shear the leaves and squeeze them for Blood using Integrated Dynamics or Forestry though.

**Comment by Timeslice42** [comment]
So they're completely useless without a squeezer from another mod?

**Comment by rubensworks** [comment]
Their main use is the crafting of Dark Sticks.

**Comment by Timeslice42** [comment]
Oh, right. My bad.
