### ISSUE TITLE
misrendered bloodstained block: chisel mod's marble

### ISSUE THREAD

**Issue by Twisted-Code** [rubensworks/EvilCraft#594]
Forge log link:
do you really need it for a rendering bug? I don't know when this bloodstained block happened anyway, so I doubt the log will show anything unless I try to reproduce the bug.
Problem:
A block that something left a bloodstain on is rendering as if the block has an invisible texture
Expected behaviour:
a block that at least rendered as solid rather than absolutely clear (minus the blood)
Steps to reproduce the problem:
-presumably, install chisel, grab some marble (chisel's variant), and drop yourself to death on top of it

**Comment by rubensworks** [comment]
Ok, so in short, Blood Stained Blocks render invisible on Chisel's Marble.

**Comment by Twisted-Code** [comment]
yeah. The bloodstain itself still shows, but nothing else

**Comment by sarge1837** [comment]
it also breaks multiblocks but he clearly couldnt care about thats thats "someone elses problem" fix your piece of shit mod and stop breaking other peoples mods with your piss poor coding ability

**Comment by josephcsible** [comment]
#678
