### ISSUE TITLE
Crash on NullPointer exception in ticking NetherFish

### ISSUE THREAD

**Issue by gelonsoft** [rubensworks/EvilCraft#599]
Forge log link: https://pastebin.com/MzTpK14i
Crash log link: https://pastebin.com/DF4wcwkh
Problem: Crash on NullPointer exception in ticking NetherFish

Expected behaviour: Don't crash...please.
Can't load the game, cause saved near NetherFish and game is crashing just after the loading (((

Steps to reproduce the problem:
-Meet NetherFish.

**Comment by rubensworks** [comment]
Can't reproduce with just EC installed.

This seems to be a crash in Vanilla logic.
For some reason the player's connection object is null, which is probably caused by another (core?)mod.
