### ISSUE TITLE
MP Server Crash - unable to find an evilcraft property

### ISSUE THREAD

**Issue by jc2xs** [rubensworks/EvilCraft#601]
Forge log link: https://pastebin.com/CXAr9hTm

Problem:  Server is trying to locate a property for a blood stained block that results in a server crash.

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, overgrown_stone, loamy, sandy, silty, origin, overgrown_netherrack, daisy, mycelial_netherrack]} as it does not exist in ExtendedBlockState{block=evilcraft:blood_stained_block, properties=[]}

Expected behaviour:
Not crashing

Steps to reproduce the problem:
Have BoP and TiC installed and be near a slime island that is above BoP blocks.

Version Info:
Forge 14.23.0.2512
BoP 7.0.1.2297
TiC 7.4.34
EvilCraft  1.12.0.10.37

Both BoP and TiC say it isn't their issue.  See the other issue reports here:
https://github.com/SlimeKnights/TinkersConstruct/issues/3202#issuecomment-338504975
https://github.com/Glitchfiend/BiomesOPlenty/issues/1114

**Comment by drakray** [comment]
I got that too, i'm trying to add biomesoplenty:grass and biomesoplenty:dirt to evilcraft blood stained blacklist

**Comment by rubensworks** [comment]
This issue is being reported occasionally (#259 and #577), but I have not been able to reproduce this myself.

For some reason, the `getSoundType` method is receiving invalid parameters. We don't change anything with regards to sounds in blood stained blocks, so I don't think EC is directly causing this. I assume a coremod is somehow messing with this.

Can you try reproducing this with just EC(+CC) and BoP installed? (And have an entity walk over a BoP blood stained block)

**Comment by jc2xs** [comment]
@drakray Could you post your list of core mods you are using?  Mine are listed in the crash report in my original post.  I would like to compare and start eliminating a few before I start testing trying to isolate which core mod is causing the issue.

**Comment by drakray** [comment]
[Here is my crashLog](https://pastebin.com/2hFs0cpV), didn't crash since I changed the blacklist though

EDIT: also, that was a Linux Server Crash, with a Win7 Client, both Java

**Comment by jc2xs** [comment]
Okay, so the common core mods are below.  It will take me a bit but I'll see if I can do some testing on the server in home with these and figure out which one might be causing it.

ForgelinPlugin (Forgelin-1.5.1.jar)
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
LoadingPlugin (Quark-r1.3-112.jar)
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
Plugin (NotEnoughIDs-1.5.4.2.jar)
IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)

Similar here on the setup.  All of my servers are Ubuntu Linux 16.04 with Oracle's Java and windows clients.

**Comment by jc2xs** [comment]
So I did a strpped down test of just the basic mods needed to reproduce.  So all that is in the test pack that produced this crash is:

Forge 14.23.0.2512
BoP 7.0.1.2301
Cyclops Core 1.12-0.10.21
EvilCraft 1.12-0.10.37
Mantle 1.12-1.3.1.21
TiC 1.12-2.7.4.34

So no core mods installed at all and this crash still happens. 

Crash report:  https://pastebin.com/TuShCXg5

I'm going to do one more test using the latest version of Forge.   But I would welcome suggestions for further testing if you have any.

**Comment by jc2xs** [comment]
Same crash:  https://pastebin.com/bLwkDmWU with forge 14.23.0.2517

**Comment by drakray** [comment]
A good test would be to disable TiC Floating Island, and then, testing by dropping Blue Slime over different block, to know if it crash only on BoP Grass, meaning the trouble would be caused by the blood block creating on BoP grass, or on every blood block, meaning it would be caused by the slime.)

**Comment by jc2xs** [comment]
Good idea...   So I did some more testing.  Both blue slime and vanilla green slime cause the crash over blood stained BoP grass blocks.  Normal vanilla blocks have no issues.  Finally wound up removing TiC altogether and just used vanilla green slime spawn egg to reproduce the error.  Same results  BoP grass crashes normal vanilla grass doesn't.

Last crash report without TiC or Mantle installed:  https://pastebin.com/V6ZXitc7

Any other ideas for testing?

**Comment by drakray** [comment]
maybe try with BoP Dirt, as it use the same "values", and some other BoP block, just to be sure that the trouble come from this?

**Comment by jc2xs** [comment]
So far I've tested a few other BoP terrain gen blocks.  The only one that causes the crash so far is BoP' Loamy Grass Block.  Loamy dirt, sandy dirt and dried sand did not cause a crash.

**Comment by drakray** [comment]
do other BoP Grasses than Loamy crashed too, or just Loamy?

**Comment by jc2xs** [comment]
Not sure on that one.  I just tested the four blocks from BoP so far.  But that should give the mod author enough to reproduce the crash.  I'm still not sure if it is Forge, BoP or EvilCraft at this point.  But they are the only mods in the pack at this point.

**Comment by jc2xs** [comment]
Oh... I couldn't not reproduce the crash with Zombies on any blocks.  So it seems restricted to slimes causing the issue.

**Comment by drakray** [comment]
could you test every BoP Grass, to check if it's just Loamy? that would give better indication
Maybe after that, testing with biomesoplenty:grass added to blood_stained_block.blockBlacklist in evilcraft.cfg, though i'm pretty sure it shouldn't crash(as I don't)

**Comment by rubensworks** [comment]
@jc2xs @drakray Thanks for your help in this issue, I've finally managed to reproduce this.

The problem seems to be caused by slimes creating blood stained blocks by falling to their death. Up until now, I thought the problem was being caused by slimes falling on _already formed_ blood stained blocks.

It seems to be an issue with Forge not considering some edge-cases, will have a look if I can fix it on my end.

**Comment by rubensworks** [comment]
Will be fixed in next update.
