### ISSUE TITLE
[1.10.2] Suggestion: Mod Compatibility with Animania animals

### ISSUE THREAD

**Issue by heyoomimi** [rubensworks/EvilCraft#602]
I was wondering if EvilCraft could have a mod compatibility with Animania animals? We are currently running a server set with only Animania animals, and the only animals we can currently obtain the Origins of Darkness book from are Mooshrooms, Wolves, Ocelots and Bats. 
Thanks in advance!

Evilcraft version: 0.10.29
Animania version: 1.3.5

**Comment by rubensworks** [comment]
I think don't really understand what you are asking.
The book should not be dropping from any mobs, if it is, then that is being customized by your pack.

**Comment by heyoomimi** [comment]
I mean, when you feed a darkened apple to an animal. It doesn't work with Animania animals.

**Comment by rubensworks** [comment]
It should work with any animal that has 10 health (5 hearts) or less, as can be seen here: https://github.com/CyclopsMC/EvilCraft/blob/master-1.12/src/main/java/org/cyclops/evilcraft/item/DarkenedApple.java#L48

Do these Animania animals by any chance have a lot of health?

**Comment by heyoomimi** [comment]
Ah I see, I wasn't aware they had to be 5 hearts or less. Thank you!
