### ISSUE TITLE
some enchantments have no description

### ISSUE THREAD

**Issue by C0rn3j** [rubensworks/EvilCraft#605]
![image](https://user-images.githubusercontent.com/1641362/32418651-2fd6652a-c26e-11e7-8765-45ef2597a24c.png)
Using MC 1.12.2 and forge 2529, latest version of this mod(Don't hate me for saying "latest" please ^^)

**Comment by rubensworks** [comment]
Already did this in #449, don't know why I used a different format there though...

**Comment by C0rn3j** [comment]
Perhaps more mods add the same thing(enchant description) and for some dumb reason they're using different localization keys? I use WAWLA.
