### ISSUE TITLE
Feature request: Configurable fortune enchantment for vengeance pickaxe

### ISSUE THREAD

**Issue by kakas123455** [rubensworks/EvilCraft#610]
Title says it all. I want the good ol' fortune X (10) enchantment and not the fortune V (5) one. I think making it configurable is the easiest way to do it,but that's up to you.

**Comment by rubensworks** [comment]
Fair enough, isn't too difficult to add.

**Comment by kakas123455** [comment]
Alright,thanks :D And if you don't mind me asking,when will a version containing that addon come out?

**Comment by rubensworks** [comment]
Not sure yet, definitely within a couple of weeks.
