### ISSUE TITLE
Animania Compatibility

### ISSUE THREAD

**Issue by MazeusXenon** [rubensworks/EvilCraft#612]
#### Issue type:
Bug

____
#### Short description:
Animania does not allow Dark Apple to be fed to animals

#### Expected behaviour:
Feed animal dark apple, dies, get anomaly to throw book into, getting EC book

#### Actual behaviour:
You cannot use the Dark Apples on animals

#### Steps to reproduce the problem:

1. Have both Animania and EC installed
2. Get Dark Apple
3. Try to feed to animal - it ignores it

I fully understand this may be an issue with Animania over EC but I figured you'd be the better first stop.

____
#### Versions:

- This mod: 0.10.40
- CyclopsCore: 0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.0.2512
- Animania: 1.4.1

**Comment by rubensworks** [comment]
Not a bug, as mentioned before in #602.
