### ISSUE TITLE
Player dismounts from broom when shooting bow

### ISSUE THREAD

**Issue by dannydjdk** [rubensworks/EvilCraft#613]
#### Issue type:
- :bug: Bug
____
#### Short description:
While flying with broom, when you release the mouse button to shoot an arrow, you are dismounted from the broom, the broom is dropped, and you fall to the ground.

#### Expected behaviour:
Player should remain mounted on the broom while shooting.

#### Actual behaviour:
Player is dismounted and the broom is dropped.

#### Steps to reproduce the problem:

1. Mount broom and fly.
2. Select your bow and right click to shoot.

____
#### Versions:
- This mod: 0.10.40
- CyclopsCore: 0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.0.2529

#### Log file:
Sorry, I no longer have the log file. I'll work on reproducing the problem again and will post the log. But, I'm going to post this now in case you can proceed without it in the meantime.

**Comment by rubensworks** [comment]
Thanks!

No log is needed here btw.
