### ISSUE TITLE
Eternal water bucket can't fill cauldron

### ISSUE THREAD

**Issue by josephcsible** [rubensworks/EvilCraft#614]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
The eternal water bucket can't be used to fill cauldrons.

#### Expected behaviour:
Right-clicking a cauldron with an eternal water bucket should fill it.

#### Actual behaviour:
Right-clicking a cauldron with an eternal water bucket places a water block next to it.

#### Steps to reproduce the problem:

1. Place a cauldron
2. Right-click the cauldron with an eternal water bucket

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.10.40
- CyclopsCore: 0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.0.2553

#### Log file:

Nothing relevant

**Comment by uhloin** [comment]
1.19.2 it is'not working again

**Comment by rubensworks** [comment]
@uhloin could you create a new issue?

**Comment by uhloin** [comment]
> @uhloin could you create a new issue?

done
