### ISSUE TITLE
Brooms sometimes do not work properly

### ISSUE THREAD

**Issue by superfluke** [rubensworks/EvilCraft#619]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
Brooms seem to randomly not work after crafting with normal flight functionality sometimes returning after restarting the client. The broom will craft normally and accept blood but will only hover in the air when used, and will not move forward. 

#### Expected behaviour:
Brooms work normally all the time. 

#### Actual behaviour:
Brooms sometimes do not want to fly. 

#### Steps to reproduce the problem:

Haven't been able to consistently reproduce the problem but it has been brought up by 3 seperate players each on their own single player world. You can see an example of it in this twitch stream (https://www.twitch.tv/videos/204741264) at the 1:52:50 mark where the broom just sits still in the sky. Then at the 2:05:20 mark, after a full restart, the broom returns to normal. 

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: EvilCraft-1.12.2-0.10.40
- CyclopsCore: CyclopsCore-1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: Forge Mod Loader version 14.23.1.2556

#### Log file:

n/a

**Comment by rubensworks** [comment]
That's strange. It seems to be right after a dimension switch, so that might have something to do with it.

**Comment by rubensworks** [comment]
I can't reproduce this myself. And the only possible causes for this would be if the player entity is not of class `EntityPlayer`, or if there is a big server delay.
The latter seems the most plausible cause, considering the switch of dimensions.

I'm putting this issue on hold until someone else is able to reproduce this in a clean (just EC+CC) environment.

**Comment by rubensworks** [comment]
If anyone would encounter this in the future, please comment here.

**Comment by superfluke** [comment]
Looks like players are still having a problem with brooms dropping their stats. Don't have a way to reliably reproduce yet. This player had crafted the broom in a previous version and the screenshot is from Evilcraft 0.10.47, Forge 14.23.1.2604
![image](https://user-images.githubusercontent.com/20022336/36115842-4d40d460-1002-11e8-8ccc-67891a32d781.png)

**Comment by rubensworks** [comment]
@superfluke That doesn't seem to be related to this issue. Could you open a new issue for this? (With some details on when/how this happened)

**Comment by MentalMouse** [comment]
I just had a broom drop its stats and not want to fly after a restart.  I was running EvilCraft 0.10.57, but have since upgraded to 0.10.60.  When I came back with the new version, the broom was working again.

**Comment by rubensworks** [comment]
Nothing has been changed to the broom, so this must have auto-fixed itself during a restart. I am starting to think that this is just a client-server desync issue.

If you would encounter the problem again in the future, could you check what happens if you restart the world/game?

**Comment by DBotThePony** [comment]
I can clarify on 'full restart': Broom modifiers 'break' when forge registries are "rebuilt" (to fit), e.g. when you load world which has registry entries which point to nowhere (e.g. you remove a mod which add items). In this case evilcraft broom modifiers break completely until hard Minecraft client/server restart.
