### ISSUE TITLE
Wrong config?

### ISSUE THREAD

**Issue by josephcsible** [rubensworks/EvilCraft#621]
https://github.com/CyclopsMC/EvilCraft/blob/0f8c2c29927593bfd276342b508bd82a540b7026/src/main/java/org/cyclops/evilcraft/event/LivingUpdateEventHook.java#L72

Am I missing something, or should this be WerewolfConfig rather than WerewolfVillagerConfig?

https://github.com/CyclopsMC/EvilCraft/blob/0f8c2c29927593bfd276342b508bd82a540b7026/src/main/java/org/cyclops/evilcraft/entity/monster/Werewolf.java#L138

Similarly, should this be WerewolfVillagerConfig instead of WerewolfConfig?

**Comment by rubensworks** [comment]
No, that should be correct.

The first thing checks if the werewolf villager is enabled before calling `WerewolfVillager.getInstance()`.

The second thing checks if the werewolf is enabled before creating a werewolf.

**Comment by josephcsible** [comment]
Are you sure? It looks like you're checking whether werewolf villagers are enabled before creating a werewolf, and then checking whether werewolves are enabled before creating a werewolf villager (both of which you know to be true, since one of them exists in the world that you're running on).

**Comment by rubensworks** [comment]
Yes, I'm sure. The first part calls the second part, which creates a werewolf from a villager. None of these functions create werewolf villagers.
