### ISSUE TITLE
Poison Bucket recipe shouldn't need an empty bucket

### ISSUE THREAD

**Issue by josephcsible** [rubensworks/EvilCraft#623]
#### Issue type:

_Only keep the issue types that are applicable._

- :heavy_plus_sign: Feature request

When you're crafting a Poison Bucket, you provide a bucket of water and an empty bucket (among other things), and you end up with a Poison Bucket and an empty bucket. Needing an empty bucket is unnecessary (you're giving one just to get it back) and unrealistic (you're just throwing the poison stuff in the bucket of water).

**Comment by rubensworks** [comment]
This was implemented like this because in the past all filled buckets that were used in recipes returned an empty bucket. This could have changed by now, not sure.

**Comment by josephcsible** [comment]
They still do by default, but you can change this with a custom recipe handler.

**Comment by josephcsible** [comment]
That wasn't quite what I had in mind, but I guess it makes sense that all the poison things are liquid-y.
