### ISSUE TITLE
Evilcraft inserting its loot into Loot Pools made by other mods

### ISSUE THREAD

**Issue by KAfable** [rubensworks/EvilCraft#625]
#### Issue type:
- :bug: Bug
- :snail: Performance issue

**#### Short description:**
EvilCraft is inserting itself into loot pools crated by other mods such as Reliquary and RandomThings. This drastically lowers the weighted chance of these mods loot actually generatingin the chest as they didn't anticipate another mod being present in their pool, eg Reliquary only uses a relative weight of 1, which would be fine normally as it's the only thing in the pool, but evilcraft then adds condensed blood, origins of darkness as relative weights of 5 and 1 respectively. 

**#### Expected behaviour:**
Editing the loot tables and loot pools, I didn't anticipate having to remove evilcraft items from multiple pools over multiple loot tables. This also becomes a worry if a modpack maker wants to use loot chests as a part of its pack mechanics.

**#### Actual behaviour:**
A lot of condensed blood everywhere, which is thematically cool in certain dungeon chests, but overall increases the amount of chest a player needs to find before using something like LootTweaker.

#### Steps to reproduce the problem:

1. Use a loot generator, I use Cyclics creative loot generator, but forge should also provide one as well. Spawn a couple of abandoned mineshaft chests, in large modpacks, Evilcraft's loot tables/pools can crowd out other mods.

**#### Versions:**
- This mod: 1.12.2-0.10.40
- Evilcraft-compat: 1.0.0
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 2556

**Comment by rubensworks** [comment]
True, this was implemented like this back in the early days when loot tables were not very well supported by Forge. Proper mechanism exist now for injecting into specific loot tables, so it would probably be better to limit the loot table targets.
