### ISSUE TITLE
Make vengeance spirits less obtrusive

### ISSUE THREAD

**Issue by josephcsible** [rubensworks/EvilCraft#632]
#### Issue type:

_Only keep the issue types that are applicable._

- :heavy_plus_sign: Feature request

Currently, vengeance spirits spawn basically every time a mob dies. This can be rather annoying since you usually don't care about them, especially in creative mode where they're always completely visible, and the only way to stop this is to turn them off completely, which means you lose the Box of Eternal Closure among other things. Could we add a setting that makes them only spawn if the entity was killed in some certain way?

**Comment by rubensworks** [comment]
> This can be rather annoying since you usually don't care about them, especially in creative mode

Most of the players will play in survival mode, which is our target audience for EC, so I don't consider this a problem.

> Could we add a setting that makes them only spawn if the entity was killed in some certain way?

This would complicate the whole spirit catching mechanic even more.
Unless you have a good suggestion for this, I'd rather make no changes to this.

**Comment by josephcsible** [comment]
How about they only spawn if killed by a player who has some item related to spirits in their inventory (vengeance ring, vengeance focus, spectral glasses, etc.)? (And even this would be a config setting vs. the way it is now)

Or failing that, how about adding a setting to not make them automatically visible in creative mode?

**Comment by rubensworks** [comment]
> How about they only spawn if killed by a player who has some item related to spirits in their inventory?

This sounds useful, but would not work well in cases where mobs are killed in group (possible for withers). So not ideal, but I can agree if that would be just a config setting. Feel free to send a PR :-)
