### ISSUE TITLE
Can't /kill vengeance spirits

### ISSUE THREAD

**Issue by josephcsible** [rubensworks/EvilCraft#635]
#### Issue type:

- :bug: Bug

____
#### Short description:
/kill cannot kill vengeance spirits.

#### Expected behaviour:
/kill should kill vengeance spirits.

#### Actual behaviour:
/kill causes the message "Killed Vengeance Spirit" to display, but the vengeance spirit stays there.

#### Steps to reproduce the problem:

1. Put on spectral glasses
2. Spawn some sort of mob
3. Kill it (there should be a vengeance spirit now)
4. Type "/kill @e[type=evilcraft:vengeance_spirit]"

You'll get a "Killed Vengeance Spirit" message, but the vengeance spirit won't go away any faster than it would have without the /kill command.

____
#### Versions:

Development version e7daae3, with all of its Gradle dependencies

#### Log file:

Nothing relevant

**Comment by rubensworks** [comment]
Spirit ignore all damage sources, but kills from commands should probably be whitelisted.

**Comment by staridiot** [comment]
This is still an issue in `evilcraft-1.21.1-neoforge-1.2.71`

**Comment by Jack-McKalling** [comment]
@staridiot could you create a new issue for this please?
