### ISSUE TITLE
Blood infuser crashes client

### ISSUE THREAD

**Issue by FeikoJoosten** [rubensworks/EvilCraft#639]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug bug

____
#### Short description:
The blood infuser crashes the client when it’s in it’s render range. 

#### Expected behaviour:
The blood infuser shouldn’t crash the client when it’s in it’s render distance. 

#### Actual behaviour:
The client now crashes when the blood infuser is in render distance. 

#### Steps to reproduce the problem:

1. Place down a blood infuser. (Single player or multiplayer)
2. Notice the client crashes. 

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.10.40
- CyclopsCore: 1.9.4-0.10.10
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.1.2562

#### Log file:

https://pastebin.com/zuHk2yzs

**Comment by josephcsible** [comment]
According to your log, you were actually using 0.10.41, not 0.10.40, which was pulled because of this problem (#638). Downgrade to 0.10.40 to fix it.

**Comment by FeikoJoosten** [comment]
Thanks for the reply! I’ve also informed the modpack devs from modern skyock 2!
