### ISSUE TITLE
Loot Tables for Ender Tear

### ISSUE THREAD

**Issue by KAfable** [rubensworks/EvilCraft#640]
#### Issue type: Loot Tables for Enderman

_Only keep the issue types that are applicable._

I noticed that you also revamped some of the loot earlier for the condensed blood, Origins of Darkness, and etc. Would it also be possible if you made it so that Evilcraft gives the same treatment with the Ender Tear and the enderman loot tables? Currently LootTweaker doesn't seem to detect the Ender Tear, and actually can't modify its drop rate.

**Comment by rubensworks** [comment]
Sure, that should be possible now with the new loot table hooks in Forge.
