### ISSUE TITLE
Infinite Blood with Blood Extractor in Forestry Bottler

### ISSUE THREAD

**Issue by ghost** [rubensworks/EvilCraft#641]
https://files.pudding.tk/eby3oh8p49.mp4

Minecraft-Version: 1.12.2
Modpack: Modern Skyblock 2
Modpack Version: 2.7.2.2
Mod-Version: EvilCraft-1.12.2-0.10.40
Core-Version: CyclopsCore-1.12.2-0.10.23

Forestry-Version: forestry_1.12.2-5.7.0.213

**Comment by rubensworks** [comment]
This was an issue on Forestry's end, and has been fixed ForestryMC/ForestryMC#1863.
