### ISSUE TITLE
Broom gives creative flight

### ISSUE THREAD

**Issue by TheWonderingMage** [rubensworks/EvilCraft#642]
#### Short description: 
On  Modern Skyblock 2 modpack
Logging out of the game and back in while on a broom gives the player creative flight

#### Steps to reproduce the problem:

1. get on broom
2. log out
3. log in

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.10.43
- CyclopsCore: 0.11.0
- Minecraft: 1.12.2
- Forge: 14.23.1.2566

Also -- EvilCraft-Compat: 1.0.0

**Comment by rubensworks** [comment]
EvilCraft never calls anything related to the creative flight mode flag. Please try reproducing this without any other mods installed, as I assume some other mod is causing this.

Or do you mean that the broom stops consuming blood?

**Comment by TheWonderingMage** [comment]
Can't reproduce with minimal mods, so its definitely some sort of mod conflict, but I have no idea which one it may be.

Also, updated one of the version numbers in original post, which was very wrong

**Comment by rubensworks** [comment]
Alright, thanks for checking. Closing this one then.
