### ISSUE TITLE
Sipirt Furnace competely crash the game [1.11.2]

### ISSUE THREAD

**Issue by LordKhaoss** [rubensworks/EvilCraft#644]
#### Short description:
Just doing right-click on spirit furnace and the game crashes.

__________________________________________
#### Steps to reproduce the problem:

1. Just do right-click on Spirit Furnace,
__________________________________________
#### Versions: 
- This mod: 0.10.30
- CyclopsCore: 0.10.9
- Minecraft: 1.11.2
- Forge: 13.20.1.2579

___________________________________________
#### Log file:

*****The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error*****

[Log File](https://pastebin.com/pamPYV9c)

**Comment by rubensworks** [comment]
Wait, 1.11? I'll check if this issue occurs on 1.12, but 1.11 is not receiving any updates anymore unfortunately.

**Comment by rubensworks** [comment]
Doesn't seem to be an issue on 1.12, you should really update :-)
