### ISSUE TITLE
[NPE] Villagers on Spirit furnace

### ISSUE THREAD

**Issue by ghost** [rubensworks/EvilCraft#650]
#### Issue type: 
- :bug: NullPointerException: Ticking block entity

#### Short description: 
Server crashed using Spirit furnace and box of eternal closure containing Villager spirit.

#### Expected behaviour:
It Should probably drop emeralds. (Villager commonly drop emerald on modded pack)
or noting.

#### Actual behaviour:
This issue makes the server crash. (NPE)

#### Steps to reproduce the problem:

1. Build 3x3x4 spirit Furnace (obviously with one controller).
2. Kill vanilla villager (i used vanilla diamond sword)
3. use evil craft feature to move the villager spirit into a box of eternal close.
4. put the box into spirit furnace (obviously and add some blood (i used blood bucket).

____
#### Versions:

- This mod: 0.10.42
- CyclopsCore:  0.10.24
- Minecraft: 1.12.2
- Forge: 8.0.99.99

#### Log file:

https://pastebin.com/4TyiWGWv

**Comment by rubensworks** [comment]
Yeah, I cannot read the crashlog, will put this on hold until I get the actual file.

**Comment by ghost** [comment]
First post edited, I added a pastbin link with the crash report.
