### ISSUE TITLE
Crash due to conflict with latest Forestry versions

### ISSUE THREAD

**Issue by raltus** [rubensworks/EvilCraft#652]
#### Issue type: Crash during load

____
#### Short description: 
I was updating some mods in my list and at first I thought it was a forge issue because it happened before with another mod. Forestry 1.12.2 versions 5.7.0.240, 5.8.0.241, and 5.8.0.242 all cause a crash during loading due to a conflict with the EvilCraft-Compat. 5.7.0.239 and before all load fine without any issues.

____
#### Versions:

- This mod: 1.12-2.1.4-57
- CyclopsCore: 1.12.2-0.11.2
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

**Comment by rubensworks** [comment]
Duplicate of #648.
