### ISSUE TITLE
Invalid item minecraft:deadBush

### ISSUE THREAD

**Issue by LemADEC** [rubensworks/EvilCraft#654]
#### Short description:
Warning popups in logs during boot:
[01:38:49] [Client thread/WARN] [EvilCraft/evilcraft]: Invalid item minecraft:deadBush

#### Steps to reproduce the problem:
Boot the game

____
#### Versions:
- This mod: EvilCraft-1.10.2-0.10.29
- CyclopsCore: CyclopsCore-1.9.4-0.10.10
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

**Comment by rubensworks** [comment]
This has been fixed for later MC versions already, 1.10 is not maintained anymore, sorry.
