### ISSUE TITLE
Vengeance Spirits rendered as Poisonous Libelles

### ISSUE THREAD

**Issue by McCarrick111** [rubensworks/EvilCraft#655]
Hi there, my name is John. I'm running a custom modpack for a small group of friends on a server. I myself have not experienced the issue, however two of the players so far on my server have since we added EvilCraft to our pack recently.

The issue in question appears to be a rendering issue where the game is misreading the ID for ghosts and rendering Posionus Libels instead. I've provided a screenshot bellow, and will include a copy of the private modpack as a mediafire download.

https://cdn.discordapp.com/attachments/246788944996335616/411592671476449290/unknown.png

Clarification: These dragonflies came from another entity after it died - they cannot be interacted with and last for only a short time. This bug has not caused any crashes but I'd prefer if I could fix it for my players.

Modpack: http://www.mediafire.com/file/51vk9li8dkmjgdq/Swamps+Reborn+2.0.zip

Version info:
- EvilCraft: 1.12.2-0.10.47
- CyclopsCore: 1.12.2-0.11.3
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.1.2582

**Comment by rubensworks** [comment]
The mod that adds these "ghosts" is probably registering the entity or entity renderer incorrectly. Make sure to report it on their issue tracker.

**Comment by josephcsible** [comment]
When you say "ghosts", are you talking about Vengeance Spirits, or some other ghost?

**Comment by McCarrick111** [comment]
Perhaps they are vengeance spirits, I'm not sure of the nomenclature. I can assure you that the ghosts are not part of another mod.

The ghosts which I'm discussing are the semi-transparent clone entities that appear after you kill a mob with the EvilCraft mod. IE if you kill a pig, it'll spawn a semi-transparent pig with altered sound effects. Normally these "ghosts" are only visible if you're in creative mode or using an item from EvilCraft in survival.

I haven't been seeing either the expected ghosts or the glitched dragonflies myself. The provided screenshot shows what one of my users has seen - a mysteriously appearing dragonfly that I theorize is a mistakenly identifying the ghost entity type as another ID (the dragonfly). Since the entity takes the form of whatever it was killed when a living mob was slain that's the best guess I've got.

Again of course I'm no expert. This seems to be exclusive to EvilCraft and doesn't happen with it removed - though I have no doubt that it is due to an interaction conflict bug with another mod.

If I provided a console log would that be at all helpful? Like I said it isn't causing crashes or anything, its purely a cosmetic issue. I will keep an eye on the console in the mean time and see if anything catches my eye.

**Comment by McCarrick111** [comment]
Follow up after some further testing;

I went both into solo and onto the server with one of my users. We repeated the test with spectral glasses item equipped and unequipped. My user saw a dragonfly spawn without the spectral glasses on as well as with them off. As for myself, when I had the glasses on I saw the vengeance spirit take the proper mob form as intended, and without the glasses on I saw no evidence of an entity.

I do not have an answer for why on earth I can see them rendering properly but my users can't. We are running the exact same pack with no texture packs to my knowledge and no client-side mods outside of the ones I've included in the pack (Dynamic Surroundings, Journey-map). 

As for the console, nothing at all came up with the console during testing. Sorry that won't be of any help. In the chance that it is important I am opped on an off-site rented server, I'm not hosting the world on my local machine, which makes the rendering differences even more confusing to me.

**Comment by rubensworks** [comment]
@McCarrick111 Ah ok, so the vengeance spirits from EC...

What happens if those users start a new SP world with the pack and try to reproduce the bug? And what if those users start a clean pack+world with only EC (and requirements) installed?

**Comment by McCarrick111** [comment]
I will have to get back to you on my other users as they are all offline at the moment. I can say for myself that the bug is not reproduced, however I have yet to experience it on the server either.

I will get one of my users to attempt to recreate the bug in solo for you tomorrow during the day and get back to you with the information as soon as I'm able to. Thank you for your time thus far.

**Comment by McCarrick111** [comment]
Ok Rubensworks, I've gotten my user to confirm the issue. In solo the Vengeance Spirits render correctly for him as expected - no dragonflies. This was with the pack so I didn't have him run it with only EvilCraft.

So this issue seems to be exclusive to the server. My user suggests it may be a conflict with the server version of forge. As an additional test I went ahead and OP'd him on my server and even with the OP he is still seeing dragonflies.

Any other suggestions? I am kind of at a loss as to what could be causing the issue, especially since I myself cannot see it.

**Comment by rubensworks** [comment]
> My user suggests it may be a conflict with the server version of forge.

So did you check this?

The only thing I can think of right now is that this player is somehow using a corrupted Forge/EC version.

Did you already try starting a brand new multiplayer world to check the issue?

**Comment by McCarrick111** [comment]
I've just gone ahead and rebooted the server (no changes yet) with the console up again. I noticed the following error spring up;

"11.02 17:14:10 [Server] Server thread/ERROR Couldn't load loot table evilcraft:inject/chests/box_of_eternal_closure from jar:file:/mods/EvilCraft-1.12.2-0.10.47.jar!/assets/evilcraft/loot_tables/inject/chests/box_of_eternal_closure.json 11.02 17:14:10 [Server] INFO com.google.gson.JsonParseException: Loot Table "evilcraft:inject/chests/box_of_eternal_closure" Duplicate entry name "evilcraft:box_of_eternal_closure" for pool #-1 entry #1"

However, this is the only major error I found and as you can see its only talking about loot tables. I had a user check for dragonflies after the reboot, and as expected he saw dragonflies.

After replacing the Forge/EC versions with fresh downloads from their respective sources (including Cyclops - still using the .3 not newest .4) I rebooted the server and have the same error. No other clues. I had another user jump in and test if dragonflies persisted after replacing the mod/forge files on the same world - still seeing the dragonflies.

Lastly I've rehosted on a newly generated world and had myself and one of my users present and killed a few wolves. I still saw the spirit of vengence entities rendering as they should, he still saw dragonflies.


So if its not Forge, its not a corrupt copy of EC/CC, it presumably must be some sort of conflict with another mod or just a multiplayer glitch with EC. Once I can get my hands on another user to test I will relaunch with ONLY CC and EC on the server and confirm if it is only with EC - but I cannot do that just yet.

Would it be at all helpful for me to give you a complete modlist? I believe I provided my modpack as a rar in my opening ticket as well.

**Comment by rubensworks** [comment]
> Once I can get my hands on another user to test I will relaunch with ONLY CC and EC on the server and confirm if it is only with EC

Sounds good!

> Would it be at all helpful for me to give you a complete modlist?

Not necessary. It's not possible for me (time-wise) to debug complete modpacks.

**Comment by McCarrick111** [comment]
Alright so I've relaunched the server using only CC and EC. Believe it or not, the problem persisted! My users still see dragonflies while I see things rendering correctly.

This was with absolutely no client side mods or mods outside of Forge, Cyclops Core and EvilCraft installed.

**Comment by McCarrick111** [comment]
Also I just want to clarify - the dragonflies I speak of are specifically Poisonous Libelles from EC, not another mods dragonfly. I went ahead and checked in-game to compare the models since one other mod I had does add a dragonfly mob (Between Lands).

**Comment by rubensworks** [comment]
Perhaps you should point this user to this issue here, this indirect communication is quite inefficient.

Can you send the client logs when only EC+CC is installed and the libelles are seen instead of the spirits?

**Comment by McCarrick111** [comment]
Here is his log from our test.

[16:55:33] [main/INFO]: Setting user: Blockhead0001
[16:55:37] [main/INFO]: LWJGL Version: 2.9.4
[16:55:40] [main/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Cyclops Core, FMLFileResourcePack:EvilCraft, FMLFileResourcePack:EvilCraft-Compat
[16:55:43] [Sound Library Loader/INFO]: Starting up SoundSystem...
[16:55:43] [Thread-6/INFO]: Initializing LWJGL OpenAL
[16:55:43] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:55:43] [Thread-6/INFO]: OpenAL initialized.
[16:55:44] [Sound Library Loader/INFO]: Sound engine started
[16:55:47] [main/INFO]: Created: 1024x512 textures-atlas
[16:55:50] [main/INFO]: Narrator library for x64 successfully loaded
[16:56:18] [main/INFO]: Connecting to 142.44.251.80, 25571
[16:56:52] [main/INFO]: Loaded 9 advancements
[16:56:53] [main/INFO]: Loaded 15 advancements
[16:57:13] [main/INFO]: [CHAT] McCarrick_I_Am joined the game
[16:58:19] [main/INFO]: [CHAT] Saved screenshot as 2018-02-12_16.58.18.png
[16:58:38] [main/INFO]: Stopping!
[16:58:38] [main/INFO]: SoundSystem shutting down...
[16:58:38] [main/WARN]: Author: Paul Lamb, www.paulscode.com

FYI regarding the SoundSystem shutting down, he didn't crash or anything on exit nor did the server.

**Comment by rubensworks** [comment]
I'll need the full forge log (please don't paste it directly in here)

**Comment by McCarrick111** [comment]
If I'm not mistaken this is the file you are asking for.

[fml-client-latest.log](https://github.com/CyclopsMC/EvilCraft/files/1718117/fml-client-latest.log)

**Comment by rubensworks** [comment]
Nothing in the logs seem to indicate a problem. I don't have a clue at the moment what could be the cause. I'm putting this on hold until someone else is able to reproduce this with (hopefully) additional information.

**Comment by McCarrick111** [comment]
Fair enough - in the mean time, I've solved the problem by disabling Vengeance Spirits in the config.

Weird note; When testing with disabling Poisonous Libelles before turning off Vengeance Spirits, I saw the Vengeance Spirit as a Poisonous Libelle while my user saw it as a Netherfish. I'll just stick to a vengeanceless world.

**Comment by rubensworks** [comment]
Hmm, are you sure the config files of that user are compatible with those of the server? That could actually explain the incorrect renderings.

**Comment by McCarrick111** [comment]
All of the configs until just now are auto-generated default. The only change being disabling Vengeance Spirits just a few minutes ago.

**Comment by josephcsible** [comment]
I know Forge has some kind of network thing to make server connections fail if some given condition is true, like configs being different. I wonder if that's worth looking into.

**Comment by CplPibald** [comment]
Experienced this issue recently.  It was caused by a config mismatch between client and server.  Server had `B:werewolf.isEnabled=false`, and client had default configs with werewolf enabled.

Syncing config between client and server resolved the issue.
