### ISSUE TITLE
Server Crash Villagers on Spirit furnace [1.11.2]

### ISSUE THREAD

**Issue by HeberonYT** [rubensworks/EvilCraft#656]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug
____
#### Short description:
I have the same problem,( #650 ) but in minecraft java, version 1.11.2
When putting boxes with the spirit of a villager, the server crashes just when it should give the first drop, and it sounds like the villager receives damage, just after crashing and the world is corrupt, he needs WordEdit to eliminate that oven.
____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: EvilCraft-1.11.2-0.10.30.jar
- CyclopsCore: CyclopsCore-1.11.2-0.10.9.jar
- Minecraft: 1.11.2
- Forge: 13.20.1.2588

#### Log file:
CrashReport
https://pastebin.com/raw/7g7065gG

**Comment by josephcsible** [comment]
1.11.2 is no longer supported. Can you reproduce this issue in 1.12.2?

**Comment by rubensworks** [comment]
Yeah, this was fixed on 1.12 already. 1.11 is not maintained anymore, sorry.
