### ISSUE TITLE
Error loading loot tables

### ISSUE THREAD

**Issue by flamechair** [rubensworks/EvilCraft#657]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
It seems that Evilcraft is having a hard time loading loot tables, causing a few stack traces in the console. The server still seems to function fine though

#### Expected behaviour:
No stacktraces

#### Actual behaviour:
Stacktraces mentioned above

#### Steps to reproduce the problem:

1. Install Evilcraft
2. Start server
3. Watch console

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: EvilCraft-1.12.2-0.10.47
- CyclopsCore: CyclopsCore-1.12.2-0.11.3
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.2.2611-universal

#### Log file:
Excerpt:
`
Couldn't load loot table evilcraft:inject/chests/box_of_eternal_closure from jar:file:/home/container/mods/EvilCraft-1.12.2-0.10.47.jar!/assets/evilcraft/loot_tables/inject/chests/box_of_eternal_closure.json
com.google.gson.JsonParseException: Loot Table "evilcraft:inject/chests/box_of_eternal_closure" Duplicate entry name "evilcraft:box_of_eternal_closure" for pool #-1 entry #1
`

Full log: https://pastebin.com/HwXhxwmM

**Comment by rubensworks** [comment]
Are the loot tables actually being loaded? I.e., do you see any additional EC loot in loot chests and so on?

**Comment by flamechair** [comment]
Yes, they are being loaded. I've seen plenty of chests with the compressed blood and evilcraft manual in them. I'd also like to add that this stacktrace probably happens 3-4 times throughout the server boot.

**Comment by rubensworks** [comment]
Ok, I see. That probably means that the loot tables are loaded multiple times for whatever reason. I can easily add a check to fix this.

**Comment by flamechair** [comment]
That'd be awesome, thanks!
