### ISSUE TITLE
evilcraft-compat forestry cyclops core and forge issues with mc 1-12-2   forge 2611 forestry_1.12.2-5.8.0.246 and EvilCraft-1.12.2-  0.10.46

### ISSUE THREAD

**Issue by trogarus** [rubensworks/EvilCraft#658]
#### Issue type: Game Crash on Startup

_Only keep the issue types that are applicable._
- :bug: Bug

____
#### Short description:
Game crash at startup

#### Expected behaviour:
Game starts, it presently does not

#### Actual behaviour:
Game crashes to launcher screen

#### Steps to reproduce the problem:

Install mods as listed below, try to start game. Crash to launcher.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: EvilCraft-1.12.2-0.10.46
- CyclopsCore: CyclopsCore-1.12.2-0.11.4
- Minecraft: 1-12-2
- Forge: 2611

#### Log file:
Crash log
[crash-2018-02-17_05.28.47-client.txt](https://github.com/CyclopsMC/EvilCraft/files/1733581/crash-2018-02-17_05.28.47-client.txt)

Latest log
[latest.log](https://github.com/CyclopsMC/EvilCraft/files/1733580/latest.log)

**Comment by trogarus** [comment]
To follow up, rolling back to forestry_1.12.2-5.7.0.238 fixes the game crash issue,

**Comment by rubensworks** [comment]
Please update to the latest EC version, this has already been fixed before, as can be seen in #652, #651, #649 and #648.

**Comment by trogarus** [comment]
Ack, sorry, missed that. Could have sworn I had the latest build, but seems I didn't. Sorry for the duplicate and taking your time on that one.
