### ISSUE TITLE
Crash Upon Opening/Loading Minecraft

### ISSUE THREAD

**Issue by princessbinas** [rubensworks/EvilCraft#661]
~~DELETE THIS LINE AFTER READING: :tada: Thanks in advance for this issue, you're awesome! :tada: Please fill in the following template and make sure your title clear and concisely summarizes the issue.~~

#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug
- :snail: Performance issue

____
#### Short description:

I am using iamtpage's MinePlus Tech Fantasy, renamed Dark MagicTech, modpack, which includes EvilCraft-1.12.2-0.10.48. Upon opening Minecraft and entering the main loading screen (the one prior to the main menu), it crashes once trying to load in the evilcraft mod.

#### Expected behaviour:

The game should allow me to proceed to the main menu and select multiplayer so I can join a server or go into single player to mess around in creative.

#### Actual behaviour:

The game crashes on the loading screen.

#### Steps to reproduce the problem:

1. Install Dark MagicTech's latest build (3.9) with optifine, voxel map and liteloader snapshot 1.12.2, and theoneprobe.

2. Try to launch game and be greeted with this:

https://media.discordapp.net/attachments/397888054704078858/418422316838551553/unknown.png

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: EvilCraft-1.12.2-0.10.48 (in Dark MagicTech 3.9 modpack)
- CyclopsCore: CyclopsCore-1.12.2-0.11.4
- Minecraft: 1.12.2
- Forge: forge-14.23.2.2611

#### Log file:

_Don't paste contents here directly, but use something like http://pastebin.com/_

Three Crash Reports:
https://pastebin.com/sHYujH7p

Logfile: 
https://pastebin.com/QBSHqmMN

**Comment by rubensworks** [comment]
Please try reproducing this without any other mods installed. This sounds like an optifine issue...

**Comment by princessbinas** [comment]
I reinstalled the modpack before you replied and it works fine now. I think it was a file corruption when I was first installing the modpack. I will keep you posted if it reoccurs. Knowing my luck, it may occur again. It happens all the time to me.

**Comment by rubensworks** [comment]
Alright, keep me posted!
