### ISSUE TITLE
Disable blood stains on magma blocks

### ISSUE THREAD

**Issue by coman3** [rubensworks/EvilCraft#662]
#### Issue type:
Bug
____
#### Short description:
Magma blocks fail to work if blood has been placed on top of them. 

Any mob dying from fall damage places blood on top of magma block.

#### Expected behaviour:
Hurt mobs emit low light levels

#### Actual behaviour:

Disables block and causes no damage, or light emission 

#### Steps to reproduce the problem:

1. Place magma block under a high platform
2. Push zombie off of high platform (too kill it from fall damage)
3. Place zombie on top of now ruined magma block
4. Observe.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.10.48
- CyclopsCore: 0.11.4
- Minecraft: 1.12.2
- Forge: 14.23.2.2623

#### Log file:

No log, ingame bug.

**Comment by rubensworks** [comment]
You can add magma blocks to the blood stained block blacklist in the config file.

Note to self: add this block to the default blacklist.
