### ISSUE TITLE
(Suggestion) Rename Breaking and Vengeance enchantments to Curse of Breaking and Curse of Vengeance

### ISSUE THREAD

**Issue by TechnoMysterio** [rubensworks/EvilCraft#663]
For an improvement to the mod's enchantments, renaming the 'Breaking' and 'Vengeance' enchantments to 'Curse of Breaking' and 'Curse of Vengeance' and making sure they have a red font (like the curses in vanilla Minecraft) would help inform players of the curses' nature, and would also make sure that they line up with vanilla's own 'Curse of Vanishing' and 'Curse of Binding'.

**Comment by rubensworks** [comment]
Sure, why not.

**Comment by rubensworks** [comment]
Will be changed in the next update, the red color will be added in the next CyclopsCore update.

**Comment by TechnoMysterio** [comment]
Just checked the commit, and noticed that you renamed Breaking, which is right, but also Unusing, which seems wrong. Unusing is useful, as it prevents your tools from breaking, but Vengeance is bad as it summons spirits, so that should be classified as a curse instead of Unusing.
