### ISSUE TITLE
(1.12.2) Issues With Recent Enchantment Updates

### ISSUE THREAD

**Issue by TechnoMysterio** [rubensworks/EvilCraft#666]
As partially a follow-up to #663, there are a couple of issues with the recent changes to enchantments.

Firstly, the names for curses have not changed. Despite the fact that en_us.lang has changed 'Breaking' to 'Curse of Breaking', the in-game enchantment is still called 'Breaking'. I think this may be because the game is reading localisation data from the en_us file in the evilcraftcompat folder (which hasn't been changed) instead of the en_us file in evilcraft folder.

Secondly, Unusing is classed as a curse while Vengeance isn't, and the guide book describes the former enchantment as being useful and having a positive effect, allowing you to preserve your equipment. I think when you were dealing with #663, you got the two enchantments mixed up, so it'd be wise to classify Vengeance as the curse, and set Unusing back as a normal enchantment.

- This mod: 0.10.49
- CyclopsCore: 0.11.4
- Minecraft: 1.12.2
- Forge: 14.23.2.2624

**Comment by rubensworks** [comment]
You're right, I made a mistake. Thanks for re-reporting!

**Comment by TechnoMysterio** [comment]
I just noticed that this issue is number 666. Quite appropriate for a mod based around evil magic and technology.

**Comment by rubensworks** [comment]
Hah, you're right, nice :)

**Comment by TechnoMysterio** [comment]
EEEEVVIILLL... PUUURREEE EEEEEEVVVILLLLLLLL
