### ISSUE TITLE
Restore Blood Magic Compatibility

### ISSUE THREAD

**Issue by TechnoMysterio** [rubensworks/EvilCraft#668]
After looking through the lang file for the mod, I noticed something mentioning compatibility between this mod and Blood Magic, with special items and the like. However, when I load up a game with both EvilCraft and Blood Magic for 1.12.2, there are no special items included, nor is there a entry in the book about compatibility between the two mods.

I'm not sure if you're aware that Blood Magic is out for 1.12.2 (it is in alpha, but it's fairly stable), but it would be good to update compatibility between the two mods, as it's a bit strange having to deal with two separate blood systems that don't cross over with each other in any ways.

- EvilCraft: 0.10.50
- CyclopsCore: 0.11.5
- Minecraft: 1.12.2
- Forge: 14.23.2.2625

As well as...

- Blood Magic: 2.2.7-90

**Comment by rubensworks** [comment]
Ah, BM is out for 1.12.2, that's good news!

I'll look into restoring compat, as that's disabled at the moment.
