### ISSUE TITLE
[1.7.10] Magic career breaks blocks in private WorldGuard

### ISSUE THREAD

**Issue by bigenergy** [rubensworks/EvilCraft#671]
Magic Kar to break other people's privates WorldGuard and grif other people's privates.
EvilCraft-1.7.10-0.9.13
Forge 1614 latest 1.7.10

**Comment by rubensworks** [comment]
I have no idea what _Magic career_ is, it's definitely not a part of this mod.

Also, 1.7.10 is not supported anymore.
