### ISSUE TITLE
Dark Ore Dropping Experience

### ISSUE THREAD

**Issue by KAfable** [rubensworks/EvilCraft#675]
#### Issue type:

- :snail: Performance issue

Hi, I'm currently trying to use [Dropt](https://minecraft.curseforge.com/projects/dropt) as a way to control block drops for my pack, however it seems that Apatite Ore still continues to drop experience after configuring Dropt to prevent that.

Would it be possible to have dark ore use
public int getExpDrop(IBlockState state, IBlockAccess world, BlockPos pos, int fortune) to provide the xp as I think dropBlockAsItemWithChance is an old method.

For what it's worth, this is my current [Dropt json](https://hastebin.com/qunukupibo.json), it manages to successfully alter Coralium ore xp drops, but Dark Ore and Apatite ore both still use `dropBlockAsitemWithChance`.

Thanks.

**Comment by rubensworks** [comment]
I'll look into it, it's possible that `dropBlockAsitemWithChance`  has been deprecated, but I'll have to dive into the code to check.

**Comment by KAfable** [comment]
Dropt dev goes into more detail here whenever you have the time, my original suggestion might not be correct as I'm still new to Java. 

https://github.com/codetaylor/dropt/issues/21
