### ISSUE TITLE
Duping glitch (Cyclic automated user, Integrated Dynamics drying basin, evilcraft condensed blood, and hopper)

### ISSUE THREAD

**Issue by Xetaxheb** [rubensworks/EvilCraft#676]
- :bug: Bug

Pack is single player FTB Horizons III

Cyclic-1.12.2-1.10.12.jar
IntegratedDynamics-1.12.2-0.10.3.jar
EvilCraft-1.12.2-0.10.45.jar

Pretty easy reproduce: Auto user with 1 (or more, it will empty down to 1) condensed blood pointing at a drying basin, basin over a hopper pointing at a chest. After it hits 1 blood left, that last blood never disappears but the user keeps putting one in the basin which the hopper also pulls one out of. Infinite item that's otherwise exclusively from dungeon chests.

edit: actually bigger problem I just noticed, anything put in the basin with specific timing while this glitch is going on will just disappear entirely

**Comment by rubensworks** [comment]
@Xetaxheb Could you check if you can reproduce this with Integrated Tunnel's Player Simulator?

**Comment by Xetaxheb** [comment]
Sorry, i'm looking at it but I have no idea how this mod works

**Comment by Xetaxheb** [comment]
Okay i think i figured out a very basic setup; can't get it to dupe though.

Cyclic's dev says this was a bug just fixed with the auto user. edit: clarity: says he had a report for this recently where auto user was doing similar thing with astral sorcery lightwell, with the issue being with the auto user; and that it 'should be fixed' in the latest aka Cyclic-1.12.2-1.14.6

**Comment by rubensworks** [comment]
Ok, that's great. Can you confirm that the latest Cyclic version does indeed solve the problem for you? If so, feel free to close this issue (and the one in Integrated Dynamics as well).

**Comment by Xetaxheb** [comment]
Latest cyclic version (Cyclic-1.12.2-1.14.6.jar) still has the issue.

**Comment by Lothrazar** [comment]
I have some GIFS uploaded and ive explored a few edge cases, two where there is no bug, and one where it is.   https://github.com/PrinceOfAmber/Cyclic/issues/757

Feel free to ask anything there, check my source code, or dm me on twitter/discord.

**Comment by rubensworks** [comment]
Not an EC issue, as reported in PrinceOfAmber/Cyclic#757.
