### ISSUE TITLE
(1.12.2) Update EvilCraft Compatibility for both Ender IO and Thaumcraft

### ISSUE THREAD

**Issue by TechnoMysterio** [rubensworks/EvilCraft#684]
Similar to the previous Blood Magic update, Thaumcraft 6 is now in beta for 1.12.2, and Ender IO was updated to 1.12.2 a little while ago. Updating compatibility for both would probably be a good step to take. 

Also, reading through the en_us.lang file shows that the Thaumcraft compat includes blood based wands, and I seem to remember that Thaumcraft 6 removed the wand system in favour of a modular gauntlet, so it would be worth changing the integration and EvilCraft book entries where appropriate.

**Comment by rubensworks** [comment]
Yep, I should update these at some point.
