### ISSUE TITLE
[1.12.2] broom bugging after dimmension visit

### ISSUE THREAD

**Issue by Gayanfalor** [rubensworks/EvilCraft#687]
#### Issue type: bug

____
#### Short description:
Was doing my first rftool dimmension and wanted to fly with the broom but it was different from normal seemed empty with bad texture.  Its acting like a non upgraded broom  bad speed bad maneuvrability etc but it had upgrades for that.

Restarted the game and even in overwolrd still bugged

how it should looks like  https://puu.sh/Aftwg/c56c043aad.png

how it is when on it  https://puu.sh/AftyY/652981570f.png

#### Expected behaviour:
Working normally

#### Steps to reproduce the problem:

1. craft a broom and upgrade it
2 go to a rf tool dimm and try to fly

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.10.53
- CyclopsCore: 0.11.5
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

#### Log file:

_Don't paste contents here directly, but use something like http://pastebin.com/_

**Comment by rubensworks** [comment]
Can you consistently reproduce this for every broom you make and use in another dimension?

What happens when you unmount? Do you get a different broom back?

Sounds similar to #619.
