### ISSUE TITLE
Unusing Enchantment not accepted by anvil

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#690]
#### Issue type:

_Only keep the issue types that are applicable._
- :bug: Bug
____
#### Short description:
Trying to anvil an Unusing book (from the Purifier) fails, tested on Vein Sword and Fishing Rod

#### Expected behaviour:
Should be added as usual to the item.

#### Actual behaviour:
Anvil shows the X for an unacceptable combination.

#### Steps to reproduce the problem:

1. Peel Unusing off a found item (in my case a fishing rod)
2. Try to use an anvil to apply it to something else
3. Gnash your teeth in frustration ;)
____
#### Versions:
CyclopsCore-1.12.2-0.11.5.jar 
EvilCraft EvilCraft-1.12.2-0.10.56.jar 
Forge 2655
Minecraft 1.12.2

#### Log file:

_Don't paste contents here directly, but use something like http://pastebin.com/_

**Comment by rubensworks** [comment]
Will be partially fixed for swords in the next update.

Other tools such as fishing rods are not supported atm, as they require a totally different usage-blocking mechanism. I've created a new issue for this: #691
