### ISSUE TITLE
Autofilling extractor fills buckets in hand

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#692]
#### Issue type:

- :bug: Bug

____

#### Short description:

When my blood extractor is set to autofill, it fills any empty bucket I wield.

#### Steps to reproduce the problem:

1. Set an extractor with at least 1000 units of blood to "auto-fill".
2. Take an empty bucket in hand.
3. Hey, that bucket you were planning to scoop lava with seems to be full of blood!

#### Expected behaviour:

Buckets should not automatically be filled with blood.  If you want a bucket of blood in the field, you can use the extractor to place a blood block, then use a bucket to scoop that up.

____

#### Versions:

- This mod: 0.10.56
- Minecraft: 1.12.2
- Forge: 2655

**Comment by rubensworks** [comment]
That's actually a feature! But I get why it might be annoying, will look into it. Perhaps a config option might be good.

**Comment by MentalMouse** [comment]
Perhaps buckets could be filled in the crafting grid. That is, empty-bucket+extractor --> blood bucket+less-full extractor.

ETA:  I understand that bucketing is part of making blood a proper fluid, but is there actually any use for a bucket of blood, that can't be served by the extractor itself?
