### ISSUE TITLE
Evilcraft modifying items's aspects

### ISSUE THREAD

**Issue by supercrasher** [rubensworks/EvilCraft#693]
#### Issue type:

- :bug: Bug

____

#### Short description:

Evilcraft modifies snowballs for example and iron nuggets and removes their aspects from thaumcraft 6

#### Steps to reproduce the problem:

    1. Have Thaumcraft 6 and Evilcraft installed;
    2.Check the aspects of snowball and iron nuggets and observe that they're non-existent
#### Expected behaviour:

The aspects should show up when pressing shift on these items just like when Evilcraft isn't installed
____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.56
- Minecraft: 1.12.2
- Forge: 2678

**Comment by rubensworks** [comment]
This sounds similar to issues from back in 1.7.10 (like #208).

**Comment by rubensworks** [comment]
I wasn't able to reproduce this, which makes me think that it's a rare mod-order-loading issue. The last commit should fix this, let me know if the issue persists for future releases.
