### ISSUE TITLE
Blood stained blocks crash

### ISSUE THREAD

**Issue by Flemmli97** [rubensworks/EvilCraft#694]
#### Issue type:

- Crash when breaking blood stained blocks propably with silk touch. 

____

#### Short description:

- break a blood stained block (silk touch?) crashed once before but i though it was a one time/rare issue and as such did not note it. happened when i broke the block with a tinkers pick having silk touch

#### Versions:

- This mod: 0.10.54
- Minecraft: 1.12
- Forge: 1.12.2-forge1.12.2-14.23.3.2676

#### Log file:
[https://pastebin.com/5yB8RXjt](url)

**Comment by rubensworks** [comment]
This is actually the same problem as CyclopsMC/CyclopsCore#110, which has been fixed in dev. Will release a new EC version soon.
