### ISSUE TITLE
Blood and EvilCraft book spawning in all chests

### ISSUE THREAD

**Issue by The-Shopkeeper** [rubensworks/EvilCraft#696]
#### Issue type:

- :bug: Bug

____

#### Short description:

Blood and EvilCraft book spawning in all chests

#### Steps to reproduce the problem:

Go to any chest in towns or normal world and blood (condensed blood i think) appears multiple times in a single chest and the Book for Evilcraft. In all the chests everywhere it seems.

I have tinkers construct and blood magic as well as loads of other mods, not sure what is causing this as there's no way to get an error report.

#### Versions:

- This mod:   1.12.2-0.12.57
- Minecraft:  1.12.2
- Forge:  14.23.3.2702

**Comment by rubensworks** [comment]
Can you check without any other mods installed?

**Comment by The-Shopkeeper** [comment]
With your mod only, first village I go to has a chest where 4 slots are taken up with condensed blood...

**Comment by rubensworks** [comment]
Does it still happen in _all_ chests you find? Or just that first one?

_If_ the condensed blood spawns in a chest, then it's normal that it will occupy multiple slots.

**Comment by The-Shopkeeper** [comment]
Can't find many on this seed, but 3 villages so far have it.  the chest in the blacksmiths I'm checking.  Just thought it a bit odd that villagers would store such a thing! :) 

And It seems to effect other villages/forts chests spawned by Ancient Warfare 2 (mod) in the other modpack I made (just for your info).

**Comment by The-Shopkeeper** [comment]
And 'The Origin of Darkness' in the 5th village. All have blood..... Vampire peasants everywhere!! (kidding) ;D

**Comment by rubensworks** [comment]
It might not be an actual bug then, I probably just have to tweak the spawn frequencies a bit.

**Comment by The-Shopkeeper** [comment]
I haven't played through the pack yet, does it need to spawn in chests? Or is there other ways of getting it (the blood and the book?)  and if there are other ways, is there a toggle to turn their spawning off for chests?  Just out of interest for my pack.  

Really excited to get my teeth stuck in to this pack! looks awesome btw.

**Comment by rubensworks** [comment]
Yes, there are plenty of other (and better) ways of obtaining blood and the book.

This mod offers to way to disable the spawning in chests though, but you might be able to achieve that by using a mod that allows you to tweak loot chests.

**Comment by The-Shopkeeper** [comment]
I'll be honest. It does make me want to take this mod out of my selection for my modpack.  As everywhere I'm going there's just lots of blood and the book. It gets a bit annoying.  Is there some way to fix it?  It makes it seems like all villages are in to Evil magic and store blood....

Using a mod to tweak the loot chest might work, but is less desirable.

**Comment by rubensworks** [comment]
There's definitely a way to fix it yes. I should be able to look into it somewhere next week.

**Comment by rubensworks** [comment]
Nvm, just did it now. Will be released next week. You can already use the dev build (see README) if you want.
