### ISSUE TITLE
Dinnerbone's (and, I'm guessing, Jeb_'s) spawn egg doesn't actually spawn anything

### ISSUE THREAD

**Issue by belathus** [rubensworks/EvilCraft#697]
#### Issue type:

- :bug: Bug

____

#### Short description:
The spawn egg created by Dinnerbone (and probably Jeb_, since they appear to be the same) doesn't actually spawn anything.

#### Steps to reproduce the problem:

1. Make spirit furnace
2. Throw in Dinnerbone (or Jeb_)
3. Wait until you obtain a spawn egg
4. Attempt to spawn creature

#### Expected behaviour:
I'm guessing the spawn egg is supposed to spawn a sheep. If so, you need to add the tag: {EntityTag: {id:"minecraft:sheep"}}

____

#### Versions:

- This mod: 0.10.57
- Minecraft: 1.12.2
- Forge: 14.23.3.2691

#### Log file:
https://github.com/CyclopsMC/EvilCraft/blob/e6b1cfa320f81a963d6850df8f297b9e304583ab/src/main/java/org/cyclops/evilcraft/tileentity/tickaction/spiritfurnace/BoxCookTickAction.java#L66-L67

**Comment by rubensworks** [comment]
It looks like I missed that in the 1.11/1.12 update, thanks for reporting!

**Comment by belathus** [comment]
Anytime. It's what I'm here for. :P
