### ISSUE TITLE
Oredict TreeLeaves

### ISSUE THREAD

**Issue by tyler489** [rubensworks/EvilCraft#698]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Please add your leaves to oredict tree Leaves that way they will be harvested by enderio farming station.
https://github.com/SleepyTrousers/EnderIO/issues/4680

**Comment by rubensworks** [comment]
Oh, I'm surprised this isn't being registered already.

**Comment by tyler489** [comment]
I was too
