### ISSUE TITLE
Brooms break with Guide-API (required for Blood Magic) installed

### ISSUE THREAD

**Issue by Darkehart** [rubensworks/EvilCraft#699]
#### Issue type:

- :bug: Bug

____

#### Short description:

When running Evilcraft with Guide-API, the broom parts lose all their stats and modifiers. Consequently, so do all brooms.

#### Steps to reproduce the problem:

1. Load Minecraft with EvilCraft and Guide-API installed properly.
2. Mouseover broom part or a completed broom or attempt to use a broom.
3. In the case of using a broom, the broom works, but since it has stats of 0 in everything it's atrociously bad.

#### Expected behaviour:

Broom performance should be normal.

____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.58
- Guide-API: Guide-API-1.12-2.1.5-60

- Minecraft: 1.12.2
- Forge: 14.23.4.2707

#### Log file:

Not Available.

**Comment by Darkehart** [comment]
Of course, as soon as I go back to my actual pack from the testing environment where I was trying to find which mod was causing this, it starts working again, AND, so does the testing environment. >.<

**Comment by rubensworks** [comment]
> Of course, as soon as I go back to my actual pack from the testing environment where I was trying to find which mod was causing this, it starts working again, AND, so does the testing environment. >.<

Wait, so brooms don't break anymore? Or do brooms that broke before automatically fix themselves?

Do you know if this Guide API is doing anything special with items held in the inventory? If so, it might be good to report this in their repo as well.
