### ISSUE TITLE
crash on startaup with forge

### ISSUE THREAD

**Issue by kuroyure** [rubensworks/EvilCraft#700]
#### Issue type:

- :bug: Bug

____

#### Short description:

crash on startup, probably an forge issue

#### Steps to reproduce the problem:

1. install this mod in the bellow version
2. install forge in the bellow version
3. install the mods present in the crash

#### Expected behaviour:

the game to launch 

____

#### Versions:

- This mod: 1.12.2-0.10.58
- Minecraft: 1.12.2
- Forge: 14.23.4.2707

#### Log file:

https://pastebin.com/AJR53bVM

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by kuroyure** [comment]
does it have a quick fix or ill need to wait to next update ?
btw np

**Comment by rubensworks** [comment]
You can either wait, or you could try temporarily disabling werewolf flesh.

**Comment by kuroyure** [comment]
how i do that ?

**Comment by rubensworks** [comment]
Via the EC config file.

**Comment by kuroyure** [comment]
what part of it??

**Comment by kuroyure** [comment]
do i set the drop chance to 0 ?

**Comment by kuroyure** [comment]
ok tks anyways
