### ISSUE TITLE
Bound blood drop crash

### ISSUE THREAD

**Issue by MrDvD** [rubensworks/EvilCraft#702]
I have a problem with bound blood drop. 
As soon as I started it nothing unusual happens, but as soon as I switch the modes, minecraft crashes. 
**I almost lost my world, where I played for 2 weeks!** 
I hope this bug will be fixed soon. 

Thanks to google translate

**Comment by rubensworks** [comment]
I hope you follow the issue template, as I can not help you otherwise.

**Comment by MrDvD** [comment]
Okay, I can provide you crash-report file and video with that bug.

**Crash-Report**: https://bit.ly/2yojj0x
**Video**: https://youtu.be/0lKUL7u_Wxg

(When I changed the mode of bound blood drop the world can not start until I remove this drop with the help of third-party software)

<blockquote><img src="https://cfl.dropboxstatic.com/static/images/icons128/page_white_text.png" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/s/xgoy597tkj9m2zw/Crash-Report.txt?dl=0">Crash-Report.txt</a></strong></div><div>Shared with Dropbox</div></blockquote>
<blockquote><img src="https://i.ytimg.com/vi/0lKUL7u_Wxg/hqdefault.jpg" width="48" align="right"><div><img src="/yts/img/favicon_144-vfliLAfaB.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=0lKUL7u_Wxg">A bug with Bound blood drop</a></strong></div><div>...</div></blockquote>

**Comment by rubensworks** [comment]
Ok, it seems to be a problem in EC compat (incompatible `ItemHelpers.updateAutoFill` signature). Will look into this soon.
