### ISSUE TITLE
4 Buckets of enternal water

### ISSUE THREAD

**Issue by MrDvD** [rubensworks/EvilCraft#703]
Well, when I crafting _"Eternal Water Bucket"_ appears 4 buckets, instead of 1. But when I use them, it appears 1. 

Minecraft Version: **1.12.2**
Forge Version: **14.23.4.2705**
Mod Version: **0.10.59**

Video with that bug: https://youtu.be/zoPJnaOMFQM

Thanks to Google Translate

**Comment by rubensworks** [comment]
Getting 4 buckets when crafting is intended. But them converting to only a single bucket is a bug.

**Comment by MrDvD** [comment]
Okay, but why not 1? This is in case 1 gets lost?

**Comment by rubensworks** [comment]
That's just a balancing decision.
