### ISSUE TITLE
Eternal water bucket deleted by other mod

### ISSUE THREAD

**Issue by TheRdMelon** [rubensworks/EvilCraft#705]
#### Issue type:

- :bug: Bug

____

#### Short description:

When putting the eternal water bucket in machines from some mods, it fills its container with water then replaces it presumably with its container item.  This deleted my eternal water bucket.

Sorry if this wasn't the issue and it was actually the other mod's fault.

**Comment by rubensworks** [comment]
What mod(s) are you experiencing this with? Because this sounds like a bug.

**Comment by TheRdMelon** [comment]
rockhounding-chemistry, any machine.

**Comment by rubensworks** [comment]
Never heard of that mod. Make sure to report it to their repo, and link back to this issue.

**Comment by rubensworks** [comment]
Following up on this one in Rockhounding_Chemistry.
