### ISSUE TITLE
Placing a Box of Eternal Closure crashes clients

### ISSUE THREAD

**Issue by hedgehog1029** [rubensworks/EvilCraft#707]
#### Issue type:

- :bug: Bug

____

#### Short description:

Placing a box of eternal closure causes the screen to fail rendering completely for all clients in range.

#### Steps to reproduce the problem:

1. Get a box of eternal closure
2. Try to place it
3. Observe that a GL error occurs, the screen goes various colors, and the game hangs or crashes.

#### Expected behaviour:

I'd expect the box to render properly and not crash clients.

____

#### Versions:

- This mod: 0.10.59
- CyclopsCore: 0.11.6
- Minecraft: 1.12.2
- Forge: 14.23.4.2717

#### Log file:

https://gist.github.com/nepeat/38f6c8943b88bb101b617acab98214c9

**Comment by rubensworks** [comment]
This seems to be caused by a change in Forge.

Downgrading to version 14.23.4.2715 should fix the problem until I push a fix.
