### ISSUE TITLE
Thaumcraft Aspects Disappearing

### ISSUE THREAD

**Issue by SpitefulFox** [rubensworks/EvilCraft#708]
#### Issue type:

- :bug: Bug

____

#### Short description:

When EvilCraft is installed and has Thaumcraft compatibility enabled, and Thaumic Equivalence is also installed, aspects disappear off of many common vanilla items like Coal, Snowballs, Blaze Rods, etc...

#### Steps to reproduce the problem:

1. Install Thaumcraft 6.1 Beta 17
2. Install EvilCraft 0.10.60
3. Install ProjectE 1.3.1B
4. Install Thaumic Equivalence 1.0.4
5. See if Coal, Blaze Rods, or Snowballs have aspects.

Could not reproduce the bug without Thaumic Equivalence also installed. The bug goes away if EvilCraft is uninstalled, or Thaumcraft compatibility is disabled in the config.

#### Expected behaviour:

Those items should have Thaumcraft aspects. They do not, when these two specific mods are present.

____

#### Versions:

- This mod: 0.10.60
- Minecraft: 1.12.2
- Forge: 14.23.4.2729
- Thaumic Equivalence: 1.0.4

**Comment by rubensworks** [comment]
Do you by any chance see anything special in the startup logs?

Perhaps it's good to also report this to the issue tracker of Thaumic Equivalence.

Possibly related to #693.

**Comment by SpitefulFox** [comment]
I couldn't find anything that looked related, but here's a log file just in case.
[2018-07-07-4.log](https://github.com/CyclopsMC/EvilCraft/files/2173523/2018-07-07-4.log)

**Comment by Lilylicious** [comment]
I've tested it myself with Thaumcraft beta17, ProjectE 1.3.1B, Thaumic Equivalence 1.0.4, and EvilCraft 0.10.60.

Coal lost its aspects. I have no idea why. I doubt my mod is the culprit, as the currently available version makes no modification to recipes or aspects, it only adds EMC to thaumcraft items. If the issue doesn't lie with you, I suspect Thaumcraft has an issue themselves. There's been whisperings about this issue for a while now.

https://github.com/Azanor/thaumcraft-beta/issues/622

Issue seems to occur with quite a few mods that have interactions with Thaumcraft, EnderIO included.

https://github.com/Azanor/thaumcraft-beta/issues/975

When I removed Thaumic Equivalence from the testing pack, coal did not regain its aspects. It did when I removed Evilcraft, even without removing Thaumic Equivalence.

**Comment by rubensworks** [comment]
I see, thanks for linking these issues @Lilylicious. Putting this on hold then. I'll be following the linked issues.

**Comment by belathus** [comment]
Re-adding missing aspects with ModTweaker seems to work for now. If anyone wants a copy of such a script, I have one; just keep in mind that this list is by no means exhaustive; I have no idea what all is losing their aspects (and the planks one might be a consequence of a pack-specific recipe change).

Here: https://github.com/belathus/Wanderlust-Renewed/blob/master/scripts/thaumcraft/aspects.zs

In regards to the problem, I have Evilcraft and EnderIO installed, but none of the other mods mentioned in this thread. I do have Thaumic Periphery, though.

<blockquote><img src="https://avatars2.githubusercontent.com/u/3826783?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/belathus/Wanderlust-Renewed">belathus/Wanderlust-Renewed</a></strong></div><div>Wanderlust-Renewed - Minecraft 1.12.2 Modpack focused on exploration</div></blockquote>

**Comment by rubensworks** [comment]
This should be fixed in the latest TC version and EC 0.10.63.
