### ISSUE TITLE
In-game recipe display shows XP costs instead of blood prices

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#711]
#### Issue type:

- :bug: Bug
____

#### Short description:
Blood Infuser Recipes displayed in-game, show prices in "XP".  This does not seem to be proportional to their blood cost.

#### Steps to reproduce the problem:

1. Use JEI or an infuser's GUI arrow to display recipes of infused items such as a Diamond Promise Acceptor.
2. Note the gray text at upper right, in this case "10.0XP".  (The blood cost is 160,000).  A sapling shows "1.5XP", for a cost of 800 blood.

#### Expected behaviour:

If you want to display the blood prices,then do that (presumably in buckets of blood).  Experience costs should only be shown if that's somehow an option (for example, some alternate mode allowing you to bypass blood costs).
____

#### Versions:
- This mod:  1.12.2 - 0.10.6.1
- Minecraft: 1.12.2
- Forge: 2705

**Comment by rubensworks** [comment]
Not sure if I understand your issue correctly. Blood infuser recipes don't require XP, instead, they _return_ XP when an item is crafted, just like furnace recipes. The blood amount that is required is shown in the tank.

**Comment by MentalMouse** [comment]
Ahh, I had not realized that!  Hmm.  I have to say that given the lower usage, the amounts of XP involved here seem pretty minimal, I'm not sure what the point is.

**Comment by rubensworks** [comment]
It should be similar to what you get from the vanilla furnace. Every bit helps I guess :-)
