### ISSUE TITLE
Rendering infobook crash 

### ISSUE THREAD

**Issue by xxlio109** [rubensworks/EvilCraft#713]
Short description:
Rendering screen crash

Steps to reproduce the problem:
Open origins of darkness look Broom basis Crash

Versions:
This mod: CyclopsCore-1.12.2-0.11.8 , EvilCraft-1.12.2-0.10.61
Minecraft: 1.12.2
Forge: 1.12.2 2705
Log file: https://gist.github.com/xxlio109/661baeb6a669d035904f212211682e01

**Comment by rubensworks** [comment]
What did you do exactly to cause the crash?

Please use the issue template in the future, then I wouldn't have to ask for this.

**Comment by xxlio109** [comment]
Open origins of darkness look  Broom basis  Crash

**Comment by xxlio109** [comment]
Steps to reproduce the problem:
Open origins of darkness look Broom basis Crash

**Comment by rubensworks** [comment]
I can't reproduce this with the information provided.

The stacktrace seems to indicate that you hovered over an item. If so, which item was this exactly?

Also please try reproducing it yourself without any other mods installed.
