### ISSUE TITLE
Bound Blood Drop does not respect Blood Magic's network limits

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#715]
#### Issue type:

- :bug: Bug

____

#### Short description:

When "filling" the Bound Blood Drop with EvilCraft blood, it does not respect the player's current (orb-based) limit to how much LP they can hold in their network.  This allows overfilling their personal network, giving them access to undue power on the Blood Magic side.

#### Steps to reproduce the problem:

1. Set up the player for Blood Magic.  Note in their guide the limit for their current orb.  For example, I had an Apprentice Orb (Tier 2) which has a 25K limit.  Also create and bind to the player a Seer's Sigil.
2. Set up an EvilCraft Blood Infuser, with a Tenacity upgrade raising its capacity well above the Blood Magic limit.  Fill the Infuser with blood.
3. Make a Bound Blood Drop, and put it in the Infuser's "fill item" slot.  
4.  Watch it drain the entire tank.. Pick up the Seer's Sigil and check the player's current LP level, which will be well above their network limit.

#### Expected behaviour:

4.  Bound Blood Drop should stop draining EC blood when the BM network has reached its current orb-based capacity.

____

#### Versions:

- This mod: 0.10.6.1
- Minecraft: 1.12.2
- Forge: 2705
- Blood Magic: 2.2.12-97

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
