### ISSUE TITLE
Evilcraft/-compat-/CyclopsCore Crash on Load - .getDamage Veined Scribing Tools

### ISSUE THREAD

**Issue by EndermanParty** [rubensworks/EvilCraft#716]
#### Issue type: Crash

- :bug: Crashed upon loading. 

____

#### Short description: Loaded Minecraft and got hit with this error. Seemed to be something with getting the damage values for other mod's items. 

- I updated a bunch of mods in my hodgepodge mod pack. I also updated forge to the version listed below. I looked into the modcompat config file and I see one for thaumcraft. Is there a way to disable specifically veined scribing tools? I would like to keep aspects on items if possible. I'll disable it and report back later if the pack loads! 
____

#### Versions:

- This mod: 0.10.61
- Minecraft: 1.12.2
- Forge: 14.23.4.2739
(Putting this here just in case) - Thaumcraft: 6.1.BETA19
#### Log file:
https://paste.dimdev.org/ivicizineg.mccrash

**Comment by wamc2017** [comment]
#712 

Should be fixed in [0.10.62](https://minecraft.curseforge.com/projects/evilcraft/files/2594472)

**Comment by EndermanParty** [comment]
Strange, Twitch didn't show me that that update existed.

**Comment by rubensworks** [comment]
No worries, the update was released around the time you posted the issue, so things might not have updated properly yet.
