### ISSUE TITLE
Make Blood Chest repairing consistent with Mending

### ISSUE THREAD

**Issue by Deuxis** [rubensworks/EvilCraft#717]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Blood chests don't repair many items they should (Immersive Engineering tools, Silent's Gems anything(!!!)...). As far as I understand, durability is just the meta value of an item and repairing it is just bumping it up, why not just do it that way and do config options for white/blacklisting compatible items?

Even if not, most of those (Silent's Gems gear, for example) work well with Mending - why can't Blood Chest just simulate Mending using blood instead of exp?

**Comment by rubensworks** [comment]
That's exactly what we do: https://github.com/CyclopsMC/EvilCraft/blob/master-1.12/src/main/java/org/cyclops/evilcraft/tileentity/tickaction/bloodchest/DamageableItemRepairAction.java#L39-L40

Some mods simply do not allow repairing through non-standard methods, nothing much I can do about that other than adding custom support (such as for TiCon).

I can look into how mending is applied exactly, but I assume it's exactly the same as how I do it now. I suspect that Silent Gems just adds custom support for Mending.

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EvilCraft">CyclopsMC/EvilCraft</a></strong></div><div>EvilCraft - An evil mod for Minecraft.</div></blockquote>

**Comment by Deuxis** [comment]
Just discovered that Powered Anvil from Cyclic works on Silent's Gems stuff. My bet is either simulated Mending or simulated vanilla anvil repairing.

**Comment by GamertechAU** [comment]
Definitely interested in this. Making a new pack featuring SG and Evilcraft and was planning on using the blood chest to repair gear.

**Comment by rubensworks** [comment]
PRs are welcome, as I won't have time for implementing this myself anytime soon.

**Comment by GamertechAU** [comment]
Silent Gems are now compatible with the blood chest.

**Comment by rubensworks** [comment]
Oh, neat. I forgot I exposed an API for that.

SilentGems commit for reference: https://github.com/SilentChaos512/SilentGems/commit/40b307e0a3876e1f2473145a7180be9f7741d007
