### ISSUE TITLE
Vengence Pickaxe has Smelting III instead of Vengence III

### ISSUE THREAD

**Issue by Alan19** [rubensworks/EvilCraft#719]
#### Issue type:

- :bug: Bug

____

#### Short description:

After changing the enchantment levels of the vengence pickaxe to Vengence III and Fortune III, the vengence pickaxe and Smelting III when crafted

#### Expected behaviour:

The Vengence Pickaxe has Vengence III and Fortune III when crafted
____

#### Versions:

- This mod: 1.12.2-0.10.61
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2739

#### Log file:

https://paste.ee/p/C6mZv

**Comment by rubensworks** [comment]
Your description is not clear to me.

How did you change the enchantment levels? Through configuration, or in-game?

**Comment by Alan19** [comment]
Through the configuration I believe. 

https://github.com/belathus/Wanderlust-Renewed/blob/master/config/evilcraft.cfg

<blockquote><img src="https://avatars2.githubusercontent.com/u/3826783?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/belathus/Wanderlust-Renewed">belathus/Wanderlust-Renewed</a></strong></div><div>Wanderlust-Renewed - Minecraft 1.12.2 Modpack focused on exploration</div></blockquote>

**Comment by rubensworks** [comment]
Have any enchantments been added to the game in the meantime?

Can you try starting a new world?

Which mod adds this smelting enchantment? Can you try removing/disabling it and see what happens?

The MC registries tend to get messed up when changing enchantments.

**Comment by Alan19** [comment]
DungeonTactics adds the smelting enchantment, I'll check if removing it helps later.

**Comment by Alan19** [comment]
Removing DungeonTactics makes Vengence Pickaxes in new worlds have curse of vengeance III while old worlds have only the fortune enchantment.

**Comment by rubensworks** [comment]
Ok, then it sounds like the MC enchantment registry issue.
This is not an issue with this mod, but simply an issue with MC's enchantment registries.
Perhaps this will be fixed in Forge in 1.13.

Until this is fixed, avoid adding mods that add enchantments to existing worlds.
