### ISSUE TITLE
White list after black list for Blood stained blocks

### ISSUE THREAD

**Issue by CaptainSilver** [rubensworks/EvilCraft#721]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Exactly what the title says. If this mod is in a kitchen sink pack it can be incredibly difficult to blacklist all the blocks that Blood stained messes up. If we were to say have a black list that is checked then a white list that is checked we could do something list this.

# The blacklisted and Whitelisted blood stained blocks, by blockState name. (Checks Blacklist first then Whitelist. Whitelist disabled by default) (Java regular expressions are allowed)
    S:blood_stained_block.blockBlacklist <
        minecraft:redstone_lamp
        minecraft:crafting_table
        
     >
     S:blood_stained_block.blockWhitelist <
        minecraft:*
     >

That would remove all interaction with other mod blocks and help modpack authors, greatly improving compatibility.

Just an instance of where it causes issues is when a colossal chest block become blood stained it removes all contents of the colossal chest and break it.

Thanks in advance.

**Comment by CaptainSilver** [comment]
Added readability test to example code.

**Comment by rubensworks** [comment]
Sure, why not.

> Just an instance of where it causes issues is when a colossal chest block become blood stained it removes all contents of the colossal chest and break it.

Note to self: look into this, as this _should_ not be able to happen.

**Comment by CaptainSilver** [comment]
I was just giving a shot trying to add it, I've been trying to break into modding for minecraft.

**Comment by rubensworks** [comment]
Sounds great, PRs are welcomed :-)

**Comment by belathus** [comment]
I'm told that a spirit furnace can be broken by blood-stained blocks, as well.

**Comment by MentalMouse** [comment]
See also #749, where RW is seeking a less finicky solution.
