### ISSUE TITLE
Bound Blood drop has new wierdnesses for capacity.

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#722]
#### Issue type:

- :bug: Bug
____

#### Short description:

My Bound Blood Drop now shows a maximum capacity of a fixed 5,000, regardless of its actual content. 

With my actual limit of nearly a million, that has its "durability" bar running clear off the screen.  For what should be obvious reasons, that prevents me from using the BBD to top off my LP network.

[Screenshot](https://www.dropbox.com/s/iuu0ip969k0dv92/Blood%20drip%202018-08-13.png?dl=0)

#### Steps to reproduce the problem:

1. Set up Blood Magic and EvilCraft.
2. Make a Bound Blood Drop and bind it to the player.
3. The Apprentice player's LP network is 5k, so upgrade to a higher orb and bind that.  Optionally upgrade your Infuser a bit and put some blood into that.
3. Load LP into the LP network, over 5k but you don't need to fill it entirely.
4. Examine the BBD in your inventory.

#### Expected behaviour:
The maximum capacity of the Bound Blood Drop should track the maximum capacity of the associated LP network.  (Watch out for the Creative Orb with its infinite capacity.)

If you instead _want_ a BBD to be fixed to the capacity of the orb it was made with, you should document that behavior.
____

#### Versions:

- This mod:  0.10.62
- Minecraft: 1.12.2
- Forge: 2705
- Blood Magic:  2.2.12-97

**Comment by rubensworks** [comment]
What is your current orb tier?

I thought I tested all tiers and their corresponding capacities when testing this...

**Comment by MentalMouse** [comment]
Master (Tier 4).  Limit is a million.  As per JEI, there are two more tiers above that, though I'm not sure if Tier 6 is actually implemented.

**Comment by rubensworks** [comment]
You are certain that your orb and bound blood drop are linked to the same player, right?

Perhaps also try re-right clicking your master orb to make sure it is linked to you.

**Comment by MentalMouse** [comment]
I'm playing single-player, so yes they are linked to the same player.  I have been using the master orb extensively (I had in fact maxed out my LP network before using some of that), so it is most certainly linked to me.

**Comment by rubensworks** [comment]
Ok, then something must be wrong on my end.

Note to self: update to latest BM version, something may have changed in the BM API.

**Comment by MentalMouse** [comment]
I tried making a new BBD from another Weak Blood Orb (tier 1).  When I right-clicked it to bind it, it dropped a block of blood (!) and then gave the same display as the first one.

**Comment by MentalMouse** [comment]
Still the same in 0.10.63

**Comment by rubensworks** [comment]
Then you'll have to provide additional details, because at this point I can not reproduce your problem anymore. A video demonstrating the issue when starting in a clean world with only BM+EC installed would be great.

Are you sure that you're using the latest BM version?

**Comment by MentalMouse** [comment]
I certainly was using the latest at the time;  I've since updated to BloodMagic-1.12.2-2.3.3-101.jar along with the EC upgrade, and now I've got *more* trouble with the nexus of these two mods:   

*Something* is draining my LP network hard (thousands/second), and it is *also* draining blood out of the EC equipment in my inventory.  It's not clear if this is connected to my looking at the bound orb, but both of those are currently tucked into chests.  I also briefly activated a containment ritual, but that's not supposed to be drain anything unless it's pulling mobs, which it isn't.  My other rituals all show unset MRSs, which is an issue in itself.  

I'm not going to be able to set up any kind of testing environment until at least tonight or tomorrow, but I'll try then.

**Comment by MentalMouse** [comment]
OK, TehNut gave me a debug build that fixed the drain.  and explained the MRSs.  Right-clicking the BBD yields a blood block, and my Master Orb is bound to me and able to absorb blood from my altar.

But, my Bound Blood Drop is still showing 5,000 capacity.  This specifically prevents me from using my full Infuser to refill my newly-emptied LP network. :-(  (Hmm. I wonder if nodes can do it....)

**Comment by MentalMouse** [comment]
Argh.  Now, suddenly, the BBD is reporting correctly.  This happened after I flattened by LP, but I've done that before in this saga and it didn't happen then.  I'll post back here if it goes wonky again.  (The LP drain is playing hide-and-seek, but I think that's on BM's side.)

**Comment by rubensworks** [comment]
Ok, thanks for checking, be sure to let me know once you encounter the issue again.
