### ISSUE TITLE
Display stand crash

### ISSUE THREAD

**Issue by flamechair** [rubensworks/EvilCraft#725]
#### Issue type:

- :bug: Bug

____

#### Short description:

Display stand iterating over itemstacks causes server to have an internal error. It looks like the display stand tries to cast `net.minecraft.item.ItemAir` to `net.minecraft.item.ItemBlock`, which fails

#### Steps to reproduce the problem:

1. Reboot server
2. Join server
3. Observe stack trace

#### Expected behaviour:

____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.63
- Minecraft: 1.12.2
- Forge: 1.12.2 2705

#### Log file:

stacktrace: https://gist.github.com/iamtpage/b5f3f150f4bddf13e649c1e0981834c0
full log: https://gist.github.com/iamtpage/1cac13885542c1519e9db4defe50968d

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
