### ISSUE TITLE
Runic Dungeons Crashing

### ISSUE THREAD

**Issue by TrisRV** [rubensworks/EvilCraft#729]
Runic Dungeons is crashing

I'm running a small RPG style minecraft server to play with my friends and I have the Runic Dungeons mod installed. This mod is crashing my server and tells me that there's a duplicated ID. I've been searching for this ID but I couldn't find it.

- This mod: Runic Dungeons
- Minecraft: 1.7.10
- Forge: 1.7.10-10.13.4.1566-1.7.10-

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 20/09/18 04:52 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: ID is already registered: 35
	at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:94)
	at net.minecraft.entity.EntityList.func_75614_a(EntityList.java:108)
	at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:251)
	at mrcomputerghost.runicdungeons.proxy.CommonProxy.registerRenderInformation(CommonProxy.java:8)
	at mrcomputerghost.runicdungeons.RunicDungeons.init(RunicDungeons.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3618381360 bytes (3450 MB) / 4267704320 bytes (4070 MB) up to 4267704320 bytes (4070 MB)
	JVM Flags: 4 total; -Xms1G -Xmx8G -Xmx4096m -Xms4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 155 mods loaded, 155 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
	UCHI	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCHI	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHI	ivtoolkit{IvToolkit} [1.2] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHI	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHI	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHI	ExtendedPotions{1.1} [Extended Potions] (ExtendedPotions-MC1.7.10-1.1.jar) 
	UCHI	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHI	dynamicswordskills{1.7.10-1.7} [Dynamic Sword Skills] (1.7.10-dynamicswordskills-1.7.jar) 
	UCHI	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UCHI	SC0_SpaceCore{0.7.10} [SpaceCore] (1.7.10-SpaceCore-0.7.10.jar) 
	UCHI	SC0_UsefulPets{1.3} [Useful Pets] (1.7.10-Useful_Pets-1.3.jar) 
	UCHI	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHI	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
	UCHI	ClothingCraft{1.2.1} [ClothingCraft] ([1.7.10] ClothingCraft 1.2.1.jar) 
	UCHI	lotr{Beta v29.6 for Minecraft 1.7.10} [The Lord of the Rings Mod] ([1.7.10] The Lord of the Rings Mod B29.6.jar) 
	UCHI	Trapcraft{v2.2.1a} [Trapcraft] ([1.7.10] Trapcraft - v2.3.0a.zip) 
	UCHI	heart{2.0.0} [Heart Health] ([MC1.7.X]Hearts-2.0.0.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHI	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCHI	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHI	AetherAspects{Alpha 1.7.10-1.2} [Aether Aspects] (AetherAspects-1.7.10-1.2.jar) 
	UCHI	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) 
	UCHI	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHI	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHI	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHI	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHI	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHI	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHI	antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-1.3.5-1.7.10.jar) 
	UCHI	antiqueatlas{4.0.1a-1.7.10} [Antique Atlas] (antiqueatlas-4.0.1a-1.7.10.jar) 
	UCHI	Artifacts{1.1.3} [Artifacts] (Artifacts-1.1.3.jar) 
	UCHI	atum{0.6} [Atum] (Atum-1.7.10-0.6.60.jar) 
	UCHI	Automagy{0.26.2} [Automagy] (Automagy-1.7.10-0.26.2.jar) 
	UCHI	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHI	chocolateQuest{1.0} [Chocolate Quest] (Better-Dungeons-Mod-1.7.10.jar) 
	UCHI	betterstorage{0.10.5.119} [BetterStorage] (BetterStorage-1.7.10-0.10.5.119.jar) 
	UCHI	BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
	UCHI	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHI	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHI	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHI	malisiscore{1.7.10-0.13.1} [MalisisCore] (malisiscore-1.7.10-0.13.1.jar) 
	UCHI	malisisdoors{1.7.10-1.12.2} [Malisis' Doors] (malisisdoors-1.7.10-1.12.2.jar) 
	UCHI	BigDoors{1.7.10-1.0.0} [Big Doors] (BigDoors-1.7.10-1.0.0.jar) 
	UCHI	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHI	Botania{r1.7-237} [Botania] (Botania r1.7-237.jar) 
	UCHI	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) 
	UCHI	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHI	chisel{2.9.4.10} [Chisel] (Chisel-2.9.4.10.jar) 
	UCHI	convenientrecipes{1.3.1} [Convenient Recipes] (ConvenientRecipes-1.7.10-1.3.1.jar) 
	UCHI	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHI	Cyan Warrior Swords Mod{2.1.1} [Cyan Warrior Swords Mod] (Cyan_Warrior_Swords_Mod_v.2.1.1.jar) 
	UCHI	DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar) 
	UCHI	props{1.11} [Decocraft] (Decocraft-v1.11_1.7.10.jar) 
	UCHI	decorativemarble{Beta 1.1710.3} [Decorative Marble] (decorativemarble-1.1710.3.jar) 
	UCHI	decorativechimney{Beta 1.1710.3} [Decorative Chimney] (decorativechimney-1.1710.3.jar) 
	UCHI	Ding{MC1.7.10} [Ding] (Ding-MC1.7.10.jar) 
	UCHI	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
	UCHI	dungeonmobs{4.1.3} [Dungeon Mobs] (Dungeon-Mobs-Mod-1.7.10.jar) 
	UCHI	dungeonpack{1.7.10-1.0} [Dungeon Pack] (Dungeon-Pack-Mod-1.7.10.jar) 
	UCHI	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHI	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) 
	UCHI	Steamcraft{0.28.7} [Flaxbeard's Steam Power] (FlaxbeardsSteamPower.jar) 
	UCHI	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (ForbiddenMagic.jar) 
	UCHI	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) 
	UCHI	FTBL{1.0.18.2} [FTBLib] (FTBLib-1.7.10-1.0.18.3.jar) 
	UCHI	FTBT{1.0.2} [FTB Tweaks] (FTBTweaks-1.0.2.jar) 
	UCHI	FTBU{1.0.18.2} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.3.jar) 
	UCHI	gadomancy{1.0.6.1} [Gadomancy] (gadomancy-1.7.10-1.0.6.3.jar) 
	UCHI	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (Grimoire-of-Gaia-3-Mod-1.7.10.jar) 
	UCHI	Growthcraft{1.7.10-2.6.2} [Growthcraft] (growthcraft-1.7.10-2.6.2-complete.jar) 
	UCHI	Growthcraft|Cellar{1.7.10-2.6.2} [Growthcraft Cellar] (growthcraft-1.7.10-2.6.2-complete.jar) 
	UCHI	Growthcraft|Apples{1.7.10-2.6.2} [Growthcraft Apples] (growthcraft-1.7.10-2.6.2-complete.jar) 
	UCHI	Growthcraft|Bamboo{1.7.10-2.6.2} [Growthcraft Bamboo] (growthcraft-1.7.10-2.6.2-complete.jar) 
	UCHI	Growthcraft|Bees{1.7.10-2.6.2} [Growthcraft Bees] (growthcraft-1.7.10-2.6.2-complete.jar) 
	UCHI	Growthcraft|Fishtrap{1.7.10-2.6.2} [Growthcraft Fishtrap] (growthcraft-1.7.10-2.6.2-complete.jar) 
	UCHI	Growthcraft|Grapes{1.7.10-2.6.2} [Growthcraft Grapes] (growthcraft-1.7.10-2.6.2-complete.jar) 
	UCHI	Growthcraft|Hops{1.7.10-2.6.2} [Growthcraft Hops] (growthcraft-1.7.10-2.6.2-complete.jar) 
	UCHI	Growthcraft|Milk{1.7.10-2.6.2} [Growthcraft Milk] (growthcraft-1.7.10-2.6.2-complete.jar) 
	UCHI	Growthcraft|Rice{1.7.10-2.6.2} [Growthcraft Rice] (growthcraft-1.7.10-2.6.2-complete.jar) 
	UCHI	gud_thaumicnei{1.3.0} [Thaumic NEI] (gud_thaumicnei-1.3.0.jar) 
	UCHI	HardcoreEnderExpansion{1.8.2} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.2.jar) 
	UCHI	HoloInventory{1.9.0.106} [HoloInventory] (HoloInventory-1.7.10-1.9.0.106.jar) 
	UCHI	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) 
	UCHI	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHI	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHI	levels{r2.3.0} [Levels] (Levels-r2.3.0.jar) 
	UCHI	magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops] (magicalcrops-4.0.0_PUBLIC_BETA_3.jar) 
	UCHI	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHI	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHI	minefantasy2{Alpha_2.4.4} [MineFantasyII] (MineFantasyII-2.4.4.jar) 
	UCHI	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (Mo-Creatures-Mod-1.7.10.zip) 
	UCHI	MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment-4.0.0.jar) 
	UCHI	MoreBows2{1.0.1} [More Bows 2] (More-Bows-2-Mod-1.7.10.jar) 
	UCHI	Mystcraft{0.12.3.02} [Mystcraft] (mystcraft-1.7.10-0.12.3.02.jar) 
	UCHI	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHI	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) 
	UCHI	recipehandler{0.2} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.2(1.7.10).jar) 
	UCHI	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHI	primitivemobs{1.0} [Primitive Mobs] (Primitive-Mobs-Mod-1.7.10.jar) 
	UCHI	recallstones{0.4.16} [Recall Stones] (RecallStones-1.7.10-0.4.16.jar) 
	UCHI	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHI	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCHI	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) 
	UCHI	Roguelike{1.5.0} [Roguelike Dungeons] (Roguelike-Dungeons-Mod-1.7.10.jar) 
	UCHI	ropebridge{1.3} [Rope Bridge] (RopeBridge-v1.3-mc1.7.10.jar) 
	UCHI	RopesPlus{1.6.3} [Ropes+] (RopePlus-1.7.10.jar) 
	UCHI	RPGAdvMod{1.0.0} [RPGAdvMod] (RPGAdvMod-1.0.0_1.7.10.jar) 
	UCHI	AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHE	runicdungeons{1.1.7b} [Runic Dungeons] (RunicDungeons-1.1.7b.jar) 
	UCHI	secretroomsmod{4.7.1} [The SecretRoomsMod] (SecretRoomsMod.jar) 
	UCHI	spacore{01.05.12} [SpACore] (SpACore-1.7.10-01.05.12.jar) 
	UCHI	SpecialMobs{3.2.2} [Special Mobs] (Special-Mobs-Mod-1.7.10.jar) 
	UCHI	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHI	StatusEffectHUD{1.27} [StatusEffectHUD] (StatusEffectHUD.jar) 
	UCHI	StorageDrawers{1.7.10-1.4.6} [Storage Drawers] (StorageDrawers-1.7.10-1.4.6.jar) 
	UCHI	TaintedMagic{1.1.6.4} [Tainted Magic] (TaintedMagic-1.1.6.4.jar) 
	UCHI	tcinventoryscan{1.0.11} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.11.jar) 
	UCHI	tcnodetracker{1.1.2} [TC Node Tracker] (tcnodetracker-1.7.10-1.1.2.jar) 
	UCHI	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHI	TextureGeneratorLib{0.2} [TextureGeneratorLib] (TextureGeneratorLib-1.7.10_vBeta2.jar) 
	UCHI	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHI	thaumicdyes{1.10.3} [Thaumic Dyes] (Thaumic-Dyes-[1.7.10]+1.10.3-0.jar) 
	UCHI	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration.jar) 
	UCHI	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCHI	thebetweenlands{1.0.6-alpha} [The Betweenlands] (TheBetweenlands-1.0.6-alpha-universal.jar) 
	UCHI	erebus{0.4.5} [Erebus] (TheErebus-0.4.5.jar) 
	UCHI	thirstmod{1.8.8} [Thirst Mod] (thirstmod-1.8.8.jar) 
	UCHI	throwabletorchmod{1.3} [ThrowableTorchMod] (ThrowableTorchMod-1.7.10-1.3.jar) 
	UCHI	totemic{1.7.10-0.6.2} [Totemic] (Totemic-1.7.10-0.6.2.jar) 
	UCHI	TownBuilder{1.0.0-Build8} [Town Builder] (Town-Builder.jar) 
	UCHI	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHI	WarpTheory{1.7.10R1.0} [WarpTheory] (WarpTheory-1.7-1.0-24.jar) 
	UCHI	weaponcaseloot{1.2.12} [WeaponCaseLoot] (weaponcaseloot-1.2.12.jar) 
	UCHI	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCHI	witchery{0.24.1} [Witchery] (Witchery.jar) 
	UCHI	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCHI	WTFCore{1.7} [WhiskyTangoFox's Core] (WTFCore-1.7.10_v1.7.jar) 
	UCHI	CaveBiomes{1.6} [WhiskyTangoFox's CaveBiomes] (WTFCaveBiomes-1.7.10_v1.6.jar) 
	UCHI	yegamolchattels{1.1.1.1} [Ye Gamol Chattels] (YeGamolChattels-1.1.1.1.jar) 
	UCHI	JustAnotherSpawner{0.16.19} [Just Another Spawner] (Just-Another-Spawner-Mod-1.7.10.jar) 
	UCHI	NEI-Mystcraft-Plugin{02.01.09} [NEI Mystcraft Plugin] (MystNEI-Plugin-1.7.10-02.01.09.jar) 
	CoFHCore: -[1.7.10]3.0.3-303
	Mantle Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	SpACore ASM Transformers: 
		GLStateManager: false
		GLStateManager debug output: false
		Debug screen replacer: true
	TConstruct Environment: Environment healthy.
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by rubensworks** [comment]
Sorry, we don't maintain 1.7.10 anymore. In any case, this looks like an issue in RunicDungeons.
