### ISSUE TITLE
Entangled chalice provides infinite fluid

### ISSUE THREAD

**Issue by LemADEC** [rubensworks/EvilCraft#730]
#### Issue type:

- :bug: Bug

____

#### Short description:

You get infinite quantity of a given fluid when an Entangled chalice and a Dark tank are both set to autosupply.

#### Steps to reproduce the problem:

1. place a dark tank, fill it with 1 bucket worth of a fluid (water, poison, blood, ...)
2. break the dark tank, sneak right click to set it to autofill, move it to hotbar slot 2
3. get an entangled chalice in hotbar slot 1, sneak right click to omnifill
4. while chalice is selected, both chalice and dark tank will fill completely with the original fluid

#### Expected behaviour:

Total quantity of fluid between containers should remains constant
____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.63
- Minecraft: 1.12.2
- Forge: 14.23.4.2759

#### Log file:

n/a

**Comment by rubensworks** [comment]
That's not good, thanks for reporting!
