### ISSUE TITLE
Crash on loading the pack if dark_gem is set to false

### ISSUE THREAD

**Issue by jinkhya** [rubensworks/EvilCraft#731]
#### Issue type:

- :bug: crash

____

#### Short description:

The pack is crashing on loading every time

#### Steps to reproduce the problem:

Install just forge 2759, evilcraft CyclopsCore-1.12.2-0.11.10 and EvilCraft-1.12.2-0.10.63
Turn B:dark_gem to false in "# If this item should be injected in loot tables.." section

#### Expected behaviour:
Not crashing :)

____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.63
- Minecraft: 1.12.2
- Forge: 2759

#### Log file:
https://pastebin.com/Qz5R3WmX

**Comment by jinkhya** [comment]
B:dark_spike=false also crashes

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by jinkhya** [comment]
thanks ! much appreciated.
