### ISSUE TITLE
Crash on entering nether

### ISSUE THREAD

**Issue by birduvprey** [rubensworks/EvilCraft#732]
#### Issue type:

- :bug: Bug

____

#### Short description:

Upon entering nether client crashes to crash report screen.

#### Steps to reproduce the problem:

1. Attempt to enter nether

#### Expected behaviour:

Enter nether

____

#### Versions:

- This mod: 1.12.2-0.10.63
- Minecraft: 1.12.2
- Forge: 14.23.4.2758

#### Log file:

https://pastebin.com/rs2EQwaK

**Comment by rubensworks** [comment]
Fixed in https://github.com/CyclopsMC/EvilCraft/commit/57b236b82bdf7e6e69dc50d09e43ba9ff5f3cfed
