### ISSUE TITLE
Blood-stained block related crash in the Twilight Forest

### ISSUE THREAD

**Issue by belathus** [rubensworks/EvilCraft#733]
#### Issue type:

- :bug: Bug

____

#### Short description:

I logged off the server for the night last night in the Twilight Forest. Logging back into the server the next day caused this crash. I was in an enchanted forest in the Twilight Forest, so it might've been trying to render a TF block that'd be found there, but I honestly have no idea which block that'd be. I was able to log into the server by moving my player out of the Twilight Forest, though I have not tried going back to the area.

#### Steps to reproduce the problem:
1. Cover random twilight forest blocks with blood?
2. I wish I could help more here; I honestly have no idea which block it was trying to render.

#### Expected behaviour:

____

#### Versions:
- This mod: 1.12.2-0.10.63
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2760

#### Log file:
https://paste.dimdev.org/ayadupayuf.mccrash

**Comment by rubensworks** [comment]
Seems to be the same crash as #732, so I'm closing this issue in favor of that one.

Strange that this crash starts appearing now though...
Maybe something has changed in Forge recently.

**Comment by belathus** [comment]
We're playing on the same modpack and server. I couldn't see his crash report, as Pastebin reported it as expired. Sorry about duplicating the report, though.
