### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by MelanX** [rubensworks/EvilCraft#734]
#### Issue type:

- :heavy_plus_sign: Feature request

Turn off (complete) ore generation in config with just one line.
____

#### Short description:

It could be nice for modpacks with a normal world generation or something like Skylands. You could just add a boolean for that. Would be very nice :)

**Comment by rubensworks** [comment]
You should be able to disable dark ore, dark temple and undead tree generation separately. Does this work for you?

For the sake of avoiding bugs to to complexity, I prefer not to add a config option to disable all of them at once. 3 isn't that much :-)
