### ISSUE TITLE
Weird spelling for the Burning Gem_stone

### ISSUE THREAD

**Issue by Lykrast** [rubensworks/EvilCraft#735]
#### Issue type:

- :bug: Typo

____

#### Short description:

The Burning Gem_stone is weirdly named and seems like a typo.

#### Expected behaviour:

Burning Gemstone or Burning Gem Stone.

____

#### Versions:

- This mod: 0.10.63

**Comment by rubensworks** [comment]
Seems like a typo indeed, thanks for reporting!
