### ISSUE TITLE
Dark Temple Generation

### ISSUE THREAD

**Issue by MelanX** [rubensworks/EvilCraft#738]
#### Issue type:

- :bug: Bug

____

#### Short description:

I set Dark Temple generation to 1.
This means every chunk has a Dark Temple. I entered a world: I saw no Dark Temple. Only far away.

#### Steps to reproduce the problem:

1. set Dark Temple generation to 1
2. Generate a new world
3. be impressed

#### Expected behaviour:

Every chunk a Dark Temple

____

#### Versions:

- This mod: 0.10.64
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

#### Log file:

https://pastebin.com/qrjJUb2q
Maybe you could need it

**Comment by rubensworks** [comment]
You should also change `darkTempleMinimumChunkDistance `, can you try that?

**Comment by MelanX** [comment]
Oh... I didn't saw it... it works fine, thank you :D
