### ISSUE TITLE
Can't find recipe for Crushed Dark Gem

### ISSUE THREAD

**Issue by Daenyth** [rubensworks/EvilCraft#739]
#### Issue type:

- :bug: I can't find a recipe for crushed dark gem - there doesn't seem to be a way to make it, and the book only mentions that it exists, there's no mention of how to craft it

____

#### Steps to reproduce the problem:

1. Read book to see if there's a recipe
2. Search JEI for a recipe
3. Unable to locate one

#### Expected behaviour:

I'd like to be able to craft it
____

#### Versions:

- This mod: 0.10.64
- Minecraft: 1.12
- Forge: 14.23.5.2768

#### Log file:

NA

**Comment by rubensworks** [comment]
You obtain it when mining Dark Ore with a fortune pickaxe, doesn't it mention that?

**Comment by Daenyth** [comment]
Ahh, no I missed that - I thought you only could get dark gems that way, not the crushed ones.

**Comment by MentalMouse** [comment]
I thought there was also an option to craft a dark gem with a spike?

**Comment by Daenyth** [comment]
I didn't see a crafting recipe for that.

It also occurs to me that I didn't see the mining recipe even though I have Just Enough Resources installed - that's weird. Perhaps it's because fortune is required?

**Comment by MentalMouse** [comment]
Hm, and I don't see an option for it.  It might have been something I hacked in with CraftTweaker last game.  Anyway, getting Fortune is easy enough once you've got diamonds -- just make a Vengance Pickaxe and start purifying it.
