### ISSUE TITLE
Box of Eternal Closure has crashed my game 

### ISSUE THREAD

**Issue by Kvarsten** [rubensworks/EvilCraft#740]
#### Issue type:

- :bug: Bug

____

#### Short description:

When I place the Box of Eternal Closure the game freezes and crashes.

#### Steps to reproduce the problem:

1. Place the Box of Eternal Closure

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2772

#### Log file:

[minecraft_crash.txt](https://github.com/CyclopsMC/EvilCraft/files/2583532/minecraft_crash.txt)

I think that works?

**Comment by rubensworks** [comment]
You are using a very outdated version of the mod, please update and report back if the issue persists.
