### ISSUE TITLE
Crash when looking at Endstone uses in JEI

### ISSUE THREAD

**Issue by hayesj1** [rubensworks/EvilCraft#743]
#### Issue type:
- :bug: Bug

____

#### Short description:
Game crashes when viewing uses of endstone in JEI. I posted this in [Chisel-Team/ConnectedTexturesMod](https://github.com/Chisel-Team/ConnectedTexturesMod) because downgrading that mod fixed the issue, but they directed me over here.

#### Steps to reproduce the problem:
1. Press the hotkey to view of the uses of a block/item, while hovering over endstone
2. Crash to desktop

#### Expected behaviour:
Recipes using endstone should have been displayed.

____

#### Versions:
Evilcraft: 1.12.2-0.10.64
This Mod:1.12.2-0.11.11
Minecraft: 1.12.2
Forge: 1.12.2-14.23.5.2784

#### Log file:
Lastest Log (Too big for Pastebin):
https://www.dropbox.com/s/p0egxc3uqmd9xm7/latest.7z?dl=0

Crash:
https://pastebin.com/vqBWMh5Q

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by ate0ate** [comment]
I have been experiencing this crash as well and was wondering if there has been any success in tracking down the cause? I most recently crashed when looking up endstone uses as mentioned above, but I have had crashes prior to that using JEI for other recipe look-ups also. It seems to happen whenever this Broompart item is rendered in any way. I'm using forge 14.23.5.2807 currently but have been encountering this crash for about a month now throughout various forge/JEI versions. Thank you for looking into the matter and I will leave my crash report here as well in case it may prove useful...
https://pastebin.com/S06synA5

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/S06synA5">CCL/EvilCraft Crash - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Sorry, haven't been able to look into this. Thanks for sharing your crashlog!
