### ISSUE TITLE
NPE Rendering Block Entity with the Entangled Chalice

### ISSUE THREAD

**Issue by Algester** [rubensworks/EvilCraft#744]
#### Issue type:

- :bug: Null Pointer Exception: Rendering Block Entity?

____

#### Short description:
It's your standard Crash when it comes to Null Pointer Exception

#### Steps to reproduce the problem:

1. have a Pair of Entangled Chalice (My Current Setup has 1 for liquid XP and the other for Blood)
2. just use them
3. Wait for the crash

#### Expected behaviour:

This is already my Third? crash pertaining to Long distance transferring of fluids at least its not a world crashing Excessive Tick Loop from the Ender Tanks from Enderstorage mod. 
____

#### Versions:

- This mod: EvilCraft 0.10.64
- Minecraft: Minecraft 1.12.2
- Forge: Forge 14.23.5.2768

#### Log file:

https://pastebin.com/ULNVm9vt <- First Crash Log
https://pastebin.com/a2whVAKX <- Second Crash Log

**Comment by rubensworks** [comment]
For some reason, the fluid has been corrupted then...

I'll look into catching those edge-cases.
