### ISSUE TITLE
Poisonous libelle infestation, strange config effects

### ISSUE THREAD

**Issue by Normal69** [rubensworks/EvilCraft#746]
#### Issue type:
- :bug: Bug
____

#### Short description:

After disabling libelles, they still spawn as unkillable "unknown" entities after server restart (and /fml confirm).

#### Steps to reproduce the problem:

1. Run the server with base config
2. notice libelle accumulation with LagGoogles
3. switch off libelle generation, restart - B:poisonous_libelle.isEnabled=false
4. notice libelles transformed to "unknown" unkillable entities still spawning
5. set minimum spawn height to 240, enable libelles:
   B:poisonous_libelle.isEnabled=true
   I:poisonous_libelle.minY=240
6. enjoy libelles not spawning anymore

#### Expected behaviour:

After disabling libelles they do not spawn.

____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.64.jar
- Minecraft: 1.12.2
- Forge: Forge Mod Loader version 14.23.5.2796 for Minecraft 1.12.2

#### Log file:
Not applicable yet.
Current evilcraft config is: https://pastebin.com/wVaVDeHd

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
I can't seem to reproduce this issue myself.
Disabling them completely disables the spawning of them.

I did notice that you have the following line in your config though:
```
B:poisonous_libelle.isEnabled=true
```

Perhaps you made a mistake there?

The unknown entities that were still remaining from before the libelle was disabled is something that Forge does, can't do anything about that on my end unfortunately.

**Comment by Normal69** [comment]
Indeed, that's why I had to leave that option "true".
Otherwise those unkillable unknowns infested me, even when I've /butcher-ed them, and restarted the server.
So it is a forge thing, no problemo then. ;)

Thank you!
