### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by Sunconure11** [rubensworks/EvilCraft#748]
#### Issue type:

- :bug: Bug

____

#### Short description:

A seemingly rare crash that fired out of nowhere.

#### Steps to reproduce the problem:

I legitimately don't know.

#### Expected behaviour:

Well, this to not fire.

____

#### Versions:

- This mod: 1.12.2-0.11.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2807

#### Log file:

https://paste.dimdev.org/eceqatupoy.mccrash

**Comment by Sunconure11** [comment]
It appears to be an evilcraft issue.

**Comment by rubensworks** [comment]
Seems to be the same problem as #748, thanks for reporting in any case!
