### ISSUE TITLE
Blood extractor in offhand deletes items

### ISSUE THREAD

**Issue by CaptPanda** [rubensworks/EvilCraft#750]
Modpack: All the Magic (All the mods)
Where: Multiplayer server

If you place the Blood Extractor in your offhand in auto-supply mode, it replaces the first item in the hotbar with an identical blood extractor. Removing either one from their slot makes the other blood extractor disappear.

From what I can tell it voids any item in the first slot of the hotbar. Hopefully this can be addressed.

**Comment by rubensworks** [comment]
Please use the proper issue template. I suspect you're not using the latest version.

**Comment by CaptPanda** [comment]
Issue type:
bug Bug
Short description:
If you place the Blood Extractor in your offhand in auto-supply mode, it replaces the first item in the hotbar with an identical blood extractor. Removing either one from their slot makes the other blood extractor disappear.

If you deactivate them both before moving them, then the blood extractor gets duplicated.

Steps to reproduce the problem:
Placing Blood Extractor in offhand and activating auto-supply mode

Expected behaviour:
Items to not be deleted/duplicated

Versions:
This mod: 0.10.64
Minecraft: 1.12.2
Forge: 2808

**Comment by rubensworks** [comment]
Could you update to the latest EC and CyclopsCore versions first to confirm that the issue still occurs for you?

**Comment by CaptPanda** [comment]
I have updated both mods, and the game crashes during startup.

https://pastebin.com/E2WvmSBx

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/E2WvmSBx">---- Minecraft Crash Report ----    WARNING: coremods are present:    RBLoadingP - Pastebin.com</a></strong></div></blockquote>

**Comment by CaptPanda** [comment]
Have created new instance with newest version of both mods, Duplication issue still persist.

**Comment by rubensworks** [comment]
Will look into it, thanks for checking!
