### ISSUE TITLE
weird rendering issue while reading origins of darkness

### ISSUE THREAD

**Issue by freopt** [rubensworks/EvilCraft#753]
Rendering bug

#### Short description:

When reading origins of darkness the outside world renders weird. It goes back to normal if you hover over an item or close the book. video:https://imgur.com/a/m2y40mj

#### Steps to reproduce the problem:

1.Open origins of darkness. 
2.See that the world looks weird. 
3.Hover over an item and see that it is fixed.
#### Expected behaviour:

No rendering issue.

#### Versions:

- This mod: 0.10.68
- Minecraft: 1.12.2
- Forge: 14.23.5.2808

**Comment by freopt** [comment]
After posting: This bug only seems to happen on pages that show recipes

**Comment by rubensworks** [comment]
It's weird that you're only having the issue when tooltips are being rendered. This makes me think that another mod is causing this, as I can not reproduce this myself in a clean environment.

In any case, I will add a safety in the next CyclopsCore update. If that wouldn't fix the issue for you, let me know, and we can discuss further steps to resolve this.

**Comment by freopt** [comment]
Problem still  occurs after updating

**Comment by rubensworks** [comment]
@freopt Can you check if it still occurs after removing all non-cyclops mods?
