### ISSUE TITLE
Broken strings in the settings

### ISSUE THREAD

**Issue by Regnander** [rubensworks/EvilCraft#755]
#### Issue type:

- :bug: Bug

____

#### Short description:

Some strings in the settings are displayed as addresses instead of text, making it hard to tell what they represent.

#### Steps to reproduce the problem:

1. Open the configuration menu for EvilCraft
2. Select either the Degradition Effect, Item, World Generation, Machine or Enchanting settings
3. Look on the left side of the screen to see addresses instead of the name of the settings in some places

#### Expected behaviour:

Some strings in en_us.lang are unused and are supposed to be used in the settings, while some settings are lacking a string in said file and are displayed as string addresses that lead nowhere.

The unused strings in the lang file can be fixed by adjusting the respective address, while the settings that are lacking a string needs to be added to the file.

##### Degradition effect settings
Broken string in-game | Unused string in en_us.lang
-|-
degradationeffect.evilcraft.knockbackdistort | degradationeffect.evilcraft.knockbackDistort
degradationeffect.evilcraft.mobspawn | degradationeffect.evilcraft.mobSpawn

##### Item settings
Broken string in-game | Unused string in en_us.lang
-|-
config.evilcraft.bloodPearl.slownessDuration | config.evilcraft.blood_pearl.slownessDuration
config.evilcraft.blood_extractor.autoFillBuckets | _Missing_
config.evilcraft.box_of_eternal_closure.injectLootTables | _Missing_
config.evilcraft.condensed_blood.injectLootTables | _Missing_
config.evilcraft.dark_tank.autoFillBuckets | _Missing_
config.evilcraft.ender_tear.injectLootTables | _Missing_
invigPendent.capacity (Full string address unknown) | ???
invigPendent.fireUsage (Full string address unknown) | ???
config.evilcraft.invigPendant.reduceDuration | config.evilcraft.invig_pendant.reduceDuration
config.evilcraft.invigPendant.usage | config.evilcraft.invig_pendant.usage
config.evilcraft.origins_of_darkness.injectLootTables | _Missing_
config.evilcraft.vengeance_pickaxe.fortuneLevel | _Missing_
config.evilcraft.vengeance_pickaxe.vengeanceLevel | _Missing_

##### World generation settings
Broken string in-game | Unused string in en_us.lang
-|-
config.evilcraft.general.evilDungeonDimensions | _Missing_

##### Machine settings
Broken string in-game | Unused string in en_us.lang
-|-
config.evilcraft.spirit_furnace.mobDrops | _Missing_

##### Enchanting settings
Broken string in-game | Unused string in en_us.lang
-|-
config.evilcraft.life_stealing.healModifier | _Missing_

____

#### Versions:

- This mod: 0.10.64
- Minecraft: 1.12.2
- Forge: 14.13.5.2814

#### Log file:

_None_

**Comment by rubensworks** [comment]
Thanks for the detailed report!
