### ISSUE TITLE
Suggestion: Shears from mods

### ISSUE THREAD

**Issue by raltus** [rubensworks/EvilCraft#757]
#### Issue type:

- :heavy_plus_sign: Feature request
Compatibility with shears from other mods.

____

#### Short description:

I was short on iron so I made copper shears from Thermal Expansion. When I tried to craft a dead bush it wouldn't work. Would it be possible to add compatibility for these shears?

**Comment by rubensworks** [comment]
As far as I can see, TE/TF doesn't add an oredict entry for their shears. This would require too much work for what it's worth, sorry.

I would suggest minetweaking the recipe in yourself for your pack.

**Comment by raltus** [comment]
No problem, thought it would be worth checking on. Played a bit with crafttweaker before, definitely less work to do it that way. Thanks for checking it.
