### ISSUE TITLE
More broken strings in the settings 

### ISSUE THREAD

**Issue by Regnander** [rubensworks/EvilCraft#758]
#### Issue type:

- :bug: Bug

____

#### Short description:

This is a continuation of #755, since new strings have been added and a few other strings were not fixed in the latest release.

#### Steps to reproduce the problem:

1. Open the configuration menu for EvilCraft
2. Select either the Item or Block settings
3. Look on the left side of the screen to see addresses instead of the name of the settings in some places

#### Expected behaviour:

I tried to locate the full addresses of the broken strings by fooling around with a `.lang` file in a resource pack, but unfortunately I only managed to find one single address.

##### Item settings
Broken string in-game | Unused string in en_us.lang
-- | --
~~bloodPearl.slownessDuration (Full address unknown)~~ | ~~config.evilcraft.blood_pearl.slownessDuration~~
~~bucket_eternal_water (Full address unknown)~~ | ~~_Missing_~~
~~invigPendent.capacity (Full address unknown)~~ | ~~config.evilcraft.invig_pendant.capacity~~
~~invigPendent.fireUsage (Full address unknown)~~ | ~~config.evilcraft.invig_pendant.fireUsage~~
~~invigPendant.reduceDuration (Full address unknown)~~ | ~~config.evilcraft.invig_pendant.reduceDuration~~
~~invigPendant.usage (Full address unknown)~~ | ~~config.evilcraft.invig_pendant.usage~~

##### Block settings
Broken string in-game | Unused string in en_us.lang
-- | --
~~block_blood (Full address unknown)~~ | ~~_Missing_~~
~~block_poision (Full address unknown)~~ | ~~_Missing_~~
config.evilcraft.blood_stained_block.blockWhitelist | _Missing_
~~hardened_blood (Full address unknown)~~ | ~~_Missing_~~
~~undead_leaves (Full address unknown)~~ | ~~_Missing_~~
~~undead_log (Full address unknown)~~ |~~_Missing_~~
~~undead_sapling (Full address unknown)~~ | ~~_Missing_~~
____

#### Versions:

- This mod: 0.10.70
- Minecraft: 1.12.2
- Forge: 14.23.5.2814

#### Log file:

_None_

**Comment by rubensworks** [comment]
Thanks for reporting!

The item issues _should_ be fixed though. Can you try resetting your config file?

**Comment by Regnander** [comment]
I removed the config file before running Minecraft and that did the trick! It seems like "config.evilcraft.blood_stained_block.blockWhitelist" is the only one that needs attention.

**Comment by rubensworks** [comment]
Thanks for checking. I'll update the "config.evilcraft.blood_stained_block.blockWhitelist" in a bit.
