### ISSUE TITLE
Broom Issue on server

### ISSUE THREAD

**Issue by MercuryAoD** [rubensworks/EvilCraft#770]
#### Issue type:

- :bug: Bug

____

#### Short description:

When log off riding a broom and re-login back in have creative flight enabled
#### Steps to reproduce the problem:

1, get on a broom
2. log off
3. log on
4. get off the broom

#### Expected behavior:

Not to have creative flight?
____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.72
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

**Comment by rubensworks** [comment]
Can you try reproducing this without any other mods installed? EC does not enable creative flight in any way, so I strongly assume that another mod is causing this.
