### ISSUE TITLE
Weather problems

### ISSUE THREAD

**Issue by HallowCheshire707** [rubensworks/EvilCraft#772]
#### Issue type:

- :bug: Bug

____

#### Short description:

The bug is a problem with the weather. The weather is locked to clear, even using commands to make rain doesn't work.

#### Steps to reproduce the problem:

1. Literally just play the game or use /weather rain 

#### Expected behaviour:

The weather does not change at all.

____

#### Versions:

- This mod: 0.10.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by rubensworks** [comment]
I doubt EC is causing this. Can you reproduce this without any other mods installed?
