### ISSUE TITLE
Promise of Productivity and Velocity can stack past 4 in a machine when Stackie is installed

### ISSUE THREAD

**Issue by Alan19** [rubensworks/EvilCraft#773]
#### Issue type:

- :bug: Bug

____

#### Short description:

When the Stackie mod is installed, promises dropped on the ground can stack past 4, allowing you to put more than 4 promises in a machine.

Related to this issue:
https://github.com/Lunatrius/Stackie/issues/13

#### Steps to reproduce the problem:

1. Have multiple stacks of promises in your inventory.
1. Drop the promises onto the floor.
1. Pick up promises to have them stack.
1. Put them into machines for lots of efficiency/speed.
#### Expected behaviour:

Promises shouldn't stack past 4 in a player's inventory and if they do, the machines should enforce the stack limit. Alternatively, there could be a config option to define how many promises can stack in a machine.

____

#### Versions:

- This mod: 0.10.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

#### Log file:

https://gist.github.com/Alan19/ad196e038ccfc4d7763644998833360e

**Comment by rubensworks** [comment]
It looks like that mod overrides max stack sizes, so there's not much I can do about it on my end.

**Comment by Alan19** [comment]
Is it possible to limit the max stack size of items in the machine upgrade slots like how the seared furnace limits stack sizes to 16?

**Comment by rubensworks** [comment]
Link to Stackie issue for reference: https://github.com/Lunatrius/Stackie/issues/13
