### ISSUE TITLE
Hardened Blood blocks don't turn into fluid when broken by botania bore lens and other automated breakers.

### ISSUE THREAD

**Issue by Dilnu** [rubensworks/EvilCraft#775]
#### Issue type:

- :bug: Bug

____

#### Short description:

When using automated breakers including: Botania bore lens and Crossroads Drill

#### Steps to reproduce the problem:

1. Place hardened blood block in front of a pulse mana spreader with a bore lens.
2. Trigger the spreader

#### Expected behaviour:

I'd expect a block of liquid blood.
Instead it destroys the hardened blood with no side effects.
____

#### Versions:

- CyclopsCore-1.12.2-0.11.10
- EvilCraft-1.12.2-0.10.63
- Minecraft: 1.12.2
- Forge: 14.23.4.2739

**Comment by rubensworks** [comment]
This is working as intended. Hardened Blood behaves the same as Ice blocks, which are also broken without side-effects with these mods. Only if Ice/Hardened Blood is being broken by (fake) players, then the side-effects will occur.

If you would like to see this behaviour changed, then it must be done in Botania and Crossroads by breaking blocks using a fake player, just like Integrated Tunnels does with it Player Simulator.
