### ISSUE TITLE
Phosphor conflict.

### ISSUE THREAD

**Issue by EightBlade** [rubensworks/EvilCraft#777]
#### Issue type:

- :bug: Bug

____

#### Short description:
Phosphor conflict, causing extreme lag.

#### Steps to reproduce the problem:

Not sure, seems random.

#### Expected behaviour:

No extreme stuttering.
____

#### Versions:

- This mod: Latest 1.12
- Minecraft: 1.12
- Forge: 14.23.5.2836

#### Log file:

https://pastebin.com/89iNfb4z

**Comment by rubensworks** [comment]
Wrong mod?

**Comment by kappa-maintainer** [comment]
The crash report is about an Ice and Fire conflict, the real conflict to EvilCraft is this:
jellysquid3/Phosphor#7

**Comment by rubensworks** [comment]
Oh, that something completely different though.

Note to self: https://pastebin.com/u5QKhrPm

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/u5QKhrPm">java.lang.ClassCastException: thaumcraft.common.tiles.essentia.TileSmelter canno - Pastebin.com</a></strong></div></blockquote>
