### ISSUE TITLE
Cannot use Box of Eternal Closure Containing a Ghast in spirit furnace

### ISSUE THREAD

**Issue by bombcat2015** [rubensworks/EvilCraft#781]
Issue description: Cannot use Box of Eternal Closure Containing a Ghast in spirit furnace.

"unable to cook" content size 1x3x1 required size 4x4x4

Steps to reproduce: Catch Ghast Vengeance Spirit in Box of Eternal Closure...put box in spirit furnace....(note: furnace is working with every other mob I've caught except this one, I have 10 boxes with 10 different mobs and the ghast is the only one not working).

Versions:
    Evilcraft: 0.10.70
    Minecraft: 1.12.2
    Forge: 14.23.5.2821

Using All the Mods: All the Magic (heavily modded version, but nothing relating to EvilCraft or Ghasts has changed in any way (that I'm aware of) I do not normally post these things as I tend to fix things myself but I cannot find a lot of information about 1.12.2 version of EvilCraft and have not been successful in my repair attempts thus far.  (You might get a laugh out of this, I posted this on McJty's Xnet github on accident and he was like, "wtf?")  lol

Relevant logs, if any: none

Love the mod, have a picture of what's occurring if you need it. Thanks!  Keep up the great work.

**Comment by rubensworks** [comment]
> "unable to cook" content size 1x3x1 required size 4x4x4

It sounds like your spirit furnace is simply too small. Have you tried making it have the inner size of 4x4x4?

> I cannot find a lot of information about 1.12.2 version of EvilCraft

Have you read the ingame book (Origins of Darkness)? All information is available in that.
