### ISSUE TITLE
Obscured glass not working

### ISSUE THREAD

**Issue by btd555** [rubensworks/EvilCraft#786]
#### Issue type:

- :bug: Bug

____

#### Short description:

Obscured glass is transparent as a dropped item, in my hand, or as particles after being broken, but I can’t see through it when it’s a placed block.
#### Steps to reproduce the problem:

1. Place obscured glass
2. Look at obscured glass

#### Expected behaviour:

Obscured glass can be seen through but does not allow the light level to pass through it, matching its description in the Origins of Darkness.
____

#### Versions:

- This mod: 0.10.77
- Cyclops Core: 1.5.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by rubensworks** [comment]
Are you using any other notable mods in your pack that may impact rendering?

**Comment by btd555** [comment]
Could not find an origin, but using a resource pack to give it a different texture seems to solve the problem.
