### ISSUE TITLE
Bound Blood Drop Capacity 

### ISSUE THREAD

**Issue by kjj194** [rubensworks/EvilCraft#788]
#### Issue type: 

- :bug: Bug

____

#### Steps to reproduce the problem: Get at least an apprentice blood orb and use it, then fill the bound blood drop, when you then use the weak blood orb it reverts the maximum to that blood orbs level.

1. ...

#### Expected behaviour: Capacity should be based on the highest tier used rather than the last tier used to avoid graphical weirdness of the capacity bar.

____

#### Versions:

- This mod: 1.12.2-0.10.77
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

**Comment by rubensworks** [comment]
It looks like the orb level changes are being done by BM itself, so there's not much I can do about that. But I can make it so that the capacity is never below the current contents level, so this should fix the graphical weirdness.
