### ISSUE TITLE
Doc: "down is to the left of the composer block" isn't helpful.

### ISSUE THREAD

**Issue by WazWaz** [rubensworks/EvilCraft#790]
#### Issue type:

- :bug: Bug

____

#### Short description:

Without knowing which way it's "facing", the "left" of the composer block doesn't mean anything. The visualization is rotating, so that's no clue.

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

"down/right [whichever is true] is the side with the composer block".

____

#### Versions:

- This mod: 0.10.77
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by rubensworks** [comment]
I have no idea what you are talking about. Are you sure you reported this to the correct mod repo?

**Comment by WazWaz** [comment]
Oops, Sorry, mixed up which part of my blood factory was what! It's a Soulus issue. Moved.
