### ISSUE TITLE
Inserting more than one Blood Cell in Blood Infuser couse Cells disappear.

### ISSUE THREAD

**Issue by mcwnuq** [rubensworks/EvilCraft#791]
#### Issue type:

- :bug: Bug

____

#### Short description:

Upon inserting more than one Blood Cell in Blood Infuser couse other Cells and blood disappear.
![image](https://user-images.githubusercontent.com/11915730/66708272-31c90380-ed4e-11e9-8a6b-745569ecec74.png)
![image](https://user-images.githubusercontent.com/11915730/66708273-3beb0200-ed4e-11e9-9e45-edf2c37df987.png)
![image](https://user-images.githubusercontent.com/11915730/66708276-473e2d80-ed4e-11e9-9d80-fb316e23dd35.png)
![image](https://user-images.githubusercontent.com/11915730/66708279-4c02e180-ed4e-11e9-97ac-6051e1a1c779.png)

#### Steps to reproduce the problem:

1. Open Blood Infuser GUI
2. Insert more than one Blood Cell

#### Expected behaviour:

____

#### Versions:

- This mod: 14.23.5.2836
- Minecraft: 1.12.2
- Forge: EvilCraft-1.12.2-0.10.77

#### Log file:
PS:
https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/399#issue-506244011

**Comment by rubensworks** [comment]
That's strange. May be a cross-mod issue. Will look into it.
