### ISSUE TITLE
Evilcraft and Bonsai Trees

### ISSUE THREAD

**Issue by UnrefinedCatalyst** [rubensworks/EvilCraft#792]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

I'm currently attempting to make Evilcraft compatible with bonsai trees, I've written the required JSON files for undead trees to be added to bonsai, and for blood waxed coal to be useable within bonsai pots as a soil type.

I figured that being able to grow undead trees in a regular dirt filled bonsai pot was a little overpowered, so I made it so that they required blood waxed coal as a soil, and so that the undead trees took a little longer to grow than regular bonsai trees.

Although, I also made it so that blood waxed coal grows trees 25% faster, and makes them produce 25% more items.

The only issue that I have, is that in the very first section of the file for the undead tree itself, I do not have a proper name. The current placeholder I've been using is evilcraft:undeadtree, but I know there's a model name, or maybe some json file for the tree schematic itself, and currently there is no model within the bonsai pot. Functionally, it's fine, but it is hard to tell whether or not I have anything in the pot in the first place until I start getting drops from the bonsai tree.

I've attached txt files, they are fully functional when I converted them to json files in github, feel free to use them.

Hope something comes of this,

Catalyst

[blood_waxed_coal_block.txt](https://github.com/CyclopsMC/EvilCraft/files/3747165/blood_waxed_coal_block.txt)

[evilcraft_undeadtree.txt](https://github.com/CyclopsMC/EvilCraft/files/3747161/evilcraft_undeadtree.txt)

**Comment by rubensworks** [comment]
I like the compatibility idea, but I don't think this repo is the proper place to add it.

I suggest opening an issue or PR to the [Bonsai Trees issue tracker](https://github.com/thraaawn/BonsaiTrees) so it can be added there.
