### ISSUE TITLE
Spirit furnace performance

### ISSUE THREAD

**Issue by bigenergy** [rubensworks/EvilCraft#795]
#### Issue type:

- :snail: Performance issue

____

#### Short description:
Spirit furnace low performance

#### Steps to reproduce the problem:

1. build spirit furnace
2. make profile laggogles

____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.78
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.5.2847

#### Profiler output:

https://sparkprofiler.github.io/#COllmGDrb8
![image](https://user-images.githubusercontent.com/17977139/71703305-fab23d80-2de4-11ea-8740-817944536cd4.png)

**Comment by rubensworks** [comment]
Please share your sampler output as described here: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.12/.github/CONTRIBUTING.md#performance-issues-snail

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsMC/CyclopsCore</div></blockquote>

**Comment by bigenergy** [comment]
Why use a sampler? Spark showed it all

**Comment by rubensworks** [comment]
> An error occurred whilst loading. Perhaps the data has expired?

This is exactly the reason why I prefer an actual sampler output file...

@bigenergy If you still have your world, be sure to share the file here, so I can reopen the issue then.
