### ISSUE TITLE
Enchantment Registration

### ISSUE THREAD

**Issue by DrGaster** [rubensworks/EvilCraft#797]
#### Issue type:

- :bug:
On Enchantment:
     ID 101
     ID 102
     ID 103

____

#### Short description:

EvilCraft enchantments conflicting with vanilla enchantments
#### Steps to reproduce the problem:

1. Running a Server with EvilCraft

2. Watch the Logs carefully

#### Expected behavior:

Not Much as I haven't logged onto the server, I am trying to get as many of the errors out as possible first.
____

#### Versions:

- This mod: EvilCraft-1.7.10-0.9.13.jar
- Minecraft: 1.7.10
- Forge: 1.7.10

#### Logfile:

https://pastebin.com/embed/7nHsnaMH

**Comment by rubensworks** [comment]
I'm sorry, but 1.7.10 is not supported anymore. 1.12 is the main target now, and 1.14 will soon become the new target.

**Comment by DrGaster** [comment]
Had it been fixed on the later versions?

**Comment by rubensworks** [comment]
Yes.
