### ISSUE TITLE
Dark Temples causing massive worldgen lag

### ISSUE THREAD

**Issue by Master00Maniac** [rubensworks/EvilCraft#798]
Using Topography, I'm generating a world with Sky Islands. I'd noticed whilst flying around that every now and then, I'd get some extreme server-side lag, up to several minutes at a time. After some effort, and diagnosing and digging, I found that EvilCraft's dark temples (the ones with the Environmental Accumulator) were the culprit. I found this using Spark, a profiler mod. Here's a link to the results of that: https://sparkprofiler.github.io/#mnsFwpC9Cb

I'm using EvilCraft version 0.10.78

EDIT: I should add that whitelisting the structures to generate only in the Nether entirely resolved this issue for me.

**Comment by rubensworks** [comment]
Closing this as your profiling output expired.
That is the reason why I ask for an `.nps` file in the issue template.

If you still have the world and can run sampler, be sure to share it here, so I can reopen the issue.
