### ISSUE TITLE
1.12.2 Game/Servercrash with Spirit Furnace

### ISSUE THREAD

**Issue by SirLevin94** [rubensworks/EvilCraft#799]
So i use Evilcraft in my 1.12.2 Modpack and got a Servercrash... after deleting the spirit furnace the server is now running again...
Out of curiosity i recreatet the same Setup in my Singleplayer World an it crashed again.

Short description:
Server crashed using Spirit furnace and box of eternal closure containing Villager spirit.

Expected behaviour:
It Should probably drop emeralds. (Villager commonly drop emerald on modded pack)
or noting.

Actual behaviour:
This issue makes the Server/Singleplayer crash. 

Steps to reproduce the problem:
Build 3x3x4 spirit Furnace.
Kill vanilla villager.
Use evil craft feature to move the villager spirit into a box of eternal close.
Put the box into spirit furnace (obviously and add some blood (i used blood bucket).

Versions:
This mod: 0.10.78.jar
CyclopsCore: 1.6.0.jar
Minecraft: 1.12.2
forge-14.23.5.2847

CrashLog file:

https://paste.dimdev.org/obuqixuzew.mccrash

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Fixed in https://github.com/CyclopsMC/CyclopsCore/commit/e1e48e93222762c537ebcdae32da4e84b08ea200
