### ISSUE TITLE
I'm not to sure if this is your issue or not, but it basically isn't (easily) reproducible

### ISSUE THREAD

**Issue by AvulcanLogic** [rubensworks/EvilCraft#801]
I didn't want to leave this blank, but I edited my crash report to be neater
it helps when you're dealing with an idiotic amount of mods and want to know the issue

I can't really give you steps, to reproduce because it crashes when initializing...
Unless one is willing to download all the mods themselves XD which is highly unlikely

I don't really know what kind of bug it is besides saying
Caused by:  java.lang.NoClassDefFoundError

Sorry for the terrible bug report, but honestly I don't know if this is technically your issue or not

Please just quickly look at the edited crash log, since even though this may not be your issue, your mod did still crash so, maybe there is a quick and dirty or a neat/permanent solution to prevent whatever happened from happening with other mods.

Simple crash report
https://paste.dimdev.org/iwununevuj.rb

Full crash report
https://paste.dimdev.org/iqitovixoz.mccrash

**Comment by AvulcanLogic** [comment]
disabling this mod allows the game to load to main menu

**Comment by rubensworks** [comment]
IC2Classic is incompatible with EvilCraft, see #785.
