### ISSUE TITLE
Vengeance Spirits  are invisible and in permanent god mode. 

### ISSUE THREAD

**Issue by Solverbolt** [rubensworks/EvilCraft#802]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. ... Break block with pickaxe of vengeance, spirit shows up. Cannot see it other than on minimap, kills all players in a chunk instantly

#### Expected behaviour:

____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.78.jar
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2847

**Comment by Solverbolt** [comment]
also, Last 4 times i attempted to use pastebin for crash logs, they are now forcing people to pay 10$ in certain parts of the world. Just an fyi

**Comment by rubensworks** [comment]
> kills all players in a chunk instantly

Wait what?!
It's the first time I hear someone mentioning this.

Are you sure it's not a feature/bug in your pack?

Have you tried without any other mods installed?
