### ISSUE TITLE
Evilcraft compat crashes on loading with ic2classic

### ISSUE THREAD

**Issue by imagelesskink** [rubensworks/EvilCraft#803]
#### Issue type:

- :bug: Bug

____

#### Short description:

Crash on loading

#### Steps to reproduce the problem:

1. Install evilcraft and ic2classic
2. Start the game

#### Expected behaviour:

Game starts
____

#### Versions:

- This mod: 0.10.78
- Minecraft: 1.12.2
- Forge: 14.23.5.284

#### Log file:

https://pastebin.com/AJFci1ME

**Comment by rubensworks** [comment]
Duplicate of #785.
