### ISSUE TITLE
Crashing during startup 'done phase?' (interacting with ae2/elevator id) 1.16.4

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [rubensworks/EvilCraft#808]
#### Issue type:

- :bug: Bug 

____

#### Short description:

During the loading phase of the game, evilcraft has some about a null Resource location, that crashes with both applied energistics 2 and openblocks elevator mod (elevator id). 

#### Steps to reproduce the problem:

1. New vanilla client with forge 35.1.15
2. add cyclopscore, evilcraft, jei, elevatorid, appliedenergistics2 8.2.beta1
3. Crash during final freezing of data

#### Expected behaviour:

Loading to game screen. 

____

#### Versions:

- This mod: evilcraft 1.16.4 1.0.0
- Minecraft: 1.16.4
- Forge: 35.1.15

#### Log file:

https://paste.ee/p/cgYbJ

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by remplerus** [comment]
can't replicate with forge 35.1.7, 35.1.13, 35.1.15 and 35.1.28

**Comment by rubensworks** [comment]
@remplerus I could replicate it, but only occured when certain other mods were present. Thanks for checking on your end though!
