### ISSUE TITLE
[1.16.4] Crash with Baubles Reborn installed while joining world.

### ISSUE THREAD

**Issue by remplerus** [rubensworks/EvilCraft#809]
#### Issue type:

- :bug: Bug

____

#### Short description:

Minecraft crashes with Evilcraft and Baubles Reborn installed when entering world.

#### Steps to reproduce the problem:

1. Install Evilcraft and Baubles Reborn
2. Create new world or join existing one
3. Crash

#### Expected behaviour:

Joining world.

____

#### Versions:

- This mod: 1.16.4-1.0.0
- Baubles Reborn: 1.8.5-1.16.4
- Minecraft: 1.16.4
- Forge: 35.1.28 (also tested with forge 35.1.7 and 35.1.13)

#### Log file:

https://gist.github.com/remplerus/408bb678b2339f4092e842a1dd128f03

**Comment by rubensworks** [comment]
Thanks for reporting!
