### ISSUE TITLE
[1.16.4]Creative Blood Drop in multiple creative Tabs

### ISSUE THREAD

**Issue by remplerus** [rubensworks/EvilCraft#810]
#### Issue type:

- :bug: Bug

____

#### Short description:

Creative Blood Drop is in multiple other creative tabs.

#### Steps to reproduce the problem:

1. Install Evilcraft
2. Join/Create world with creative mode
3. Scroll at the end of any creative tab, you find the creative blood drop. You also see it, when deleting items (that little red X in Inventory).

#### Expected behaviour:

That item should just be in Evilcraft Tab.

____

#### Versions:

- This mod: 1.0.0
- Minecraft: 1.16.4
- Forge: 35.1.28

#### Log file:

https://hp.rempler.com/pic/Screenshot1.png
https://hp.rempler.com/pic/Screenshot2.png
https://hp.rempler.com/pic/Screenshot3.png
https://hp.rempler.com/pic/Screenshot4.png

**Comment by rubensworks** [comment]
Thanks for reporting!
