### ISSUE TITLE
Ticking block entity crash on environmental accumulator

### ISSUE THREAD

**Issue by JonaBrackenwood** [rubensworks/EvilCraft#811]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Random crash when in the neighbourhood of an environmental accumulator

#### Steps to reproduce the problem:

1. Have the environmental accumulator in render/active chunck distance

#### Expected behaviour:

No crash.

____

#### Versions:

- This mod: 1.16.4-1.0.0
- Minecraft: 1.16.4
- Forge: 35.1.13

#### Log file:

https://gist.github.com/JonaBrackenwood/e136411bb841759fe340ddef154e4827

**Comment by rubensworks** [comment]
Thanks for reporting!
