### ISSUE TITLE
Double controls in options

### ISSUE THREAD

**Issue by JonaBrackenwood** [rubensworks/EvilCraft#812]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Controls appear double in options

#### Steps to reproduce the problem:

1. Go to the EvilCraft controls section in the options
2. They appear double
3. When changing one, both change

#### Expected behaviour:

Single options
____

#### Versions:

- This mod: 1.16.4-1.0.0
- Minecraft: 1.16.4
- Forge: 35.1.13

#### Log file:

![Evilcraft double controls](https://user-images.githubusercontent.com/1567798/103318008-4bc33480-4a2d-11eb-8e68-c45880223d44.png)

**Comment by rubensworks** [comment]
Thanks for reporting!
