### ISSUE TITLE
Crash when launch Evilcraft 1.16.4-1.0.1

### ISSUE THREAD

**Issue by Dokman** [rubensworks/EvilCraft#814]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Install clean forge version , Cyclops Core 1.9.2 and Evilcraft 1.16.4-1.0.1 then i have a crash

#### Steps to reproduce the problem:

1. Install Forge 35.1.28
2. Install CyclopsCore-1.16.4-1.9.2
3. Install EvilCraft-1.16.4-1.0.1
4. Launch the game
5. Crash

#### Expected behaviour:

Clear launch into the game
____

#### Versions:

- This mod: EvilCraft-1.16.4-1.0.1
- Minecraft: 1.16.4
- Forge: 1.16.4 - 35.1.28

#### Log file:

[https://pastebin.com/huGNbBNN](https://pastebin.com/huGNbBNN)

**Comment by rubensworks** [comment]
Thanks for reporting!
