### ISSUE TITLE
Farting is glitchy

### ISSUE THREAD

**Issue by JonaBrackenwood** [rubensworks/EvilCraft#815]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Farting particles display wrongly, both brown and colorful variants

#### Steps to reproduce the problem:

1. Fart

#### Expected behaviour:

Small amount of particles without glitching

____

#### Versions:

- This mod: 1.16.4-1.0.1
- Minecraft: 1.16.4
- Forge: 35.1.13

**Comment by rubensworks** [comment]
Thanks for reporting!
