### ISSUE TITLE
Biome Extracts Not Working As Intended

### ISSUE THREAD

**Issue by selened** [rubensworks/EvilCraft#818]
#### Issue type:

- :bug: Bug: Biome Extracts don't work as intended.

____

#### Short description:

Throwing biome extracts of any kind in the ground will only create ocean biomes (as observed with the debug screen). Furthermore, when saving and quitting the world, and then re-entering, the patch of transformed biome will return to its original type (a patch of changed biome in a taiga biome will become taiga again and so on).

#### Steps to reproduce the problem:

1. Use minecraft 1.16.4 with forge (version 35.1.4) and have these mods installed:
CyclopsCore (version 1.9.2), Evilcraft (version 1.0.1), JEI (version 7.6.0.62)
2. Enter a world and throw a biome extract of any type in the ground.
3. Save and quit the game, and then enter again.

#### Expected behaviour:

Once the biome extract would be thrown to the ground, a small area would transform into the biome contained in the extract bottle, and would stay there even after logging off.

____

#### Versions:

- This mod: EvilCraft-1.16.4-1.0.1, CyclopsCore-1.16.4-1.9.2
- Minecraft: 1.16.4
- Forge: forge-35.1.4

**Comment by rubensworks** [comment]
Thanks for reporting!
