### ISSUE TITLE
Broom Parts Crafting and Rendering Weirdness

### ISSUE THREAD

**Issue by selened** [rubensworks/EvilCraft#819]
#### Issue type:

- :bug: Bug: Broom parts not rendering and weird recipes

____

#### Short description:

All broom parts can be made with any other broom part and the specific material. For example a feather brush can be made with feathers and a bare rod or brush or cap or even other rod/brush/cap parts. I don’t know if that’s a bug or a feature. Furthermore the JEI and Origins of Darkness book’s recipes show all the broom parts craft with their respected materials and an invisible item called “Broom Part”. This invisible “Broom Part” item is also the result for the leaf and dark power gem broom parts recipes. A “Broom Part” made with leaves can stack with another “Broom Part” made the same way, but not with one made from dark power gems. And vice versa. The vanilla recipe book also recognizes them as different recipes, but they can’t be used to craft any brooms. Finally a wool brush can be made with wool (as expected) but also with blocks of honey for some reason.

#### Steps to reproduce the problem:

1. Use minecraft 1.16.4 with forge (version 35.1.4) and have these mods installed:
CyclopsCore (version 1.9.2), Evilcraft (version 1.0.1), JEI (version 7.6.0.62)
2. Open up the Origins of Darkness book for the broom part recipes or search “bare rod” in JEI to see them there
3. Try to craft any broom part with the respective material and any cap/rod/brush made of any material

#### Expected behaviour:

Crafting a broom part would require the respective material and the specific bare broom part. An undead rod for example would only be crafted with a bare rod and undead planks. At least if it isn’t intended. If it is, then ignore that part I guess. The jei recipes would render the materials instead of showing the invisible “Broom Part”, unless that’s a compromise to not have to cycle through all broom parts in the jei window. Finally the items crafted out of leaves and dark power gems would be usable and visible and wool brushes wouldn’t be crafted out of honey.

____

#### Versions:

- This mod: EvilCraft-1.16.4-1.0.1, CyclopsCore-1.16.4-1.9.2
- Minecraft: 1.16.4 
- Forge: forge-35.1.4

**Comment by rubensworks** [comment]
Thanks for reporting!
