### ISSUE TITLE
Promise of Productivity applies when filling a Blood Extractor in a Blood Infuser

### ISSUE THREAD

**Issue by dashkal16** [rubensworks/EvilCraft#820]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When infusing a blood extractor manually, the promise of productivity applies, effectively multiplying blood.

#### Steps to reproduce the problem:

1. Upgrade a blood infuser with at least a Promise of Tenacity I and a single Promise of Productivyt
2. Ensure there is at least some blood in the infuser
3. Insert an empty Blood Extractor in the input slot
4. Observe more blood appears in the extractor than was in the infuser

#### Expected behaviour:

Promise of Productivity should not apply when using the infuser to fill a fluid container.

____

#### Versions:

- This mod: EvilCraft-1.16.4-1.0.1.jar
- Minecraft: 1.16.4
- Forge: 1.16.4-35.1.11

**Comment by rubensworks** [comment]
Thanks for reporting!
