### ISSUE TITLE
Armor parts can be put on wrong part in blood chest

### ISSUE THREAD

**Issue by JonaBrackenwood** [rubensworks/EvilCraft#821]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Armor parts can be put on wrong part in blood chest

#### Steps to reproduce the problem:

1. Open the blood chest
2. Put an armor part in an unintened slot, for example boots on the chest plate slot
3. This works for all armor slots, not items

#### Expected behaviour:

Armor can only be put in the correct slots.

____

#### Versions:

- This mod: 1.16.4-1.0.3
- Minecraft: 1.16.4
- Forge: 35.1.13

#### Log file:

![blood chest armor](https://user-images.githubusercontent.com/1567798/103415001-9d300880-4b80-11eb-8ef4-f9cf53765801.png)

**Comment by rubensworks** [comment]
Thanks for reporting!
