### ISSUE TITLE
Spiked plate not returned when breaking block underneath

### ISSUE THREAD

**Issue by Davivs69** [rubensworks/EvilCraft#824]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When placing the spiked plate on top of a block, then breaking that block results in getting the block back, but not the spiked plate. (This was tested with a block of cobblestone)

#### Steps to reproduce the problem:

1. Place spiked plate on top of a block (cobbelstone)
2. Break block on which you just placed the dark plate (cobblestone)
3. Do not get spiked plate back

#### Expected behaviour:

Get back spiked plate after breaking block on which it was placed.
____

#### Versions:

- This mod: 1.16.4
- Minecraft: 1.16.4
- Forge: 1.16.4

**Comment by rubensworks** [comment]
Thanks for reporting!
