### ISSUE TITLE
Liquid Blood Issues MC 1.15.2

### ISSUE THREAD

**Issue by Wolfofthenyght** [rubensworks/EvilCraft#825]
Hello! Firstly, if this version of Evilcraft is no longer supported/being updated (MC 1.15.2), or if this is the wrong place to report, I apologize & please feel free to close this submission. Secondly, if it's still being updated, there are two issues involving liquid blood & it's bi-products I'd like to bring to your attention:

https://user-images.githubusercontent.com/7939382/103488493-f98e6480-4dda-11eb-9808-5d6e2ebe7a2d.mp4

Rendering for placing blood (and poison) in world seems to not be working. When I place down either liquid I can see the shadow of the block, but the liquid itself doesn't render. I've tried this in both my private world & on my server but the results seem to be the same. To my knowledge, I don't have any mod that might effect liquid rendering installed, and I don't run optifine or connected textures mods. I'm running with forge 31.2.12 at the moment, and other liquids from base MC & other mods that add some (Industrial Foregoing for example) render ok. (I attached a small video for you)

The second issue involves the liquid blood is after it becomes hardened blood- When lit on fire (in order to make the blood shards) it just stays on fire, or go out. It never breaks apart into the shards, & breaking the hardened blocks while on fire (as a test) doesn't yield shards. I realize you can pick these up with silky touch pick axes & cook them, which is how I was able to get started with the mod on our server, but I wanted to make you aware that the light on fire mechanic doesn't seem to be working as intended. I made sure doFireTick was enabled in the game rules, and I toggled it a few times in between tries, but to no avail.

(I also saw someone else already reported the issues with the broom parts, this seems to be present in the 1.15.2 version as well)

Thank you so much for all your work on this mod & getting it updated! By far, it's one of my favorites!

**Comment by rubensworks** [comment]
Thanks for reporting, but unfortunately 1.15 is not being maintained anymore.
All of these issues have been fixed for 1.16, so I would recommend migrating to that version (mods are overall more stable there).
