### ISSUE TITLE
Purifier dupliates Enchantments from Tetra-Tools

### ISSUE THREAD

**Issue by rxwsh** [rubensworks/EvilCraft#826]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When trying to take of enchantments from tools created in Tetra with the purifier you get the enchanted book but the tool stays enchanted.
Tetras Dev Mickelus said that this has to be fixed on your end, which doesn't make much sense to me but gotty let you know anyways.

#### Steps to reproduce the problem:

Place tool created with Tetra with at least one enchanted module in the purifiere
place Blook in Purifier
Get enchanted book and still enchanted item out of the purifier.

1. ...

#### Expected behaviour:

The enchantment that it on the book should not be on the Tetra tool anymore.

____

#### Versions:

- This mod: 1.16.3-1.0.4
- Minecraft: 1.16.4
- Forge: 35.1.28
- Tetra: 1.16.3-3.5.1

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
EvilCraft is simply calling the standard `EnchantmentHelper.getEnchantments` and `EnchantmentHelper.setEnchantments`  of vanilla.
Enchantments are removed just fine from vanilla tools, so I suspect this is a bug in Tetra's enchantment handling.
I suggest opening an issue on their tracker, feel free to link back to here.

**Comment by rxwsh** [comment]
Thought as much, when stating my doubt that this is on you to fix they bannd me from their discord server, but I try to let them know. Thank you for your hard work!

**Comment by rubensworks** [comment]
That's very unfortunate...
We as modders should be grateful towards players that actually take the effort to report bugs, as this only improves the stability of our mods.

**Comment by rxwsh** [comment]
It's give and take, players get so much out of it, it's he least they can do. Especially as someone with a programming backround myself I can really appriciate all the work you people put into the mods.
As it seems like the Tetra dev is really not interested in resolving this issue I would advise to really just blacklist Tetra Items from getting purified, it might be fun getting fortune X as easily as this unlimited times but really not the point of the purifier.

**Comment by rubensworks** [comment]
As concluded in https://github.com/mickelus/tetra/issues/305, the tools from the mod should be blacklisted.
