### ISSUE TITLE
Ticking Entity - Lightning Grenade

### ISSUE THREAD

**Issue by Darkfiend009** [rubensworks/EvilCraft#827]
Minecraft Version: 1.16.4
Forge Version: 35.1.36
EvilCraft Version: 1.16.4-1.0.5

Server crash when throwing Lightning Grenade. Redstone Grenade seems to work fine!

Crash Report: https://pastebin.com/N9sCXHZZ

**Edit:** I wanted to add on to this post since the crash reports are almost identical. 

Getting the same Ticking Entity crash for the Blood Pearl of Teleportation.

Crash Report: https://pastebin.com/k7wHNZiP

And the Lightning Bomb:

Crash Report: https://pastebin.com/ahpZVcQG

**Comment by rubensworks** [comment]
Thanks for reporting!
