### ISSUE TITLE
The collosal blood chest repair issue.

### ISSUE THREAD

**Issue by Lloergwaed** [rubensworks/EvilCraft#828]
i put a item in the collossal blood chest which repair it up to full, then return it to 0 durability and then repair it again, in a endless loop?
using version 1.16.4-1.0.5 of the mod in direwolf20 1.16.4 modpack

it does it for vanilla weapon, modded weapon, tetra weapon.

**Comment by rubensworks** [comment]
@Lloergwaed Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
