### ISSUE TITLE
Broom Parts Not Showing Up (And An Issue With Dungeons Gear)

### ISSUE THREAD

**Issue by selened** [rubensworks/EvilCraft#829]
#### Issue type:

- :bug: When Evilcraft is used with the mod Dungeons Gear, the broom parts don't show up.

____

#### Short description:

When Evilcraft is used with the mod Dungeons Gear, the broom parts don't show up. In the info book and jei all of the recipes only show an invisible item called "Broom Part" - in a manner similar to issue #819 - instead of the specific rod/feather/cap etc. While each broom part is visible in the creative inventory, attempting to take one will also yield an invisible "Broom Part". When I play the game without Dungeons Gear installed, it all works fine except from the dark power gem cap which also only appears as a "Broom Part". This is kind of a separate issue from Dungeons Gear compatibility but it's too similar so I didn't open a separate issue.

#### Steps to reproduce the problem:

1. Use minecraft 1.16.4 with forge (version 35.1.36) and have these mods installed:
CyclopsCore (version 1.9.5), Evilcraft (version 1.0.5), JEI (version 7.6.1.65), Dungeons Gear (version 3.0.6).
2. Open up the Origins of Darkness book for the broom part recipes or search “bare rod” in JEI.
3. Open up Evilcraft's creative inventory and try to take any broom part.

#### Expected behaviour:

On its own, Evilcraft would have an output for the dark power gem cap recipe instead of an invisible "Broom Part" item. With Dungeons Gear installed, all the broom parts would be visible and craftable instead of yielding a "Broom Part".

____

#### Versions:

- This mod: EvilCraft-1.16.4-1.0.5, CyclopsCore-1.16.4-1.9.5
- Minecraft: 1.16.4
- Forge: 35.1.36

**Comment by rubensworks** [comment]
Could you share your full forge logs?

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by selened** [comment]
Latest log
https://pastebin.com/DWYQ6DNs


<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/DWYQ6DNs">[15:18:45] [main/INFO]: ModLauncher running: args [--username, theTDgal, --versi - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>
