### ISSUE TITLE
Environmental Accumulator Worldgen Config Option

### ISSUE THREAD

**Issue by ghost** [rubensworks/EvilCraft#830]
- :heavy_plus_sign: Feature request 

____

#### Short description:

Please add config option to configure rate of environmental accumulator generation chance per chunk

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Such config options in fact already exist: https://github.com/CyclopsMC/EvilCraft/blob/master-1.16/src/main/java/org/cyclops/evilcraft/world/gen/structure/WorldStructureDarkTempleConfig.java#L34-L37

**Comment by ghost** [comment]
Sorry I did not know that Dark Temples were the accumulator worldgen name XD
