### ISSUE TITLE
Flopper integration for dropping blood collection

### ISSUE THREAD

**Issue by AbacusOperator** [rubensworks/EvilCraft#831]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

It would be nice, if flopper (from your other mod) could collect blood dropping from undead trees or collect blood if mob is killed above it.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
That's what the Sanguinary Pedestal is for :-)
I won't hardcode support for that into Flopper, otherwise the Sanguinary Pedestal becomes useless.
