### ISSUE TITLE
Glitching Enchantment Glint For Humanoid/Werewolf Flesh

### ISSUE THREAD

**Issue by selened** [rubensworks/EvilCraft#834]
#### Issue type:

- :bug: The enchantment glint effect for humanoid and werewolf flesh glitches during the night

____

#### Short description:

Humanid and Werewolf Flesh have no enchantment glint during the day, but once the game is set to nighttime, the glint effect seems to be glitching when it's in the player inventory. Viewing the items in the creative or jei menu and also when they are thrown on the ground the glint effect is stable for both of them. Picking them up will cause them to blink rapidly both in the inventory and the creative/jei menus and items thrown on the ground. Getting rid of them will make the items revert back to a non-blinking glint effect or, occasionally, no glint effect at all. Once the day comes the items don't have the glint effect. One minor thing that happens is if you aren't holding the items in your inventory when the night ends and day comes, the flesh items will still have the glint effect in the creative and jei menus but picking any of them up will make the items normal again.

#### Steps to reproduce the problem:

1. Use minecraft 1.16.4 with forge (version 35.1.36) and have these mods installed:
CyclopsCore (version 1.9.5), Evilcraft (version 1.0.5), JEI (version 7.6.1.65)
2. Boot up the game and enter a world
3. Acquire humanoid or werewolf flesh during the day and look at the items either in the jei or creative menu
4. Set time to night or wait for nighttime to come and observe the items in your inventory and menus

#### Expected behaviour:

The enchantment glint effect wouldn't glitch and would be stable during nighttime

____

#### Versions:

- This mod: CyclopsCore (version 1.9.5), Evilcraft (version 1.0.5)
- Minecraft: 1.16.4
- Forge: 35.1.36

**Comment by rubensworks** [comment]
Thanks for reporting!
