### ISSUE TITLE
Ιncompatibility with Dungeons Gears and Broom Parts 

### ISSUE THREAD

**Issue by selened** [rubensworks/EvilCraft#836]
#### Issue type:

- :bug: Evilcraft with Dungeons Gear makes broom parts unusable (issue #829 not completely solved)

____

#### Short description:

Issue #829 has only been solved as far as the dark power gem cap is concerned. The visual bug with broom parts and their unusability has remained and it's been already described in that issue, however there is some extra information on how it works in regards to how worlds are generated. Booting up the game with evilcraft and dg (dungeons gear) and creating a new world (world 1) will result in that bug. Rebooting the game, this time without dg, and making a new world (world 2) the bug won't persist, but reentering World 1 which has been generated with dg, the bug persists and upon reentering World 2 the bug will apply there too. Upon booting up the game again without dg and opening both worlds, you see they are fine. So any world with dungeons gear in it will be bugged, and the only way to solve it is to boot up the game without dungeons gear and open your world, and then exit and boot it up again and enter the world.

#### Steps to reproduce the problem:

1. Use minecraft 1.16.4 with forge (version 35.1.37) and have these mods installed:
CyclopsCore (version 1.10.0), Evilcraft (version 1.0.6), JEI (version 7.6.1.65), Dungeons Gear (version 3.0.6).
2. Start minecraft with those mods and create a world (world 1). The exit minecraft.
3. Start minecraft again but without Dungeons Gear and create a second world (world 2). Exit world 2 and enter world 1. Then exit world 1 and reenter world 2. Then exit minecraft.
4. Start minecraft again without Dungeons Gear and enter either world.

#### Expected behaviour:

Broom parts would be visible, usable and craftable when playing with evilcraft and dungeons gear together.

____

#### Versions:

- This mod: CyclopsCore (version 1.10.0), Evilcraft (version 1.0.6)
- Minecraft: 1.16.4
- Forge: 35.1.37

#### Log file:

Since a log file was requested last time, I'll post them here just in case:

Log for step 2
https://pastebin.com/3Y6LeezU
Log for step 3
https://pastebin.com/hH4mvLTe
Log for step 4
https://pastebin.com/WwZxNGvt

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
All items are in fact properly being registered, as they are visible in the creative tab.
However, trying to get a broom item from the creative tab is somehow impossible.

Since Dungeons Gears makes use of mixins, and this issue does not occur with any other mod, I highly suspect the issue lies on their end.

Could you report this to the issue tracker of Dungeons Gears? Feel free to link back here.

**Comment by rubensworks** [comment]
Closing this issue here in the meantime.
