### ISSUE TITLE
Simple Storage Network plus Evilcraft Crafting Bug

### ISSUE THREAD

**Issue by Ragotha** [rubensworks/EvilCraft#837]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Attempting to speed about the hard parts of Evilcraft, I had prepared iron promise acceptors and bowls of promises tier 2, and upon attempting to craft multiple (8) promises of efficiency within my crafting system , I only received one, it consumed the items for all 7 others, and only got one empty bowl of promises in turn.

#### Steps to reproduce the problem:

1. Attempt to craft multiple promises of efficiency/velocity within a simple storage network
2. suffer

#### Expected behaviour:

Successfully crafting and receiving the intended amount of promises as well as empty bowls

____

#### Versions:

- Evilcraft: 1.0.5
- Cyclops Core: 1.9.5
- Simple Storage Network: 1.3.1
- Minecraft: 1.16.4
- Forge: 35.1.37

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Does the same thing happen in regular crafting tables?
