### ISSUE TITLE
[1.16.4] Item Durability Overflow in Colossal Blood Chest

### ISSUE THREAD

**Issue by Hjaldar** [rubensworks/EvilCraft#839]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When fully repaired items are placed in the Colossal Blood Chest, they become damaged back to 0 or 1 durability (can't tell which), and then keep repairing back to full durability and keep cycling infinitely.

The issue is not present in the normal Blood Chest.

#### Steps to reproduce the problem:

1. Build a Colossal Blood Chest.
2. Fill it with blood.
3. Place an undamaged item in the chest, e.g. diamond pick.
4. Item becomes fully damaged and begins repairing back to full, when fully repaired it immediately becomes damaged again, and so on, forever.

#### Expected behaviour:

When item is fully repaired in a Colossal Blood Chest it should not have durability reset to 0 (or 1).

____

#### Versions:

- This mod: EvilCraft-1.16.4-1.0.6, CyclopsCore-1.16.4-1.10.1
- Minecraft: 1.16.4
- Forge: forge-1.16.4-35.1.37
- JEI: jei-1.16.4-7.6.1.65

No other mods present.

#### Log file:

Provided upon request.

**Comment by rubensworks** [comment]
Thanks for reporting!
