### ISSUE TITLE
Ticking Entity - Blood Pearl 1.15.2

### ISSUE THREAD

**Issue by nicolasboattini** [rubensworks/EvilCraft#840]
#### Issue type:

- :bug: Bug
____

Minecraft Version: 1.15.2
Forge Version: 31.2.47
EvilCraft Version: 1.15.2-1.0.0

Server crashed when throwing Blood Pearl of Teleportation.

Crash Report: https://pastebin.com/UEJs0Vbk

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This has been fixed for 1.16. 1.15 is not maintained anymore unfortunately.

**Comment by nicolasboattini** [comment]
@rubensworks Yikes! Is there a way to fix this for now just to continue running the server? Thanks in advance.

**Edit:**
I mean, a way to delete that Ticking Entity. 'Cause the server has no backup, and I tried with the chaotic method of Forge to delete entities and it didn't work.

**Comment by rubensworks** [comment]
Not that I'm aware of.
You're welcome to backport the fix to 1.15, since this mod is open source.
