### ISSUE TITLE
Exalted Crafter still not exposing all slots to JEI recipe auto-fill

### ISSUE THREAD

**Issue by Hjaldar** [rubensworks/EvilCraft#841]
#### Issue type:

- :bug: Bug

____

#### Short description:

![Exalted Crafter](https://i.imgur.com/fF2pJHR.png?1)

The inventory slots shown in the above screenshot (those 10 slots containing oak planks) are not checked for JEI's recipe auto-fill when using an exalted crafter. This is possibly related to #817 .

#### Steps to reproduce the problem:

1. Open any exalted crafter with inventory slots filled as shown in the above screenshot.
2. Attempt to craft a vanilla Crafting Table using JEI's recipe auto-fill.
3. Note the + button in JEI is not active.

#### Expected behaviour:

All inventory slots are exposed to JEI's recipe auto-fill when using an exalted crafter.

____

#### Versions:

- This mod: EvilCraft-1.16.4-1.0.6, CyclopsCore-1.16.4-1.10.1
- Minecraft: 1.16.4
- Forge: 35.1.37
- JEI: jei-1.16.4-7.6.1.65

No other mods present.

**Comment by rubensworks** [comment]
Thanks for reporting!
