### ISSUE TITLE
Incompatibility with Easy Villagers

### ISSUE THREAD

**Issue by cking** [rubensworks/EvilCraft#843]
#### Issue type:
- :bug: Bug

____
#### Short description:
Having a pack with Evil Craft and [Easy Villagers](https://www.curseforge.com/minecraft/mc-mods/easy-villagers) has the werewolf profession overwrite the butcher profession in the trader and auto trader of Easy Villagers

#### Steps to reproduce the problem:
1. Grab: A Trader of Easy Villagers, a Smoker, a Villager from Easy Villagers
2. Place down the Trader, right click the smoker into the trader, right click the villager into the Trader

#### Expected behaviour:
Villager will turn profession into a butcher

____
#### Versions:
- This mod: 1.0.8
- Minecraft: 1.16.4
- Forge: 35.1.37
- Easy Villagers: 1.1.28

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Have you reported to Easy Villagers already?
Sounds more likely that this mod is causing the problem.
If so, can you add a link here to the issue?

**Comment by cking** [comment]
okay, i'll do that.

**Comment by cking** [comment]
i fail to get it to reproduce now.
sometimes the game is way to random... sorry
