### ISSUE TITLE
Some Recipe Issues with the Bowl of Promises

### ISSUE THREAD

**Issue by belathus** [rubensworks/EvilCraft#844]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I've been trying to tech through Evilcraft. I've noted a few issues with the bowl of promises.

The tier 3 bowl of promises currently has no uses in crafting.

Once, when I had a Promise of Tenacity 1 in the blood infuser, I've gotten the tier 0 bowl of promises. I'm not sure if this happened because I had a tier 0 in the output already or something like that, as I can't seem to reproduce this right now.

I can't do much with the tier 0 bowl of empty promises other than make a Promise of Tenacity 1, which also has no uses beyond being a minor upgrade for machines. I'd like to request the ability to empty a bowl of promises tier 0 without having to spend a block of iron on it.

#### Steps to reproduce the problem:

1. Make bowl of Promises in a blood infuser with a Promise of Tenacity 3. Then try to do something with that bowl.

#### Expected behaviour:

I'd expect the Bowl of Promises tier 3 to be able to be used in the same recipes as tiers 0 through 2. Also, I was a little surprised that the tier 0 couldn't be used to make the upgrades.

____

#### Versions:

- This mod: 1.16.4-1.0.8
- Minecraft: 1.16.4
- Forge: 1.16.4-35.1.37

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> Then try to do something with that bowl.

Can you give a concrete example of a recipe where this fails?

**Comment by belathus** [comment]
I know you already closed this, but I figured I'd answer your question.

![2021-02-08_23 07 50](https://user-images.githubusercontent.com/3826783/107316286-50d0c600-6a66-11eb-88b6-d29c9546e3a6.png)
![2021-02-08_23 07 56](https://user-images.githubusercontent.com/3826783/107316294-53cbb680-6a66-11eb-9ae8-c5359bcba876.png)

**Comment by rubensworks** [comment]
Ah, that has actually been fixed already in 4d734d5a5721020b9f3982b0c5825c85c5603357 (not released yet)
