### ISSUE TITLE
[1.12.2] Feature: Blood stains from undead trees

### ISSUE THREAD

**Issue by CurePindal** [rubensworks/EvilCraft#846]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

I understood that blood stains from undead trees had been added in later versions. It makes them super useful with the pedestals.
And because theres still many active 1.12.2 users and modpacks out there I would love to see the stains added/retro-fitted into a 1.12.2 version. If possible. 
Thx for considering.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Unfortunately. 1.12 is not being maintained anymore.
