### ISSUE TITLE
Blood Infuser doesn't return a Bowl of Promises: Tier 1 when loaded with Promise of Tenacity I

### ISSUE THREAD

**Issue by soulhakr** [rubensworks/EvilCraft#847]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Blood Infuser doesn't return a Bowl of Promises: Tier 1 when loaded with Promise of Tenacity - as the recipe indicates it should.

#### Steps to reproduce the problem:

1. Craft an _Empty Bowl of Promises_ in a **Crafting Table**
2. Craft a Dusted Bowl of Promises in a **Crafting Table**
3. Infuse a _Dusted Bowl of Promises_ into a _Bowl of Promises: Tier 0_ in the **Blood Infuser**
3. Infuse a block of iron into an _Iron Promise Acceptor_ in the **Blood Infuser**
4. Infuse an _Iron Promise Acceptor_ into a _Promise of Tenacity I_ in the **Blood Infuser**
4. Craft a _Dusted Bowl of Promises_ in a **Crafting Table**
5. Load the _Promise of Tenacity I_ into the **Blood Infuser**
6. Attempt to Infuse a Dusted Bowl of Promises into a Bowl of Promises: Tier 1 in the Blood Infuser.

#### Expected behaviour:

With a _Promise of Tenacity_ loaded in the **Blood Infuser**, the _Dusted Bowl of Promises_ should Infuse into a _Bowl of Promises: Tier 1_, but instead a _Bowl of Promises: Tier 0_ comes out.

____

#### Versions:

- This mod: EvilCraft 1.16.4-1.0.8
- Minecraft: 1.16.5
- Forge: 36.0.14

#### Log file:

no error messages logged

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can't reproduce this myself unfortunately.

Do you have any other mods installed? If so, please try again without any others.
It's possible that another mods is breaking things.

**Comment by Kitti-Source** [comment]
Hi I am fairly new to this mod but i am also having this same issue. The server i am on does have a lot of mods is there something that is causing it from one of  the other mods in use?

**Comment by rubensworks** [comment]
> The server i am on does have a lot of mods is there something that is causing it from one of the other mods in use?

Probably. If you can, please check if you can reproduce it without other mods.

**Comment by Kitti-Source** [comment]
On further testing, I was able to get to the tier 1 but when trying to advance to tier 2 I was coming across the same issue again. I tested it on single player with all the mods running. When i tested it with just EvilCraft, i was able to advance to the other tiers.  
The only way I have seem to get around this is to make another Blood Infuser and put in the Promise of Tenacity 2 in it first. It seems to not recognize when I place a new Promise of Tenacity in it. which is doable at least but can get annoying with space and the cost eventually.

**Comment by rubensworks** [comment]
Any chance you're using the Performant mod? That one is known to break mods.

**Comment by belathus** [comment]
We're having this issue and we do have Performant. The other tiers work fine, just not tier 1.

**Comment by bigenergy** [comment]
@rubensworks pls see https://github.com/someaddons/performant_issues/issues/161#issuecomment-863105588
