### ISSUE TITLE
Failed to load on game load

### ISSUE THREAD

**Issue by ghost** [rubensworks/EvilCraft#848]
#### Issue type:

Failed to load at startup

#### Steps to reproduce the problem:

Load game with latest evilcraft
____

#### Versions:

- This mod: 1.0.8
- Minecraft: 1.16.5
- Forge:  36.0.14

#### Log file:
https://pastebin.com/Ys2JaMTf

**Comment by rubensworks** [comment]
This doesn't seem to be an EC issue.
I see Optifine mentioned in the logs though, so that's likely your problem.

In any case, it's important to test these cases always without any other mods installed.
