### ISSUE TITLE
Crash with 1.16.5-forge-36.0.42

### ISSUE THREAD

**Issue by Maxi90909** [rubensworks/EvilCraft#849]
#### Issue type:

-Crash

____

#### Short description:

I don't know why it is crashing I just started up the game with my mods and when the loading is finished the minecraft screen says saving world and after that I get kicked out of the game back to the play button screen. I don't know why it is crashing maybe some of my mods are incompatible

#### Steps to reproduce the problem:

1. Start up the game 2. wait for the load to finish 3. saving world screen 4. Crash

#### Expected behaviour:

I don't know how this is meant, but do you mean what I expect from you to do? If so I expect you to fix this Bug

#### Versions:

- This mod:EvilCraft-1.16.4-1.0.8.jar , CyclopsCore-1.16.4-1.11.1.jar
- Minecraft: 1.16.5
- Forge:1.16.5-forge-36.0.42 

I am Using an self created modpack

#### Log file:

https://pastebin.com/4MttY2B5 this is the crash report I get
[latest.log](https://github.com/CyclopsMC/EvilCraft/files/5987431/latest.log) these are my logs sorry for posting them in like this but pastebin wouldn't allow so much words I also tried to make an pastebin account to bypass the limit but the activation code is still not there

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by quicktinker** [comment]
Yup, got the exact same Issue. Just tested it, its not a problem with cyclops core.

**Comment by rubensworks** [comment]
This is due to an implementation flaw. I'm actually really surprised it took this long for this bug to occur. Easy fix though.
