### ISSUE TITLE
Crash when opening creative tab

### ISSUE THREAD

**Issue by rafaelkai** [rubensworks/EvilCraft#850]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The game crashes when opening the creative tab, seems related to the item "Rejuvenated Flesh" (Maybe a mod conflict).

#### Steps to reproduce the problem:

1.  Simply open the creative menu.

#### Expected behaviour:

Not to crash.

____

#### Versions:

- This mod: 1.1.0
- Minecraft: 1.16.5
- Forge: 36.0.42

#### Log file:

https://textbin.net/untitled-64

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you share the logs in a different way? Can't access the website.

**Comment by rafaelkai** [comment]
Sure: https://ctxt.io/2/AACgoYwaFQ

<blockquote><img src="/favicon.png" width="48" align="right"><div><strong><a href="https://ctxt.io/2/AACgoYwaFQ">Context – share whatever you see with others in seconds</a></strong></div></blockquote>
