### ISSUE TITLE
crash while reading The Origins of Darkness

### ISSUE THREAD

**Issue by LlubNek** [rubensworks/EvilCraft#851]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Minecraft crashed while reading _The Origins of Darkness_.

#### Steps to reproduce the problem:

1. open _The Origins of Darkness_
2. go to second age
3. read on

#### Expected behaviour:

no crash...

____

#### Versions:

- This mod: EvilCraft-1.16.5-1.1.0.jar
- Minecraft: 1.16.5
- Forge: 36.0.42

#### Log file:

[crash-2021-02-17_07.50.22-client.txt](https://github.com/CyclopsMC/EvilCraft/files/5995768/crash-2021-02-17_07.50.22-client.txt)
[latest.log](https://github.com/CyclopsMC/EvilCraft/files/5995770/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Looks like the same problem as in #850.
