### ISSUE TITLE
Crashes when Rendering blood Extractor icon

### ISSUE THREAD

**Issue by quicktinker** [rubensworks/EvilCraft#852]
#### Issue type:

- :bug: Bug 

____

#### Short description:

the game crashes when rendering the blood extractor inventory icon through JEI or the creative menu

#### Steps to reproduce the problem:

go into creative, scroll down to evil craft items, the game will then crash
you can also search for the blood infuser and the game will crash

#### Expected behaviour:

I expect to see the icons and not have the game crash in the inventory menus

____

#### Versions:

- This mod: 1.1.0
- Minecraft: 1.16.5
- Forge: 36.0.42

#### Log file:

https://pastebin.com/qxsTTiZk

**Comment by rubensworks** [comment]
Thanks for reporting!
