### ISSUE TITLE
Item issue: "Bowl of Promises: Tier 3" not craftable for recipe: "Promise of Productivity" nor "Promise of Velocity"

### ISSUE THREAD

**Issue by Davivs69** [rubensworks/EvilCraft#853]
#### Issue type:

- :bug: Bug

____

#### Short description:

The "Bowl of Promises: Tier 3" can not be used to craft "Promise of Productivity" nor "Promise of Velocity" (I suspect this is not intentional).

#### Steps to reproduce the problem:

1. Craft a "Bowl of Promises: Tier 3"
2. Combine it with a Block of Redstone/Lapis Lazuli Block and an "Iron Promise Acceptor".
3. The recipe can not be preformed.

#### Expected behaviour:

I would expect the same behaviour from the tier 3 promise, as I would from the previous tiers promises.

____

#### Versions:

- This mod: 1.16.4
- Minecraft: 1.16.4

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This bug has actually been fixed already, you may not be using the latest version.
