### ISSUE TITLE
Cant open the evilcraft book

### ISSUE THREAD

**Issue by MasterQuentus** [rubensworks/EvilCraft#854]
Cant open the evilcraft book

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
@MasterQuentus Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
