### ISSUE TITLE
Appears to be a random crash on loading terrain with Terraforged?

### ISSUE THREAD

**Issue by Jackiecrazy** [rubensworks/EvilCraft#857]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I'm not sure how this bug even came to be. I was just walking around and presumably a blood dungeon was generated.
#### Steps to reproduce the problem:

1. create a world
2. walk around

#### Expected behaviour:

I'd expect it to not crash. The strange thing is, reading line 135 in WorldFeatureEvilDungeon, there is absolutely no reason it should be a chest instead of a spawner, hence my report.
____

#### Versions:

- This mod: 1.1.0
- Minecraft: 1.16.5
- Forge: 36.0.45

#### Log file:
https://pastebin.com/hCuHp7Ak

**Comment by rubensworks** [comment]
Thanks for reporting!
