### ISSUE TITLE
Crash when put a tool of "the betweenlands mod" to the Purifier

### ISSUE THREAD

**Issue by qingyiwebt** [rubensworks/EvilCraft#859]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Hmmm, because I use the EvilCraft mod on my server, and another player cause crash, so I can't describe the whole process.
And my English is not very good, so in this issue, I use some translators.

#### Steps to reproduce the problem:

1. Put a tool of "the betweenlands mod" to the Purifier

#### Expected behaviour:

____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.78.jar , CyclopsCore-1.12.2-1.6.3.jar
- Minecraft: 1.12.2
- Forge: 14.23.5.2855

#### Log file:

https://pastebin.com/2UXeuQ1A

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, but 1.12 is not supported anymore. I recommend updating to a more recent MC version.
