### ISSUE TITLE
Dark Temples seem to only spawn at y90

### ISSUE THREAD

**Issue by Jomeaga** [rubensworks/EvilCraft#860]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The default config for Dark Temple spawning says they should spawn between y64 and y90, but they only seem to spawn AT y90. Even over oceans with nothing blocking them. Reducing the max y just makes it spawn at what you set it at.
____

#### Versions:

- EvilCraft: 1.1.0
- Minecraft: 1.16.5
- Forge: 36.1.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Seems to work fine on my end.
First two temples I found were at 76 and 88, so the height definitely seems to vary.
Could be another mod messing with things if you have other mods installed.
