### ISSUE TITLE
Unrecoverable SSP Rendering-Related Crash with Evil Spirits 

### ISSUE THREAD

**Issue by KirinDave** [rubensworks/EvilCraft#861]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Hello, I am the lead pack dev for Unlikely Reunion. I opened this to re-open the discussion around #858.

Some mobs can trigger rendering crashes when viewed as spirits. Since many modpacks have many different mob types and the crash logs do not suggest which mods are implicated, it's extremely difficult to identify which mobs are interacting with EvilCraft's evil spirit visualization to cause crashes.

In all my reproductions of this bug, I haven't seen M&A mobs nearby (as implicated in #858), nor has anything killed one. If many mods are not properly implementing models for vengeance spirit visualization, I'm not sure how I can identify and report to individual mod authors about it.

#### Steps to reproduce the problem:

1. Load up the Unlikely Reunion modpack, start a single player map.
2. Put on the appropriate goggles and a Vengenace Ring
3. Bide your time before your instance crashes unrecoverably.

#### Expected behaviour:

I would expect that if EvilCraft cannot render modded spirits safely, it might not render sprites for spirits and instead render them as the (already very cool and menacing) particle effects of the spirit as is. Since most activities with spirits start with a known living mob and tend to get sunk into an item immediately, it is not very confusing.

Perhaps we could have a whitelist or blacklist feature that works both individually or by mod so that pack devs can use it to isolate which mods are likely to be causing issues?

____

#### Versions:

- This mod: EvilCraft-1.16.5-1.1.1.jar
- Minecraft: 1.16.5
- Forge: 36.1.0

#### Log file:

[Linked here.](https://gist.github.com/KirinDave/a85501696220a26d442fcf898ccb3bc8)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
There is a blacklist config options btw: `entityBlacklist`

**Comment by KirinDave** [comment]
I suppose I could blacklist all the entities from mods we know to be problematic as an initial option.

Once I compile this I'll report back on this bug and share it, as other pack makers might find that useful.

**Comment by rubensworks** [comment]
I've included a potential fix in the next release.
@KirinDave Please let me know if the problem would still occur.
And if so, please let me know an offending mob that I can debug with (preferably from an open-source mod).
