### ISSUE TITLE
Anti-vengeance beam entering portal causes crash on server

### ISSUE THREAD

**Issue by Divineaspect** [rubensworks/EvilCraft#862]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Anti-vengeance beam entering portal causes crash on server

#### Steps to reproduce the problem:

Fire the focus into a nether portal while attempting to seal a blaze into a box.

#### Expected behaviour:

blaze vengeance spirit into the box of eternal closure.

____

#### Versions:

- This mod: 1.1.1
- Minecraft: 1.16.5
- Forge: 36.0.58

#### Log file:

https://gist.github.com/belathus/6cb43c254c009979b4c48cbab3f796a5

**Comment by rubensworks** [comment]
Thanks for reporting!
