### ISSUE TITLE
visual bug with BoxOfEternalClosure

### ISSUE THREAD

**Issue by Divineaspect** [rubensworks/EvilCraft#863]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Visual bug, the interior of boxes of eternal closure are rotated 90 degrees.

#### Steps to reproduce the problem:

Open box of eternal closure on server

#### Expected behaviour:

not this

____

#### Versions:

- This mod: 1.1.1
- Minecraft: 1.16.5
- Forge: 36.0.58

#### Log file:

https://cdn.discordapp.com/attachments/176845387431149568/830172516227743744/2021-04-09_15.09.01.png

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I seem to be unable to reproduce this myself. All rotations work fine, both on server and client.
Could you try reproducing without any other mods installed?

**Comment by noobanidus** [comment]
@Divineaspect Do you have a list of mods installed alongside this one?
