### ISSUE TITLE
Eternal Water Block destroyed by placing annother block in the same space

### ISSUE THREAD

**Issue by Divineaspect** [rubensworks/EvilCraft#865]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Eternal Water Block destroyed by placing annother block in the same space

#### Steps to reproduce the problem:

Placed block down and then a dark tank atop it. Eternal water block was destroyed and the dark tank was one block lower then I expected. Reproduced overwriting with stone.

#### Expected behaviour:

Eternal water block should not be displaced as if it were water.

____

#### Versions:

  -  This mod: 1.1.1
  -  Minecraft: 1.16.5
  -  Forge: 36.0.58

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Divineaspect** [comment]
also when broken the eternal water block leaves behind a water source block
