### ISSUE TITLE
Brooms are uncraftable.

### ISSUE THREAD

**Issue by KirinDave** [rubensworks/EvilCraft#867]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Brooms do not appear to be craftable in the latest version.

#### Steps to reproduce the problem:

1. Make 3 broom components in unlikely reunion.
2. Place them in a crafting grid in SMP.
3. No option to craft is presented.

#### Expected behaviour:

I would expect the brooms to be craftable as the guidebook implies.
____

#### Versions:

- This mod: 1.16.5-1.1.2
- Minecraft:  1.16.5
- Forge: 36.1.1

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Do you have any other mods installed? If so, could you try with just EvilCraft?

**Comment by rubensworks** [comment]
Seems to work fine on my end.
