### ISSUE TITLE
Crash when using biome extract on headless server

### ISSUE THREAD

**Issue by belathus** [rubensworks/EvilCraft#868]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Tossed a desert biome extract on a headless server and the server immediately crashed when the extract landed.

#### Steps to reproduce the problem:

1. Run headless server.
2. Make biome extract.
3. Throw biome extract somewhere.

#### Expected behaviour:

Not crash.

____

#### Versions:

- This mod: 1.16.5-1.1.2
- Minecraft: 1.16.5
- Forge: 1.16.5-36.1.1

#### Log file:
https://gist.github.com/belathus/881a2e2cbbca6ad498c572d3e43247a2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by belathus** [comment]
Quick! Awesome.

**Comment by belathus** [comment]
Hm. Tried again on version 1.1.3. Got a slightly different crash: https://gist.github.com/belathus/5d126ad8771ae2587039bdc4f676e4bf

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/belathus/5d126ad8771ae2587039bdc4f676e4bf">gist:5d126ad8771ae2587039bdc4f676e4bf</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>
