### ISSUE TITLE
NullPointerException while generating box of closure NBT

### ISSUE THREAD

**Issue by Austin5003** [rubensworks/EvilCraft#869]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Bot of eternal closure item crashes when copying NBT data

#### Steps to reproduce the problem:

1. Place box of eternal closure
2. Break the block under the box to make it drop

#### Expected behavior:
Box of eternal closure drops with proper NBT data

____

#### Versions:

- This mod: 1.1.4
- Minecraft: 1.16.5
- Forge: 36.1.13

#### Log file:

[crash-2021-04-30_15.14.09-server.txt](https://github.com/CyclopsMC/EvilCraft/files/6407582/crash-2021-04-30_15.14.09-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!
