### ISSUE TITLE
You can only craft  the 144 bucket dark tank once

### ISSUE THREAD

**Issue by belathus** [rubensworks/EvilCraft#870]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Trying to craft a rather large dark tank. I put a half stack of iron blocks and dark blocks with the glass in the crafting grid and got one tank before the recipe seemed to lock itself. The recipe still shows up on JEI, but you cannot craft it.

I can still craft the 16 bucket versions of the tank, though, and restarting the server seems to restore the ability to craft more large tanks. And, of course, combining tanks in the crafting grid still works fine, so I can still get a large tank, it'll just cost me more glass.

#### Steps to reproduce the problem:

1. Craft a dark tank using blocks of iron and dark blocks.
2. Try to do it again.

#### Expected behaviour:

I'd expect to be able to make more than one 144 bucket dark tank using the larger recipe.

____

#### Versions:

- This mod: 1.1.4
- Minecraft: 1.16.5
- Forge: 36.1.16

#### Log file:

Can provide. I didn't see anything on the server log, though.

**Comment by rubensworks** [comment]
Thanks for reporting!
