### ISSUE TITLE
[1.16.5] Add support for NBT data in Blood Infuser recipe output

### ISSUE THREAD

**Issue by JaisDK** [rubensworks/EvilCraft#871]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

It would be great for modpack custom recipes if the blood_infuser could support NBT on the output item.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by JaisDK** [comment]
**Inspiration**
Thermal: https://github.com/KingLemming/1.16/blob/main/CoFHCore/src/main/java/cofh/lib/util/recipes/RecipeJsonUtils.java#L95
Tinkers Construct (Mantle): https://github.com/SlimeKnights/Mantle/blob/1.16/src/main/java/slimeknights/mantle/recipe/ItemOutput.java#L71
MA: https://github.com/BlakeBr0/MysticalAgriculture/blob/1.16/src/main/java/com/blakebr0/mysticalagriculture/crafting/recipe/InfusionRecipe.java#L86

Mystical Agriculture looks to be the simplest.

<blockquote><img src="https://opengraph.githubassets.com/9cad032ef4831e48e199d125af5a90ca6d4129dd62ca14143f4f40530f5c18ab/KingLemming/1.16" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/KingLemming/1.16">KingLemming/1.16</a></strong></div><div>Contribute to KingLemming/1.16 development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/c36230e2b9eec8c4aaf35953d8599bafabecece6392eff0fdc774b103052861c/SlimeKnights/Mantle" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/SlimeKnights/Mantle">SlimeKnights/Mantle</a></strong></div><div>Public shared library for Forge mods. Contribute to SlimeKnights/Mantle development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/f94cf310e254ec5c0f58d5c017ed41eb4d87262b11eb009927172530b209167d/BlakeBr0/MysticalAgriculture" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/BlakeBr0/MysticalAgriculture">BlakeBr0/MysticalAgriculture</a></strong></div><div>Adds Resource Crops, Armor, Tools, and other cool things! - BlakeBr0/MysticalAgriculture</div></blockquote>

**Comment by rubensworks** [comment]
Should be possible now since we're using JSON recipe files.
