### ISSUE TITLE
Biome extract are really hard to predict

### ISSUE THREAD

**Issue by Hiranus** [rubensworks/EvilCraft#872]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Biome extracts are really hard to predict. Sometimes each thrown bottle works, but sometimes no matter how many I throw they just... don't work. In my main gameplay I wanted to turn area into river biome but result wasn't great. Some places converted easily while others didn't want to convert at all. Here is example with desert biome bottle.
![obraz](https://user-images.githubusercontent.com/6943031/119270874-2f53ae80-bbff-11eb-95cf-850d3653bd8a.png)

#### Steps to reproduce the problem:
Its really hard to give reproduction steps on something so random. Maybe try flying backwards while constantly throwing biome extracts with biome that has different grass color. What I think you should get is nice wide line of new biome, but instead you will see something like this:
![obraz](https://user-images.githubusercontent.com/6943031/119271006-cfa9d300-bbff-11eb-84db-445bfc62e35b.png)

#### Expected behaviour:
Biome bottle is way more predictable. Maybe you could turn it into something like this:
![obraz](https://user-images.githubusercontent.com/6943031/119271119-66768f80-bc00-11eb-804c-8cfa0fd8c973.png)
Red - block where bottle was thrown: 100% chance to change biome
Yellow - 100% chance to change biome
Green - 50% chance to change biome
Blue - 25% chance to change biome

____

#### Versions:

- This mod: 
- 
![obraz](https://user-images.githubusercontent.com/6943031/119271227-ee5c9980-bc00-11eb-8dfe-97a485491163.png)

- Minecraft: 1.16.5
- Forge: 36.1.2

#### Log file:
There is nothing in the config connected to evilcraft or biome extract.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Yeah, Mojang made biomes really complicated in this MC version. Not sure I'll be able to improve this. I hope this is improved by the next MC version.

**Comment by Hiranus** [comment]
> 
> 
> Yeah, Mojang made biomes really complicated in this MC version. Not sure I'll be able to improve this. I hope this is improved by the next MC version.

@rubensworks That's why there are no other tools to change biome but this mod. When I used this Biome Border Viewer mod it looked like biomes can change on Y too. from what I noticed previously biomes changed only based on X and Z, and no matter how high or low player was, biome didn't change. 
If possible could you turn this biome extract bottle into sphere-like effect area with a bit bigger radius than what i proposed (if this will be easier)? 
If you could explain what those complications come from then maybe I will be able to come with ideas that wont be too hard to implement. I would prefer to have those extracts be a little too powerful but actually work.
