### ISSUE TITLE
Crushed Dark Gems are uncraftable

### ISSUE THREAD

**Issue by Emmeep06** [rubensworks/EvilCraft#873]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crushed dark gems do not have a crafting recipe, and do not work with immersive engineering crushers either.

#### Steps to reproduce the problem:

1. Throw evil ore/gems into crusher
2. Nothing happens

#### Expected behaviour:

Evil gems/ore should be able to be thrown into a crusher and crushed into crushed dark gems.

____

#### Versions:

- This mod: 1.1.4
- Minecraft: 1.16.5
- Forge:  36.1.24

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Emmeep06** [comment]
You're welcome! forgot to mention, but it doesnt work with Thermal's pulverizers either. pressing R on it in jei also shows nothing.

**Comment by rubensworks** [comment]
Crushed dark gems drop when breaking dark ore with a fortune pickaxe.

The crusher and pulverizer are from other mods, so it's normal that the crushed dark gem can not be produced from this; this would require custom integration in the mod or modpack.
