### ISSUE TITLE
Crash on Spirit Furnace

### ISSUE THREAD

**Issue by koratzu** [rubensworks/EvilCraft#874]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When I use the spirit furnace after a while it saves the game and crashes, it only happens on client side and I still don't know why.

#### Steps to reproduce the problem:

1. Introduce a Box of Eternal Clousure
2. Introduce some blood
3. Exit the Spirit Furnace 
4. Click on the Spirit Furnace

#### Expected behaviour:

To not crash, or close the game

____

#### Versions:

- This mod: EvilCraft-1.16.5-1.1.5 - CyclopsCore-1.16.5-1.11.7
- Minecraft: 1.16.5
- Forge: 1.16.5-forge-36.1.25

#### Log file:

[crash-2021-06-04_01.38.00-client.txt](https://github.com/CyclopsMC/EvilCraft/files/6596335/crash-2021-06-04_01.38.00-client.txt)

https://pastebin.com/wK44tuXR

**Comment by rubensworks** [comment]
Thanks for reporting!
