### ISSUE TITLE
Crash on empty entangled chalice

### ISSUE THREAD

**Issue by aburone** [rubensworks/EvilCraft#875]
#### Issue type:

- :bug: Bug

____

#### Short description:
I have an entangled chalice with a Pipez pipe emptying into a big dark tank.
I was looking at it, about to move some things when the chalice got empty (the tank was feeding the furnace). The second it got empty, the game crashed.
Can't log in into the same game again, each time it finishes loading, it crashes with the same error

#### Steps to reproduce the problem:

1. Use Pipez to feed a tank from a chalice
2. Consume blood with some machine that has a chalice in the same network 
3. Be looking at the chalice when it gets empty

The chalice got empty several times, The only difference was I was looking at it this time
#### Versions:

- Minecraft: 1.16.5
- Forge: 36.1.4
EvilCraft-1.16.5-1.1.5.jar
pipez-1.16.5-1.2.7.jar

#### Log file:

https://hastebin.com/raw/siyakineye

**Comment by rubensworks** [comment]
Thanks for reporting!
