### ISSUE TITLE
When player use "spirit_reanimator" to create spawnegg server crash

### ISSUE THREAD

**Issue by beibao233** [rubensworks/EvilCraft#876]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Kill a creature 
2. Use closure to capture soul
3. Destory closure
4. Put closure in spirit reanimator
#### Expected behaviour:
Game won't crash and create a spawn egg

____

#### Versions:

- This mod: both 1.1.0 and 1.1.5
- CyclopsCoreVersion: 1.16.5-1.11.7
- Minecraft: 1.16.5
- Forge: 36.1.24
- Server: Mohist-1.16.5-629

#### Log file:

https://pastebin.com/n6YSzU4j - Crash-Report

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by beibao233** [comment]
> Thanks for reporting!

I am a server owner of nonprofit in China. I love player playing in my server.
When they know I have to delete EvilCraft they are very sad.
So I do this Issue report. Hope EvilCraft can be better in future.
Thanks you guys make this great mod!
