### ISSUE TITLE
Crash when looking up the use for Condensed Blood in JEI.

### ISSUE THREAD

**Issue by SephirothWS** [rubensworks/EvilCraft#880]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Looking up the uses of **Condensed Blood** in JEI crashes the client.

#### Steps to reproduce the problem:

1. ... Search JEI for **Condensed Blood**
2. Mouse Over **Condensed Blood** in JEI's listing
3. Press *U* on the keyboard to look up what its used in.
4. ???
5. Profit.

#### Expected behaviour:

JEI would display what **Condensed Blood** can be used for.

____

#### Versions:

Minecraft Version: 1.16.5
Minecraft Version ID: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_301, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 3534355088 bytes (3370 MB) / 7121928192 bytes (6792 MB) up to 7635730432 bytes (7282 MB)
CPUs: 16
JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx8192m
FML: 36.1
Forge: net.minecraftforge:36.1.65
EvilCraft: EvilCraft-1.16.5-1.1.6

#### Log file:

[crash-2021-07-26_00.37.08-client.txt](https://github.com/CyclopsMC/EvilCraft/files/6876495/crash-2021-07-26_00.37.08-client.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
That's a first...

Probably shouldn't be creating immutable lists in places like this: https://github.com/CyclopsMC/EvilCraft-Compat/blob/master-1.16/src/main/java/org/cyclops/evilcraftcompat/modcompat/jei/bloodinfuser/BloodInfuserRecipeJEI.java#L85-L89

<blockquote><img src="https://opengraph.githubassets.com/6b0e3c729326cded0ffb0347efcca9bc7403f51e26f30012453d1aee2a000b29/CyclopsMC/EvilCraft-Compat" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EvilCraft-Compat">EvilCraft-Compat/BloodInfuserRecipeJEI.java at master-1.16 · CyclopsMC/EvilCraft-Compat</a></strong></div><div>EvilCraft compatibility with other mods. Contribute to CyclopsMC/EvilCraft-Compat development by creating an account on GitHub.</div></blockquote>

**Comment by rubensworks** [comment]
Actually, that should be mutable...

@SephirothWS I see you have a bunch of other mods installed. So chances are big that another mod is causing the problem. Could you try again without any other mods installed?

**Comment by SephirothWS** [comment]
Can't load up the mod just on its own because it complains about requiring some cyclopscore mod. I miss when mods didn't need multiple jars to operate.

That said, an instance with just JEI, CyclopsCore and Evilcraft does NOT crash when looking up the uses of condensed blood. So ... guess its down to figure out what mod is causing the incompatibility here.

**e**: Trying to enable mods one by one on my list and getting extremely frustrated with mods that need multiple jars as I'm loading the instance and getting screen about mods whining some stupid coremod isn't installed. ... Its something I don't have the patience to wade through, so I am not sure which mod is causing this problem. So what I have done is cleared the logs directory, caused the crash and I am attaching it here.

[debug.log](https://github.com/CyclopsMC/EvilCraft/files/6881357/debug.log)
[latest.log](https://github.com/CyclopsMC/EvilCraft/files/6881358/latest.log)

**Comment by rubensworks** [comment]
> just JEI, CyclopsCore and Evilcraft does NOT crash

Thanks for checking!

**Comment by SephirothWS** [comment]
@rubensworks Cool, glad the issue is closed. Do you have any idea what is causing the crash or is that up to me to find the cause?

**Comment by rubensworks** [comment]
There's probably another mod in your pack that has an illegal JEI implementation, which also incorporates Condensed Blood (probably because it's a fluid handler).
