### ISSUE TITLE
Multiplayer: Blood Infuser does not give proper tier promises when using appropriate promises of tenacity

### ISSUE THREAD

**Issue by 2468cool** [rubensworks/EvilCraft#882]
#### Issue type:

- :bug: Bug

____

#### Short description:

When playing in multiplayer and trying to create higher tier bows of promises, it instead only creates tier zero promises, even with correct promises of tenacity as shown in screenshots. This error does not happen in single-player. Playing with a custom made modpack but since error only occurs in multiplayer I would think the mods installed do not affect the bug.

#### Steps to reproduce the problem:

1. Play in multiplayer
2. Add a promise of tenacity 1 to the blood infuser
3. Fill blood infuser
4. Place a dusted bowl of promises into the blood infuser and wait to complete

#### Expected behaviour:

Placing a dusted bowl of promises into the Blood Infuser while a promise of tenacity 1 is inside the infuser should give a bowl of promises tier 1.

____

#### Versions:

- This mod: 1.1.6
- Minecraft: 1.16.5
- Forge: 1.16.5-36.2.0

![2021-08-14_21 38 15](https://user-images.githubusercontent.com/83475290/129464414-fd5e1401-35c3-4766-8a01-9e19bd384201.png)
![2021-08-14_21 38 17](https://user-images.githubusercontent.com/83475290/129464415-a4b32d98-b0f9-4b6c-9f10-85a69b48fc5a.png)
![2021-08-14_21 38 19](https://user-images.githubusercontent.com/83475290/129464416-f929e2a9-069e-497c-85c8-4f35e3d6d004.png)
![2021-08-14_21 38 25](https://user-images.githubusercontent.com/83475290/129464417-1531dddc-5e66-4779-9721-69d3c8b8cb22.png)
![2021-08-14_21 39 17](https://user-images.githubusercontent.com/83475290/129464418-7ce1bcd0-d80b-42d7-a673-5d6bd7744f0c.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by 2468cool** [comment]
You're welcome. Updated the post to include pictures and correct versions

**Comment by rubensworks** [comment]
Are you using the Performant mod? If so, please remove it. It breaks mods (#847).

**Comment by 2468cool** [comment]
You are correct. That fixed the issue. Thank you very much for your help.
