### ISSUE TITLE
Immersive Engineering integration not functioning

### ISSUE THREAD

**Issue by squidgirll** [rubensworks/EvilCraft#883]
I'm using a modpack with the latest versions of Evilcraft and Immersive Engineering, and using the Industrial Squeezer does not produce blood from Undead logs or leaves like the Origins of Darkness book says it should

**Comment by rubensworks** [comment]
@squidgirll Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
