### ISSUE TITLE
Box of Eternal Closure render bug

### ISSUE THREAD

**Issue by VallenFrostweaver** [rubensworks/EvilCraft#885]
Minecraft 1.16.5
Forge 3.2.2
EvilCraft 1.1.6
Curseforge Modpack: Magical Mischief Tour 0.11beta

The Eternal Boxes of Closure all seem to open with the interior askew. Referencing previous issue #863 as well. Image below: 
![image](https://user-images.githubusercontent.com/13642054/132692665-5c049157-90b8-4a81-a2ee-56d7757918b3.png)

**Comment by rubensworks** [comment]
As mentioned in #863, I am unable to reproduce the issue myself.
Are you placing the box in a special way? What if you place the box at different rotations?
It would be good if you could share a detailed step-by-step guide on how you cause the bug.

**Comment by VallenFrostweaver** [comment]
It appears like this in ANY orientation at any time any box I have come across or closed and re-opened. There is no circumstance where it actually lines up properly that I can find. I believe it may be another mod interaction but have no idea how to test for this. Using the modpack listed (very heavy pack) it does this. I'm happy to try more things.

**Comment by rubensworks** [comment]
> I believe it may be another mod interaction but have no idea how to test for this.

Could you try it without any other mods installed?
That way, we know if it's cross-mod interaction or just environment-specific.

**Comment by VallenFrostweaver** [comment]
I just tested with all the same setup but no modpack. Only the required mods for EvilCraft and vanilla. It renders properly in this setting.

Thus it has to be another mod interaction. I do NOT use Optifine. As far as changing things, I also tried adding in a couple mods that I know changes how things are rendered including Better Foliage and Dynamic Surroundings (plus required files to run them) and these did NOT have an effect on the rendering so are unlikely to be at fault. I can't think of where to start to find the mod that is causing the issue beyond this.

**Comment by rubensworks** [comment]
Thanks for checking!

**Comment by rubensworks** [comment]
Changed some things that may fix the problem.
Please let me know if it still renders incorrectly in your pack, so we can re-open this issue.

**Comment by VallenFrostweaver** [comment]
> Changed some things that may fix the problem.
> Please let me know if it still renders incorrectly in your pack, so we can re-open this issue.

It's still rendering the same. No changes. 😢

**Comment by rubensworks** [comment]
No idea what's going on then tbh 🤷‍♂️ 
If someone is able to pinpoint what mod exactly triggers the the rotation issue, then we could investigate what causes the conflict.

**Comment by VallenFrostweaver** [comment]
> No idea what's going on then tbh 🤷‍♂️
> If someone is able to pinpoint what mod exactly triggers the the rotation issue, then we could investigate what causes the conflict.

I'll ask my community if they have any input on it. Many are also modders so there may be some insights that could help.

**Comment by noobanidus** [comment]
If the author of the previous issue is able to provide a mod list, it might be possible to do an intersection of the MMT pack and their pack to see what the issue could be.

I'll ask around to see if anyone is aware of anything that changes the ender portal renderer.

[MMT mod list](https://gist.github.com/noobanidus/5909ec317136c4bd052c425e99a59b8b).
