### ISSUE TITLE
Spirit Furnace mobDrops config not respecting changes

### ISSUE THREAD

**Issue by VallenFrostweaver** [rubensworks/EvilCraft#886]
Minecraft 1.16.5
Forge 3.2.2
EvilCraft 1.1.6
Curseforge Modpack: Magical Mischief Tour 0.11beta

Using the example in the Spirit Furnace config (see image below) I am not able to get the Spirit Furnace to give Sheep drops instead of Pig drops. Ultimately, I want to have artifacts:mimic give another mob drop but I can't get that to work let alone the example. I'm sure it may be user error here.
![image](https://user-images.githubusercontent.com/13642054/132701563-785c7b4e-f31b-46dc-97c0-db5e884ef13e.png)

EDIT: I also tried with single quote marks as shown in the example just in case and that didn't produce the results expected either.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by VallenFrostweaver** [comment]
> Thanks for reporting!

I just tested and it's partially working. Using the pig/sheep example, it gives mutton but no wool. I suspect it's because the sheep could be of any number of colors...?

**Comment by rubensworks** [comment]
> Using the pig/sheep example, it gives mutton but no wool. I suspect it's because the sheep could be of any number of colors...?

Yeah, It's very likely that the wool-dropping-logic is hardcoded, and is not present within a loot table.
If you want wool as well, then it might be better to create a new loottable within a custom data pack.

**Comment by VallenFrostweaver** [comment]
> > Using the pig/sheep example, it gives mutton but no wool. I suspect it's because the sheep could be of any number of colors...?
> 
> Yeah, It's very likely that the wool-dropping-logic is hardcoded, and is not present within a loot table.
> If you want wool as well, then it might be better to create a new loottable within a custom data pack.

I think it's fine though. No need to address this. It's here for posterity should anyone have an issue in the future. Thank you for fixing it!
