### ISSUE TITLE
minecraft (1.12.2) crash 

### ISSUE THREAD

**Issue by wingtofly** [rubensworks/EvilCraft#887]
#### Issue type:

- :bug: Bug 

____

#### Short description:

minecraft (1.12.2) crash after i click (shift+right click) to the entangled chalice(with blood) to autofill or not autofill with me left hand(non-main hand),and i can't enter that world again.

#### Steps to reproduce the problem:

1. filling your entangled chalice with some blood 

2.putting it on your left hand
3. shift right click the entangled chalice to switch on or off the autofill
4. 4.minecraft crash

#### Expected behaviour:

switching on or off autofill without crash.

____

#### Versions:
- cyclopscore-1.12.2-1.6.6
- This mod: EvilCraft-1.12.2-0.10.78
- Minecraft: 1.12.2
- Forge: 1.12.2-forge-14.23.5.2855

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, but 1.12 is not supported anymore.
