### ISSUE TITLE
Blood Extractor duplicate

### ISSUE THREAD

**Issue by bigenergy** [rubensworks/EvilCraft#888]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Blood Extractor duplicate crafting

#### Steps to reproduce the problem:

https://www.youtube.com/watch?v=ZZo9fgHWk3k

____

#### Versions:

- This mod: EvilCraft-1.16.5-1.1.7
- Minecraft: 1.16.5
- Forge: 1.16.5-36.2.4

**Comment by rubensworks** [comment]
Thanks for reporting!
