### ISSUE TITLE
Invalid character in tooltips

### ISSUE THREAD

**Issue by Regnander** [rubensworks/EvilCraft#891]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Retrieve an item that can hold blood.
2. Hover your cursor over said item to see the current amount.
3. An invalid character can be seen in the tooltip.

![nbsp](https://user-images.githubusercontent.com/17113053/139563628-e7598716-8055-40aa-a73c-fbdefb0f4280.png)

#### Expected behaviour:

I expected the thousand separators to show up as regular spaces, but I got an NBSP character instead.
____

#### Versions:

- This mod: 1.16.5-1.1.8
- Minecraft: 1.16.5
- Forge: 1.16.5 - 36.2.8

**Comment by rubensworks** [comment]
Thanks for reporting!
