### ISSUE TITLE
[1.16.5] Crash with Chisel & Bits when taking chisel in hand

### ISSUE THREAD

**Issue by Lgmrszd** [rubensworks/EvilCraft#892]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When selecting hotbar slot with chisel, the game crashes.

#### Steps to reproduce the problem:

1. Give yourself chisel
2. Game crashes when hotbar slot with the chisel is selected.

#### Expected behaviour:

Game does not crash

____

#### Versions:

* MC Version: 1.16.5
* Forge version: 36.2.8
* C&B: 1.0.43
* EvilCraft: 1.16.5-1.1.8
* CyclopsCore: 1.16.5-1.12.0

#### Log file:
[link](https://gist.github.com/Lgmrszd/4f528c643a9905d31bff3e1a379b931d)

____

Issue in the C&B tracker: https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/784

**Comment by rubensworks** [comment]
Thanks for reporting!
