### ISSUE TITLE
Can't get hardened blood with a lighter

### ISSUE THREAD

**Issue by Mgil10** [rubensworks/EvilCraft#893]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Burning hardened blood with the lighter does not turn into hardened blood fragments

#### Steps to reproduce the problem:

1. Put blood on the ground
2. Wait for the blood to harden
3. Burn the blood with a lighter

#### Expected behaviour:

This would have to give me shards of hardened blood

____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.16.5
- Forge: 36.2.8

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You need to break the hardened blood with your flint and steel.
