### ISSUE TITLE
Breaking an Eternal Water Block drops nothing

### ISSUE THREAD

**Issue by belathus** [rubensworks/EvilCraft#896]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Breaking an eternal water block drops nothing using both bare hands and a pickaxe. I haven't tried silk touch.

#### Steps to reproduce the problem:

1. craft eternal water block
2. place
3. break it
4. check for drops

#### Expected behaviour:

I would think that this block is supposed to drop normally.

____

#### Versions:

- This mod:  1.1.11
- Minecraft: 1.16.5
- Forge: 36.2.21

**Comment by rubensworks** [comment]
Thanks for reporting!
