### ISSUE TITLE
Entangled Chalice Infinite liquid

### ISSUE THREAD

**Issue by WitherZiby** [rubensworks/EvilCraft#897]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Entangled Chalice gives infinite liquids.
Here's a video of me preforming it: https://youtu.be/r6jVpzEV1sY

#### Steps to reproduce the problem:

1. Craft the Entangled Chalice
2. Unstack them 
3. Place one down and fill it with any liquid
4. Activate Omni-supply with the one in your inventory
5. Hold any fillable items (pendants, tanks, or buckets) or place it in a machine to fill

#### Expected behaviour:

I believe the liquid in the Entangled Chalice should be drained. 

____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.16.5
- Forge: 36.2.20

**Comment by rubensworks** [comment]
Thanks for reporting!
