### ISSUE TITLE
[Feature Request] Option to disable dark shrines

### ISSUE THREAD

**Issue by notWaterGuy12** [rubensworks/EvilCraft#898]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

There are options to change where the structures generate, but no option to disable them entirely. It would be nice for pack devs who want to change how the environmental accumulator is obtained or who just don't want the structure to generate at all.

**Comment by rubensworks** [comment]
Thanks for the suggestion!
