### ISSUE TITLE
Game crashes at startup: java.lang.ArrayIndexOutOfBoundsException: 4096

### ISSUE THREAD

**Issue by kurpav00** [rubensworks/EvilCraft#899]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The game with a custom modpack crashes randomly on startup, reporting java.lang.ArrayIndexOutOfBoundsException: 4096 and EvilCraft  as the source of the error.
#### Steps to reproduce the problem:

Unknown.

#### Expected behaviour:

The game to load up and not crash.
____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.16.5
- Forge: 36.2.22

#### Log file:

https://pastebin.com/FgYzat6w

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Nothing I can do about this on my end unfortunately.
This seems to be caused by another (core)mod, as the item color code in the stacktrace does not correspond to vanilla.
Please try removing mods from your pack until you find the offending mod.
