### ISSUE TITLE
Config has no effect on any of the configurable features

### ISSUE THREAD

**Issue by notWaterGuy12** [rubensworks/EvilCraft#900]
#### Issue type:

- :bug: Bug 

____

#### Short description:

All changes I have attempted to the "common" config have had no effect. This includes both option that use true/false and the ones that use numerical values.

#### Steps to reproduce the problem:

1. Change a config
2. Items will still generate in loot tables, structures still generate, etc.

#### Expected behaviour:

Self explanatory. If it helps, I've noticed that the mod only prints configs to "common". Maybe something in forge is not allowing certain things to work because it's all in the common config file? I honestly don't know how this could be happening.

____

#### Versions:

- This mod: 1.1.12
- Minecraft: 1.16.5
- Forge: 36.2.23

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you give a concrete example of a setting that does not work for you?

Are you running a client-side world or on a server?

**Comment by notWaterGuy12** [comment]
I'm using a client-side world. The main thing I noticed was the dark temple config not working. I attempted to set the dark gem veinsPerChunk to 0, which also wasn't working. The only other major part I noticed was that the loot table configs were also not working. I was using it in a modpack, but after making a fresh instance with just EvilCraft the issues still persisted.

**Comment by rubensworks** [comment]
Most worldgen features seem to be not (easily) configurable in Forge anymore, so they have now been removed to avoid confusion.
