### ISSUE TITLE
Crash when empowering Exalted Crafter via lightning

### ISSUE THREAD

**Issue by Timbroglio** [rubensworks/EvilCraft#901]
Hello! I'm one of the developers on the modpack Smashing Mods Together, we're looking to add Evilcraft in the next patch, so I've been doing some testing. I suspect this is a modpack-specific issue, but I'm unsure as to the exact cause and would appreciate any information you have.

#### Issue type:

- :bug: Bug 

____

#### Short description:

Error: Ticking entity when hitting an Exalted Crafter with a lightning bolt

#### Steps to reproduce the problem:

1. Drop Exalted Crafter as an item
2. Strike item with a lightning bolt

#### Expected behaviour:

Exalted Crafter becomes empowered

____

#### Versions:

- This mod: 1.1.13
- Minecraft: 1.16.5
- Forge: 36.2.23

#### Log file:

[crash-2022-02-09_13.48.19-server.txt](https://github.com/CyclopsMC/EvilCraft/files/8036489/crash-2022-02-09_13.48.19-server.txt)
[2022-02-09-1.log](https://github.com/CyclopsMC/EvilCraft/files/8036517/2022-02-09-1.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Doesn't seem to be a cross-mod issue, just a bug in EvilCraft (that should be very easy to fix).
