### ISSUE TITLE
cannot access main blood chest inventory from outside

### ISSUE THREAD

**Issue by plushbean** [rubensworks/EvilCraft#904]
#### Issue type:

- :bug: Bug 

____

#### Short description:

both the colossal and normal blood chests cannot have their actual inventory accessed by any outside methods, including InDy tunnels and readers.any side always accesses the blood slot

#### Steps to reproduce the problem:

1.place a hopper
2.place a blood chest on top
3.insert any item into the main blood chest inventory
4.it does not move 
![2022-03-14_17 57 05](https://user-images.githubusercontent.com/70825631/158217025-ca7ca5b3-516e-474d-bcc6-064b65a0db5c.png)
![2022-03-14_17 57 17](https://user-images.githubusercontent.com/70825631/158217032-4f1ff6d2-e9d0-41d4-b74e-b1d6ba24483f.png)
![2022-03-14_17 57 20](https://user-images.githubusercontent.com/70825631/158217035-da5a50a4-810d-492f-834f-113ea8d43832.png)

#### Expected behaviour:

blood inventory accessible from sides and main inventory accessible from top and bottom

____

#### Versions:
![unknown-198](https://user-images.githubusercontent.com/70825631/158216925-4fc000ca-71f2-4d51-8c97-f42edceb00cb.png)
![unknown-423](https://user-images.githubusercontent.com/70825631/158216928-ec8f6f06-012c-40da-87cb-c4a278aef655.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by plushbean** [comment]
there is now a new issue where you cannot access the blood tank of a colossal chest with piping. normal blood chest is accessible. both were tested with fluid translocators from the translocator mod, fluid readers from InDy and fluid parts from InTu

**Comment by plushbean** [comment]
oh and every side of a colossal blood chest has 0 slots when checked with inventory readers readers and is not accessible in that capacity either. so this fix pretty much only fixed normal blood chests

**Comment by plushbean** [comment]
nvm sorry apparently you cannot access anything when interacting with reinforced planks only the actual core works,my bad

**Comment by rubensworks** [comment]
> nvm sorry apparently you cannot access anything when interacting with reinforced planks only the actual core works,my bad

This is indeed the intended behaviour.
