### ISSUE TITLE
Crash when loading without CommonCapabilities

### ISSUE THREAD

**Issue by Geicosuave** [rubensworks/EvilCraft#905]
#### Issue type:

- :bug: Bug 

____

#### Short description:
I apologize if i did something wrong in this report, i havent done this before, but anyway
The game lets me load into the world but when loading certain chunks it'll crash. With my basic knowledge looking at the report it seems to have something to do with the sanguinary accumulator.

#### Steps to reproduce the problem:

1. Create a new world and load a chunk with an evil temple

#### Expected behaviour:
Normal chunk loading

____

#### Versions:

- This mod: tried with both 1.1.14 and 1.1.15
- Minecraft: 1.18.1
- Forge: 39.0.64

#### Log file:

[crash-2022-03-16_05.25.47-server.txt](https://github.com/CyclopsMC/EvilCraft/files/8260633/crash-2022-03-16_05.25.47-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Ouch, there seems to be a hard dependency on the commoncapabilities, while it should be a soft dependency.

Just installing the commoncapabilities mod should make the error go away, until this bug is fixed.
