### ISSUE TITLE
[1.18.1] Crash when placing Blood Infuser

### ISSUE THREAD

**Issue by Darkfiend009** [rubensworks/EvilCraft#907]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Server crash when placing the Blood Infuser.

#### Steps to reproduce the problem:

1. Craft Blood Infuser
2. Place Blood Infuser
3. Crash

#### Expected behaviour:

The Blood Infuser placed in the world without crashing.
____

#### Versions:

- This mod: 1.18.1-1.1.16
- Minecraft: 1.18.1
- Forge: 39.1.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Not sure why this is still happening, this should be fixed in this release.

Could you try without any other mods installed? Perhaps some other mod is messing with things.

See #905 for a temp workaround.

**Comment by Darkfiend009** [comment]
Sure! I just tested with the same mod and forge versions listed above in a single player world with only Evilcraft and Cyclops Core:

Crash Report: https://pastebin.com/vhE2TSR7

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/vhE2TSR7">---- Minecraft Crash Report ----// Shall we play a game?Time: 4/4/22, 11:1 - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by yuto226** [comment]
Hi! I have encountered a similar bug. I hope this will be resolved soon.
Thank you!
