### ISSUE TITLE
Undead trees not producing bloodstains

### ISSUE THREAD

**Issue by Johannason** [rubensworks/EvilCraft#909]
#### Issue type:

- :bug: Bug

____

#### Short description:

The blood-dripping leaves of the Undead Tree are not producing bloodstains on the ground.  
This hamstrings passive blood collection with a pedestal, without building some form of mobfarm.

#### Steps to reproduce the problem:

1. Plant undead sapling.
2. Bonemeal sapling (optional).
3. Stare at ground underneath tree (???).

#### Expected behaviour:

In previous versions, Undead Trees would produce bloodstains on the ground, similar to the ones created when a mob dies of fall damage. These could be captured and tanked with Sanguinary Pedestals for easy blood generation.

____

#### Versions:

- This mod: EvilCraft-1.18.1-1.1.17, CyclopsCore-1.18.1-1.13.3
- Minecraft: 1.18.1
- Forge: forge-1.18.1-39.1.2

Tested and confirmed with _only_ EvilCraft and CyclopsCore installed, no other mods present.

#### Log file:

(Not a crash issue, no log entries created after world generation)

**Comment by rubensworks** [comment]
Thanks for reporting!
