### ISSUE TITLE
Vengeance Spirits can be targeted even when invisible, which may cause some attacks to miss

### ISSUE THREAD

**Issue by James103** [rubensworks/EvilCraft#910]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If a mob is killed, a Vengeance Spirit spawns. Even if that Vengeance Spirit isn't visible, it can still be targeted, and will cause any attack intended to target a mob behind the Spirit to miss, including melee hits and projectiles.

#### Steps to reproduce the problem:

1. Reproduce the following setup in a superflat world. The stone blocks can be any full cube and the trapdoor must be open, but the type of wood used to make it doesn't matter.
![image](https://user-images.githubusercontent.com/37945304/167907137-994579bd-69a4-4208-bef3-fedcfb7d0019.png)
2. Spawn two zombies, one in each hole.
3. Stand on the block with the trapdoor, pressing against the trapdoor, facing the two zombies.
4. Give yourself a sword and start attacking.
5. Once the first zombie is killed, keep attacking.
6. Subsequent attacks will miss for the next few seconds. During that time, WAILA says that you are targeting a Vengeance Spirit instead of an actual zombie.
7. Once the vengeance spirit disappears, keep attacking. The second zombie should die in a few hits once the first vengeance spirit despawns.

The above steps can be repeated with a bow and arrows with the same results. Once the first zombie is killed, subsequent shots will bounce midway to the second zombie and may instead damage/kill the shooter.

#### Expected behaviour:

If a Vengeance Spirit isn't visible, it should not affect your ability to attack mobs or place blocks.
Physical projectiles should go through Vengeance Spirits and hit whatever's behind instead of bouncing off them and potentially hitting the shooter.

____

#### Versions:

- CyclopsCore: 1.13.6
- EvilCraft: 1.1.19 
- Minecraft: 1.18.2
- Forge: 40.1.19

#### Log file:

_No relevant entries_

**Comment by rubensworks** [comment]
Thanks for reporting!
