### ISSUE TITLE
Dark Tank Reset on break

### ISSUE THREAD

**Issue by Mxater** [rubensworks/EvilCraft#911]
Issue type:

    🐛 Bug

Short description:

When destroy Dark Tank with any object in hand, or without items, the Dark Tank reset to a empty Dark Tank with reset capacity.

Steps to reproduce the problem:

  1. Craft 2 Dark Tank
  2. Craft 2 Dark Tank together to get a 32 mB Dark Tank.
  3. Place the Dark Tank.
  4. Put some Blood inside.
  5. Destroy the Dark Tank.
  6. Receive a empty 16 mB Dark Tank.

Expected behaviour:

In previous versions, when destroy a Dark Tank, I get the same Dark Tank with blood Inside.

Versions:
-   This mod: EvilCraft-1.18.2-1.1.19, CyclopsCore-1.18.2-1.13.6
-   Minecraft: 1.18.2
-   Forge: forge-1.18.2-40.1.19

**Comment by rubensworks** [comment]
Thanks for reporting!
