### ISSUE TITLE
Spirit reanimator failure with modded mobs

### ISSUE THREAD

**Issue by Divineaspect** [rubensworks/EvilCraft#912]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Spirit Reanimator isn't generating spawn eggs for modded mobs.

#### Steps to reproduce the problem:

1. Capture a non-vanilla mob
2. Attempt to impart into an egg

#### Expected behaviour:

I expected to get spawn eggs
Tested with mobs from Ars Nouveau, Primal Magic, Hexeri

____

#### Versions:

- This mod: 1.18.2-1.1.20
- Minecraft: 1.18.2
- Forge: 40.1.20

**Comment by rubensworks** [comment]
Thanks for reporting!
