### ISSUE TITLE
Dark tanks seems to reset their data after breaking

### ISSUE THREAD

**Issue by Z-S117** [rubensworks/EvilCraft#913]
#### Issue type:

- :bug: Bug 

____

#### Short description:

A few issues regarding the Dark tank in order of severity.
1) When picking up a dark tank the liquid contained inside disappears. Silk does not seem to affect this.

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Z-S117** [comment]
Moderator Via Discord notified me there was a fix in the most recent update of evilcraft.
