### ISSUE TITLE
Tank can't hold liquid when breaking and give back wrong mB

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [rubensworks/EvilCraft#914]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Dark tanks not holding liquid when breaking. Multiple crafted tanks, like 128.000 mb placed, and broken gives back 16.000 mb tank.

#### Steps to reproduce the problem:

1. Craft 2-6 Tanks
2. Craft 96.000 mB tank
3. place tank, fill liquid
4. break tank
5. get back empty tank with 16.000 mB

#### Expected behaviour:

To hold the liquid if broken. To give back the correct  x mB back when broken.

____

#### Versions:

- This mod: [EvilCraft-1.16.5-1.1.15.jar](https://www.curseforge.com/minecraft/mc-mods/evilcraft/files/3693401)
- Minecraft: 1.16.5
- Forge: 36.2.34

**Comment by rubensworks** [comment]
Thanks for reporting!
