### ISSUE TITLE
1.18.2 Dark Ore Config

### ISSUE THREAD

**Issue by Tyrius1** [rubensworks/EvilCraft#916]
#### Issue type:

- :heavy_plus_sign: Feature request 
A config to toggle Dark Ore Generation
____

#### Short description:

Allowing the ore generation to be disabled allows for using mods like Ore-Tweaker to generate unique ore veins in unique biomes.
Alternatively, a biome whitelist config(or biome tag in data) added to the mod for the ore gen as well as min/max Y, vein chance and vein size would work as well.

Thank you!

**Comment by rubensworks** [comment]
Thanks for the suggestion!
