### ISSUE TITLE
Werewolvian Villager created by lightning does not generate tier 1 trades

### ISSUE THREAD

**Issue by belathus** [rubensworks/EvilCraft#917]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When striking a villager with lightning and they become a werewolvian, they spawn with two of three trades: emeralds for inverted potentia, emeralds for blooks, and undead saplings for emeralds. I looked through the [source](https://github.com/CyclopsMC/EvilCraft/blob/master-1.18/src/main/java/org/cyclops/evilcraft/entity/villager/VillagerProfessionWerewolf.java#L29-L31) and realized that these are tier 2 trades.

#### Steps to reproduce the problem:

1. Strike villager with lightning
2. observe trades

#### Expected behaviour:

Looking at the source, I would expect the villager to generate with tier 1 trades. I'm guessing that since he generates as a tier 2 villager, he does not get those. Which is a shame, as I'd love to be able to buy dark gems for emeralds.

____

#### Versions:

- This mod: 1.1.21
- Minecraft: 1.18.2
- Forge: 40.1.20

#### Log file:
N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
