### ISSUE TITLE
 crash when throw a weather container in an environmental accumulator

### ISSUE THREAD

**Issue by ToxicDwaechi** [rubensworks/EvilCraft#919]
#### Issue type:

- :bug: Bug 

____

#### Short description:

 Сrash when i throw a weather container in an environmental accumulator

#### Steps to reproduce the problem:

1. Throw a weather container in an environmental accumulator

#### Expected behaviour:

____

#### Versions:

- This mod: 1.1.16
- Minecraft: 1.16.5
- Forge: 36.2.34

#### Log file:

https://pastebin.com/gccRDuCx

UPD: found logs. mb it will help
https://drive.google.com/file/d/1qTI7obn0EpdXZvS-S6PVu_Bse2OenRpZ/view?usp=sharing

**Comment by rubensworks** [comment]
Thanks for reporting!
