### ISSUE TITLE
Werewolves do not drop flesh

### ISSUE THREAD

**Issue by jpruitt2297** [rubensworks/EvilCraft#920]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Killed 100+ werewolf villagers (both forms, idk if makes a difference) with max looting sword, no werewolf  flesh dropped.
Took a look through config to see if maybe a drop rate config. Found that the werewolf flesh drop chance config says humanoidFlesh rather than werewolfFlesh. Tried to change that in the config, booted instance up again, config reverted back. Is this an error? Or is there something I'm missing?

#### Steps to reproduce the problem:

1. Install Evilcraft and all requirements of said version below.
2. Enter world and either find/spawn werewolf  villagers.
3. Loot their corpses.
4. Repeat step 2 and 3 until satisfied.

#### Expected behaviour:
Werewolf should have dropped flesh.

____

#### Versions:

- This mod: 1.1.16
- Minecraft: 1.16.5
- Forge: 36.2.34

**Comment by rubensworks** [comment]
Thanks for reporting!
