### ISSUE TITLE
monster spirit appearing wittout any killing and in wrong dimension

### ISSUE THREAD

**Issue by Szadeck** [rubensworks/EvilCraft#921]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I've got Alex mobs and Evilcraft in my personal mod list. I was testing them when, in a fresh new world, i saw a spirit of a void worm (a boss from alex mob normally appearing  in the end) in a plain biome in overworld. I didn't kill any monster yet and could manage to capture the void worm spirit using the usual stuff from evil craft in a spirit chest. Then i could reincarnate it into an egg and summon it right away.

#### Steps to reproduce the problem:

1. Create a fresh world with Alex mob
2. Equip the tools to see spirit
3. wander around

#### Expected behaviour:

I think that we are not suppose to see any spirit from a creature we didn't kill and even less a spirit from a monster who belong to a different dimension. 

____

#### Versions:

- This mod: EvilCraft-1.18.2-1.2.0
- Minecraft: 1.18.2
- Forge: 40.1.52

#### Log file:

No log as there wasn't any error.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
That's not a bug, it's a feature :-)

If you don't want this, you can play around with any of these config options: https://github.com/CyclopsMC/EvilCraft/blob/master-1.18/src/main/java/org/cyclops/evilcraft/entity/monster/EntityVengeanceSpiritConfig.java#L30-L48

<blockquote><img src="https://opengraph.githubassets.com/b0358f68edae94813be9ecd2074ac460504176ba672d14c39800693e94bbb116/CyclopsMC/EvilCraft" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EvilCraft">EvilCraft/EntityVengeanceSpiritConfig.java at master-1.18 · CyclopsMC/EvilCraft</a></strong></div><div>An evil mod for Minecraft. Contribute to CyclopsMC/EvilCraft development by creating an account on GitHub.</div></blockquote>
