### ISSUE TITLE
Blood Stains cause null pointer crashes

### ISSUE THREAD

**Issue by dkmk100** [rubensworks/EvilCraft#922]
#### Issue type:

- :bug: Bug

____

#### Short description:

When blood stains spawn on other modded blocks, they can lead to a crash as blood stains pass an unexpected null value to 

#### Steps to reproduce the problem:

1. have a block that overrides isValidSpawn and uses the entity
2. have a mob die by falling on the block
3. it'll crash when it tries to spawn a blood stain

#### Expected behaviour:

for a bloodstain to spawn and the game to keep running. If you insist on a valid spawn check, may I suggest either using the dying entity OR haivng a try-catch and doing something else on error?
____

#### Versions:

- This mod: 1.2.0
- Minecraft: 1.18.2
- Forge: 40.1.31

#### Log file:

[https://pastebin.com/JedufvsH](url)

**Comment by rubensworks** [comment]
Thanks for reporting!
