### ISSUE TITLE
evilcraft should probably not populate jei with dark tanks with flowing liquid, only non-flowing liquid

### ISSUE THREAD

**Issue by esotericist** [rubensworks/EvilCraft#924]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

while setting up a quick test for tinkers construct, i grabbed a dark tank w/lava from jei, and was surprised and confused to have the smeltery inform me that lava was not a valid melting fuel.

took me a bit, but i eventually realized i had grabbed a lava dark tank instead of a lava dark tank. ... they show exactly the same in jei, but one has a liquid you are meant to obtain, and the other does not.

while iterating over the fluid registry it would probably be better to skip the flowing liquids.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Sounds like a bug. What versions are you using?

**Comment by esotericist** [comment]
sorry for not getting back to this sooner, i have evilcraft 1.18.2-1.2.2, cyclops core 1.18.2-1.15.1, forge 40.1.54, jei 1.18.2-9.7.0.209

i see that there's been an evilcraft release since i encountered this, but it doesn't sound like it would impact this.

**Comment by esotericist** [comment]
to rule out cross-mod interaction, i set up an instance with just those mods
<img src="https://user-images.githubusercontent.com/1569754/178183757-62371668-380d-468d-a00e-fdbb43f9afdf.png" width="100">

grabbed both tanks from jei, and put them down so i could use `/data get block ...` on each
![image](https://user-images.githubusercontent.com/1569754/178184146-086e91c8-80c7-4f88-8df4-f3abb1f3a387.png)

more generalized there's definitely source and flowing versions of the tank in jei for other fluids as well:
![image](https://user-images.githubusercontent.com/1569754/178184246-687d987a-b475-427c-a4b8-9bbfb18fbd63.png)

this list is obviously much larger in a highly populated modpack
