### ISSUE TITLE
Evilcraft causes socket resets on servers when throwing weather potions into accumulator

### ISSUE THREAD

**Issue by rosshar** [rubensworks/EvilCraft#925]
After throwing rain potion into accumulator, Ive had major problems with Evilcraft booting me from servers and then causing socket timeout errors afterwards so that I can't login to the server for several hours or never (depending on the server) without staff assistance. Please don't say this is an an issue with my internet connection or my computer, as it has happened twice on two different servers, including the official ATM7 server. The first time it happened, even staff that went in the immediate area of the accumulator was locked out and could not get back on to the server for the same reasons and he had to get the owner to teleport him out of that area.

The solution is to have staff or owner teleport the affected individual to another area (i.e. spawn) when that person is logging in.  

I have no idea why this is happening, but I thought I would report it, since it has happened several times and does prevent people from logging back into servers.

**Comment by rubensworks** [comment]
@rosshar Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
