### ISSUE TITLE
Crash on launch in Turkish locale

### ISSUE THREAD

**Issue by jeremiahwinsley** [rubensworks/EvilCraft#926]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Mod crashes on launch in Turkish locale due to use of toLower without specifying a locale.

https://github.com/CyclopsMC/EvilCraft/blob/eeaf772b5293ea7b690da42404a7a82f46f3329b/src/main/java/org/cyclops/evilcraft/block/BlockInfestedNetherConfig.java#L46

https://github.com/CyclopsMC/EvilCraft/blob/eeaf772b5293ea7b690da42404a7a82f46f3329b/src/main/java/org/cyclops/evilcraft/core/broom/BroomPartBase.java#L54

#### Steps to reproduce the problem:

1. Fresh install of Forge 1.18.2 with Evilcraft installed.
2. Add these args to startup to set the locale: `-Duser.language=tr -Duser.country=TR`
3. Start the game.

#### Expected behaviour:

Calls to toLower should specify Locale.ROOT so that this doesn't crash.

____

#### Versions:

- This mod: 1.2.2
- Minecraft: 1.18.2
- Forge: 40.1.30

#### Log file:

https://gist.github.com/jeremiahwinsley/70ec10f61b33f92ad258a8aff3972993

**Comment by rubensworks** [comment]
Thanks for reporting!
