### ISSUE TITLE
[1.18.2] Rare occasional crash on startup

### ISSUE THREAD

**Issue by Saereth** [rubensworks/EvilCraft#928]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I'm occasionally getting a crash with evilcraft on start up. This happens maybe 1/10 launches.

#### Steps to reproduce the problem:

Just launch the game and sometimes it happens

1. ...

#### Expected behaviour:

Not crash

____

#### Versions:

- This mod: EvilCraft-1.18.2-1.2.4
- Minecraft: 1.18.2
- Forge: 40.1.68

This is a modpack and I am the author, I have reported it to myself :p

I have not been able to reproduce it with no other mods installed

Due to the nature of the inconsistency in the crash this would be a very unreliable method unfortunately 

#### Log file:
Crashlog:
https://www.toptal.com/developers/hastebin/etojuluduf.rb

Latest:
https://www.toptal.com/developers/hastebin/uyatevuhuq.yaml

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Note to self: might be a race condition. Check if there's a colors event we should be using instead.

**Comment by Saereth** [comment]
This is unfortunately still happening on the latest version
https://hastebin.com/akonotuvus.properties
reported by several users, happens once or twice per day according to them always on launch

<blockquote><div><strong><a href="https://hastebin.com/akonotuvus.properties">Just a moment...</a></strong></div></blockquote>

**Comment by Saereth** [comment]
I wanted to mention upon investigation this isnt the same error. Before it was crashing on the broom color registration and your commit here https://github.com/CyclopsMC/EvilCraft/commit/6aa5952802a0c712f388413fd0d06ed10338b01d seems to have fixed that, we've had no more reports on the broom part reg crashing but the biome extraction coloring is now crashing and the code there looks similar to your pre https://github.com/CyclopsMC/EvilCraft/commit/6aa5952802a0c712f388413fd0d06ed10338b01d change. So possibly similar, issue if that helps. If I can provide any more debug info for you I'll be glad to help, thanks!

**Comment by Saereth** [comment]
noticed in various other places in a few provided crashlogs, ItemPoisonBottleConfig etc as well
