### ISSUE TITLE
Humanoid Flesh & Dark Gems ATM7 1.18.2

### ISSUE THREAD

**Issue by GBatro** [rubensworks/EvilCraft#929]
#### Issue type:

- :question: Question 

____

#### Question:

Hey, I was wondering two things. 

1. Did the spawn levels for Dark Ore change on the update to 1.18.2? I can't find anything about it, but I can't seem to find any gems:(
2. Is humanoid flesh available with Corails Tombstone enabled? I'm unsure if it conflicts by having a tombstone placed on death rather than the drops actually falling.

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
1. Can you try in a pack with just EvilCraft? If you ca reproduce it there, then it might be a bug. Otherwise, probably a bug in some other mod.
2. Not sure, I don't know that mod. Best to take this up with the mod author to see if they somehow block the `LivingDeathEvent`.

**Comment by GBatro** [comment]
1. If you haven't changed it, that's all I needed to know. I'll look into it being a bug if it comes to that, I just wanted to make sure there wasn't explicit generation changes on the update that changed ore generation as a whole. 
2. I'll see about doing that then, thanks. Someone else on this server had gotten humanoid flesh at some point but doesn't know how, so it's possible by some means. I just wasn't able to get anything when attempting to directly.

**Comment by rubensworks** [comment]
> If you haven't changed it, that's all I needed to know. I'll look into it being a bug if it comes to that, I just wanted to make sure there wasn't explicit generation changes on the update that changed ore generation as a whole.

Well, it has changed, significantly. But so has the whole worldgen in Minecraft. So all worldgen is different.
You should be able to find Dark Ore at the same levels as Redstone Ore.

**Comment by GBatro** [comment]
Oh okay, that helps a lot! I had been looking between 6 and 66 (what I was told). That makes life a lot easier, I really appreciate the help.

**Comment by rubensworks** [comment]
@GBatro Where did you find that info? I thought the book was already updated to reflect the new location, but perhaps I missed something.

**Comment by GBatro** [comment]
[Feed The Beast Wiki](https://ftb.fandom.com/wiki/Dark_Ore#:~:text=Found%20between%20levels%206%20and%2066.&text=The%20Dark%20Ore%20is%20an,dropping%20a%20Crushed%20Dark%20Gem.)

I didn't see anything about spawn levels in the book. I've read it a few times looking for it and never found it, but I have a reading comprehension problem. So there's a genuine chance I missed it if it *is* in the book.

**Comment by rubensworks** [comment]
> [Feed The Beast Wiki](https://ftb.fandom.com/wiki/Dark_Ore#:~:text=Found%20between%20levels%206%20and%2066.&text=The%20Dark%20Ore%20is%20an,dropping%20a%20Crushed%20Dark%20Gem.)

Aha, that's outdated indeed. If you want, feel free to contact the authors to request an update :-) (but I guess this will be the case for most mods)

> I didn't see anything about spawn levels in the book. I've read it a few times looking for it and never found it, but I have a reading comprehension problem. So there's a genuine chance I missed it if it is in the book.

Indeed, just checked, it's not in the book. Maybe it should be though... Feel free to create an issue/PR to add/request it.
