### ISSUE TITLE
Pool Of Blood

### ISSUE THREAD

**Issue by GBatro** [rubensworks/EvilCraft#931]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Hello!
Would it be possible to have the "pool of blood" required for the first powered dark gem be a little more clear? It specifies "at least 5 buckets worth", but it seems like there is a required shape as well. I originally tried a 3x3 with 5 buckets worth along the edges, and then tried a straight line with 5 buckets worth (and neither worked). I had also assumed "pool of blood" required an item, such as a cauldron. Definitely not a huge issue, but would be a nice change I think.

**Comment by rubensworks** [comment]
Thanks for the suggestion!
