### ISSUE TITLE
[1.18.2] Eternal water block dupe with ars nuveaou spells

### ISSUE THREAD

**Issue by Saereth** [rubensworks/EvilCraft#933]
Using projectile->break->extract->item pickup on an Eternal Water Block  from evilcraft returns two of them to inventory.
I'm not really sure which mod's end this is on so reporting to both
 
https://github.com/baileyholl/Ars-Nouveau/issues/656

**Comment by rubensworks** [comment]
@Saereth Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
