### ISSUE TITLE
Server 1.16.5 spongeforge crash after putting blood chest

### ISSUE THREAD

**Issue by NMorero** [rubensworks/EvilCraft#935]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Every time a player put a blood chest in the ground the server crashes with the following error: 
- Something happened when trying to unwind Packet{PlaceBlock}
The server is a modded spongeforge 1.16.5 latest version.

#### Steps to reproduce the problem:

1. Open server and log into it
2. Put a blood chest into the ground
3. Server crashes

#### Expected behaviour:
Let put blood chest and not crash the server.

____

#### Versions:

- This mod: EvilCraft-1.16.5-1.1.17.jar
- Minecraft: 1.16.5 
- Forge: forge-1.16.5-36.2.39-installer.jar

#### Log file: 
[crash-2022-08-16_14.54.09-server.txt](https://github.com/CyclopsMC/EvilCraft/files/9353357/crash-2022-08-16_14.54.09-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> Something happened when trying to unwind Packet{PlaceBlock}

I don't see that error in the log, only `ServerHangWatchdog`. Do you have any other logs?

**Comment by NMorero** [comment]
I found the error i think, it was sponge. 
I remove it and works fine for now, also resolved issues with other mods so maybe it was that.

**Comment by rubensworks** [comment]
Super!
