### ISSUE TITLE
[1.18.2] Apotheosis and Evilcraft crash (crossposted from apotheosis github)

### ISSUE THREAD

**Issue by Mitchell5200** [rubensworks/EvilCraft#936]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. install apotheosis and evilcraft in the same instance, or use ATM 7 pack version 0.4.27
2. find a vengeance spirit

#### Expected behaviour:

for the game to not crash

____

#### Versions:

- This mod: EvilCraft-1.18.2-1.2.6
- Minecraft: 1.18.2
- Forge: 40.1.68
Apotheosis version 1.18.2-5.5.1
Placebo-1.18.2-6.6.1

https://github.com/Shadows-of-Fire/Apotheosis/issues/629
#### Log file:
[crash-2022-08-22_10.55.03-server.txt](https://github.com/CyclopsMC/EvilCraft/files/9395890/crash-2022-08-22_10.55.03-server.txt)
[crash-2022-08-22_15.22.37-server.txt](https://github.com/CyclopsMC/EvilCraft/files/9395891/crash-2022-08-22_15.22.37-server.txt)
[crash-2022-08-22_15.39.36-server.txt](https://github.com/CyclopsMC/EvilCraft/files/9395892/crash-2022-08-22_15.39.36-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Related to CyclopsMC/CyclopsCore#172

**Comment by rubensworks** [comment]
Note to self: use `EntityAttributeCreationEvent` for registering attributes.
