### ISSUE TITLE
Remove Obscured Glass In 1.18

### ISSUE THREAD

**Issue by elementsplayer** [rubensworks/EvilCraft#938]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

As the title, I would suggest to remove the obscured glass since minecraft already had same function block in 1.18.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
I don't this calls for removal of the block.
The recipe and texture are slightly different.
