### ISSUE TITLE
[Magma-Servers] Hovering over Human-flesh crashes

### ISSUE THREAD

**Issue by C0D3-M4513R** [rubensworks/EvilCraft#940]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Hovering over a (survival obtained) Humanoid flesh on a Magma server crashes the game.

#### Steps to reproduce the problem:

1. Make a Magma server (tested 40.1.80-16e69898 and 40.1.79-34b302fa)
2. Install EvilCraft 1.2.8 and CyclopsCore 1.16.0
3. Start, and join server
4. Die, until you get a Humanoid flesh
5. go to the inventory and hover over it

#### Expected behaviour:

You do not crash, and it is fine to hover over, and move about in the inventory.

____

#### Versions:

- This mod: 1.2.8 or 1.2.7
- Minecraft: 1.18.2
- Forge: 40.1.80 or 40.1.79

Initially found on ATM7 v.0.4.30, but reproduced standalone. 
https://github.com/AllTheMods/ATM-7/issues/1495
Reorted to Magma:
https://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/issues/102

#### Log file:

[crash-2022-09-15_11.58.14-client.txt](https://github.com/CyclopsMC/EvilCraft/files/9574192/crash-2022-09-15_11.58.14-client.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can you try reproducing it without any mods installed? Just so we can rule out other mods causing this problem.

**Comment by Jorue23** [comment]
I wouldn't recommend to use magma at all especially the 1.18 version is still highly unstable. And Magma as well as Mohist have forge poorly implememted some parts are not implemented correctly and many are even missing.

**Comment by C0D3-M4513R** [comment]
Please look at the crashreport. I do not have any other mods than the bare nessesary evilcraft and cyclops core.
`without any mods installed` also I fail to see how I can reproduce this crash without evilcraft.

Also which part here wasn't clear? `Initially found on ATM7 v.0.4.30, but reproduced standalone.`

**Comment by C0D3-M4513R** [comment]
Also @Jorue23 we need Magma for plugin support.
Like profilers, kits, worldedit and permissions.

**Comment by rubensworks** [comment]
If I understand correctly, you have still Magma mod installed, right?
Can you try without it?

**Comment by C0D3-M4513R** [comment]
magma is a server implementation, that supports forge. It is not a mod
Without magma, and only regular forge, it works perfectly fine, but we need plugins as serverhosters (which magma supports).

**Comment by C0D3-M4513R** [comment]
```
│   Magma-1.18.2-40.1.80-16e69898-server.jar
│
└───mods
        CyclopsCore-1.18.2-1.16.0.jar
        EvilCraft-1.18.2-1.2.8.jar
```

**Comment by rubensworks** [comment]
Could you try without magma?

**Comment by C0D3-M4513R** [comment]
> magma is a server implementation, that supports forge. It is not a mod Without magma, and only regular forge, it works perfectly fine, but we need plugins as serverhosters (which magma supports).

It works fine with regular forge.
So I guess we are done here?

**Comment by rubensworks** [comment]
Sounds like a magma issue then, as also remarked by @Jorue23.
Could you report it to their issue tracker?

**Comment by C0D3-M4513R** [comment]
https://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/issues/102

<blockquote><img src="http://git.magmafoundation.org/assets/twitter_card-570ddb06edf56a2312253c5872489847a0f385112ddbcd71ccfa1570febab5d2.jpg" width="48" align="right"><div>GitLab</div><div><strong><a href="http://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/issues/102">Evilcraft - Hovering over Humanoid Flesh crashes the game (#102) · Issues · Magma Foundation / Magma-1-18-x · GitLab</a></strong></div><div> Summary Whilst playing on a server using magma, when hovering over a humanoid flesh, you will instantly crash the client (server...</div></blockquote>
