### ISSUE TITLE
Broom Parts do not have a tooltip

### ISSUE THREAD

**Issue by aaronhowser1** [rubensworks/EvilCraft#941]
#### Issue type:

- :bug: Bug 

____

#### Short description:

![image](https://user-images.githubusercontent.com/15698722/191242566-473019d2-cf5e-4a41-b1d6-6ee4409e6f63.png)

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

It should have a tooltip, as the book says

____

#### Versions:

- This mod: EvilCraft-1.18.2-1.2.9
- Minecraft: 1.18.2
- Forge: 40.1.80

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by aaronhowser1** [comment]
Actually I might have misinterpreted the book. It shows on the *Broom's* tooltip, not the part's.

**Comment by aaronhowser1** [comment]
Should I move this to a new issue as a suggestion instead of a bug report, to have it be on the part's tooltip as well? As it is, you can't know what part you want to craft, as the only way to find its stats is to craft it and put it on a Broom.

**Comment by rubensworks** [comment]
It's working fine for me:
<img width="301" alt="Screenshot 2022-10-02 at 07 51 32" src="https://user-images.githubusercontent.com/440384/193440082-4cddae22-e855-4e2b-8b78-bf6b2ed0202f.png">

I suspect there's a mod in your pack breaking the `ItemTooltipEvent`. Might be best to take this up with your modpack author.
