### ISSUE TITLE
The Necromancer Staff's projectiles don't do anything

### ISSUE THREAD

**Issue by aaronhowser1** [rubensworks/EvilCraft#942]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I spawned in a Staff with full blood, and using it shoots out skull projectiles. However, when they land, nothing happens. When it hits a block, it just vanishes. When it hits a mob, it deals 0 damage but knocks them back as if they were hurt. No zombies or anything are spawning.

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

    This mod: EvilCraft-1.18.2-1.2.9
    Minecraft: 1.18.2
    Forge: 40.1.80

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can't reproduce this on my end. Like your other issue, I suspect there's a mod in your pack breaking mob spawns somehow.
