### ISSUE TITLE
"Environmental accumulator" degradation breaking chunk saving

### ISSUE THREAD

**Issue by a-sakharov** [rubensworks/EvilCraft#943]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Environmental accumulator can corrupt chunk (or somehow other prevent chunk from saving) when performing chunk degradation.

#### Steps to reproduce the problem:

1. Start server only with EvilCraft and CyclopsCore, fresh world
2. Place/find environmental accumulator
3. Use it 3 times (maybe less or more also work)
4. Try to save world by unloading chunks, command or logout (maybe you need to be perform it few times)

#### Expected behaviour:

When world should be saved - some error appear in server console: Failed to save chunk (link for more below). When chunks will be reloaded you can see that no changes actually saved. This is not only break game experience, but can also be used for duping, because no chunk updates will be written to disk.

____

#### Versions:

- This mod: 1.2.8
- Minecraft: 1.19.2
- Forge: 43.1.24

#### Log file:

https://pastebin.com/kwrpaerM

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by a-sakharov** [comment]
Looks like this bug can also crush server. 
Sometimes my server crush unique way: no message in logs, no cleanup and saving worlds, process just ends and file with name like hs_err_pid996.log appears in directory with executable. Example file contents: https://pastebin.com/CSmn87hf
I think this is EvilCraft, because it mentions net.minecraft.world.level.chunk.storage.RegionFileStorage, and server log have lot of "Failed to save chunk" errors connected with this bug
