### ISSUE TITLE
Vengeance ring lag due to constantly recreating objects

### ISSUE THREAD

**Issue by jeremiahwinsley** [rubensworks/EvilCraft#944]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

When the vengeance ring is active, these two constructors are called repeatedly, causing a large amount of lag. This TagKey could just be created once for the entire mod and reused.

https://github.com/CyclopsMC/EvilCraft/blob/60b991cbec15acc73d271a9fa465b86cc6094085/src/main/java/org/cyclops/evilcraft/entity/monster/EntityVengeanceSpirit.java#L592

![2022-09-29 20_55_25-Window](https://user-images.githubusercontent.com/7946299/193167218-95ecf552-6d38-4432-8589-41e531b19ec8.png)

#### Steps to reproduce the problem:

1. turn on vengeance ring (not sure if it needs to be in a curios slot, but was when this profile was taken)
2. run spark profile

____

#### Versions:

- This mod: 1.2.8
- Minecraft: 1.19.2
- Forge: 43.1.27

#### Profiler output:

https://spark.lucko.me/m7J50qlNz9

**Comment by rubensworks** [comment]
Thanks for reporting!
