### ISSUE TITLE
Not sure if bug/feature with EvilCraft or Torchmaster

### ISSUE THREAD

**Issue by Aedda** [rubensworks/EvilCraft#946]
#### Issue type:

- :question: Question 

____

#### Question:

I'm on a hybrid Direwolf20/ATM7 pack and I've noticed that the Mega Torch from Torchmaster is preventing all hostile mob spawns as designed except for Poison Libelles. Not sure if this is intentional or not and on which side the bug if any resides so I wanted to ask here about it. Thanks!

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Could you report this to the issue tracker of Mega Torch, and link back here?
I'm not sure what could be causing this on my end (the entity is being registered to the spawn list as a MONSTER, just like other hostile mobs).
Happy to make changes here if needed.
