### ISSUE TITLE
Keybinds showing twice for Evilcraft

### ISSUE THREAD

**Issue by Saereth** [rubensworks/EvilCraft#947]
![image](https://user-images.githubusercontent.com/9200909/199596910-c8d46a51-06ce-4e4f-8193-dd142edea6e5.png)

With evilcraft+controlling the keybinds are showing twice.

#### Versions:

- This mod: EvilCraft-1.18.2-1.2.10
- Minecraft: 1.18.2
- Forge: 40.1.80
- Modpack: FTB Inferno

let me know if I can get you any addition info thanks
Originally reported by this a user on our tracker and I confirmed it
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1515

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you report this to the controlling issue tracker?

AFAIK, EvilCraft is registering keys in the correct way (`ClientRegistry.registerKeyBinding` in `FMLClientSetupEvent`).
I do the same thing across all my mods.
