### ISSUE TITLE
EvilCraft reporting Core Mod Biome issue

### ISSUE THREAD

**Issue by Zelioth** [rubensworks/EvilCraft#948]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Evil Craft seems to be having some sort of start failure for a core mod Biome modifier or something along those lines. 

[net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod coremods/field_to_method.js function biome

#### Steps to reproduce the problem:

Install Evil Craft
Run Minecraft

#### Expected behaviour:

____

#### Versions:

- This mod: 1.19.2 1.2.9
- Minecraft: 1.19.2
- Forge: 43.1.47

#### Log file:

I'll post Two log files. One with Evil Craft, one without to show difference 

Without EvilCraft
https://pastebin.com/MKt53eA1

With Evil Craft
https://pastebin.com/VirMv3qX

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Zelioth** [comment]
No, Thank you for replying. Most mod creators don't care about the small issues reported. I mean this one hasn't been noted and it's been out awhile haha.
