### ISSUE TITLE
Crashed bc of blood_splash

### ISSUE THREAD

**Issue by Felix2144** [rubensworks/EvilCraft#949]
#### Issue type: Crash

- :bug: Bug 

____

#### Steps to reproduce the problem: its random

1. ...

#### Expected behaviour: a bat died and it createt a blood_splash that crashed my game

____

#### Versions:

- This mod: 1.2.9
- Minecraft: 1.19.2
- Forge: 43.1.47

**Comment by rubensworks** [comment]
Thanks for reporting!
