### ISSUE TITLE
Blood has no display name in JEI, it says "fluid_type.unregistered_sadface"

### ISSUE THREAD

**Issue by Jack-McKalling** [rubensworks/EvilCraft#950]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If you open the Blood Infuser recipe for Dark Powered Gems, and hover over the blood fluid, it says `fluid_type.unregistered_sadface`.

This happens everywhere the fluid is displayed in JEI, not just there.

#### Steps to reproduce the problem:

1. Open creative inventory
2. Browse to EvilCraft tab
3. Hover over the blood-infused dark gem, and press R to view its recipe
4. Browse to the Blood Infuser category tab
5. Hover over the blood fluid in the recipe
![Blood Infuser recipe](https://user-images.githubusercontent.com/14236702/201355768-237235b9-4170-4f42-a162-e2ab6c3f7b20.png)

#### Expected behaviour:

It should display a proper name for the blood like any other fluid

____

#### Versions:

- This mod: `1.2.9` & `1.2.10`
- Minecraft: `1.19.2`
- Forge: `43.1.47` & `43.1.52`

Smallest set of mods this applies to:
- EvilCraft
- Cyclops Core
- Just Enough Items (JEI)

I expect it to have nothing to do with the other mods, but I don't think it can be revealed without JEI installed, and CC is of course required to run EC. Originally encountered the issue in modpack https://www.curseforge.com/minecraft/modpacks/chunk-block

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
This also applies to poison.
And to menril resin in Integrated Dynamics. You've said before you collect all reports in one place, so I figured I'll mention that in here as well.
