### ISSUE TITLE
Hunger can go negative when repeatedly eating Humanoid or Werewolf Flesh

### ISSUE THREAD

**Issue by James103** [rubensworks/EvilCraft#951]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Hunger can go negative when repeatedly eating Humanoid Flesh or Werewolf Flesh.

#### Steps to reproduce the problem:

1. Obtain some Humanoid or Werewolf Flesh.
2. Go into survival mode and eat the flesh until your hunger level becomes empty.
3. Continue to eat the flesh a few more times.
4. Check your hunger level with `data get entity @s foodLevel`
5. The value returned is negative.

#### Expected behaviour:

The hunger level should not ever go below zero even when eating foods with negative nutrition such as Humanoid Flesh.
`data get entity @s foodLevel` should never return a value below 0 outside of NBT editing.

A workaround could be to make the food item give no hunger or saturation and instead instantly inflict 20 exhaustion points when eaten for a similar effect without the possibility of negative hunger. (4 exhaustion gained = 1 hunger or saturation lost)

____

#### Versions:

- CyclopsCore: 1.17.0
- EvilCraft: 1.2.10 
- Minecraft: 1.19.2
- Forge: 43.1.52

#### Log file:

_No relevant entries_

**Comment by rubensworks** [comment]
Thanks for reporting!
