### ISSUE TITLE
Environmental Accumulator crush with biome bottle

### ISSUE THREAD

**Issue by uhloin** [rubensworks/EvilCraft#952]
MC 1.19.2 
forge-1.19.2-43.1.55-installer.jar 
EvilCraft-1.19.2-1.2.10.jar 

Crash on finish of process of putting biome (birch forest) into Biome Extract Bottle.

[crash-2022-11-23_19.32.47-server.txt](https://github.com/CyclopsMC/EvilCraft/files/10077239/crash-2022-11-23_19.32.47-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!
