### ISSUE TITLE
maxTankSize Does not limit tank size

### ISSUE THREAD

**Issue by dannydjdk** [rubensworks/EvilCraft#953]
#### Issue type:

- :bug: Bug

____

#### Short description:

Setting the maxTankSize to a number smaller than the default does not properly limit the size of the tanks that can be crafted.

#### Steps to reproduce the problem:

1. Change maxTankSize to 64000 in evilcraft-common.toml in the config folder.
2. Craft 8 tanks together and get a tank holding 144000, more than the configuration should allow.

#### Expected behaviour:

Crafting of tanks larger than 64000mB should not be possible.
____

#### Versions:

- This mod: 1.2.10
- CyclopsCore: 1.7.10
- Minecraft: 1.19.2
- Forge: 43.1.57

Reproducible with no other mods installed.

#### Log file:

https://pastebin.com/1hVmQgu0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
The `maxTankSize` has become deprecated in MC 1.18+, and can now be modified by overriding the dark tank combination recipe in a datapack like this: https://github.com/CyclopsMC/EvilCraft/blob/master-1.19/src/main/resources/data/evilcraft/recipes/special/combine_dark_tank.json#L4

Will remove this config option in next update to avoid confusion.

<blockquote><img src="https://opengraph.githubassets.com/c2a13436b7d17adc470d66f32deeaa2a9ac6e350dbef58ad3cc3ee8d5be77a71/CyclopsMC/EvilCraft" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EvilCraft">EvilCraft/combine_dark_tank.json at master-1.19 · CyclopsMC/EvilCraft</a></strong></div><div>An evil mod for Minecraft. Contribute to CyclopsMC/EvilCraft development by creating an account on GitHub.</div></blockquote>
