### ISSUE TITLE
Eternal water bucket can't fill cauldron

### ISSUE THREAD

**Issue by uhloin** [rubensworks/EvilCraft#955]
Minecraft 1.19.2
forge-1.19.2-43.1.55-installer.jar 
EvilCraft-1.19.2-1.2.10.jar 

Right click with Eternal Water Bucket on Cauldron does not fill it (and does not empty).

Previously the same bug was in 1.12.2:
https://github.com/CyclopsMC/EvilCraft/issues/614

**Comment by rubensworks** [comment]
Thanks for reporting!
