### ISSUE TITLE
Unusing does not work with Vengeance Pickaxe

### ISSUE THREAD

**Issue by uhloin** [rubensworks/EvilCraft#957]
Minecraft 1.19.2
forge-1.19.2-43.1.55-installer.jar 
EvilCraft-1.19.2-1.2.10.jar 

I created **Vengeance Pickaxe**, removed curse by **Purifier** and enchanted it with **Unusing**. But it was broken during work as if not enchanted. I did not forget enchant, checked it twice.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Just tested myself on both 1.18 and 1.19, and unusing seems to be working fine (blocks are not broken anymore once the tool is almost broken, and the durability does not drop).

Can you try without other mods installed?
There might be another mod breaking things.

**Comment by uhloin** [comment]
About other mods I can say that "Rive" enchantment from DivineRPG is definitely incompartible with your "Unusing". Pickaxe with Rive loses durability very fast, broken and disappeared. May be because Rive spents durability not by -1 but with bigger decrement. But without RIve pickaxe also disappears until I updated evilcraft, cyclopscore and forge to 43.1.57. Looks like bug is gone without Rive but still existing with Rive.

**Comment by rubensworks** [comment]
> May be because Rive spents durability not by -1 but with bigger decrement.

Yep, that will be definitely it!
Unusing will block usages if less than 5 damage points remain, so if a mod damages by more than 5, then Unusing won't work.
