### ISSUE TITLE
Used Boxes of Eternal Closure do not stacked with unused

### ISSUE THREAD

**Issue by uhloin** [rubensworks/EvilCraft#958]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Used Boxes of Eternal Closure do not stacked with unused

#### Steps to reproduce the problem:

1. Catch some spirit into box of eternal closure.
2. Use it in Spirit Reanimator to produce spawn egg.
3. The depleted box will be marked "Empty".
4. Place box on the ground, break it with pickaxe. Now box will be marked as "Contents: Vengeance Spirit". This is a first bug because really there is no spirit inside. If place box again it will be already opened and no spirit appears from it.
5. Both types of boxes after step 3 and after step 4 have not spirits inside but they are not stacked together. Need to make step 3->4 to stack them. This is second bug. 
6. Sometimes <b>unused</b> boxes which have the same title "Contents: Vengeance Spirit" may be found in the world. But they are different: if place such a box it is visible as closed and of open it the spirit fly out and hit player. And they also do not stack.

#### Expected behaviour:

Box without spirit should be always marked as "Empty", shown as opened if set on ground and stacks with other boxes without spirits.

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.10.jar
- Minecraft: 1.19.2
- Forge: forge-1.19.2-43.1.55-installer.jar

**Comment by rubensworks** [comment]
@uhloin Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by uhloin** [comment]
done
