### ISSUE TITLE
Crashing with many mobs.

### ISSUE THREAD

**Issue by ChivalKnight** [rubensworks/EvilCraft#959]
#### Issue type: Crash

- :bug: Bug 

____

#### Short description:

When I was playing All the Mods 8 (ATM8), I found myself battling wither skeletons in the sky of the overworld. However, I then crashed. I loaded into the world again, and then crashed seconds later.

#### Steps to reproduce the problem:

1. Have many mobs by you
2. I don't know what happens next, I just crash. Sometimes it crashes after I attack them, sometimes it just happens.

#### Versions: 

- This mod: EvilCraft-1.19.2-1.2.11.jar
- Minecraft: 1.19.2
- Forge:  43.1.55

(Already reported, told me to report it to the EvilCraft dev) I was told it had something to do with blood stains.

#### Log file: https://mclo.gs/0ThGYDk

**Comment by rubensworks** [comment]
Thanks for reporting!
