### ISSUE TITLE
blood infuser recipes not showing in jei

### ISSUE THREAD

**Issue by TheNimbleNinja** [rubensworks/EvilCraft#960]
#### Issue type:

blood infuser recipes dont show up
____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

they show up in jei
____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.11.jar
- Minecraft: 1.19.2
- Forge: 43.2.1

**Comment by rubensworks** [comment]
They show up fine here.

Can you try without any other mods installed?

If the problem still occurs after that, could you share your client logs?
