### ISSUE TITLE
vilcraft:netherfish (org.cyclops.evilcraft.entity.monster.EntityNetherfish) Crashing public servers

### ISSUE THREAD

**Issue by Zelioth** [rubensworks/EvilCraft#962]
- :bug: Bug 

____

#### Short description:

Player for my mod pack Friends United are finding when you mind the nether fish blocks it instantly crashes the public server.

#### Steps to reproduce the problem:

1. ... Users are just playing Friends United Mod pack and crashing when mining the infested stones. happens with regular SIlver Fish as well.

#### Expected behaviour:

____

#### Versions:

- This mod:  1.2.12
- Minecraft: 1.19.2
- Forge: 43.2.1

#### Log file:
https://pastebin.com/wGyyhJhd

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
`net.silentchaos512.gear.util.DataResource.trait(net.minecraft.resources.ResourceLocation)'`

This seems to be a problem in another mod in your pack (not sure which one that is).
Could you report it to their issue tracker instead?
