### ISSUE TITLE
Mahou Tsukai incompartibility for Invigorating Pendant

### ISSUE THREAD

**Issue by uhloin** [rubensworks/EvilCraft#963]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Invigorating Pendant clears effect "Fay sight" marked as neutral instead of clear only negative effects.

#### Steps to reproduce the problem:

Install mods evilcraft and mahou tsukai (latest versions for 1.19.2). 
Create Invigorating Pendant
Put some blood to it
Create item "Mystic Code First Sorcery" and scroll "Mystic Eyes of Fay sight", 
wear Mystic Code, 
press crouch + right mouse button, 
put scroll to leftmost cell of Mystic Code, 
close Mystic Code interface, 
go to coordinates (0,0) 
press and release right button to activate scroll inside Mystic Code.
Now magic lines should appear in air on height 70. But they quickly disappeared beause the Pendant clear effect.

#### Expected behaviour:

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.12.jar 
- Minecraft: 1.19.2
- Forge: 43.2.0
mahoutsukai-1.19.2-v1.34.37.jar

**Comment by rubensworks** [comment]
Thanks for reporting!
