### ISSUE TITLE
Crash when throwing biome bottles near other players.

### ISSUE THREAD

**Issue by Chloethecat** [rubensworks/EvilCraft#965]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Throwing a biome bottle near another player causes them to crash the person who throws the bottle is fine.

#### Steps to reproduce the problem:

Throw bottle near another player in multiplayer.

#### Expected behaviour:

No crash.

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.14.jar
- Minecraft: 1.19.2
- Forge: 43.2.0

#### Log file:

https://pastebin.com/5RXMTLXi

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Do you have any other mods installed? If so, please try again without any others.
It's possible that another mods is breaking things.

**Comment by Chloethecat** [comment]
No other mods where installed at time of crash tested on new test server with only evilcraft and Cyclops Core
