### ISSUE TITLE
game crashes when cursor near humanoid flesh in inventory

### ISSUE THREAD

**Issue by D4rkMn** [rubensworks/EvilCraft#966]
#### Issue type:

- :bug: Bug

____

#### Short description:

I have been playing a modded server with my friends for a while with this mod on (EvilCraft 1.2.12, Forge 1.18.2) and have never experienced any problems in regards to humanoid flesh but suddenly simply hovering over one of it crashes the game (not the server, just the client of whoever hovered over the humanoid flesh). It only happens with a very specific humanoid flesh so i suspect it has something to do with the name of the player the flesh belongs to or something but i might be wrong. Also for some reason neither the EvilCraft mod nor humanoid flesh seem to be mentioned on the crash report log which is weird. The bug however is consistent as me and my friends have all consistently had our games crash the exact moment that happens.

#### Steps to reproduce the problem:

1. Open a chest with the "corrupted" humanoid flesh.
2. As soon as the mouse cursor hovers over said humanoid flesh, the client crashes.

#### Expected behaviour:

The game shouldn't crash, that's it.

____

#### Versions:

- This mod: 1.2.12
- Minecraft: 1.18.2
- Forge: Arclight (for mods and plugins for the server), Forge 40.1.80

(this problem ONLY happens with a specific "corrupted" humanoid flesh, so im not sure if any other mods installed on the server might be causing the problem)

#### Log file:

https://pastebin.com/13hdk43h

**Comment by rubensworks** [comment]
Thanks for reporting!
