### ISSUE TITLE
[1.19.3] Blood extractor auto-Supply crashes the game 

### ISSUE THREAD

**Issue by Kilppux** [rubensworks/EvilCraft#967]
#### Issue type:

- :bug: Bug 

____

#### Short description:

While playing with friends I used the auto-supply option with the blood extractor and crafted a tank to put it down but right when the tank was in my active hotbar slot the game crashed. After rejoining the tank had disappeared, when mutiple tanks were in a stack the game crashed when loading into game as many times as there were tanks. Entangled chalice seems to crash as well when the omni-supply is active.

#### Steps to reproduce the problem:

1. Have an blood extractor with auto-supply on in your inventory
2. Have an item that can be filled
3. Put the fillable item in your active slot in the hotbar
4. Game crashes

#### Expected behaviour:

Not have the game crash.

#### Versions:

- This mod: 1.2.15
- Minecraft: 1.19.3
- Forge: 44.1.1

#### Log file:

https://pastebin.com/9uHQXjRf

**Comment by rubensworks** [comment]
Thanks for reporting!
