### ISSUE TITLE
Lightning grenade DC's people its thrown at

### ISSUE THREAD

**Issue by sprocketaudio** [rubensworks/EvilCraft#968]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When you throw a Lightning Grenade at another player it will forcefully disconnect them from the game with the following error message:

![image](https://user-images.githubusercontent.com/13222732/217889364-2f1f3273-2553-4468-b164-30629d5f2a63.png)

#### Steps to reproduce the problem:

Throw a Lightning Grenade at another player (I assume PVP on needed but didnt test)

#### Expected behaviour:

The player should should not DC

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.14
- Minecraft: 1.19.2
- Forge: 43.2.3

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you share the server and client logs?

Sounds related to #965
