### ISSUE TITLE
Poison and Blood liquids are mixed up.

### ISSUE THREAD

**Issue by MindBrain27** [rubensworks/EvilCraft#969]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Blood and Poison liquids seem to be mixed up.

#### Steps to reproduce the problem:

See JEI for both Blood and Poison liquids, the name and color is not the same as the ID.

#### Expected behaviour:

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.15.jar
- Minecraft: 1.19.2
- Forge: 43.2.3

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by MindBrain27** [comment]
No problem! Recipes still work fine, just names are backwards.
