### ISSUE TITLE
[ATM8] EvilCraft attempts to divide by zero while the invigorating pendant is in use.

### ISSUE THREAD

**Issue by Zanctarian** [rubensworks/EvilCraft#972]
#### Issue type:

- :bug: Bug 

____

#### Short description:
As the title states, while the invigorating pendant is in use, there's some sort of scenario where the game softlocks because of it trying to divide by zero.

#### Steps to reproduce the problem:

1. Wear the invigorating pendant
2. ???

#### Expected behaviour:
No issue with arithmetic.

____

#### Versions:

- This mod: 1.2.15
- Minecraft: 1.19.2
- Forge: 43.2.6

#### Log file:
https://pastebin.com/JpUE3xF0

### Thoughts
Should be an easy fix. Assuming version 1.2.16 doesn't modify the ItemInvigoratingPendant file, it seems the "effect.getAmplifier()" has a chance to be -1, probably due to poor coding from another mod. Maybe something like Math.max(1, amplifier) would fix it. I can't do the pull request as I don't really want to bother setting up a development environment.

**Comment by rubensworks** [comment]
Thanks for reporting!
