### ISSUE TITLE
Vengance Spirit Invincible bug

### ISSUE THREAD

**Issue by Dev0lved** [rubensworks/EvilCraft#974]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Playing on a modpack server (All The Mods 8) and when i place down the box containing the vengeance spirit and open it yes i see the spirit and using the piercing focus laser while holding down RMB seems to do absolutely nothing I've traded the Vengeance Spirit with the laser until its lifespan runs out multiple times if i am clueless and just doing something wrong i apologize for wasting your time in advance

#### Steps to reproduce the problem:

1. place down the box containing the vengeance spirit and open it use the piercing focus laser while holding down RMB seems to do absolutely nothing
#### Expected behaviour:The Spirit to die and drop its items to further progress in the modpack

____

#### Versions:

- This mod: 1.19.2-1.2.16
- Minecraft: 1.19.2
- Forge: 43.2.6

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Dev0lved** [comment]
[](url)
![item1](https://user-images.githubusercontent.com/129639307/229330372-1a78fc1d-82e5-4cff-a13e-ec41a9678d62.PNG)
![item2](https://user-images.githubusercontent.com/129639307/229330376-d5e15127-9ada-4067-b521-0b553a87e4a8.PNG)
![item3](https://user-images.githubusercontent.com/129639307/229330379-e8348448-0596-439f-8ad3-550090167ed9.PNG)
