### ISSUE TITLE
Weird "soft touch" in book text

### ISSUE THREAD

**Issue by vadcx** [rubensworks/EvilCraft#978]
#### Issue type:

- :question: Question 

____

#### Question:

From the book: https://github.com/CyclopsMC/EvilCraft/blob/9bc368791a852cad5ae85dfe9fa4eba7dddab03e/src/main/resources/assets/evilcraft/lang/en_us.json#L596

> **maybe a soft touch can help?",**

The "soft touch" here sounds weird to me, as if someone tried to put "silk touch" in English but forgot the original. https://youtu.be/WaUDpdhoBl4?t=1300

I suggest to rephrase it slightly, at the very least something like "maybe a softer touch can help". This still keeps the calembour on the Silk Touch enchant name but appears intentional.

Full quote:

> As we all know, &4Blood&0 will dry out after a while when it is in a dry area. Breaking the &1Hardened Blood&0 with a pickaxe or your fists will turn it into regular &4Blood&0 again. Breaking such &1Hardened Blood&0 with &1Flint and Steel&0 will give some &1Hardened Blood Shards&0 which might come in handy later on. It looks like these shards can also be obtained when cooking such a &1Hardened Blood&0 block, if you can obtain it in some way ... **maybe a soft touch can help?",**

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
I don't see a problem with a current phrasing tbh, so I'd prefer to keep it as-is.
