### ISSUE TITLE
missing textures libelle

### ISSUE THREAD

**Issue by cosmoderp** [rubensworks/EvilCraft#980]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Poisonous Libelle spawns with broken textures.

#### Steps to reproduce the problem:

1. Spawn Poisonous Libelle
2. textures are broken

#### Expected behaviour:

Expect to see properly textured mob.

____

#### Versions:

- This mod: Evilcraft 1.2.19
- Minecraft: 1.19.2 
- Forge: 43.2.11

#### image file:

https://cdn.discordapp.com/attachments/386054141237002241/1108256479401746452/image.png

**Comment by rubensworks** [comment]
Thanks for reporting!
