### ISSUE TITLE
Trader Llama cannot be fed Darkened Apple

### ISSUE THREAD

**Issue by TBrauns** [rubensworks/EvilCraft#981]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The description of the Darkened Apple implies that it just needs to be fed to "some animal". Trader Llamas, however, cannot be fed this item.

#### Steps to reproduce the problem:

1. Craft a Darkened Apple as normal.
2. Equip Darkened Apple in active slot.
3. Right-click to attempt to feed to Trader Llama

#### Expected behaviour:

Trader Llamas are animals and should be viable targets for this item.

____

#### Versions:

- This mod: 1.19.2-1.2.18
- Minecraft: 1.19.2
- Forge: 43.2.8

**Comment by rubensworks** [comment]
Thanks for reporting!
