### ISSUE TITLE
Any animal is able to be fed any item as you would a darkened apple

### ISSUE THREAD

**Issue by Gronglegrowth** [rubensworks/EvilCraft#982]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using _any_ item on any animal, it consumes the item and inflicts the animal with Paling, as if you've just given them a darkened apple.

#### Steps to reproduce the problem:

1. Approach an animal
2. Use any item on them
3. Watch the animal be inflicted with Paling, and create a vortex, as if they were under the effects of darkened apple

#### Expected behaviour:

The item would not be used at all, or used for its intended purpose (e.g. wheat for breeding sheep)
____

#### Versions:

- This mod: 1.2.20
- Minecraft: 1.19.2
- Forge: 43.2.11

**Comment by rubensworks** [comment]
Thanks for reporting!
