### ISSUE TITLE
Flint and Steel is not required to get Hardened Blood Shards, they drop when broken by anything

### ISSUE THREAD

**Issue by aaronhowser1** [rubensworks/EvilCraft#983]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Mine Hardened Blood with anything
2. Get Shards instead of liquid blood

![image](https://github.com/CyclopsMC/EvilCraft/assets/15698722/2b17751a-1302-4b55-9864-e619c7ecc129)
![image](https://github.com/CyclopsMC/EvilCraft/assets/15698722/48b542c5-76f6-4b81-9222-fc71ebfa0e76)

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.21
- Minecraft: 1.19.2
- Forge: 43.2.8

**Comment by rubensworks** [comment]
Thanks for reporting!
