### ISSUE TITLE
Crushed Dark Gem does not appear to drop from Dark Ore, as the book implies

### ISSUE THREAD

**Issue by aaronhowser1** [rubensworks/EvilCraft#984]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

![image](https://github.com/CyclopsMC/EvilCraft/assets/15698722/2cc921ac-df7e-4efe-a949-c5745e87903f)
I started with a stack of Dark Ore, and that's what I got from mining what's missing from it. A lot more Gems than I would have expected to be honest.

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.21
- Minecraft: 1.19.2
- Forge: 43.2.8

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You must mine them with Fortune. Will be updated in the book.
