### ISSUE TITLE
EMI (JEI/REI alternative) is visible in Origins of Darkness

### ISSUE THREAD

**Issue by aaronhowser1** [rubensworks/EvilCraft#985]
#### Issue type:

- :bug: Bug 

____

#### Short description:

![image](https://github.com/CyclopsMC/EvilCraft/assets/15698722/3b60489c-7cce-46b2-9117-3a7a69b04716)

I guess this might be counting as an inventory screen for some reason? It doesn't happen with JEI, so idk why it would with EMI

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.22
- Minecraft: 1.19.2
- Forge: 43.2.8

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Since EvilCraft doesn't have any ties to EMI, this looks like an EMI bug, that should be fixed on their end. Could you report it to their issue tracker?
