### ISSUE TITLE
Right clicking a Colossal Blood Chest sends the chat message twice

### ISSUE THREAD

**Issue by aaronhowser1** [rubensworks/EvilCraft#986]
#### Issue type:

- :bug: Bug 

____

#### Short description:

![image](https://github.com/CyclopsMC/EvilCraft/assets/15698722/2f5ed384-3884-4a0d-8c45-fc0e83e23fdd)

Possibly it's not checking for client/serverside on the click event?

#### Versions:

    This mod: EvilCraft-1.19.2-1.2.21
    Minecraft: 1.19.2
    Forge: 43.2.8

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by aaronhowser1** [comment]
Also shouldn't this say 3x3x3, not 2x2x2? When I do have a 2x2x2, it says it's 1x1x1

**Comment by aaronhowser1** [comment]
Did this also fix the message sending twice?

**Comment by aaronhowser1** [comment]
Oh yep it did, only saw the size thing
