### ISSUE TITLE
Config option for Infested Netherrack / Nether Bricks spawnrates to adjust Nether Fish encounters

### ISSUE THREAD

**Issue by Cakx** [rubensworks/EvilCraft#987]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

I would very much appreciate a config option to adjust the worldgen spawnrates of Infested Netherrack and Infested Nether Brick Blocks in the Nether Dimension.

In your current config I was not able to find anything related.

While mining in the Nether the amount of Nether Fish encounters spawned by mining these blocks is just way too high for my taste. 
This is especially true when you are using fast mining tools like modded 3x3 Hammers. 
In such case you are encountering more than one group of Nether Fish per minute which presents itself as rather unrelaxing.
Silk Touch also didn't help to guard myself from this. 

Upon some quick google search I noticed that some other players had similar complaints.

I hope you keep up the good work with this awesome Mod, I have beein enjoying EvilCraft for years.

I am using:

**Evilcraft Version: 1.19.2-1.2.19** 
Minecraft Version: 1.19.2
Forge Version: 43.2.11

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
This will be possible using datapacks as of MC 1.19.3: https://github.com/CyclopsMC/EvilCraft/blob/master-1.19/src/main/resources/data/evilcraft/worldgen/placed_feature/ore_infested_nether.json

<blockquote><img src="https://opengraph.githubassets.com/17ec5baf6b9a2c8977429a121000cfa28ae52e2ad1b9287ed912418da9320b21/CyclopsMC/EvilCraft" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EvilCraft">EvilCraft/ore_infested_nether.json at master-1.19 · CyclopsMC/EvilCraft</a></strong></div><div>An evil mod for Minecraft. Contribute to CyclopsMC/EvilCraft development by creating an account on GitHub.</div></blockquote>
