### ISSUE TITLE
Acceleration is listed twice in the book's page on Broom modifiers

### ISSUE THREAD

**Issue by aaronhowser1** [rubensworks/EvilCraft#988]
#### Issue type:

- :bug: Bug 

____

#### Short description:
![image](https://github.com/CyclopsMC/EvilCraft/assets/15698722/4d310e3b-ea5b-49d7-9330-5c20f16ff385)
![image](https://github.com/CyclopsMC/EvilCraft/assets/15698722/057f0138-a342-4a96-bec9-3676a7f7f8e9)

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.23
- Minecraft: 1.19.2
- Forge: 43.2.14

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by aaronhowser1** [comment]
Additionally, it looks like Sturdyness (which should be spelled Sturdiness) is referred to as "Thoughness" (Toughness, I assume)

![image](https://github.com/CyclopsMC/EvilCraft/assets/15698722/faa2a468-b9ce-4d31-9a6f-172c31fcda50)
![image](https://github.com/CyclopsMC/EvilCraft/assets/15698722/b75536f5-34c2-49a9-bbbe-57c556b00fc0)

![image](https://github.com/CyclopsMC/EvilCraft/assets/15698722/4be7d4ff-bcbf-4916-912a-921d34d0f36e)
