### ISSUE TITLE
The Kamakaze Broom trait behaves strangely

### ISSUE THREAD

**Issue by aaronhowser1** [rubensworks/EvilCraft#989]
#### Issue type:

- :bug: Bug 

____

#### Short description:

https://github.com/CyclopsMC/EvilCraft/assets/15698722/9f16bb8e-3481-439b-9049-1a00330996f0

It's spamming tons of explosions, and doesn't actually damage the cow at all

____

#### Versions:

- This mod: EvilCraft-1.19.2-1.2.23
- Minecraft: 1.19.2
- Forge: 43.2.14

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Seems to be working fine here on my end. Are you certain that no other mod is causing conflicts?
Anyways, the fact that the player is not being dismounted is a bug, so I'll look into that.

**Comment by aaronhowser1** [comment]
It is causing explosions, just very very small ones. That crater on the right when I go into third person was from when I discovered it

**Comment by rubensworks** [comment]
Note that explosion power is relative to speed, so it may be that you're moving too slowly, causing only you to take damage, and not the cow.
Can you try flying faster?
