### ISSUE TITLE
org.cyclops.evilcraft.entity.monster.EntityVengeanceSpirit tried to access private field net.minecraft.world.entity.Entity.f_19793

### ISSUE THREAD

**Issue by sandalle** [rubensworks/EvilCraft#991]
#### Issue type:

- :bug: Bug 

____

#### Short description:

While walking around a new world, I got this crash:
```
java.lang.IllegalAccessError: class org.cyclops.evilcraft.entity.monster.EntityVengeanceSpirit tried to access private field net.minecraft.world.entity.Entity.f_19793_ (org.cyclops.evilcraft.entity.monster.EntityVengeanceSpirit is in module evilcraft@1.2.23 of loader 'TRANSFORMER' @b32e983; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @b32e983)
```

#### Steps to reproduce the problem:

1. I'm unsure, looks to be when a Vengeance Spirit tries to load/spawn.

#### Expected behaviour:

Not accessing a private field and causing a crash. ;)

____

#### Versions:

- This mod: 1.20.1-1.2.23
- Minecraft: 1.20.1
- Forge: 1.20.1-47.0.35

#### Log file:

[crash-2023-07-02_01.41.38-server.txt](https://github.com/CyclopsMC/EvilCraft/files/11929030/crash-2023-07-02_01.41.38-server.txt)
And again later roaming around:
[crash-2023-07-02_01.53.57-server.txt](https://github.com/CyclopsMC/EvilCraft/files/11929048/crash-2023-07-02_01.53.57-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by sandalle** [comment]
Thank you for the quick fix! :)
