### ISSUE TITLE
The game crashed whilst ticking entity VengeanceSpirit 1.20.1

### ISSUE THREAD

**Issue by OBS3SS1ON** [rubensworks/EvilCraft#992]
1.20.1-forge-47.0.35

The game crashed whilst ticking entity
Error: java.lang.IllegalAccessError: class org.cyclops.evilcraft.entity.monster.EntityVengeanceSpirit tried to access private field net.minecraft.world.entity.Entity.f_19793_ (org.cyclops.evilcraft.entity.monster.EntityVengeanceSpirit is in module evilcraft@1.2.23 of loader 'TRANSFORMER' @720c8f80; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @720c8f80)

crash-2023-07-02_08.53.56-server
https://pastebin.com/nFZskyfv

[latest.log](https://github.com/CyclopsMC/EvilCraft/files/11929406/latest.log)
[debug.log](https://github.com/CyclopsMC/EvilCraft/files/11929407/debug.log)

**Comment by rubensworks** [comment]
Thanks for reporting!
