### ISSUE TITLE
what does the werewolf flesh do?

### ISSUE THREAD

**Issue by UwUsheep** [rubensworks/EvilCraft#994]
#### Issue type:

- :question: Question 

____

#### Question:

I got the werewolf flesh and was wondering what it does? I don't know at all and it doesn't give me any details in the book. Also this is not relevant but great mod! I hope you expand on the mod and hope for the best!

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
You can eat it for boost effects. But only eat it during the night, bad things will happen otherwise.

**Comment by UwUsheep** [comment]
oh ok thanks I love your mod btw it's one of my number 1 favorites.
