### ISSUE TITLE
Effortless ring crashes when put in hand or curio

### ISSUE THREAD

**Issue by SixShooterGun** [rubensworks/EvilCraft#995]
#### Issue type:

- :bug: Bug 
____

#### Short description:

My effortless ring crashes my game when I either take it from creative or craft it and put it in my inventory or curio ring

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

I want to be able to use it :C

____

#### Versions:

EvilCraft 1.20.1-1.2.25 (Latest)

- This mod: EvilCraft
- Minecraft: 1.20.1
- Forge: Latest

#### Log file:
https://pastebin.com/NDVcvCbz

**Comment by rubensworks** [comment]
Thanks for reporting!
