### ISSUE TITLE
[Minor] Box of eternal closure hitbox seems to be rotated 90 degrees about the vertical axis away from the model

### ISSUE THREAD

**Issue by TLop503** [rubensworks/EvilCraft#996]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. When placing and looking at a box of eternal closure the wireframe that appears to show the hitbox does not match the model. It appears to be rotated 90 degrees from what would be expected.
2. Please note this was found in all the mods 8, if this pack uses an outdated version of the mod then please disregard.

#### Expected behaviour:

The hitbox seems to be the same dimensions as the model, I assume they would line up.
____

#### Versions:

- This mod: 1.2.24 (?)
- Minecraft: 1.19.2
- Forge: 43.2 (?) - latest default by curseforge for 1.19.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I can't reproduce this on the latest version (same version as you).
There's probably a mod in your pack that alters hitboxes somehow.
I recommend reporting this to your modpack author, and asking them about this.

Happy to make any changes in here if the need for that would exist.

**Comment by TLop503** [comment]
cool, thanks for taking a look.
