### ISSUE TITLE
An exception occurred while updating the block entity

### ISSUE THREAD

**Issue by luluxiaoyu** [rubensworks/EvilCraft#998]
#### Issue type:

- :bug: Bug 

____

#### Short description:
An exception occurred while updating the block entity

#### Steps to reproduce the problem:

1. Drop the Storm glass into the environment memory

2. Generate weather bottle

3. When resuming charging (until halfway)

#### Expected behaviour:

____

#### Versions:

- This mod: 1.2.25
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:
https://pastebin.com/SpkmY581
craftlog https://pastebin.com/rWB1iRr8

**Comment by rubensworks** [comment]
Thanks for reporting!
