### ISSUE TITLE
1.20.1 La escoba no se puede utilizar, cuando la intentas usar vuelve automaticamente al inventario.

### ISSUE THREAD

**Issue by ShadowWolf0311** [rubensworks/EvilCraft#999]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!
